### ISSUE TITLE
Adding a link does not add linked items to channels

### ISSUE THREAD

**Issue by aounhaider1** [eclipse/smarthome#1284] opened 2016-03-28 20:11 UTC
After creation of a thing I am adding links to /links endpoint using channelUID and itemName. The links are successfully added but they are shown under the linked items of the things.
I added: 

```
channelUID:"hue:LWB004:338217b4:brightness"
itemName:"hue_LWB004_338217b4_brightness" 
```

which was successfully added and its showing exactly the same in links. But in my things it is like this:
![screen shot 2016-03-28 at 22 08 02](https://cloud.githubusercontent.com/assets/5161937/14088796/c2cd215e-f531-11e5-9e85-b048dfd7d1ca.png)

**Comment by aounhaider1** [comment] 2016-03-28 20:22
Also do I need to add the item manually before adding a link or is it created automatically because endpoint '/items/{itemname}' returns a 404 when I search the item with the itemName: 'hue_LWB004_338217b4_brightness'.

**Comment by cdjackson** [comment] 2016-03-30 09:14
I'm pretty sure that the adding of channel/item links works in HABmin - what call are you making to add the links?

**Comment by aounhaider1** [comment] 2016-03-30 09:29
I am posting the above mentioned channelUID,itemName to /links/{itemName}/{channelUID}.

**Comment by cdjackson** [comment] 2016-03-30 09:43
I think this is also what I'm doing in HABmin...

```
PUT http://localhost:8080/rest/links/zwave_serial_zstick_1530ee834f6_serial_can/zwave:serial_zstick:home:serial_can
```

and then 

```
GEThttp://localhost:8080/rest/things/zwave:serial_zstick:home
```

results in -:

```
{
  "statusInfo": {
  },
  "link": "http://localhost:8080/rest/things/zwave:serial_zstick:home",
  "label": "Z-Wave Serial Controller",
  "configuration": {
  },
  "properties": {
  },
  "UID": "zwave:serial_zstick:home",
  "thingTypeUID": "zwave:serial_zstick",
  "channels": [
    {
      "linkedItems": [
        "zwave_serial_zstick_1530ee834f6_serial_can"
      ],
      "uid": "zwave:serial_zstick:home:serial_can",
      "id": "serial_can",
      "channelTypeUID": "zwave:serial_can",
      "itemType": "Number",
      "properties": {},
      "configuration": {}
    }
  ]
}
```

(note that I removed some of the response (config/properties/status) to focus on the bit we're interested in... If I understand your report, the `linkedItems` in the channels is not being updated, but it is here...

**Comment by aounhaider1** [comment] 2016-03-30 09:51
You have itemName=zwave_serial_zstick_1530ee834f6_serial_can, and
channelUID=zwave:serial_zstick:home:serial_can.
But I am building itemName directly from channelUID by replacing ":" with "_". Is it the wrong way?

**Comment by cdjackson** [comment] 2016-03-30 10:05
I'm doing the same thing if I create a new item. What I showed above is just the link call - if I create a new item, then there's another call before this to create the item, and then I link it to the channel.

What I did here is to link the channel to an existing item, so the channel and item names don't match. If I do another call with a new auto-generated item name -:

```
PUT http://localhost:8080/rest/items/zwave_serial_zstick_home_serial_can
PUT http://localhost:8080/rest/links/zwave_serial_zstick_home_serial_can/zwave:serial_zstick:home:serial_can
```

I get -:
```
    {
      "linkedItems": [
        "zwave_serial_zstick_1530ee834f6_serial_can",
        "zwave_serial_zstick_home_serial_can"
      ],
      "uid": "zwave:serial_zstick:home:serial_can",
      "id": "serial_can",
      "channelTypeUID": "zwave:serial_can",
      "itemType": "Number",
      "properties": {},
      "configuration": {}
    },
```

**Comment by aounhaider1** [comment] 2016-03-30 10:13
Ok, so item is not automatically created if its not inside items. I thought it otherwise.

**Comment by cdjackson** [comment] 2016-03-30 10:15
You need to create the item first (as far as I know anyway). The link just links an item and returns an error if there’s no such item (from memory).

**Comment by aounhaider1** [comment] 2016-03-30 10:18
No, it does not give any error on adding link if there is no item of the name inside items. It just adds it but as a consequence linkedItems stay empty.

**Comment by aounhaider1** [comment] 2016-03-30 13:03
@kaikreuzer can you please confirm this?

**Comment by sjka** [comment] 2016-03-30 17:15
right, afaik you can add links even if the corresponding item does not exist without running into errors.

**Comment by sja** [comment] 2016-03-31 19:55
I can confirm this, too. They are just standalone entities, even links. Thats sometimes a bit strange.
That also means that you have to delete a link, even if it's item and channel does not exist anymore.

**Comment by kaikreuzer** [comment] 2016-03-31 20:06
@sja For the deletion, there is https://github.com/eclipse/smarthome/issues/1018 already.

For this issue here, yes, creating a link does not mean that an item is created and this behavior is fully correct.
What we could add though is a check whether the item that is being linked exists at all and if not, return a HTTP 400.

**Comment by maggu2810** [comment] 2016-04-03 10:08
Is there a way to create an Item using the PaperUI?

**Comment by kaikreuzer** [comment] 2016-04-03 19:52
If the question is "is there a way [...] FOR the Paper UI", the answer is yes, by using the /rest/items url - currently it creates the items implicitly by using the "/rest/setup" url.

**Comment by triller-telekom** [comment] 2017-09-22 08:27
> What we could add though is a check whether the item that is being linked exists at all and if not, return a HTTP 400.

Shouldn't this rather be a 2XX status code because the action (to create that link) was successful? And in addition one could provide the information that the item was missing?

**Comment by kaikreuzer** [comment] 2017-09-22 08:38
What does the UI expect? We might actually have to handle the two situations differently:

- Simple mode: As the item will always be created, a success is always expected
- Non-simple mode: Creating a link to an non-existent item would lead to a dangling link and must be avoided - an error response and NO link is imho expected in that case

Imho this would be in line with https://github.com/eclipse/smarthome/issues/1018, where we also want to avoid dangling links.

We can also ask whether the UI should be allowed to specify an item name at all in "simple mode". Alternatively, we could have a separate url, which could leave the definition of the referenced item name to the runtime - this would imho the better place than the client.

**Comment by htreu** [comment] 2018-04-24 14:10
@kaikreuzer do we have an open issue on the REST API then? From what I know the original issue described here is resolved by now. Could you please close here and create a new issue for you latest comments if required?

**Comment by kaikreuzer** [comment] 2018-05-04 21:41
I cannot really well describe my last comment as an issue - I am still unsatisfied with the whole "simple mode", but don't yet have a suggestion on how to improve it. So let's just close this issue here for now.

**Closed by kaikreuzer** 2018-05-04 21:41 UTC
