### ISSUE TITLE
Phantom items appear after exception while saving items and things

### ISSUE THREAD

**Issue by jackdewinter** [eclipse/smarthome#2830] opened 2017-01-15 20:41 UTC
Log file below.  I am not 100% sure, but after that error happens is when this seems to occur.  

I am not sure how I got into this state, but once there, I see logs like:
```
12:20:21.269 [WARN ] [ome.core.thing.internal.ThingManager] - Cannot delegate update 'on' for item 'Office_DeskBackLight_Status' to handler for channel 'exec:command:office_deskbacklight_check:output', because no thing with the UID 'exec:command:office_deskbacklight_check' could be found.
12:20:36.602 [WARN ] [ome.core.thing.internal.ThingManager] - Cannot delegate update 'on' for item 'Office_DeskBackLight_Status' to handler for channel 'exec:command:office_deskbacklight_check:output', because no thing with the UID 'exec:command:office_deskbacklight_check' could be found.
12:20:51.902 [WARN ] [ome.core.thing.internal.ThingManager] - Cannot delegate update 'on' for item 'Office_DeskBackLight_Status' to handler for channel 'exec:command:office_deskbacklight_check:output', because no thing with the UID 'exec:command:office_deskbacklight_check' could be found.
12:20:55.336 [WARN ] [ome.core.thing.internal.ThingManager] - Cannot delegate update '0' for item 'Office_DeskBackLight_Ping_Exit' to handler for channel 'exec:command:office_deskbacklight_ping:exit', because no thing with the UID 'exec:command:office_deskbacklight_ping' could be found.
12:20:55.338 [WARN ] [ome.core.thing.internal.ThingManager] - Cannot delegate update '{"sent":5,"replies":5,"state":"online"}' for item 'Office_DeskBackLight_Ping_Out' to handler for channel 'exec:command:office_deskbacklight_ping:output',because no thing with the UID 'exec:command:office_deskbacklight_ping' could be found.
12:20:55.340 [WARN ] [ome.core.thing.internal.ThingManager] - Cannot delegate update '2017-01-15T12:20:55.336-0800' for item 'Office_DeskBackLight_Ping_Last' to handler for channel 'exec:command:office_deskbacklight_ping:lastexecution', because no thing with the UID 'exec:command:office_deskbacklight_ping' could be found.
```
This was from development, and may have been caused by other bugs I reported.  The important things are "exec:command:office_deskbacklight_check" and "exec:command:office_deskbacklight_ping".  In both cases, these were named differently, and were things that were refreshing every 15 and 60 seconds.  At those intervals, messages like the above are injected into the log files.

Picking the check one, I created a thing with the name from the UID:
```
exec:command:office_deskbacklight_check 							"dead"				[command="/.../tplink.exe check", interval=60, timeout=10, transform="REGEX(.*stateX\":\"(.*)\".*)", autorun=false]
```
At this point, the message turns to:
```
12:30:51.163 [INFO ] [ome.core.thing.internal.ThingManager] - Not delegating update 'on' for item 'Office_DeskBackLight_Status' to handler for channel 'exec:command:office_deskbacklight_check:output', because handler is not initialized (thing must be in status UNKNOWN, ONLINE or OFFLINE).
```
Trying various things at this point, the only one that seems to work is:
1) Change the name of an item to the one it complains about:
2) save the file and observe this in the file:
```
12:37:37.443 [INFO ] [el.core.internal.ModelRepositoryImpl] - Refreshing model 'jack.items'
12:37:37.451 [INFO ] [smarthome.event.ItemAddedEvent      ] - Item 'Office_DeskBackLight_Status' has been added.
12:37:37.452 [INFO ] [home.event.ItemChannelLinkAddedEvent] - Link 'Office_DeskBackLight_Status-exec:command:office_desk_backlight_check:output' has been added.
12:37:37.458 [INFO ] [smarthome.event.ItemRemovedEvent    ] - Item 'Office_DeskBackLight_Status' has been removed.
12:37:37.464 [INFO ] [el.core.internal.ModelRepositoryImpl] - Refreshing model 'jack.items'
```
In the cases where that exception occurred, this pattern off added and removed was not present.

```
12:18:32.995 [INFO ] [el.core.internal.ModelRepositoryImpl] - Refreshing model '
jack.things'
12:18:33.021 [INFO ] [smarthome.event.ThingRemovedEvent   ] - Thing 'ntp:ntp:dem
o' has been removed.
12:18:33.025 [INFO ] [smarthome.event.ThingRemovedEvent   ] - Thing 'yahooweathe
r:weather:duvall' has been removed.
12:18:33.034 [INFO ] [smarthome.event.ThingRemovedEvent   ] - Thing 'astro:sun:h
ome' has been removed.
12:18:33.037 [INFO ] [smarthome.event.ThingRemovedEvent   ] - Thing 'astro:moon:
home' has been removed.
12:18:33.044 [INFO ] [smarthome.event.ThingRemovedEvent   ] - Thing 'exec:comman
d:officedeskbacklight' has been removed.
12:18:33.048 [INFO ] [smarthome.event.ThingRemovedEvent   ] - Thing 'exec:comman
d:officedeskbacklightcheck' has been removed.
12:18:33.051 [INFO ] [smarthome.event.ThingRemovedEvent   ] - Thing 'exec:comman
d:officedeskbacklightping' has been removed.
12:18:33.053 [INFO ] [smarthome.event.ThingRemovedEvent   ] - Thing 'exec:comman
d:yedead' has been removed.
12:18:33.058 [INFO ] [me.event.ThingStatusInfoChangedEvent] - 'exec:command:offi
ce_deskbacklight_ping' changed from ONLINE to UNINITIALIZED (HANDLER_MISSING_ERR
OR)
12:18:33.059 [INFO ] [smarthome.event.ThingRemovedEvent   ] - Thing 'exec:comman
d:office_deskbacklight_ping' has been removed.
12:18:33.082 [INFO ] [me.event.ThingStatusInfoChangedEvent] - 'exec:command:dead
' changed from UNINITIALIZED to INITIALIZING
12:18:33.084 [INFO ] [me.event.ThingStatusInfoChangedEvent] - 'exec:command:dead
' changed from INITIALIZING to ONLINE
12:18:33.085 [ERROR] [ore.thing.internal.ThingRegistryImpl] - Could not inform t
he ThingTracker 'org.eclipse.smarthome.core.thing.internal.ThingManager@13ad5b2'
 about the 'THING_UPDATED' event!
java.lang.NullPointerException
        at org.eclipse.smarthome.core.thing.internal.ThingManager.thingUpdated(T
hingManager.java:542)[105:org.eclipse.smarthome.core.thing:0.9.0.201701140927]
        at org.eclipse.smarthome.core.thing.internal.ThingRegistryImpl.notifyTra
ckers(ThingRegistryImpl.java:227)[105:org.eclipse.smarthome.core.thing:0.9.0.201
701140927]
        at org.eclipse.smarthome.core.thing.internal.ThingRegistryImpl.notifyLis
tenersAboutUpdatedElement(ThingRegistryImpl.java:150)[105:org.eclipse.smarthome.
core.thing:0.9.0.201701140927]
        at org.eclipse.smarthome.core.thing.internal.ThingRegistryImpl.notifyLis
tenersAboutUpdatedElement(ThingRegistryImpl.java:1)[105:org.eclipse.smarthome.co
re.thing:0.9.0.201701140927]
        at org.eclipse.smarthome.core.common.registry.AbstractRegistry.updated(A
bstractRegistry.java:167)[98:org.eclipse.smarthome.core:0.9.0.201701140927]
        at org.eclipse.smarthome.core.common.registry.AbstractProvider.notifyLis
teners(AbstractProvider.java:57)[98:org.eclipse.smarthome.core:0.9.0.20170114092
7]
        at org.eclipse.smarthome.core.common.registry.AbstractProvider.notifyLis
tenersAboutUpdatedElement(AbstractProvider.java:82)[98:org.eclipse.smarthome.cor
e:0.9.0.201701140927]
        at org.eclipse.smarthome.model.thing.internal.GenericThingProvider.acces
s$4(GenericThingProvider.java:1)[133:org.eclipse.smarthome.model.thing:0.9.0.201
701140927]
        at org.eclipse.smarthome.model.thing.internal.GenericThingProvider$21.ap
ply(GenericThingProvider.java:1044)[133:org.eclipse.smarthome.model.thing:0.9.0.
201701140927]
        at org.eclipse.smarthome.model.thing.internal.GenericThingProvider$21.ap
ply(GenericThingProvider.java:1)[133:org.eclipse.smarthome.model.thing:0.9.0.201
701140927]
        at org.eclipse.xtext.xbase.lib.IteratorExtensions.forEach(IteratorExtens
ions.java:363)[146:org.eclipse.xtext.xbase.lib:2.9.2]
        at org.eclipse.xtext.xbase.lib.IterableExtensions.forEach(IterableExtens
ions.java:333)[146:org.eclipse.xtext.xbase.lib:2.9.2]
        at org.eclipse.smarthome.model.thing.internal.GenericThingProvider.creat
eThingsFromModelForThingHandlerFactory(GenericThingProvider.java:1054)[133:org.e
clipse.smarthome.model.thing:0.9.0.201701140927]
        at org.eclipse.smarthome.model.thing.internal.GenericThingProvider.acces
s$1(GenericThingProvider.java:1008)[133:org.eclipse.smarthome.model.thing:0.9.0.
201701140927]
        at org.eclipse.smarthome.model.thing.internal.GenericThingProvider$1$1.a
pply(GenericThingProvider.java:236)[133:org.eclipse.smarthome.model.thing:0.9.0.
201701140927]
        at org.eclipse.smarthome.model.thing.internal.GenericThingProvider$1$1.a
pply(GenericThingProvider.java:1)[133:org.eclipse.smarthome.model.thing:0.9.0.20
1701140927]
        at org.eclipse.xtext.xbase.lib.IteratorExtensions.forEach(IteratorExtens
ions.java:363)[146:org.eclipse.xtext.xbase.lib:2.9.2]
        at org.eclipse.xtext.xbase.lib.IterableExtensions.forEach(IterableExtens
ions.java:333)[146:org.eclipse.xtext.xbase.lib:2.9.2]
        at org.eclipse.smarthome.model.thing.internal.GenericThingProvider$1.app
ly(GenericThingProvider.java:239)[133:org.eclipse.smarthome.model.thing:0.9.0.20
1701140927]
        at org.eclipse.smarthome.model.thing.internal.GenericThingProvider$1.app
ly(GenericThingProvider.java:1)[133:org.eclipse.smarthome.model.thing:0.9.0.2017
01140927]
        at org.eclipse.smarthome.config.core.BundleProcessorVetoManager.applyAct
ionFor(BundleProcessorVetoManager.java:121)[94:org.eclipse.smarthome.config.core
:0.9.0.201701140927]
        at org.eclipse.smarthome.model.thing.internal.GenericThingProvider$6.app
ly(GenericThingProvider.java:320)[133:org.eclipse.smarthome.model.thing:0.9.0.20
1701140927]
        at org.eclipse.smarthome.model.thing.internal.GenericThingProvider$6.app
ly(GenericThingProvider.java:1)[133:org.eclipse.smarthome.model.thing:0.9.0.2017
01140927]
        at org.eclipse.xtext.xbase.lib.IteratorExtensions.forEach(IteratorExtens
ions.java:363)[146:org.eclipse.xtext.xbase.lib:2.9.2]
        at org.eclipse.xtext.xbase.lib.IterableExtensions.forEach(IterableExtens
ions.java:333)[146:org.eclipse.xtext.xbase.lib:2.9.2]
        at org.eclipse.smarthome.model.thing.internal.GenericThingProvider.creat
eThingsFromModel(GenericThingProvider.java:323)[133:org.eclipse.smarthome.model.
thing:0.9.0.201701140927]
        at org.eclipse.smarthome.model.thing.internal.GenericThingProvider.model
Changed(GenericThingProvider.java:901)[133:org.eclipse.smarthome.model.thing:0.9
.0.201701140927]
        at org.eclipse.smarthome.model.core.internal.ModelRepositoryImpl.notifyL
isteners(ModelRepositoryImpl.java:207)[122:org.eclipse.smarthome.model.core:0.9.
0.201701140927]
        at org.eclipse.smarthome.model.core.internal.ModelRepositoryImpl.addOrRe
freshModel(ModelRepositoryImpl.java:120)[122:org.eclipse.smarthome.model.core:0.
9.0.201701140927]
        at org.eclipse.smarthome.model.core.internal.folder.FolderObserver.check
File(FolderObserver.java:270)[122:org.eclipse.smarthome.model.core:0.9.0.2017011
40927]
        at org.eclipse.smarthome.model.core.internal.folder.FolderObserver.acces
s$1(FolderObserver.java:264)[122:org.eclipse.smarthome.model.core:0.9.0.20170114
0927]
        at org.eclipse.smarthome.model.core.internal.folder.FolderObserver$Watch
QueueReader.processWatchEvent(FolderObserver.java:145)[122:org.eclipse.smarthome
.model.core:0.9.0.201701140927]
        at org.eclipse.smarthome.core.service.AbstractWatchQueueReader.run(Abstr
actWatchQueueReader.java:122)[98:org.eclipse.smarthome.core:0.9.0.201701140927]
        at java.lang.Thread.run(Thread.java:745)[:1.8.0_111]
```

**Comment by kaikreuzer** [comment] 2017-01-15 21:20
It would be awesome if you could analyze it a bit yourself and come up with a short and easy example of how to reproduce a concrete problem. It should not involve non-ESH bindings, so best use the existing [demo configuration files](https://github.com/eclipse/smarthome/blob/master/distribution/smarthome/conf/things/demo.things) and describe a simple change that causes an issue.

**Comment by jackdewinter** [comment] 2017-01-17 04:56
I'll give it a try... stay tuned.

**Comment by Rossko57** [comment] 2017-02-11 11:53
This looks like a manifestation of this reported problem -
https://community.openhab.org/t/modbus-log-erro-item-that-doesn-t-exists-anymore/22661/2
there are quite a few similar reports of "ghost items"

Reproduceable by (1) declare a 'faulty' item in 1.x binding (2) Edit out said item
I cannot do that myself, not an OH2 user.
I guess it does not fill the ESH requirement as it is 1.x binding involved.

**Comment by kaikreuzer** [comment] 2017-08-28 11:47
This should have been fixed by https://github.com/eclipse/smarthome/pull/3639.

**Closed by kaikreuzer** 2017-08-28 11:47 UTC
