### ISSUE TITLE
Dynamically added channels can't link to items in PaperUI

### ISSUE THREAD

**Issue by pathec** [eclipse/smarthome#2903] opened 2017-01-27 10:33 UTC
I've a Problem that the PaperUI does not found dynamically added channels with dynamic channel uid's, when I try to link a channel manually. 
What means dynamic? A thing has no channels at first and all channels are added during thing creation. Additional a thing has multiple channels of the same channel type, so I attach a unique identifier to channel uid.

Example:

- static defined channel type (XML): switchColorTemperature
- channel uid after thing creation: switchColorTemperature-ZWayVDev_zway_21-0-51-0

Error message when I'm try to link a channel:
![channeltype02](https://cloud.githubusercontent.com/assets/9437468/22367735/6b1d135a-e483-11e6-895a-bafc11074745.png)

Detailed information are in openhab forum: https://community.openhab.org/t/things-with-multiple-channels-of-the-same-channel-type/21118?u=pathec

Please let me know if more information are needed or something is not understandable.

**Comment by kaikreuzer** [comment] 2017-01-27 11:12
> I think it is because the REST API does not deliver the channel type. When I call http://localhost:8080/rest/channel-types/zway:zwayDevice:b0bb9280:21:switchColorTemperature-ZWayVDev_zway_21-0-51-1, I get a 204 no content as response.

You are passing a channel UID instead of a channel type UID, so it is correct that you do not get a response.

So do I understand it right: The REST API correctly returns all (including dynamically added) channels of your Thing? Then the only problem is that the Paper UI crashes when trying to render it, so the Paper UI needs to be fixed here? If this is the correct summary, you should adapt the issue title as it says something fairly different.

**Comment by pathec** [comment] 2017-01-27 14:06
@kaikreuzer, yes the thing contains all generated channels and the REST API deliveries all channel types. Then it is probably a problem of PaperUI.

**Comment by pathec** [comment] 2017-01-27 14:23
Same error in PaperUI when I make channel type uid shorter, for example: instead of "switchColorTemperature-ZWayVDev_zway_21-0-51-0" -> "switchColorTemperature0". So the underscores and dashes should not be the problem.

**Comment by pathec** [comment] 2017-01-27 14:43
AngularJS model looks good to me, but maybe it help to find the problem:
![thingdetails](https://cloud.githubusercontent.com/assets/9437468/22374623/330364b4-e4a7-11e6-9520-645253a45222.png)

**Comment by kaikreuzer** [comment] 2017-01-27 15:17
@aounhaider1 Could you check why it isn't possible to link the channel?

**Comment by kaikreuzer** [comment] 2017-01-27 15:19
@pathec The title now says "PaperUI can't render some channel types" - but the channels ARE rendered on the Thing detail page, right? So the problem is that there is a JS error once you click the "link" button? Could you please describe it in detail?

**Comment by maggu2810** [comment] 2017-01-27 17:10
> because a thing may not have several channels of the same type

I don't understand why a thing should not consists of different channels of the same type.
Using the same channel type for different channels of one thing works fine for me.

**Comment by pathec** [comment] 2017-01-27 17:21
That's my code to add channel to thing, when I'm try to add multiple channels of same type:

```
ThingBuilder thingBuilder = editThing();
ChannelTypeUID channelTypeUID = new ChannelTypeUID(BINDING_ID, id);
Channel channel = ChannelBuilder.create(new ChannelUID(getThing().getUID(), id), acceptedItemType)
    .withType(channelTypeUID).withLabel(label).withProperties(properties).build();
thingBuilder.withChannel(channel);
thingBuilder.withLabel(thing.getLabel());
updateThing(thingBuilder.build());
```

Resulting for the second channel in: _Duplicate channels zway:zwayDevice:141_32_62_157:21:switchColorTemperature_.

When I change the third line it works:

```
Channel channel = ChannelBuilder.create(new ChannelUID(getThing().getUID(), id + getInstanceIdByDeviceId(properties.get("deviceId"))), acceptedItemType)
    .withType(channelTypeUID).withLabel(label).withProperties(properties).build();
```

**Comment by maggu2810** [comment] 2017-01-27 17:41
Perhaps my reading was not correct.
The channel type of a channel is identified by the channel type UID.
So, two different channels (two different channel UIDs) can use the same channel type (channel type UID).

In your changed third line you still use `.withType(channelTypeUID)` so, isn't it using the same type?

**Comment by pathec** [comment] 2017-01-27 17:58
You're right. I was wrong. The same type is possible but not the same channel uid. I change that in my comment above.

**Comment by pathec** [comment] 2017-01-27 18:12
The problem is probably the `getChannelTypeById(...)` function of the PaperUI. Because how to move from the channel id (_switchColorTemperature0_) conclusions to the channel type (_switchColorTemperature_). Or I'm thinking wrong?

**Comment by aounhaider1** [comment] 2017-02-06 13:52
This should be fixed by https://github.com/eclipse/smarthome/pull/2949

**Comment by pathec** [comment] 2017-02-06 13:54
Thank you for your message. I test it as soon as the change is in the build.

**Closed** 2017-02-14 15:11 UTC
