### ISSUE TITLE
[Paper UI] Control Section in Paper UI is empty

### ISSUE THREAD

**Issue by marcolino7** [eclipse/smarthome#4358] opened 2017-09-29 14:47 UTC
Hi,
I have installation of OH2 on a Debianbox, installed from repository.
Before last upgrade done 2 days ago, this issue is not present and all working fine.
After last upgrade, the Control Page on Paper UI is empty. Issue is described here:
https://community.openhab.org/t/paper-ui-500-internal-server-error/34576/11

Before upgrade I have OH2 version 2.1.0-SNAPSHOT Build #887
After Upgrade I have OH2 version 2.2.0-SNAPSHOT Build #1047

**Comment by lolodomo** [comment] 2017-10-03 07:33
It is working for me with snapshot 1053.
Have you linked channels to items ?

**Comment by marcolino7** [comment] 2017-10-03 07:39
Yes, sure.
Installation is working fine before upgrade. I have at least 50 items linked to things

**Comment by lolodomo** [comment] 2017-10-03 07:43
Did ypu clear ypur WEB browser cache ?

**Comment by marcolino7** [comment] 2017-10-03 07:57
Hi tried clearing cache, i also tried with othe browser and with privacy mode

**Comment by lolodomo** [comment] 2017-10-03 08:16
Difficult to help if we can't reproduce. Sorry.

**Comment by marcolino7** [comment] 2017-10-03 08:48
Let me know if there is some kind of log I can capture

**Comment by marcolino7** [comment] 2017-10-03 19:38
updateting to last commit, issue seems to be fixed.

Marco

**Comment by htreu** [comment] 2017-10-04 05:16
@marcolino7 please close the issue if its fixed for you. tnx.

**Closed** 2017-10-04 08:05 UTC
