### ISSUE TITLE
module.timer.test module fails to compile

### ISSUE THREAD

**Issue by 9037568** [eclipse/smarthome#1285] opened 2016-03-28 20:23 UTC
[INFO] Eclipse SmartHome Automation Timer Modules ......... SUCCESS [ 0.490 s]
[INFO] Eclipse SmartHome Automation Module Timer Tests .... FAILURE [ 0.733 s]
[INFO] Eclipse SmartHome Automation Script Modules ........ SKIPPED
...
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-surefire-plugin:0.23.1:test (default-test) on project org.eclipse.smarthome.automation.module.timer.test: Execution default-test of goal org.eclipse.tycho:tycho-surefire-plugin:0.23.1:test failed: Cannot resolve dependencies of MavenProject: org.eclipse.smarthome.bundles:org.eclipse.smarthome.automation.module.timer.test:0.8.0-SNAPSHOT @ C:\Users\Jack\openhab2-master\git\smarthome\bundles\automation\org.eclipse.smarthome.automation.module.timer.test\pom.xml: See log for details -> [Help 1]

**Comment by maggu2810** [comment] 2016-04-02 07:14
Hi @9037568, is this error permanent?

"Cannot resolve dependencies" could be caused by a broken internet connection while resolving the dependencies.

**Comment by 9037568** [comment] 2016-04-02 11:34
Yes, just rechecked and the failure is still occurring. Also noticed this section of the output for the first time. It complains about the core.scheduler, even though that is shown as having been successfully compiled...

[ERROR] Cannot resolve project dependencies:
[ERROR]   You requested to install 'bundle org.eclipse.smarthome.core.scheduler 0.0.0' but it could not be found
[ERROR]
[ERROR] See http://wiki.eclipse.org/Tycho/Dependency_Resolution_Troubleshooting for help.
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Eclipse SmartHome Core Scheduler Service ........... SUCCESS [  2.962 s]
[INFO] Eclipse SmartHome I/O Components ................... SUCCESS [  0.131 s]
[INFO] Eclipse SmartHome Console .......................... SUCCESS [  0.448 s]
[INFO] Eclipse SmartHome Network I/O ...................... SUCCESS [  0.547 s]
[INFO] Eclipse SmartHome Models ........................... SUCCESS [  0.113 s]
[INFO] Eclipse SmartHome Model Core ....................... SUCCESS [  0.871 s]
[INFO] Eclipse SmartHome Model Lazy Generation ............ SUCCESS [  0.561 s]
[INFO] Eclipse SmartHome Model Items ...................... SUCCESS [  8.877 s]
[INFO] Eclipse SmartHome Model Persistence ................ SUCCESS [  8.394 s]
[INFO] Eclipse SmartHome Model Script ..................... SUCCESS [ 12.509 s]
[INFO] Eclipse SmartHome Core Transformation Service ...... SUCCESS [  0.509 s]
[INFO] Eclipse SmartHome Core Binding XML ................. SUCCESS [  0.309 s]
[INFO] Eclipse SmartHome Core Binding XML Tests ........... SUCCESS [  9.591 s]
[INFO] Eclipse SmartHome Core Thing XML ................... SUCCESS [  0.782 s]
[INFO] Eclipse SmartHome Core Thing XML Tests ............. SUCCESS [  7.492 s]
[INFO] Eclipse SmartHome Automation ....................... SUCCESS [  0.123 s]
[INFO] Eclipse SmartHome Automation API ................... SUCCESS [  0.716 s]
[INFO] Eclipse SmartHome Automation Commands .............. SUCCESS [  0.400 s]
[INFO] Eclipse SmartHome Automation Parser GSON ........... SUCCESS [  0.304 s]
[INFO] Eclipse SmartHome Automation Providers ............. SUCCESS [  0.481 s]
[INFO] Eclipse SmartHome Automation Core .................. SUCCESS [  0.488 s]
[INFO] Eclipse SmartHome Automation Core Tests ............ SUCCESS [  6.422 s]
[INFO] Eclipse SmartHome Automation Sample JSON ........... SUCCESS [  0.558 s]
[INFO] Eclipse SmartHome Automation Core Modules .......... SUCCESS [  0.387 s]
[INFO] Eclipse SmartHome Automation Core Module Tests ..... SUCCESS [  4.218 s]
[INFO] Eclipse SmartHome Automation Timer Modules ......... SUCCESS [  0.453 s]
[INFO] Eclipse SmartHome Automation Module Timer Tests .... FAILURE [  0.668 s]
[INFO] Eclipse SmartHome Automation Script Modules ........ SKIPPED

**Comment by maggu2810** [comment] 2016-04-03 10:17
The real information which test fails will be found above the lines you posted (see e.g. #1131).
Are you using the current master or could you post the commit ID of your head, so we can test it?

**Comment by 9037568** [comment] 2016-04-03 15:23
I did a fresh pull and got this:
>Fast-forwarded master to 92f07b6bb7517e8f10448b91b536e5b3fde17d43.

Now the failure is occurring in a different place. Module Timer Tests succeeds, but Sample REST Api fails.  Though the cause appears to be the same - "[ERROR]   Missing requirement: org.eclipse.smarthome.feature.runtime.automation.feature.group 0.8.0.qualifier requires 'org.eclipse.smarthome.automation.module.script 0.0.0' but it could not be found"

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Eclipse SmartHome Automation Timer Modules ......... SUCCESS [  0.235 s]
[INFO] Eclipse SmartHome Automation Module Timer Tests .... SUCCESS [  0.423 s]
[INFO] Eclipse SmartHome Automation Script Modules ........ SUCCESS [  0.271 s]
[INFO] Eclipse SmartHome Automation Script Default Scope .. SUCCESS [  5.711 s]
[INFO] Eclipse SmartHome Automation Script Module Tests ... SUCCESS [  0.469 s]
[INFO] Eclipse SmartHome Automation Event Tests ........... SUCCESS [  0.449 s]
[INFO] Eclipse SmartHome Automation Integration Tests ..... SUCCESS [  0.763 s]
[INFO] Eclipse SmartHome Automation Sample Extension Java . SUCCESS [  0.330 s]
[INFO] Eclipse SmartHome Automation REST API .............. FAILURE [  0.209 s]
[INFO] Eclipse SmartHome Automation Sample REST API ....... SKIPPED


[INFO] Resolving class path of MavenProject: org.eclipse.smarthome:org.eclipse.smarthome.feature.runtime.ui:0.8.0-SNAPSHOT @ C:\Users\Jack\openhab2-master\git\smarthome\features\org.eclipse.smarthome.feature.runtime.ui\pom.xml
[INFO] Computing target platform for MavenProject: org.eclipse.smarthome:org.eclipse.smarthome.feature.runtime.automation:0.8.0-SNAPSHOT @ C:\Users\Jack\openhab2-master\git\smarthome\features\org.eclipse.smarthome.feature.runtime.automation\pom.xml
[INFO] Resolving dependencies of MavenProject: org.eclipse.smarthome:org.eclipse.smarthome.feature.runtime.automation:0.8.0-SNAPSHOT @ C:\Users\Jack\openhab2-master\git\smarthome\features\org.eclipse.smarthome.feature.runtime.automation\pom.xml
[INFO] {osgi.os=linux, osgi.ws=gtk, org.eclipse.update.install.features=true, osgi.arch=x86}
[ERROR] Cannot resolve project dependencies:
[ERROR]   Software being installed: org.eclipse.smarthome.feature.runtime.automation.feature.group 0.8.0.qualifier
[ERROR]   Missing requirement: org.eclipse.smarthome.feature.runtime.automation.feature.group 0.8.0.qualifier requires 'org.eclipse.smarthome.automation.module.script 0.0.0' but it could not be found

**Comment by maggu2810** [comment] 2016-04-04 12:47
Recent changes introduced some test failures. I didn't see the same as yours, but perhaps you can wait until the other ones are resolved. Is this okay for you?

**Comment by maggu2810** [comment] 2016-04-04 12:48
Please test also a <code>mvn clean install -DskipTests=true</code>

**Comment by kaikreuzer** [comment] 2016-04-21 07:47
Build is successful on Hudson since a while - so closing this issue.

**Closed by kaikreuzer** 2016-04-21 07:47 UTC
