### ISSUE TITLE
Basic UI Text Item problem

### ISSUE THREAD

**Issue by s-simma** [eclipse/smarthome#957] opened 2016-01-30 15:52 UTC
Hi,
item 1:
Writing from Device Handler to String item by:
this.updateState(new ChannelUID(getThing().getUID(), CHANNEL_INFO), new StringType(info));
- The text is updated in the browser -> ok
- After page change or Refresh Browser -> Text information is lost (nothing diaplayed)
item definition:
String Shutter_GF_OfficeBInfo "Büro Balkon [%s]" (GF_Office, Shutters)   {channel="siennapl:Sienna_SAM2:1:PL1:info"}
(I think this is a bug)

item2:
"Rollershutter" items can only display  the 3 buttons and execute their functions ?
So if i want to display addition informations (position, go up, go down, isup, isdown, motor blocked) i need an extra String item ?
(i think it is only my wish to display the "staus info" left to the push-buttons).

**Comment by kaikreuzer** [comment] 2016-02-01 18:48
I would say that (1) is a duplicate of https://github.com/eclipse/smarthome/issues/640.
Regarding (2): You should be able to also display the current state on the label, so you could see a 30% next to the buttons. If this does not work, please enter a separate issue for it.

**Closed by kaikreuzer** 2016-02-01 18:48 UTC
