### ISSUE TITLE
PaperUI: Values of OH2 things should have identifyable names

### ISSUE THREAD

**Issue by Boby71** [eclipse/smarthome#2324] opened 2016-10-15 18:37 UTC
When I discover a thing in OH2 with more than one channel, it appears in the "control" view of OH2 the following way:
![paperui_value](https://cloud.githubusercontent.com/assets/22266373/19412449/c95f4654-9316-11e6-8984-33c5fa00b374.png)
As you can see, it's not possible to identify which value belongs to which channel.
At least the name of the channel should appear here in order to be able to identify which returned value belongs to which channel. "Value" is not really very helpful. Thank you!

**Comment by kaikreuzer** [comment] 2016-10-15 18:43
I actually think this is a duplicate of https://github.com/eclipse/smarthome/issues/1550, but I have to agree that #1550 is a bit cryptic to read...

Is it possible that the labels are correctly shown after you added a thing and they only disappear after a restart of the runtime?
There is no general problem with Things with more than one channel, this is for sure.

**Closed** 2016-11-26 16:23 UTC
Labels: duplicate
