### ISSUE TITLE
Unable to build ref-0.9.0.b2

### ISSUE THREAD

**Issue by shankarkalmade** [eclipse/smarthome#2730] opened 2017-01-03 09:41 UTC
I cloned master and checkout to specific tag ref-0.9.0.b2 and then i tried mvn clean install 

.
.
.
[INFO] Computing target platform for MavenProject: org.eclipse.smarthome.test:org.eclipse.smarthome.test:0.9.0.b2 @ /home/shankar/Documents/esh_clone/smarthome/bundles/test/org.eclipse.smarthome.test/pom.xml
[INFO] Fetching p2.index from http://download.eclipse.org/tools/orbit/downloads/drops/R20140525021250/repository/ (0B at 0B/s)
[INFO] Adding repository http://download.eclipse.org/tools/orbit/downloads/drops/R20140525021250/repository
[INFO] Fetching p2.index from http://download.eclipse.org/eclipse/updates/4.4/ (0B at 0B/s)
[INFO] Adding repository http://download.eclipse.org/eclipse/updates/4.4
[INFO] Fetching p2.index from http://download.eclipse.org/modeling/tmf/xtext/updates/releases/2.9.2/ (0B at 0B/s)
[INFO] Adding repository http://download.eclipse.org/modeling/tmf/xtext/updates/releases/2.9.2
[INFO] Adding repository http://download.eclipse.org/modeling/emft/mwe/updates/releases/2.8.3
[INFO] Adding repository http://download.eclipse.org/modeling/emf/emf/updates/2.11/core/R201506010402
[INFO] Adding repository http://dist.springsource.org/release/GRECLIPSE/e4.4
[INFO] Fetching p2.index from http://download.eclipse.org/releases/luna/201406250900/ (0B at 0B/s)
[INFO] Adding repository http://download.eclipse.org/releases/luna/201406250900
[INFO] Adding repository http://www.jupnp.org/update-site/2.2.0
[INFO] Adding repository http://hstaudacher.github.io/osgi-jax-rs-connector/5.3.0
[INFO] Adding repository http://download.eclipse.org/paho
[INFO] Adding repository http://eclipse.github.io/smarthome/third-party/target/repository
[ERROR] Failed to resolve target definition /home/shankar/Documents/esh_clone/smarthome/targetplatform/smarthome.target: Could not find "javax.measure.unit-api/0.8.0" in the repositories of the current location -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MavenExecutionException
 

Please can you suggest any fix for this. 
maven version 3.3.9
openjdk 8
ubuntu 16.04 64 bit

**Comment by kaikreuzer** [comment] 2017-01-03 10:20
Should be solved as soon as #2732 is merged.
The easy workaround for you is to remove the reference to unit-api and unit-ri in the smarthome.target file.

**Comment by sjka** [comment] 2017-01-04 09:57
as it merged now this issue is solved, right?

**Comment by kaikreuzer** [comment] 2017-01-04 09:58
I would say so.

**Closed by kaikreuzer** 2017-01-04 09:58 UTC

**Comment by IOOOTAlan** [comment] 2017-03-02 12:01
Where those two artifacts removed again? 
0.9.0-b2 seems to be broken again today...

**Comment by maggu2810** [comment] 2017-03-02 15:33
@IOOOTAlan You are right
Caused by: https://github.com/eclipse/smarthome/commit/98ad74e10e05a715c131a41cb1280f2d28632809
Related: https://github.com/eclipse/smarthome/pull/1857#issuecomment-283598036

We need to define how we should proceed with that custom p2 repos.
Perhaps we need to create a p2 repo for every ref build and refer to this one in the ref-build itself.
IMHO this is the only way to keep old builds to be build in future to.

The normal p2 repo could be kept as a moving target for the current master, but the ref-tag tool should create a p2 repo and use that for the currently build itself.
This should solve the situation then for future ref-tags.

**Comment by kaikreuzer** [comment] 2017-03-02 15:45
Oops, sorry, maybe I should have removed it only when doing the next beta release...

I am not sure if we can/should provide p2 repos of un-approved dependencies - I'd prefer not to, even if this means that older ref-tags are potentially not buildable anymore.

@IOOOTAlan Why do you need to build it from sources at all, if there are the binaries available in the Maven repo? And IF you are building a custom fork, you can very easily fix the build problem by removing the libs from the smarthome.target file (as they are anyhow not needed).

**Comment by maggu2810** [comment] 2017-03-02 15:53
> I am not sure if we can/should provide p2 repos of un-approved dependencies - I'd prefer not to, even if this means that older ref-tags are potentially not buildable anymore.

Ah, I remember our previous discussion.
An approved dependency could be revoked, this has to be removed, regardless if it breaks something.

**Comment by IOOOTAlan** [comment] 2017-03-02 16:01
Sorry @kaikreuzer , I guess my wording could sound ambiguous: our build currently references ESH maven artifacts, so the problem is that the target platform used throughout the build points to the same repository location of the latest versions, where those versions were recently removed, resulting in a failed build process because of missing target platform dependencies.
If there's no other way out of this we'll just have to update to the latest versions, I guess.
May I ask if there's documentation on breaking changes between the various versions? I try to keep up to date on the project, but I could've missed something important...

**Comment by kaikreuzer** [comment] 2017-03-02 16:19
> If there's no other way out of this we'll just have to update to the latest versions, I guess.

As a temporary measure, I could bring back the two artifacts on the p2 site again.

Nonetheless, upgrading might make sense as there is by now already a 0.9.0.b4 (which will have the same build issues, though...)

> May I ask if there's documentation on breaking changes between the various versions?

I have tried to mark all potentially breaking changes with the "APIBreaking" label: https://github.com/eclipse/smarthome/pulls?q=is%3Apr+is%3Aclosed+label%3AAPIBreaking

**Comment by kaikreuzer** [comment] 2017-03-02 16:23
FTR: https://github.com/eclipse/smarthome/pull/3107

**Comment by IOOOTAlan** [comment] 2017-03-02 16:53
Thank you very much @kaikreuzer , for both the PR and info :wink:
