### ISSUE TITLE
Bug in ThingHandlerCallback#changeThingTyp: timing issues

### ISSUE THREAD

**Issue by afuechsel** [eclipse/smarthome#1605] opened 2016-06-03 13:34 UTC
It happens during changing of the thing type of several things at the same time, that some of these things end up in INITIALIZED state afterwards (not ONLINE). It has been analyzed, that the handler initiating the migration is not correctly removed but still handles the thing with the new changed thing type initiating another migration which then fails.

```` 
Cannot notify handler about updated thing hue:extended_color_light, because thing is not initialized (must be in status ONLINE or OFFLINE).
...
Changed ThingType of Thing hue:LCT001:001788141f1a:2 to hue:extended_color_light. New ThingHandler is com.qivicon.binding.hue.migration.HueMigratorHandler@3cd7ef.
````

**Comment by maggu2810** [comment] 2016-06-03 14:25
Is this a duplicate of #1506?

**Comment by sjka** [comment] 2016-06-06 08:07
Not really sure, but it might. I'm having a look...

**Comment by sjka** [comment] 2016-06-07 10:54
After analyzing @afuechsel's logs, it looks like for one of the Hue bulbs the ThingHandler did not get removed entirely, i.e. I can see the attempt to remove it, but it never actually happened, so no serviceRemoved events were triggered in time. I basically see two possible reasons for it: Either it happened asynchronously and the changeThingType didn't wait for it to finish so there was no new ThingHandler created, or there were two ThingHandlerFactories for the same ThingType registered so the one being asked to clean up didn't know the ThingHandler in its cache failing silently because of the NULL guard. As the serviceRemoved events never arrived, I would assume the latter. 
Nevertheless, I created #1629 which fixes the first case and would detect the later one, failing more loudly than before.

**Comment by sjka** [comment] 2016-06-08 13:23
@afuechsel could you please verify that #1629 indeed fixes this issue?

**Comment by afuechsel** [comment] 2016-06-08 13:57
Having done my migration back and forth 3 times now it seems that #1629 fixes this issue.

**Closed** 2016-06-09 07:53 UTC
