### ISSUE TITLE
Thread pool issues on Thing update State

### ISSUE THREAD

**Issue by bpesty** [eclipse/smarthome#5746] opened 2018-06-18 08:39 UTC
In our project we have an ESH binding to get and show 
image from an ipcam. We call the ipcam each second to get 
a new image, and than update the state of our Thing Handler.

We've noticed that while the binding is running (we are updating 
an image view each second) there is an increase of threads in our
application, and when we close the binding it stops. Our binding appears to spawn about 150 threads, and then the expansion stops. 

We did some debugging, and observed that the point where the threads started to 
increase is inside the updateState method, inside the BaseThingHandler class. 
The exact point seems to be inside the OsgiEventManager class, where it publishes
the event on the EventAdmin, every time it does eventAdmin.postEvent we observe 
the threads increase.
It's curious that the threads will never decrease even if we stop polling the camera (keeping the binding up and running): they stay there for hours. Only when we stop the binding they are suddendly all closed.

Did somebody observe a simile behavior? Is it attended and normal?

**Comment by kaikreuzer** [comment] 2018-06-18 08:45
Does not sound intended nor normal. Would you be able to provide a thread dump or at least an excerpt from it, which shows who is actually holding / keeping alive those threads?

**Comment by bpesty** [comment] 2018-06-18 11:28
[threads.txt](https://github.com/eclipse/smarthome/files/2111059/threads.txt)
@kaikreuzer attached a thread dump that i was able to extract from karaf.

**Comment by kaikreuzer** [comment] 2018-06-18 11:35
Thanks @bpesty!
It looks as if the culprit is some code that creates the "pool-31" thread pool. Within the ESH code, we always created named thread pools afaik (@sjka can you confirm this for all the stuff in the communication manager as well?), so I'd assume that this problem is NOT within the framework itself, but caused by some extension/binding - maybe your own?

**Comment by sjka** [comment] 2018-06-18 12:14
As you tracked it down to the moment when an OSGi event is fired, this doesn't necessarily mean that the OsgiEventManager or the EventAdmin themselves are the culprits. You should actually widen the search scope to all event receivers, including (but not limited to) implementors of the EventSubscriber interface. Unfortunately your threaddump doesn't help much, as they are all idle. Maybe you can catch one "red handed", i.e. at the moment in time when at least one of them is actually doing something. That would give a better indication how they are spawned (btw, `kill -3 <PID>` will make most JVMs write a thread dump to standard out, if that helps). 

Regarding @kaikreuzer's question about "the stuff": The `CommunicationManager` is also only using the `SafeCaller`, which in turn makes use of the `ThreadPoolManager` to instantiate a named thread pool:

https://github.com/eclipse/smarthome/blob/5156d01972a6d5dde1fc83c680ee9e7577f3743f/bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/internal/common/SafeCallerImpl.java#L77-L79

Therefore they should be easily identifiable (as threads named `safeCall-...`) and will not grow beyond their max capacity (of 5 by default). I think we can tick that one off the list.

What puzzles me a little is the fact that these aren't in your thread dump... Considering that your bindings sends updates every second it seems unlikely to me that they all died of boredom (they have an idle timeout of 65s). Which leads me to another question: What version/commit/state of the Eclipse SmartHome framework are we talking about?

**Comment by bpesty** [comment] 2018-06-19 07:51
As @sjka suggested I did some search in our code on the event receiver(s) side, and it seems that we  found the source of the augmenting threads.  
Currently we are on the stable 0.9.0 version. 
Thank you for your time and precocious tips!

**Comment by sjka** [comment] 2018-06-19 10:53
Sure, no problem. I'm glad I could help. 

Let us know in case some traces lead back to the framework or if you see anything missing which could help developing bindings safely in that aspect. In the meantime I suggest to close this issue here.

**Closed by sjka** 2018-06-19 10:53 UTC
