### ISSUE TITLE
 [Homematic] Partial no updates from homematic binding

### ISSUE THREAD

**Issue by e36Alex** [eclipse/smarthome#6230] opened 2018-09-18 17:45 UTC
Hello,

i am trying out homematic binding two things, a radiator valve (HM-CC-RT-DN) and a door sensor (HmIP-SRH). if a value of the radiator valve changes, it gets updated in openhab. if the door sensor changes its state, there is no update to openhab - i have to “reload from gateway” to get the new values.

in the log i got no errors (even no entries at loglevel debug or trace), so i even integrated homematic in an test-installation of iobroker - there the state of the sensor changes immidiatly, so it should be a problem on openhab.

actually i am using 2.4.0 Build #1365 but had the same problem on 2.4M2 and 2.4M3.

https://community.openhab.org/t/partial-no-updates-from-homematic-binding/51582

## Expected Behavior
State of the HmIP-SRH should update directly after change.

## Current Behavior
Stata of the HmIP-SRH changes just, if i reload all values from the gateway

## Possible Solution
-

## Steps to Reproduce (for Bugs)
1. Open or close a window
2. Check out, if state in homematic, openhab and iobroker changes

## Context
-

## Your Environment
Distributor ID: Debian
Description: Debian GNU/Linux 9.5 (stretch)
Release: 9.5
Codename: stretch

OpenHAB 2.4.0 Build #1365 but had the same problem on 2.4M2 and 2.4M3

Homematic CCU3

Thanks for help!

Alex

**Comment by e36Alex** [comment] 2018-09-26 17:41
Hello,

today i got a few more hmip-devices for testing - it seems like the problem is depending on homematic ip, because i got the same problem with all hm-ip devices.

now i tried out to set some parameters in the thing-file to the default values. and now i get the following message in the logs:


```   
Bridge homematic:bridge:ccu3 [ gatewayAddress="192.168.178.65", callbackHost="192.168.178.11", xmlCallbackPort="9125", hmIpPort="2010"]

```


```   
21:26:11.705 [ERROR] [unicator.server.BinRpcResponseHandler] - No BinX signature
java.io.UnsupportedEncodingException: No BinX signature
        at org.eclipse.smarthome.binding.homematic.internal.communicator.message.BinRpcMessage.validateBinXSignature(BinRpcMessage.java:106) [203:org.eclipse.smarthome.binding.homematic:0.10.0.oh240M3]
        at org.eclipse.smarthome.binding.homematic.internal.communicator.message.BinRpcMessage.<init>(BinRpcMessage.java:82) [203:org.eclipse.smarthome.binding.homematic:0.10.0.oh240M3]
        at org.eclipse.smarthome.binding.homematic.internal.communicator.server.BinRpcResponseHandler.run(BinRpcResponseHandler.java:48) [203:org.eclipse.smarthome.binding.homematic:0.10.0.oh240M3]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
        at java.lang.Thread.run(Thread.java:748) [?:?]
21:26:11.725 [ERROR] [unicator.server.BinRpcResponseHandler] - No BinX signature
java.io.UnsupportedEncodingException: No BinX signature
        at org.eclipse.smarthome.binding.homematic.internal.communicator.message.BinRpcMessage.validateBinXSignature(BinRpcMessage.java:106) [203:org.eclipse.smarthome.binding.homematic:0.10.0.oh240M3]
        at org.eclipse.smarthome.binding.homematic.internal.communicator.message.BinRpcMessage.<init>(BinRpcMessage.java:82) [203:org.eclipse.smarthome.binding.homematic:0.10.0.oh240M3]
        at org.eclipse.smarthome.binding.homematic.internal.communicator.server.BinRpcResponseHandler.run(BinRpcResponseHandler.java:48) [203:org.eclipse.smarthome.binding.homematic:0.10.0.oh240M3]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
        at java.lang.Thread.run(Thread.java:748) [?:?]
```

**Comment by FStolte** [comment] 2018-09-27 11:28
Hello @e36Alex,

Regarding the error you received after setting some parameters in the thing-file: I can see that you have specified the xmlCallbackPort, but not the binCallbackPort. The stacktrace shows that the binding is using a BinRpcServer for communication to the CCU. Can you try to also specify a binCallbackPort (default is 9126) and check if the error remains?

The error message suggests that the CCU sent a request which was not a valid Bin-Rpc call. My assumption is that the CCU tries to send Xml-Rpc messages to the binding, which expects Bin-Rpc messages.

In any case, this very likely points to a bug in the binding, since I would not expect the CCU to send falsely formatted Bin-Rpc requests under any circumstances if it is not defect.

**Comment by e36Alex** [comment] 2018-09-27 17:49
Hello @FStolte ,

adding the the binCallbackPort resolved the problem with the error message at the log, but the items still dont get an update by the ccu3 after a change of the state. the manual refresh still works fine.

**Comment by MHerbst** [comment] 2018-09-30 10:55
It does not seem to be a general problem with all HmIP devices. I have got a dimmable power outlet (HmIP-PDT) and I have performed the following test:

- Switched the device on/off via the CCU: openHAB 2.4 M4 shows the new state automatically (at least in Paper UI)
- Changed the level on the CCU: the new level is shown automatically in PaperUI; only in my first test the level in PaperUI was not updated (but the events.log contained a message, so it was received correctly).

I have tested with openHAB 2.4 M4 in an Ubuntu 18.04 VM. As CCU I am using a Raspi with Raspberrymatic 3.37.8.20180929. This should be very similar to a CCU3. I have configured the bridge in PaperUI and set only the gateway IP address and no other settings.

**Comment by e36Alex** [comment] 2018-09-30 16:18
This is the a part of the ccu3-log after a restart of the ccu:
`Sep 30 18:12:04 de.eq3.cbcs.legacy.bidcos.rpc.LegacyServiceHandler INFO  [vert.x-worker-thread-0] (un)registerCallback on LegacyServiceHandler called from url: http://127.0.0.1:9292/bidcos 
Sep 30 18:12:04 de.eq3.cbcs.legacy.bidcos.rpc.LegacyServiceHandler INFO  [vert.x-worker-thread-0] init finished 
Sep 30 18:12:04 de.eq3.cbcs.legacy.bidcos.rpc.internal.InterfaceInitializer INFO  [vert.x-worker-thread-3] Added InterfaceId: HmIP-RF_java 
Sep 30 18:12:04 de.eq3.cbcs.legacy.bidcos.rpc.internal.DeviceUtil INFO  [vert.x-worker-thread-3] updateDevicesForClient HmIP-RF_java -> 24 device addresses will be added 
Sep 30 18:12:05 de.eq3.ccu.server.BaseHMServer INFO  [Thread-2] Starting HMServer done 
Sep 30 18:12:08 de.eq3.cbcs.legacy.bidcos.rpc.LegacyServiceHandler INFO  [vert.x-worker-thread-4] (un)registerCallback on LegacyServiceHandler called from url: http://192.168.178.11:9125 
Sep 30 18:12:08 de.eq3.cbcs.legacy.bidcos.rpc.LegacyServiceHandler INFO  [vert.x-worker-thread-4] init finished 
Sep 30 18:12:08 de.eq3.ccu.virtualdevice.service.internal.rega.VirtualDeviceHandlerRega INFO  [vert.x-eventloop-thread-4] (un)registerCallback on VirtualDeviceHandlerRega called from url: http://192.168.178.11:9125 
Sep 30 18:12:08 de.eq3.cbcs.legacy.bidcos.rpc.LegacyServiceHandler INFO  [vert.x-worker-thread-0] (un)registerCallback on LegacyServiceHandler called from url: http://192.168.178.11:9125 
Sep 30 18:12:08 de.eq3.cbcs.legacy.bidcos.rpc.LegacyServiceHandler INFO  [vert.x-worker-thread-0] init finished 
Sep 30 18:12:08 de.eq3.cbcs.legacy.bidcos.rpc.internal.InterfaceInitializer INFO  [vert.x-worker-thread-3] Added InterfaceId: HMIP-ccu3 
Sep 30 18:12:08 de.eq3.ccu.virtualdevice.service.internal.rega.VirtualDeviceHandlerRega INFO  [vert.x-eventloop-thread-4] (un)registerCallback on VirtualDeviceHandlerRega called from url: http://192.168.178.11:9125 
Sep 30 18:12:08 de.eq3.ccu.virtualdevice.service.internal.rega.VirtualDeviceHandlerRega INFO  [vert.x-eventloop-thread-4] Added InterfaceId: GROUP-ccu3 
Sep 30 18:12:08 de.eq3.ccu.virtualdevice.service.internal.rega.BackendWorker INFO  [vert.x-worker-thread-11] Execute BackendCommand: de.eq3.ccu.virtualdevice.service.internal.rega.BackendUpdateDevicesCommand 
Sep 30 18:12:08 de.eq3.cbcs.legacy.bidcos.rpc.internal.InterfaceInitializer ERROR [vert.x-worker-thread-3] IO Exception: Could not add interface: HMIP-ccu3 
de.eq3.cbcs.legacy.communication.rpc.RpcIOException: java.net.ConnectException: Connection refused (Connection refused)
	at de.eq3.cbcs.legacy.communication.rpc.internal.transport.http.HttpTransport.sendRequest(HttpTransport.java:90)
	at de.eq3.cbcs.legacy.communication.rpc.internal.rpc.RpcClient.sendRequest(RpcClient.java:99)
	at de.eq3.cbcs.legacy.communication.rpc.internal.rpc.RpcClient.invoke(RpcClient.java:87)
	at com.sun.proxy.$Proxy21.listDevices(Unknown Source)
	at de.eq3.cbcs.legacy.bidcos.rpc.internal.LegacyBackendClient.listDevices(LegacyBackendClient.java:140)
	at de.eq3.cbcs.legacy.bidcos.rpc.internal.DeviceUtil.synchronizedBackendDevices(DeviceUtil.java:116)
	at de.eq3.cbcs.legacy.bidcos.rpc.internal.InterfaceInitializer.handle(InterfaceInitializer.java:107)
	at de.eq3.cbcs.legacy.bidcos.rpc.internal.InterfaceInitializer.handle(InterfaceInitializer.java:31)
	at io.vertx.core.eventbus.impl.HandlerRegistration.deliver(HandlerRegistration.java:212)
	at io.vertx.core.eventbus.impl.HandlerRegistration.handle(HandlerRegistration.java:191)
	at io.vertx.core.eventbus.impl.EventBusImpl.lambda$deliverToHandler$3(EventBusImpl.java:505)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:337)
	at io.vertx.core.impl.TaskQueue.lambda$new$0(TaskQueue.java:60)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:120)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:179)
	at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:144)
	at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:134)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:612)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:447)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:884)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
	at de.eq3.cbcs.legacy.communication.rpc.internal.transport.http.HttpTransport.sendRequest(HttpTransport.java:86)
	... 15 more
Sep 30 18:12:18 de.eq3.ccu.virtualdevice.service.internal.rega.VirtualDeviceHandlerRega INFO  [vert.x-eventloop-thread-4] (un)registerCallback on VirtualDeviceHandlerRega called from url: xmlrpc_bin://127.0.0.1:1999 
Sep 30 18:12:18 de.eq3.ccu.virtualdevice.service.internal.rega.VirtualDeviceHandlerRega INFO  [vert.x-eventloop-thread-4] Added InterfaceId: 1008 
Sep 30 18:12:18 de.eq3.ccu.virtualdevice.service.internal.rega.BackendWorker INFO  [vert.x-worker-thread-12] Execute BackendCommand: de.eq3.ccu.virtualdevice.service.internal.rega.BackendUpdateDevicesCommand 
Sep 30 18:12:28 de.eq3.cbcs.legacy.bidcos.rpc.LegacyServiceHandler INFO  [vert.x-worker-thread-3] (un)registerCallback on LegacyServiceHandler called from url: xmlrpc_bin://127.0.0.1:1999 
Sep 30 18:12:28 de.eq3.cbcs.legacy.bidcos.rpc.LegacyServiceHandler INFO  [vert.x-worker-thread-3] init finished 
Sep 30 18:12:28 de.eq3.cbcs.legacy.bidcos.rpc.internal.InterfaceInitializer INFO  [vert.x-worker-thread-1] Added InterfaceId: 1009 `

**Comment by e36Alex** [comment] 2018-10-01 17:13
I dont think that the devices are the problem, because on a vm-installation i got no problems with them and the ccu3. Also i get all state updates, if i use the "reload all from ccu" switch.

Yesterday i set up my whole system completely new, because i thought it was depending on some point of my configuration - but even after a fresh install i got the same problem.

Also i did a Portscan yesterday and i was wondering that (at the relevant range) just the ports 9124 and 9126 where shown by the portscanner. So i changed the Ports by the thing file, but the xml-port (9125) was still invisible, in spite of no active firewall that could be blocking the port. Maybe this is even the reason, why the ccu logs the error.

**Comment by e36Alex** [comment] 2018-10-01 20:22
Now i checked, if the port 9125 is open with:
`lsof -i -n -P`
the result:
`java      1189  openhab   79u  IPv6  37065      0t0  TCP 127.0.1.1:9125 (LISTEN)`

i am no expert in that, but the ip seems a bit curios to me?

to compare, this is how the discovered port 9126 looks like:
`java      1189  openhab  112u  IPv6 167450      0t0  TCP 192.168.178.11:9126 (LISTEN)`
(192.168.178.11 is the ip of my openhab-system)

**Comment by FStolte** [comment] 2018-10-02 07:32
This is definitely the source of your problem. For a CCU, the callback for Homematic uses BinRpc (port 9126), while the HmIP callback uses XmlRpc (port 9125). If this callback port is not reachable by the CCU, you won't get any events for HmIP. This is exactly what you described.

Now, I don't know why the IP address from the config is transformed into the loopback address 127.0.1.1, but it looks like this comes from Debian. Compare this section of the reference: https://www.debian.org/doc/manuals/debian-reference/ch05.en.html#_the_hostname_resolution

So without knowing what exactly goes wrong, here's a naive suggestion how to solve it: Add this entry to the beginning of your etc/hosts file: `192.168.178.11 ccu-callback`
Then, configure "ccu-callback" as the "callbackHost" for the bridge. Maybe this bypasses whatever Debian mechanism resolves the wrong address.

Since the resolving of the callbackHost happens in the class `java.net.InetSocketAddress`, I assume that the problem is on OS-side and not in the binding. So googling for known problems with resolving hostnames on Debian due to the 127.0.1.1 loopback address might find you a solution, if my suggestion doesn't work out.

**Comment by e36Alex** [comment] 2018-10-02 17:46
thank you very much for that, i think i am close to a solution now, but also have some questions:

> Since the resolving of the callbackHost happens in the class java.net.InetSocketAddress, I assume that the problem is on OS-side and not in the binding.
If the problem is in debian, why is there no problem with port 9126? i would expect the same behaviour there. even at other ports i dont have this problem (there are running a few other services on the system). so are you sure, it could not be in the binding?

i googled the problem and found the hint, so set the network interface from static ip to dhcp and then to tell the router always to assign the "right" ip.
when i set the system to dhcp, it really works! i can reach the port from the network - but if i set the ip at the router, i got the same problem again and cant detect the port.
do you have an idea why?

**Closed** 2018-10-03 18:48 UTC
Labels: Binding-Homematic

**Comment by FStolte** [comment] 2018-10-04 06:36
I'm glad I could help! :)
