### ISSUE TITLE
The first line in transformation map-files is ignored

### ISSUE THREAD

**Issue by tonyalpskog** [eclipse/smarthome#6502] opened 2018-11-11 19:21 UTC
openHAB version: 2.3.0-1
Ubuntu 18

I had a map file for transformation of a rain sensor state into swedish.
sv_rain.map

CLOSED=Uppehåll
OPEN=Nederbörd
NULL=Okänt
This was shown all over in the logs:

[WARN ] [rm.AbstractFileTransformationService] - Could not transform 'CLOSED' with the file 'sv_rain.map' : Target value not found in map for 'CLOSED'

During debug of this issue I put this line on top:
-=Okänt
Now the CLOSED transformation started to work.
So finally I just removed the "-=Okänt" and ended up with (empty first line):

CLOSED=Uppehåll
OPEN=Nederbörd
NULL=Okänt
This still works so I guess the first line is just ignored.

**Comment by kaikreuzer** [comment] 2018-11-12 11:43
Sorry, I cannot reproduce it with the openHAB demo setup.

Steps I did:
- Downloaded 2.3.0 from https://bintray.com/openhab/mvn/download_file?file_path=org%2Fopenhab%2Fdistro%2Fopenhab%2F2.3.0%2Fopenhab-2.3.0.zip
- Unzipped and started the runtime
- Chose "Demo" setup package
- checked that there's a file `conf/transform/en.map` with `CLOSED=closed` as a first line
- opened Basic UI at http://localhost:8080/basicui/app?w=020102&sitemap=demo
- Saw all window states correctly shown as "closed".

Could you please start from here and see what is special about your situation?

**Comment by tonyalpskog** [comment] 2018-11-12 16:11
After some further research (sorry didn't install a new vanilla setup) I noticed that the files causing trouble had different permissions.
I had two different set of files:
1. Files with openhab user as Owner [rw-] and Group [rw-], others as [r--]
  These files was all OK and causing no trouble.
2. Files with <my home user> as Owner [rw-] and Group [rw-], others as [r--]
  These files behaves like I described in this issue.

This situation occurred because I moved some files from my home user folders to the openhab folders.

**Comment by tonyalpskog** [comment] 2018-11-12 16:33
This is so weird. I just gave one of the home user files the exact same permissions as en.map and de.map has = Owner openhab [rw-], Group openhab [rw-], Other [r--]
But this this file still caused problems. Even after a service restart of openhab.

**Comment by tonyalpskog** [comment] 2018-11-12 16:35
I won't care about this issue any more. If you can't reproduce it even with this additional information, let's close it. There is a work-around after all...

**Comment by kaikreuzer** [comment] 2018-11-12 19:34
> If you can't reproduce it 

My question rather was whether YOU can reproduce it - the steps I mentioned above take less than 5 minutes to perform. So IF there is a bug, we should take this as a basis for analysis. So if you can make the demo setup break this way, we can be sure that there is some bug that can be analysed. If not, feel free to close the issue again.

**Closed** 2018-11-12 19:59 UTC
