### ISSUE TITLE
Dynamic channels defined in DSL are not created (re-open #1847)

### ISSUE THREAD

**Issue by kgoderis** [eclipse/smarthome#2042] opened 2016-08-25 08:26 UTC
Dynamic channels, defined in ESH-INF/, when declared through the DSL, are not created. This error occurs since the XML bundle loading refactoring.

In ESH-INF: [Abbreviated]

```
    <bridge-type id="ip">
        <label>KNX/IP gateway</label>
        <description>This Bridge is for IP based KNX gateways</description>
        
        <channels>
            <channel id="errorsall" typeId="errors" />
            <channel id="errors5min" typeId="errors" />
        </channels>
        
        <config-description> [Deleted]
        </config-description>
    </bridge-type>
    
[Deleted]
        
    <channel-type id="switch">
		<item-type>Switch</item-type>
		<label>Input/Output Channel</label>
		<description>The IO channel allows to read/write values from/to the group address</description>
		<config-description> [Deleted]
		</config-description>
	</channel-type>
```

in .things DSL Declaration:

```
Bridge knx:ip:ip1 [ ipAddress="192.168.0.10", portNumber=3671, localIp="192.168.0.200", ipConnectionType="TUNNEL", readingPause=50, responseTimeOut=1000, readRetriesLimit=3, autoReconnectPeriod=1,localSourceAddr="0.0.0" ] 
{
[Deleted]
Channels:
Switch : ga_8_5_2 [ address="8/5/2", dpt="1.001", read=true, autoupdate=true, interval=3600]
Switch : ga_8_5_3 [ address="8/5/3", dpt="1.001", read=true, autoupdate=true, interval=3600]
Switch : ga_8_5_4 [ address="8/5/4", dpt="1.001", read=true, autoupdate=true, interval=3600]
}
```

Then the Thing "ip1" only has the errorsall and errors5min channels, e.g. the dynamic channels ga_8_5_2 and others are not created. This happens only with Karaf, not in the IDE

Something is quite broken (including my operational environment :-()

**Comment by maggu2810** [comment] 2016-08-25 11:03
* I started my custom Karaf distribution that is using Eclipse SmartHome, too.
* I installed the Yahoo Weather binding feature
* I have added a test.things file (containing an additional channel)
* I see the thing with the additional channel in the Paper UI
* I restarted the custom distribution (keep the feature installed and the test.things in the FS)
* I reloaded the Paper UI and does NOT see the additional channel
* I touched the test.things file, to force a refresh of the file in the ESH instance
* I reloaded the Paper UI and see the additional channel

So, I assume I can say: I can reproduce the problem you have :wink:

**Comment by sjka** [comment] 2016-08-26 08:54
funny, as the XML loading change only defers the handler initialization, but nothing else. Anyway, that does not sound good. Thanks for the detailed analysis, I will have a look...

**Comment by sjka** [comment] 2016-08-26 09:14
looks like the culprit is #365 - when the ThingHandlerFactory is not yet ready, there will be Thing created during retry, but that's not merged with the stuff coming from the DSL.
Will provide a fix.

**Closed** 2016-09-02 20:21 UTC
