### ISSUE TITLE
dispatch.test FAIL

### ISSUE THREAD

**Issue by ehousepro** [eclipse/smarthome#4758] opened 2017-12-16 11:04 UTC
I have following  failure while doing "mvn clean install" of smarthome git (Win 10).
This Git exists in recent openhab2 repository
I'm not sure if problem resides on Eclipse or openhab2 side.

-------------------------------------------------------------------------------
Test set: org.eclipse.smarthome.config.dispatch.test.ConfigDispatcherOSGiTest
-------------------------------------------------------------------------------
Tests run: 27, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 25.014 sec <<< FAILURE! - in org.eclipse.smarthome.config.dispatch.test.ConfigDispatcherOSGiTest
allConfigurationFilesWithGlobalPIDsAreProcessedAndConfigurationIsUpdated(org.eclipse.smarthome.config.dispatch.test.ConfigDispatcherOSGiTest)  Time elapsed: 0.504 sec
whenExclusivePIDFileIsDeleted_DeleteTheConfiguration(org.eclipse.smarthome.config.dispatch.test.ConfigDispatcherOSGiTest)  Time elapsed: 0.457 sec
propertiesForTheSameGlobalPIDInDifferentFilesMustBeOverriddenInTheOrderTheyWereLastModified(org.eclipse.smarthome.config.dispatch.test.ConfigDispatcherOSGiTest)  Time elapsed: 0.468 sec
ifThereIsNoPropertyValuePairForGlobalPIDAConfigurationWithTheGivenPIDWillNotExist(org.eclipse.smarthome.config.dispatch.test.ConfigDispatcherOSGiTest)  Time elapsed: 0.407 sec
valueIsStillValidIfItIsLeftEmpty(org.eclipse.smarthome.config.dispatch.test.ConfigDispatcherOSGiTest)  Time elapsed: 0.484 sec
PropertyValuePairsForALocalPIDInDifferentFilesAreStillAssociatedWithThatPID(org.eclipse.smarthome.config.dispatch.test.ConfigDispatcherOSGiTest)  Time elapsed: 0.453 sec
allConfigurationFilesWithLocalPIDsAreProcessedAndConfigurationIsUpdated(org.eclipse.smarthome.config.dispatch.test.ConfigDispatcherOSGiTest)  Time elapsed: 0.485 sec
propertiesForLocalPIDCanBeOverridden(org.eclipse.smarthome.config.dispatch.test.ConfigDispatcherOSGiTest)  Time elapsed: 0.453 sec
whenExclusivePIDisDefinedInlineFromDifferentFile_skipTheLine(org.eclipse.smarthome.config.dispatch.test.ConfigDispatcherOSGiTest)  Time elapsed: 0.469 sec
IfNoPIDIsDefinedInConfigurationFileWithNo_dotNameTheDefaultNamespacePlusTheFileNameBecomesPID(org.eclipse.smarthome.config.dispatch.test.ConfigDispatcherOSGiTest)  Time elapsed: 0.468 sec
localPIDIsOverriddenByGlobalPIDInDifferentFileIfTheFileWithTheGlobalOneIsModifiedLast(org.eclipse.smarthome.config.dispatch.test.ConfigDispatcherOSGiTest)  Time elapsed: 0.469 sec
whenPropertyValuePairsForAGlobalPIDAreInDifferentFilesPropertiesWillNotBeMerged(org.eclipse.smarthome.config.dispatch.test.ConfigDispatcherOSGiTest)  Time elapsed: 0.469 sec
whenTheConfigurationFileNameContainsDotAndNoPIDIsDefinedTheFileNameBecomesPID(org.eclipse.smarthome.config.dispatch.test.ConfigDispatcherOSGiTest)  Time elapsed: 0.485 sec
whenLocalPIDIsDefinedForGlobalPIDFile_AbortParsing(org.eclipse.smarthome.config.dispatch.test.ConfigDispatcherOSGiTest)  Time elapsed: 0.453 sec
whenLocalPIDIsAnEmptyStringTheDefaultNamespacePlusDotIsTheOverallPID(org.eclipse.smarthome.config.dispatch.test.ConfigDispatcherOSGiTest)  Time elapsed: 0.468 sec
ifPropertyIsLeftEmptyAConfigurationWithTheGivenPIDWillNotExist(org.eclipse.smarthome.config.dispatch.test.ConfigDispatcherOSGiTest)  Time elapsed: 0.409 sec
whenLocalPIDDoesNotContainDotTheDefaultNamespacePlusThatPIDIsTheOverallPID(org.eclipse.smarthome.config.dispatch.test.ConfigDispatcherOSGiTest)  Time elapsed: 0.468 sec
whenExclusiveConfigFileIsDeleted_shouldRemoveConfigFromConfigAdmin(org.eclipse.smarthome.config.dispatch.test.ConfigDispatcherOSGiTest)  Time elapsed: 12.973 sec  <<< FAILURE!
java.lang.AssertionError: The configuration with properties for the given pid was found but should have been removed.
Expected: is null
     but: was <org.eclipse.equinox.internal.cm.ConfigurationDictionary@2abf4075>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.eclipse.smarthome.config.dispatch.test.ConfigDispatcherOSGiTest.lambda$1(ConfigDispatcherOSGiTest.java:599)

propertiesForTheSameLocalPIDInDifferentFilesMustBeOverriddenInTheOrderTheyWereLastModified(org.eclipse.smarthome.config.dispatch.test.ConfigDispatcherOSGiTest)  Time elapsed: 0.469 sec
ifThePropertyIsNotPrefixedWithLocalPIDTheLastPIDBecomesPIDForThatProperty(org.eclipse.smarthome.config.dispatch.test.ConfigDispatcherOSGiTest)  Time elapsed: 0.484 sec
ifThePropertyValuePairIsPrefixedWithLocalPIDInTheSameFileTheGlobalPIDIsIgnored(org.eclipse.smarthome.config.dispatch.test.ConfigDispatcherOSGiTest)  Time elapsed: 0.469 sec
commentLinesAreNotProcessed(org.eclipse.smarthome.config.dispatch.test.ConfigDispatcherOSGiTest)  Time elapsed: 0.406 sec
whenGlobalPIDIsEmptyStringItRemainsAnEmptyString(org.eclipse.smarthome.config.dispatch.test.ConfigDispatcherOSGiTest)  Time elapsed: 0.453 sec
propertiesForPIDInFilesInServicesDirectoryMustOverrideDefaultProperties(org.eclipse.smarthome.config.dispatch.test.ConfigDispatcherOSGiTest)  Time elapsed: 0.469 sec
globalPIDIsOverriddenByLocalPIDInDifferentFileIfTheFileWithTheLocalOneIsModifiedLast(org.eclipse.smarthome.config.dispatch.test.ConfigDispatcherOSGiTest)  Time elapsed: 0.469 sec
txtFilesAreNotProcessed(org.eclipse.smarthome.config.dispatch.test.ConfigDispatcherOSGiTest)  Time elapsed: 0.406 sec
whenExclusiveConfigIsTruncated_OverrideReducedConfig(org.eclipse.smarthome.config.dispatch.test.ConfigDispatcherOSGiTest)  Time elapsed: 0.532 sec

**Comment by triller-telekom** [comment] 2017-12-18 14:28
I guess this is a duplicate of #4370, like #4734, which will hopefully be solved by PR #4685

**Closed** 2018-01-03 14:13 UTC
Labels: Test
