### ISSUE TITLE
 Paper UI: Control page not working properly in high (4K) resolutions

### ISSUE THREAD

**Issue by jangrewe** [eclipse/smarthome#4759] opened 2017-12-16 14:03 UTC
On the Control page, all Items in any location tab except the first one are stacked and can not really be used anymore.
There is also no sliding animation when switching tabs.

It looked fine with v2.1, but i thought going to 2.2 would be reasonably safe, considering the late stage of development

## Expected Behavior
I was expecting the Things/Items to be placed next to each other.

## Current Behavior
The tab for any location other than the very first stacks all Things on top of each other.

## Steps to Reproduce (for Bugs)
1. install openHABian
2. use `openhabian-config` to switch to the current snapshot
3. put separate things into separate locations with `@ "somewhere"`

## Your Environment
* Version used: 2.2.0~20171216031002-1 (openHABian)
* Environment name and version: current Firefox and Chrome
* Operating System and version: Windows 10

![Screenshot](https://screenshots.firefoxusercontent.com/images/011166be-2c2b-4465-8107-147839ca807a.png)

**Comment by jangrewe** [comment] 2017-12-16 16:21
I finally found the reason why it worked fine on a different computer, but doesn't work on my desktop machine: 4K resolution.
If i resize the browser window (even on the 4K screen), the cards slide into place.
Looks like some faulty JS calculation...

**Comment by triller-telekom** [comment] 2017-12-18 15:44
I can reproduce this issue though it is a bit tricky to do so.

* You have to have things in two different "Locations", so you have two tabs in the control page.
* While being on the first tab, resize the window do a very small size: Everything is fine.
* Switch to the second tab while keeping the window small: Everything is still fine.
* Making the second tab full screen: All controls are reorganized and everything is OK
* Switch to the first tab and see some controls stacked onto each other.

But i think this is just due to a missing refresh because if I press "F5", the controls will reorganize itself and everything looks OK again.

**Comment by jangrewe** [comment] 2017-12-18 16:22
For me it's even easier to reproduce:
- Have things in two different locations
- Open the control page on a high resolution screen
- Click on the second tab

The first tab will always look correct, any other tabs will always be stacked - no need to resize the window to trigger this ;-)

**Comment by htreu** [comment] 2017-12-19 13:26
Right now 1680x1050 is the largest I can test with. With this resolution everything works fine. I will check again in the office tomorrow in case a 4k Display is available.

**Comment by htreu** [comment] 2017-12-19 14:04
@triller-telekom I proposed a fix with https://github.com/htreu/smarthome/commit/74ccfed14fcf00b507fbf4d9a465780e167f131e. Maybe you can give it a try on your screen before I submit a PR to ESH.

**Comment by triller-telekom** [comment] 2018-01-08 12:08
With the fix https://github.com/htreu/smarthome/commit/74ccfed14fcf00b507fbf4d9a465780e167f131e  from @htreu I cannot reproduce the issue anymore. All controls are aligned next to/below each other.

**Comment by jangrewe** [comment] 2018-01-08 12:53
Great, thanks @htreu and @triller-telekom! Looking forward to the merge...

**Comment by kaikreuzer** [comment] 2018-01-08 13:42
Before anything can be merged, @htreu should create a PR for it :-)

**Closed** 2018-01-08 14:34 UTC

**Comment by jangrewe** [comment] 2018-02-09 18:50
Hi, i just upgraded to OH 2.2 - was this fix included in that release? Because if it was, it didn't work. :-(

**Comment by sjka** [comment] 2018-02-09 19:38
openHAB 2.2 was released in Dec 2017, the fix (#4876) was done in Jan 2018, so: No.

**Comment by jangrewe** [comment] 2018-02-09 20:00
Oh, how time flies... i didn't look at the release date, sorry.

**Comment by sjka** [comment] 2018-02-09 20:08
No problem 😄
