### ISSUE TITLE
Basic UI Incremental Refresh not working for group count updates

### ISSUE THREAD

**Issue by Dizlem** [eclipse/smarthome#2478] opened 2016-11-17 10:22 UTC
When using Basic UI if a group state changes e.g. a set of lights, the symbol changes from green to red or visa versa but the group count in brackets does not auto update on the web page (it is all correct following an F5 refresh). Same on all my groups.

This works on the iOS app and the Classic UI just not in the Basic UI, so Kai has suggested this is a bug in the new incremental refresh process for Basic UI.

I have a pretty standard group setup in my .items file:

Group:Switch:OR(ON, OFF) Lights "All Lights [(%d)]"

**Comment by lolodomo** [comment] 2016-11-17 14:02
That looks like a duplicate of my issue #2443.

**Comment by kaikreuzer** [comment] 2016-11-17 14:04
Yes, you are right. Closing as duplicate then.

**Closed by kaikreuzer** 2016-11-17 14:04 UTC
Labels: BasicUI, bug
