### ISSUE TITLE
Prevent hidden files from being parsed

### ISSUE THREAD

**Issue by snoekieboe** [eclipse/smarthome#2100] opened 2016-09-02 08:01 UTC
When using Mac OS X to edit Openhab files through an SMB share, files with a leading ._ are created by Mac OS X to store file information about the actual file in.

**Example:**
Create/edit a file called "test.item" using OS X finder application  and Mac OS X also creates a file called "._test.item".

Although these ._ files do not contain any valid information for Openhab, they are being parsed causing problems in mainly the Openhab rule engine.
This leads to errors in the Openhab log like:

2016-09-02 09:54:45.764 [ERROR] [.script.engine.ScriptExecutionThread] - Rule 'Pantry light motion': Script interpreter couldn't be obtain

2016-09-01 15:47:55.026 [WARN ] [pse.smarthome.core.items.GenericItem] - failed notifying listener '[org.eclipse.smarthome.model.rule.runtime.internal.engine.RuleEngineImpl@1ec05f5, Home_State, null]' about state update of item java.lang.NullPointerException: {}

Perhaps preventing the ._ files to be parsed would help in preventing issues caused by these files?

**Comment by kaikreuzer** [comment] 2017-04-21 13:54
Is this a duplicate of https://github.com/eclipse/smarthome/issues/2854?

**Comment by maggu2810** [comment] 2017-04-22 11:51
I think so

**Closed** 2017-04-27 09:28 UTC
Labels: bug
