### ISSUE TITLE
[Tradfri] Binding bug

### ISSUE THREAD

**Issue by tam481** [eclipse/smarthome#3869] opened 2017-07-20 20:44 UTC
**Expected Behavior**

I expect the switch item to always reflect the status of the light.

**Current Behavior**

A while after configuring the binding and linking the dimmer item with the bulb the status of the light is no longer reflected. The light can be controlled through the dimmer item but its status is no longer update if the light is switched on/off or the brightness changes using the Tradfri Android app or the physical remote/dimmer.

**Possible Solution**

**Steps to Reproduce (for Bugs)**

Configure binding
Assign dimmer item to "tradfri channel"
Use as normal. Check using the physical remote and app and the status updates correctly on OpenHAB.
A while later....
Binding works to control the light but is no longer receiving status update.
Context

I cannot get the status of the light as it stops changing to reflect the actual status if turned on using the IKEA Tradfri remote. The IKEA Tradfri app updates immediately as soon as I turn the light on/off from within OpenHAB so I know the gateway is working fine.

**Your Environment**

Using OpenHAB 2.1 from the official repo on a Raspberry Pi 2

**Environment name and version (e.g. Chrome 39, node.js 5.4, Java 8, ...):**
Using Google Chrome, Firefox and Opera

**Operating System and version (desktop or mobile, Windows 10, Raspbian Jessie, ...):**
Raspbian lite (latest release as of 19/07/2017

**Comment by hreichert** [comment] 2017-08-04 14:57
Exactly the same behaviour here.
I also have the effect that that the IKEA app updates everything correctly, only the Tradfri-Binding is not updating the status anymore.
 OpenHAB 2.1

**Comment by thelaoshi** [comment] 2017-08-28 19:05
I can confirm this behaviour too. Usually it takes around a day till the updates stop working. I always have to restart openhab, to get it working again :-(

**Comment by kaikreuzer** [comment] 2017-08-31 12:51
#4159 probably does not cover all potential situations, so I am re-opening the issue.

**Comment by ivivanov-bg** [comment] 2017-09-25 18:49
Is this still reproducible with the latest changes (from today) ?

**Comment by hreichert** [comment] 2017-09-25 18:57
As mentioned above, I had the same problem with the binding from OpenHAB 2.1 stable.

Currently I'm running a snapshot from September 21th in my "production" environment and had no problems regarding THIS issue. Last remaining problems were related due to mass-updates, but with the changes from @ivivanov-bg these should also be gone now.

So from my point of view this issue is fixed, but not yet available to all OpenHAB users.

**Comment by kaikreuzer** [comment] 2017-09-25 19:05
Will be available with a new distro build tomorrow - so I suggest to close this issue and anyone who still has issues can open a new one.

**Closed by kaikreuzer** 2017-09-25 19:05 UTC
Labels: Binding-Trådfri, bug
