### ISSUE TITLE
Automation: missing handler after restart

### ISSUE THREAD

**Issue by tavalin** [eclipse/smarthome#1651] opened 2016-06-09 21:52 UTC
I seem to have run into an issue whereby after creating a rule and restarting, it fails to restore the rule properly.  The rule looks as follows after the restart:

```
{
  "enabled": true,
  "status": {
    "status": "NOT_INITIALIZED",
    "statusDetail": "HANDLER_INITIALIZING_ERROR",
    "description": "Missing handler  'ItemStateChangeTrigger' for module 'trigger_1'\nMissing handler  'ItemStateCondition' for module 'condition_2'\nMissing handler  'ItemPostCommandAction' for module 'action_3'\n"
  },
  "triggers": [
    {
      "id": "trigger_1",
      "label": "Item State Trigger",
      "description": "This triggers a rule if an items state changed",
      "configuration": {
        "itemName": "morning_alarm"
      },
      "type": "ItemStateChangeTrigger"
    }
  ],
  "conditions": [
    {
      "id": "condition_2",
      "label": "Item state condition",
      "description": "compares the items current state with the given",
      "configuration": {
        "itemName": "morning_alarm",
        "state": "ON",
        "operator": "="
      },
      "type": "ItemStateCondition"
    }
  ],
  "actions": [
    {
      "id": "action_3",
      "label": "Post command to an item",
      "description": "posts commands on items",
      "configuration": {
        "itemName": "XBMC_OpenMedia",
        "command": "\"http://a.files.bbci.co.uk/media/live/manifesto/audio/simulcast/hls/uk/sbr_high/ak/bbc_1xtra.m3u8\""
      },
      "type": "ItemPostCommandAction"
    }
  ],
  "configuration": {},
  "configDescriptions": [],
  "uid": "rule_2",
  "name": "Morning Alarm",
  "tags": [],
  "description": "What to do when my alarm goes off"
}
```

To resolve this I have to go into edit mode on the rule and then OK the rule to update/fix.

**Comment by danchom** [comment] 2016-06-10 11:10
Sorry, but what is the problem with this rule? If you mean that it has additional statusInfo and enable state - they are available only in rest responses not in the rule itself. It is done for convenience to get these three peace of information with one rest call.

**Comment by maggu2810** [comment] 2016-06-10 11:22
@danchom 
Reading the topic of this issue and the posted rule I assume it is about the status itself.

* Missing handler  'ItemStateChangeTrigger' for module 'trigger_1'
* Missing handler  'ItemStateCondition' for module 'condition_2'
* Missing handler  'ItemPostCommandAction' for module 'action_3'
```
    "status": "NOT_INITIALIZED",
    "statusDetail": "HANDLER_INITIALIZING_ERROR",
    "description": "Missing handler  'ItemStateChangeTrigger' for module 'trigger_1'\nMissing handler  'ItemStateCondition' for module 'condition_2'\nMissing handler  'ItemPostCommandAction' for module 'action_3'\n"
 ```

@tavalin Has the handler been available before? Is the handler really missing? Have you changed the runtime setup, ...

**Comment by tavalin** [comment] 2016-06-10 11:53
@danchom @maggu2810 

From a user point of view the problem is simple: I created a rule which worked OK but after I restarted the runtime (OH2 in my instance) the rule did not work which I assume is due to the "missing handler" message.  The action taken to 'fix' the rule was to put the rule into edit mode and confirm (without actually changing anyting).

**Comment by danchom** [comment] 2016-06-13 10:43
@tavalin you are correct your rule is not executing due to the missing handler. The rules have states, when the state is a not initialized, this means that the rule engine can't find some of the handlers needed by the modules of the rule. When all the modules of the rule have associated handlers then the rule does into IDLE state and it can be executed by the rule engine. The OSGi is dynamic environment and bundles which registers module handler factory services can appeared and disappeared at any time. In your case the module handler factory, which creates handlers for ItemStateChangeTrigger module type was not registered for some reason. (It is part of the bundle org.eclipse.smarthome.automation.module.core.jar.) Please check if after restart the bundle org.eclipse.smarthome.automation.module.core.jar is available and started.
Unfortunately I can't reproduce exactly your case, because I don't use OH2, but I think I'm reproducing same situation using demo json rules (org.eclipse.smarthome.automation.sample.extension.json.jar).    After restart all the rules created before it are available and IDLE.

**Comment by tavalin** [comment] 2016-06-13 16:46
I've restarted OH2 and the rule is still missing the handlers, i.e. not working.  I've also checked the bundles and they all appear to be active.

```
206 | Active   |  80 | 0.8.0.201605311814    | Eclipse SmartHome Automation API
207 | Active   |  80 | 0.8.0.201605311814    | Eclipse SmartHome Automation commands
208 | Active   |  80 | 0.8.0.201605311814    | Eclipse SmartHome Automation Core
209 | Active   |  80 | 0.8.0.201605311814    | Eclipse SmartHome Automation Module Core
210 | Active   |  80 | 0.8.0.201605311814    | Eclipse SmartHome Automation Module Script
211 | Active   |  80 | 0.8.0.201605311814    | Eclipse SmartHome Automation Script Globals
212 | Active   |  80 | 0.8.0.201605311814    | Eclipse SmartHome Automation Module Timer
213 | Active   |  80 | 0.8.0.201605311814    | Eclipse SmartHome Automation GSON Parser
214 | Active   |  80 | 0.8.0.201605311814    | Eclipse SmartHome Automation Providers
215 | Active   |  80 | 0.8.0.201605311814    | Eclipse SmartHome Automation REST API

```

**Comment by tavalin** [comment] 2016-07-14 13:21
Any more ideas about this? I'm still experiencing it with latest snapshots.

**Comment by danchom** [comment] 2016-08-02 11:55
Unfortunately I can't reproduce your problem, but I guess what is going on:
1) The rule is loaded from DB
2) The module handler factory (BasicModuleHandlerFactory) is registered.
3) The rule engine was notified about new types carried by the BasicModuleHandlerFactory and tries to resolve NOT_INITIALIZED rules
4) The rule resolution fails because the needed the needed MuduleTyeps were not parsed by the ModuleTypeResourceBundleImporter
5) The module types are parsed by  ModuleTypeResourceBundleImporter, but there isn't amy notification about this to rule engine.
The problem is that the registration of moduleHandlerFactories and parsing of its module types are independent processes without any communication between them. May be this can be fixed with registration of ModuleRegistry as AbstractRegistry.

**Comment by maggu2810** [comment] 2016-09-28 15:22
@tavalin Do you still see this error?

**Comment by triller-telekom** [comment] 2017-09-07 11:18
Since this issue is older than a year and there was no reaction at the end of last september when the creater was pinged again, I think we can close this issue. @tavalin feel free to reopen with new information if it still exists in the current version.

@kaikreuzer @sjka Can you please close this issue?

**Closed** 2017-09-07 11:22 UTC
Labels: Automation
