### ISSUE TITLE
[Paper UI] Use locale settings to display numeric values

### ISSUE THREAD

**Issue by cweitkamp** [eclipse/smarthome#5747] opened 2018-06-18 13:30 UTC
My locale settings are `de_DE`. The numeric values are not displayed in corresponding number format (e.g. 
decimal separator `,` instead of `.`).

```
2018-06-18 15:16:27.283 [INFO ] [.core.internal.i18n.I18nProviderImpl] - Locale set to 'de_DE'.
```

![bildschirmfoto von 2018-06-18 15-23-14](https://user-images.githubusercontent.com/5131747/41538585-fbb25bd8-730b-11e8-855e-04e8f8025fb7.png)

**Comment by cweitkamp** [comment] 2018-06-18 13:47
Other UIs (e.g. Basic UI) are already supporting this (see screenshot in #5749).

**Comment by MHerbst** [comment] 2018-06-18 21:43
Looks like a duplicate of #2714

**Comment by kaikreuzer** [comment] 2018-06-18 21:51
I'd agree - so let's close this one.

**Closed by kaikreuzer** 2018-06-18 21:51 UTC
Labels: UI-PaperUI
