### ISSUE TITLE
500 Request failed while updating a rule

### ISSUE THREAD

**Issue by aounhaider1** [eclipse/smarthome#708] opened 2015-12-10 10:10 UTC
Server responds with a 500 Request failed error when we try to update a rule by adding a new trigger of type 'GenericEventTrigger' or 'TimerTrigger' (trigger configuration not specified). The new triggers is however added to the server.

**Comment by kaikreuzer** [comment] 2015-12-10 10:18
@aounhaider1 Could you please add the exception from your log?

**Comment by aounhaider1** [comment] 2015-12-10 10:35
```javascript 
2015-12-10 11:21:20 [WARN ] [e.jetty.servlet.ServletHandler:620  ] - javax.servlet.ServletException: java.lang.NullPointerException
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:423)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:386)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:334)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:221)
	at com.eclipsesource.jaxrs.publisher.internal.ServletContainerBridge.service(ServletContainerBridge.java:76)
	at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:128)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:68)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
Caused by: java.lang.NullPointerException: null
	at org.eclipse.smarthome.automation.module.core.handler.GenericEventTriggerHandler.<init>(GenericEventTriggerHandler.java:66)
	at org.eclipse.smarthome.automation.module.core.factory.BasicModuleHandlerFactory.internalCreate(BasicModuleHandlerFactory.java:196)
	at org.eclipse.smarthome.automation.handler.BaseModuleHandlerFactory.getHandler(BaseModuleHandlerFactory.java:37)
	at org.eclipse.smarthome.automation.core.internal.RuleEngine.getModuleHandler(RuleEngine.java:597)
	at org.eclipse.smarthome.automation.core.internal.RuleEngine.setModuleHandler(RuleEngine.java:478)
	at org.eclipse.smarthome.automation.core.internal.RuleEngine.setRule(RuleEngine.java:387)
	at org.eclipse.smarthome.automation.core.internal.RuleEngine.updateRule(RuleEngine.java:330)
	at org.eclipse.smarthome.automation.core.internal.RuleRegistryImpl.update(RuleRegistryImpl.java:135)
	at org.eclipse.smarthome.automation.core.internal.RuleRegistryImpl.update(RuleRegistryImpl.java:1)
	at org.eclipse.smarthome.automation.rest.internal.RuleResource.update(RuleResource.java:149)
	at sun.reflect.GeneratedMethodAccessor51.invoke(Unknown Source)

2015-12-10 11:21:20 [WARN ] [lipse.jetty.server.HttpChannel:395  ] - /rest/rules/rule_38javax.servlet.ServletException: javax.servlet.ServletException: java.lang.NullPointerException
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:130)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by danchom** [comment] 2015-12-11 08:48
The problem is that the default values from ModuleTypes definition are not get in mind when the configuration is missing or a property with default value  is not appear in configuration. Same as #706

**Comment by kaikreuzer** [comment] 2015-12-11 08:51
It is clear that the request is invalid in this case, but the issue is that HTTP 500 is not a valid response to this either.

**Comment by kaikreuzer** [comment] 2015-12-16 09:40
Fixed by https://github.com/eclipse/smarthome/pull/725

**Closed by kaikreuzer** 2015-12-16 09:40 UTC
Labels: Automation, bug, REST/SSE
