### ISSUE TITLE
Build 1004 Groups not loading and duplicate item errors for first 1-3 restarts

### ISSUE THREAD

**Issue by VibroAxe** [eclipse/smarthome#3981] opened 2017-08-08 07:44 UTC
Have just installed build 1004 (upgraded from 2.1 release) and the migration process was not smooth. On first startup the log was full of duplicate item errors from all of my jsondb configured items (confdb items loaded fine throughout). Items still showed up and were labelled correctly however no group info was loaded. 

After the first/second reboot the duplicate item errors went away but it took another reboot before the grouping information came back.

```
17:36:49.867 [WARN ] [ore.common.registry.AbstractRegistry] - org.eclipse.smarthome.core.library.items.NumberItem with key'Hallway_Evohome_CurrentSetPoint' already exists! Failed to add a second with the same UID!
17:36:49.880 [WARN ] [ore.common.registry.AbstractRegistry] - org.eclipse.smarthome.core.library.items.StringItem with key'Landing_Evohome_SetPointStatus' already exists! Failed to add a second with the same UID!
17:36:49.881 [WARN ] [ore.common.registry.AbstractRegistry] - org.eclipse.smarthome.core.library.items.DimmerItem with key'Lounge_Mainlight1_Dimmer' already exists! Failed to add a second with the same UID!
17:36:49.882 [WARN ] [ore.common.registry.AbstractRegistry] - org.eclipse.smarthome.core.library.items.DimmerItem with key'Lounge_Mainlight2_Dimmer' already exists! Failed to add a second with the same UID!
17:36:49.883 [WARN ] [ore.common.registry.AbstractRegistry] - org.eclipse.smarthome.core.library.items.NumberItem with key'Conservatory_Evohome_CurrentSetPoint' already exists! Failed to add a second with the same UID!
17:36:49.884 [WARN ] [ore.common.registry.AbstractRegistry] - org.eclipse.smarthome.core.library.items.DimmerItem with key'Hallway_Multisensor_SensorLuminance' already exists! Failed to add a second with the same UID!
17:36:49.888 [WARN ] [ore.common.registry.AbstractRegistry] - org.eclipse.smarthome.core.library.items.NumberItem with key'Landing_Evohome_CurrentSetPoint' already exists! Failed to add a second with the same UID!
17:36:49.890 [WARN ] [ore.common.registry.AbstractRegistry] - org.eclipse.smarthome.core.library.items.StringItem with key'Lounge_Evohome_SetPointStatus' already exists! Failed to add a second with the same UID!
17:36:49.891 [WARN ] [ore.common.registry.AbstractRegistry] - org.eclipse.smarthome.core.library.items.DimmerItem with key'DiningRoom_WallLight_Dimmer' already exists! Failed to add a second with the same UID!
17:36:49.892 [WARN ] [ore.common.registry.AbstractRegistry] - org.eclipse.smarthome.core.library.items.StringItem with key'Bedroom2_Evohome_SetPointStatus' already exists! Failed to add a second with the same UID!
17:36:49.896 [WARN ] [ore.common.registry.AbstractRegistry] - org.eclipse.smarthome.core.library.items.SwitchItem with key'Lounge_Shield_Online' already exists! Failed to add a second with the same UID!
17:36:49.903 [WARN ] [ore.common.registry.AbstractRegistry] - org.eclipse.smarthome.core.library.items.StringItem with key'OfficeEvohome_SetPointStatus' already exists! Failed to add a second with the same UID!
17:36:49.904 [WARN ] [ore.common.registry.AbstractRegistry] - org.eclipse.smarthome.core.library.items.DimmerItem with key'Lounge_Multisensor_SensorLuminance' already exists! Failed to add a second with the same UID!
17:36:49.905 [WARN ] [ore.common.registry.AbstractRegistry] - org.eclipse.smarthome.core.library.items.SwitchItem with key'Hallway_Mainlight_Switch' already exists! Failed to add a second with the same UID!
17:36:49.907 [WARN ] [ore.common.registry.AbstractRegistry] - org.eclipse.smarthome.core.library.items.NumberItem with key'Office_Evohome_CurrentSetPoint' already exists! Failed to add a second with the same UID!
17:36:49.908 [WARN ] [ore.common.registry.AbstractRegistry] - org.eclipse.smarthome.core.library.items.SwitchItem with key'Hallway_Multisensor_SensorMotion' already exists! Failed to add a second with the same UID!
17:36:49.908 [WARN ] [ore.common.registry.AbstractRegistry] - org.eclipse.smarthome.core.library.items.StringItem with key'Bedroom1_Evohome_SetPointStatus' already exists! Failed to add a second with the same UID!
17:36:49.911 [WARN ] [ore.common.registry.AbstractRegistry] - org.eclipse.smarthome.core.library.items.DimmerItem with key'Hallway_Multisensor_BatteryLevel' already exists! Failed to add a second with the same UID!
17:36:49.912 [WARN ] [ore.common.registry.AbstractRegistry] - org.eclipse.smarthome.core.library.items.SwitchItem with key'Office_Multisensor_SensorMotion' already exists! Failed to add a second with the same UID!
17:36:49.913 [WARN ] [ore.common.registry.AbstractRegistry] - org.eclipse.smarthome.core.library.items.DimmerItem with key'Bedroom2_Mainlight_Dimmer' already exists! Failed to add a second with the same UID!
17:36:49.914 [WARN ] [ore.common.registry.AbstractRegistry] - org.eclipse.smarthome.core.library.items.DimmerItem with key'Office_Mainlight_Dimmer' already exists! Failed to add a second with the same UID!
17:36:49.918 [WARN ] [ore.common.registry.AbstractRegistry] - org.eclipse.smarthome.core.library.items.StringItem with key'Bedroom4_Evohome_SetPointStatus' already exists! Failed to add a second with the same UID!
17:36:49.918 [WARN ] [ore.common.registry.AbstractRegistry] - org.eclipse.smarthome.core.library.items.SwitchItem with key'Kitchen_Multisensor_SensorMotion' already exists! Failed to add a second with the same UID!
17:36:49.919 [WARN ] [ore.common.registry.AbstractRegistry] - org.eclipse.smarthome.core.library.items.DimmerItem with key'Lounge_Multisensor_BatteryLevel' already exists! Failed to add a second with the same UID!
17:36:49.920 [WARN ] [ore.common.registry.AbstractRegistry] - org.eclipse.smarthome.core.library.items.DimmerItem with key'Kitchen_Mainlight2_Dimmer' already exists! Failed to add a second with the same UID!
17:36:49.924 [WARN ] [ore.common.registry.AbstractRegistry] - org.eclipse.smarthome.core.library.items.NumberItem with key'Landing_Evohome_Temperature' already exists! Failed to add a second with the same UID!
17:36:49.924 [WARN ] [ore.common.registry.AbstractRegistry] - org.eclipse.smarthome.core.library.items.NumberItem with key'Office_Multisensor_SensorLuminance' already exists! Failed to add a second with the same UID!
17:36:49.928 [WARN ] [ore.common.registry.AbstractRegistry] - org.eclipse.smarthome.core.library.items.NumberItem with key'Bedroom4_Evohome_CurrentSetPoint' already exists! Failed to add a second with the same UID!
17:36:49.928 [WARN ] [ore.common.registry.AbstractRegistry] - org.eclipse.smarthome.core.library.items.SwitchItem with key'Lounge_Samsung55TV_Online' already exists! Failed to add a second with the same UID!
17:36:49.929 [WARN ] [ore.common.registry.AbstractRegistry] - org.eclipse.smarthome.core.library.items.NumberItem with key'Conservatory_Evohome_Temperature' already exists! Failed to add a second with the same UID!
17:36:49.930 [WARN ] [ore.common.registry.AbstractRegistry] - org.eclipse.smarthome.core.library.items.DimmerItem with key'Lounge_Walllights_Dimmer' already exists! Failed to add a second with the same UID!
17:36:49.930 [WARN ] [ore.common.registry.AbstractRegistry] - org.eclipse.smarthome.core.library.items.NumberItem with key'Bedroom2_Evohome_CurrentSetPoint' already exists! Failed to add a second with the same UID!
17:36:49.931 [WARN ] [ore.common.registry.AbstractRegistry] - org.eclipse.smarthome.core.library.items.SwitchItem with key'Presence_Vibs_Oneplus3_Online' already exists! Failed to add a second with the same UID!
17:36:49.931 [WARN ] [ore.common.registry.AbstractRegistry] - org.eclipse.smarthome.core.library.items.DimmerItem with key'Kitchen_Multisensor_SensorLuminance' already exists! Failed to add a second with the same UID!
17:36:49.932 [WARN ] [ore.common.registry.AbstractRegistry] - org.eclipse.smarthome.core.library.items.NumberItem with key'DiningRoom_Evohome_CurrentSetPoint' already exists! Failed to add a second with the same UID!
17:36:49.933 [WARN ] [ore.common.registry.AbstractRegistry] - org.eclipse.smarthome.core.library.items.DimmerItem with key'Kitchen_Mainlight1_Dimmer' already exists! Failed to add a second with the same UID!
17:36:49.935 [WARN ] [ore.common.registry.AbstractRegistry] - org.eclipse.smarthome.core.library.items.StringItem with key'Hallway_Evohome_SetPointStatus' already exists! Failed to add a second with the same UID!
17:36:49.936 [WARN ] [ore.common.registry.AbstractRegistry] - org.eclipse.smarthome.core.library.items.DimmerItem with key'1FOffice_Mainlight_Dimmer' already exists! Failed to add a second with the same UID!
17:36:49.937 [WARN ] [ore.common.registry.AbstractRegistry] - org.eclipse.smarthome.core.library.items.NumberItem with key'1FOffice_Evohome_Temperature' already exists! Failed to add a second with the same UID!
17:36:49.937 [WARN ] [ore.common.registry.AbstractRegistry] - org.eclipse.smarthome.core.library.items.StringItem with key'ConservatoryEvohome_SetPointStatus' already exists! Failed to add a second with the same UID!
17:36:49.939 [WARN ] [ore.common.registry.AbstractRegistry] - org.eclipse.smarthome.core.library.items.NumberItem with key'Bedroom4_Evohome_Temperature' already exists! Failed to add a second with the same UID!
17:36:49.943 [WARN ] [ore.common.registry.AbstractRegistry] - org.eclipse.smarthome.core.library.items.DimmerItem with key'DiningRoom_MainLight_Dimmer' already exists! Failed to add a second with the same UID!
17:36:49.944 [WARN ] [ore.common.registry.AbstractRegistry] - org.eclipse.smarthome.core.library.items.NumberItem with key'Lounge_Evohome_CurrentSetPoint' already exists! Failed to add a second with the same UID!
17:36:49.945 [WARN ] [ore.common.registry.AbstractRegistry] - org.eclipse.smarthome.core.library.items.SwitchItem with key'Presence_Nikki_OnePlusX_Online' already exists! Failed to add a second with the same UID!
17:36:49.945 [WARN ] [ore.common.registry.AbstractRegistry] - org.eclipse.smarthome.core.library.items.DimmerItem with key'Bedroom1_Mainlight_Dimmer' already exists! Failed to add a second with the same UID!
17:36:49.946 [WARN ] [ore.common.registry.AbstractRegistry] - org.eclipse.smarthome.core.library.items.NumberItem with key'Bedroom2_Evohome_Temperature' already exists! Failed to add a second with the same UID!
17:36:49.952 [WARN ] [ore.common.registry.AbstractRegistry] - org.eclipse.smarthome.core.library.items.NumberItem with key'Lounge_Evohome_Temperature' already exists! Failed to add a second with the same UID!
17:36:49.953 [WARN ] [ore.common.registry.AbstractRegistry] - org.eclipse.smarthome.core.library.items.ColorItem with key'Node24_RGBW_Color' already exists! Failed to add a second with the same UID!
17:36:49.953 [WARN ] [ore.common.registry.AbstractRegistry] - org.eclipse.smarthome.core.library.items.NumberItem with key'1FBathroom_Evohome_Temperature' already exists! Failed to add a second with the same UID!
17:36:49.954 [WARN ] [ore.common.registry.AbstractRegistry] - org.eclipse.smarthome.core.library.items.StringItem with key'EvoTouch_Mode' already exists! Failed to add a second with the same UID!
17:36:49.954 [WARN ] [ore.common.registry.AbstractRegistry] - org.eclipse.smarthome.core.library.items.NumberItem with key'Bathroom_Evohome_CurrentSetPoint' already exists! Failed to add a second with the same UID!
17:36:49.955 [WARN ] [ore.common.registry.AbstractRegistry] - org.eclipse.smarthome.core.library.items.NumberItem with key'Bedroom1_Evohome_CurrentSetPoint' already exists! Failed to add a second with the same UID!
17:36:49.975 [WARN ] [ore.common.registry.AbstractRegistry] - org.eclipse.smarthome.core.library.items.NumberItem with key'DiningRoom_Evohome_Temperature' already exists! Failed to add a second with the same UID!
17:36:49.975 [WARN ] [ore.common.registry.AbstractRegistry] - org.eclipse.smarthome.core.library.items.DimmerItem with key'ZWaveNode23FGRGBWRGBWController_Dimmer3' already exists! Failed to add a second with the same UID!
17:36:49.975 [WARN ] [ore.common.registry.AbstractRegistry] - org.eclipse.smarthome.core.library.items.DimmerItem with key'ZWaveNode23FGRGBWRGBWController_Dimmer5' already exists! Failed to add a second with the same UID!
17:36:49.975 [WARN ] [ore.common.registry.AbstractRegistry] - org.eclipse.smarthome.core.library.items.DimmerItem with key'ZWaveNode23FGRGBWRGBWController_Dimmer4' already exists! Failed to add a second with the same UID!
17:36:49.975 [WARN ] [ore.common.registry.AbstractRegistry] - org.eclipse.smarthome.core.library.items.SwitchItem with key'Lounge_Multisensor_SensorMotion' already exists! Failed to add a second with the same UID!
17:36:49.976 [WARN ] [ore.common.registry.AbstractRegistry] - org.eclipse.smarthome.core.library.items.DimmerItem with key'Kitchen_Multisensor_BatteryLevel' already exists! Failed to add a second with the same UID!
17:36:49.976 [WARN ] [ore.common.registry.AbstractRegistry] - org.eclipse.smarthome.core.library.items.DimmerItem with key'ZWaveNode23FGRGBWRGBWController_Dimmer1' already exists! Failed to add a second with the same UID!
17:36:49.976 [WARN ] [ore.common.registry.AbstractRegistry] - org.eclipse.smarthome.core.library.items.NumberItem with key'1FOffice_Evohome_CurrentSetPoint' already exists! Failed to add a second with the same UID!
17:36:49.976 [WARN ] [ore.common.registry.AbstractRegistry] - org.eclipse.smarthome.core.library.items.DimmerItem with key'Bedroom4_Mainlight_Dimmer' already exists! Failed to add a second with the same UID!
17:36:49.979 [WARN ] [ore.common.registry.AbstractRegistry] - org.eclipse.smarthome.core.library.items.NumberItem with key'Office_Evohome_Temperature' already exists! Failed to add a second with the same UID!
17:36:49.980 [WARN ] [ore.common.registry.AbstractRegistry] - org.eclipse.smarthome.core.library.items.NumberItem with key'Hallway_Evohome_Temperature' already exists! Failed to add a second with the same UID!
17:36:49.980 [WARN ] [ore.common.registry.AbstractRegistry] - org.eclipse.smarthome.core.library.items.StringItem with key'Bathroom_Evohome_SetPointStatus' already exists! Failed to add a second with the same UID!
17:36:49.983 [WARN ] [ore.common.registry.AbstractRegistry] - org.eclipse.smarthome.core.library.items.StringItem with key'1FOfficeEvohome_SetPointStatus' already exists! Failed to add a second with the same UID!
17:36:49.984 [WARN ] [ore.common.registry.AbstractRegistry] - org.eclipse.smarthome.core.library.items.DimmerItem with key'Landing_Mainlight_Dimmer' already exists! Failed to add a second with the same UID!
```

**Comment by kaikreuzer** [comment] 2017-08-08 08:54
Sounds like some migration issue from between openHAB versions - if I understand correctly, this is no bug report about Eclipse SmartHome, so closing it here.
You might want to discuss issues about openHAB upgrade issues at https://community.openhab.org/.

**Closed by kaikreuzer** 2017-08-08 08:54 UTC

**Comment by VibroAxe** [comment] 2017-08-08 09:04
@kaikreuzer might be wrong on this, but isn't the item loading from ESH?
"org.eclipse.smarthome.core.library.items"

**Comment by kaikreuzer** [comment] 2017-08-08 09:22
Yes, but if I get you right, there is actually no issue anymore after multiple restarts.
ESH only tells you that it is not ok to add multiple items with the same name to the registry, which is fine.
So the issue is that your openHAB 2.1 installation for some reason has multiple items of the same name - this is an issue of that installation and not an ESH bug. Not wanting to say that it is a personal issue just of you, maybe this is a general problem of all openHAB 2.1 users. But this needs to be sorted out on openHAB side and I think the forum is the best place for that. If we find out that there is a bug in ESH that needs to be addressed, we can open an according issue then.
