### ISSUE TITLE
[Sonos] Music not resuming after notification

### ISSUE THREAD

**Issue by rtvb** [eclipse/smarthome#1653] opened 2016-06-10 12:03 UTC
When music is playing and a notification is sent, the music does not continue after the notification has finished.

Logfile:
http://pastebin.com/jkckE9cU

(It looks like some XML parsing issue)

**Comment by kaikreuzer** [comment] 2016-06-12 09:13
@kgoderis & @R-Edelhoff Could one of you comment on this?

**Comment by kgoderis** [comment] 2016-06-12 11:00
This issue has the same root cause as  https://github.com/eclipse/smarthome/issues/1600

**Comment by rtvb** [comment] 2016-06-12 15:46
After creating the issue, I noticed that I had 2 Sonos things: an old one through discovery and the used one from my `.things` file. I deleted the first/old one and restarted OH2. That has helped a little (gut feeling). I still get xml parsing errors.

**Comment by rtvb** [comment] 2016-06-12 15:51
Something else I have noticed is, that it matters what file I present. I use as `.wav` file that has been build in different ways.

For example:

1. Directly from say command:

    $ say -o start.wav --dataformat=LEF32@32000 'openHAB started'

2. Through Audacity

    $ say -o start.aiff 'openHAB started'

That `.aiff` file is than run through Audacity and exported as "Microsoft signed 16 bit WAV". While exporting I can add meta tags.

The first one creates XML parsing errors and does not play, the second plays properly.

(Should I report a separate issue for this one)?

**Comment by lolodomo** [comment] 2016-11-22 08:26
@rtvb : can you confirm this issue (problem with notification) can be closed ? If true, please close it. If not, please explain how to reproduce it ?

**Comment by rtvb** [comment] 2016-12-12 06:14
I haven't been using oh2 recently. So I can't confirm. Sorry.





Op Di nov 22 2016, om 09:26 schreef lolodomo:

> @rtvb[1] : can you confirm this issue (problem with notification) can
> be closed ? If true, please close it. If not, please explain how to
> reproduce it ?
> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[2], or mute the thread[3].
> 




Links:

  1. https://github.com/rtvb
  2. https://github.com/eclipse/smarthome/issues/1653#issuecomment-262176979

**Comment by lolodomo** [comment] 2017-02-06 11:08
Please close this issue.

**Closed** 2017-02-06 11:21 UTC
Labels: bug, Sonos
