### ISSUE TITLE
[lsp] Exiting vscode causes openHAB java process to exit

### ISSUE THREAD

**Issue by mhilbush** [eclipse/smarthome#6291] opened 2018-09-28 11:45 UTC
See discussion here.
https://community.openhab.org/t/lsp-in-vs-code-causes-openhab-restart/52439/5

What I’m seeing on OH build 1372 is that the openHAB Java process exits silently when VS Code is closed, or when you close the conf folder in VS Code (which likely has the same effect as closing VS Code).

I’m not seeing this behavior on 1368.

I put the following LSP bundles in TRACE mode to see if I could capture indication of what might be happening. Nothing was logged when I exited VS Code .
```
 94 x Active   x  80 x 0.4.1.v20180515-1321   x org.eclipse.lsp4j
 95 x Active   x  80 x 0.4.1.v20180515-1321   x org.eclipse.lsp4j.jsonrpc
129 x Active   x  80 x 0.10.0.201809210646    x org.eclipse.smarthome.model.lsp
```
In the interest of full disclosure, I’m running OpenJDK.
```
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-8u181-b13-0ubuntu0.16.04.1-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)
```

Edit: I'm seeing this on three different OH installations, all of which are running 1372 or later.

**Comment by kaikreuzer** [comment] 2018-09-28 11:50
> Java process exits silently

What does that exactly mean? Afaik, Java only exists silently, if `System.exit()` is called - in the case of a crash, it will rather log some crash dump message.

**Comment by kaikreuzer** [comment] 2018-09-28 11:55
Uh, wow, I can indeed reproduce it. Not by closing VSCode (openHAB keeps running), but by closing the folder in VS Code. Indeed, a sudden death :-/

**Comment by kaikreuzer** [comment] 2018-09-28 11:56
FTR: Running
```
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
```
from Oracle on a Mac.

**Comment by mhilbush** [comment] 2018-09-28 11:56
Right, in my case, either closing the folder, or exiting VS Code causes the issue.

**Comment by mhilbush** [comment] 2018-09-28 11:57
It truly is silent. Nothing logged in any of the OH log files, nothing in syslog, and nothing logged to stdout (when run from a shell using start.sh).

**Comment by kaikreuzer** [comment] 2018-09-28 11:58
Might be related to this discussion: https://github.com/eclipse/lsp4j/issues/161
Sounds like a feature, not a bug 😟

**Comment by mhilbush** [comment] 2018-09-28 12:03
> Sounds like a feature

Oh my! :-o

**Comment by MHerbst** [comment] 2018-09-30 17:16
I had a look into the code of `org.eclipse.xtext.ide.server.LanguageServerImpl` and the `exit()` method contains calls to `System.exit()`.
The coding has been added about a year ago with this commit: https://github.com/eclipse/xtext-core/commit/27bd8abb0d78cfbd201a48a940617b85fa84bf67#diff-0fc0eb4aab841adf6e1c198a00c6e95d

This implementation follows the LSP specification of the "exit" request (https://microsoft.github.io/language-server-protocol/specification#exit):

> A notification to ask the server to exit its process.

**Comment by kaikreuzer** [comment] 2018-10-01 06:53
I have created https://github.com/eclipse/xtext-core/issues/885 for discussion and will check out if I can find a workaround for the time being.

**Comment by mhilbush** [comment] 2018-10-08 11:09
@kaikreuzer I see more people reporting "random OH restarts", which could be caused by the xtext issue referenced above. It looks like openHAB core hasn't been built in a while. As it contains your workaround to this issue, could you kick off a build of openHAB core so that it gets included in the next OH build? Thanks!

**Comment by meingraham** [comment] 2018-10-14 21:38
@kaikreuzer,

 I updated to SNAPSHOT 2.4.0~20181001112604-1 (Build #1378) on October 2. Does this build contain the work-around for the VS Code "exit" issue? I can report that with this OH build, when I exit VS Code, OH goes through a hard restart.

I'm also dealing with MQTTITUDE having been moved to legacy status in the 2.4.0M4 milestone. I have not had time yet to migrate to using GPSTracker... so I need to continue using MQTTITUDE for the time being. According to what I read, to continue to use this OH1 binding, I had to add it to addons.cfg. The problem is, when OH stops (as when VS Code causes if to "crash"), all of my bindings get uninstalled (I found this - https://community.openhab.org/t/reinstall-bindings-after-restart-oh2/18945/6). So, the VS Code issue is really painful.

Of course, if I'm doing something wrong (either with VS Code or with OH1 bindings), I'm WIDE open to being steered in the right direction ;-)

Regards.

Mike

**Comment by kaikreuzer** [comment] 2018-10-14 22:01
>  Does this build contain the work-around for the VS Code "exit" issue? I can report that with this OH build, when I exit VS Code, OH goes through a hard restart.

Then it does not contain it ;-) Afaik, it's only included in builds from Oct 2 onwards.

Wrt mqttitude, please do not go off-topic here, but rather ask those questions at https://community.openhab.org/. Thanks!

**Comment by meingraham** [comment] 2018-10-15 00:36
> Afaik, it's only included in builds from Oct 2 onwards

This [post](https://github.com/eclipse/smarthome/issues/6291#issuecomment-425806504), dated Oct. 1 is the reason I wasn't sure if I had a "late enough" build. I guess by the time your workaround was reviewed and merged, the workaround didn't make it until and October 2 build.

> Wrt mqttitude, please do not go off-topic here

I was more mentioning it because of the extent of the problem the VS Code issue is causing... but yes, I was fishing for a resolution ;-) I'll post over on the OH Community ;-)

Regards.

Mike

**Comment by radokristof** [comment] 2018-10-18 23:08
@kaikreuzer Can you provide me when a new testing release will be released? I'm using the Milestone builds and I don't want to change to snapshots.

Thanks!

**Comment by mhilbush** [comment] 2018-11-29 14:57
I see the long-term fix has been added to [xtext-core](https://github.com/eclipse/xtext-core/commit/4f53fd0588b35c397b9a4e9a5b3ef1ad9ac6d07f), and is in the 2.16.0.M3 release.

I don't know when the final 2.16.0 release is planned, but hopefully the timing will work out and the next openHAB xtext upgrade will pick this up.

**Closed** 2019-04-17 04:52 UTC
