### ISSUE TITLE
RulesJvmModelInferrer :  Duplicate field WARNings

### ISSUE THREAD

**Issue by kgoderis** [eclipse/smarthome#1769] opened 2016-06-28 18:29 UTC
With the latest snapshot, when starting the runtime I see a massive amount of messages like:

`2016-06-28 18:07:51.982 [WARN ] [.rule.jvmmodel.RulesJvmModelInferrer] - Duplicate field: 'BathroomKidsSonosVolume'. Ignoring 'org.eclipse.smarthome.core.library.items.DimmerItem'.`

**Comment by lolodomo** [comment] 2016-06-28 21:15
It is a duplicate of #1574.

**Closed** 2016-06-28 22:22 UTC

**Comment by kaikreuzer** [comment] 2016-09-01 15:23
FTR: I have just fixed an issue (https://github.com/eclipse/smarthome/issues/2095), which caused these messages - yours might have been due to the same root cause.
