### ISSUE TITLE
Add support for Image items in Sitemaps and Classic+Basic UI

### ISSUE THREAD

**Issue by digitaldan** [eclipse/smarthome#1800] opened 2016-07-04 15:47 UTC
Continuing the discussion from https://community.openhab.org/t/squeezebox-display-coverart/12072/4

The Squeezebox binding implemented image support (coverart) by retrieving the image from a URL and converting the raw image data to a RawType.  Is this a supported use of a RawType?  I remember reading in a comment that images were one of its intended uses, but is this still the case? Right now I do not think there is a way of displaying a RawType in any client.  Also there may be some other issues with this, like how to know if the RawType is jpeg, png or gif for images.

**Comment by kaikreuzer** [comment] 2016-07-04 20:50
Yes, absolutely, there is even an [ImageItem](https://github.com/eclipse/smarthome/blob/master/bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/items/ImageItem.java) type, although I just noticed that this isn't listed in the documentation.

The Paper UI already supports it and we should imho also add support in the Classic UI and the Basic UI.

**Comment by kgoderis** [comment] 2016-07-09 07:09
@kaikreuzer We should/could add that to the Sonos binding as well

**Comment by kaikreuzer** [comment] 2016-07-19 00:45
@kgoderis Yes, this should probably be covered by https://github.com/eclipse/smarthome/issues/1617.

**Comment by lolodomo** [comment] 2016-08-02 17:48
Is the ImageItem type alreaded supported by HABdroid ?

**Comment by kaikreuzer** [comment] 2016-08-02 19:05
No, feel free to enter issues for the mobile apps in their respective openHAB repos.

**Comment by lolodomo** [comment] 2016-10-31 10:41
@kaikreuzer : could give an example of how item and sitemap should be defined ?
In OH 1.x wiki, we can find the syntax for Image and Video elements:
> Image [item=<itemname>] [icon="<iconname>"] url="<url of image>" [label="<labelname>"] [refresh=xxxx]
Is it still valid in OH 2 ?
Unfortunately I don't understand what represents the item in this case as you have to define at the same time the URL of the image.

**Comment by watou** [comment] 2016-10-31 16:38
It would be great if `image` and `Video` sitemap elements could take the string version of the associated `item`'s state in place of the explicitly specified `url` parameter, and make the `url` parameter optional.  Whenever the associated item's state changes, the sitemap element would take it as the URL from which to fetch the image or video.  There are existing bindings that could benefit from this enhancement with no code changes required in the bindings.

**Comment by lolodomo** [comment] 2016-10-31 17:09
Isn't it what is done in OH 1.x ? If not, what is done with the provided item ?

**Comment by watou** [comment] 2016-10-31 17:49
> Isn't it what is done in OH 1.x ?

* The `url` parameter is [mandatory](https://github.com/openhab/openhab/blob/1.8/bundles/model/org.openhab.model.sitemap/src/org/openhab/model/Sitemap.xtext#L46).

* I don't find any evidence on the 1.8 branch of any use of the `item=` attribute of the `Image` widget ([here](https://github.com/openhab/openhab/blob/1.8/bundles/ui/org.openhab.ui.webapp/snippets/image.html#L1) for example).

**Comment by lolodomo** [comment] 2016-11-01 08:53
So, we have to wait for Kai's explanation as he said that it works in Paper UI.

**Comment by kaikreuzer** [comment] 2016-11-01 10:01
Well, as there weren't any Image items in OH1, the (current) sitemaps do not support them. So adding support in Classic/Basic UI actually also means to add support in the sitemaps first (I adapted the issue title accordingly).

I think the sitemap change is pretty straight forward: Instead of having the url mandatory, we require either a url OR an item to be specified.

**Comment by watou** [comment] 2016-11-01 10:07
@kaikreuzer - In OH2, does the use case work where `item=MyStringItem` containing a URL from which the client retrieves the image?  I would find this much easier to work with than having to set the state of an ImageItem to the raw image data.

**Comment by kaikreuzer** [comment] 2016-11-01 10:22
@watou Currently no, because the UIs simply do not support it.
I also think that IF we consider to support this, it will often only be an ugly workaround as a last resort. It will only work, if the url points to some publicly available server on the Internet, since the UI has to resolve it. And if you are using an app on your smartphone while you are on the road, it won't be able to get images e.g. from your local squeezebox or whatever. That's why piping it through the runtime is imho the best option. But yes, for cases where it is an album cover that can be taken from the Internet, we can also support String item types in the Image widget.

**Comment by watou** [comment] 2016-11-01 11:14
Thanks for resolving that question, @kaikreuzer.  Could the StringItems' states, treated as URLs, be piped through the runtime just as the `url=` attribute is currently?  There are currently bindings that report image URLs that change over time, and being able to specify `Image item=MyImageURLStringItem` in the sitemap, proxying the image through the runtime and refreshing the widget on state changes (and the optional refresh cycle) would address that nicely.

**Comment by lolodomo** [comment] 2016-11-01 12:05
String item that eould be set to an URL + image element in sitemap. This will perfect for album cover.

I have mo idea how is remdered image by UIs in OH 1.x (using url parameter). Do we meed an optional size to resize the image to a particlar size ?

**Comment by kaikreuzer** [comment] 2016-11-03 13:55
>  Could the StringItems' states, treated as URLs, be piped through the runtime just as the url= attribute is currently?

I think this is difficult, since "piping through the runtime" would either mean to sent the content as a state event (that's what is done for ImageItems) or to provide a specific servlet, where the runtime would serve the content. Both is not really easy to do and probably rather results in something ugly, especially if this is only meant to be a temporary solution.

So I think there should only be the three possibilities:
1. No item + Image widget with url param: The UIs resolve and display the image from the url. No updates required
2. StringItem + Image widget with item param: The UIs dynamically receive urls that they themselves resolve
3. ImageItem + Image widget with item param: The UIs dynamcally receives the image content through SSE as an event from the runtime.

> Do we meed an optional size to resize the image to a particular size ?

No, I didn't introduce this in the sitemap and left it to the UIs and their layout/rendering decisions to scale images to an appropriate size.

**Comment by watou** [comment] 2016-11-03 14:12
> especially if this is only meant to be a temporary solution

I don't recall any suggestion of using StringItems holding URLs as being a temporary solution; sorry if I missed that somewhere.  As I said, there are a few bindings already that update items with image URLs, but there is no UI that can make use of them without `item=StringItem` support.  Option 2 above would not be useful because, as you said, the client may not be able to reach the URL.  The Classic UI already does all proxying server-side for the `url=` parameter, so I don't see why "piping through the runtime" (your catchy phrase :smile:) would be any more difficult.  

If someone submitted a PR that implemented your option 2 but with proxying as is done for the `url=` attribute, would you reject it?

**Comment by kaikreuzer** [comment] 2016-11-03 14:40
> I don't recall any suggestion of using StringItems holding URLs as being a temporary solution

Sorry, I interpreted "There are currently bindings that report image URLs" as "soon there won't be such bindings anymore" ;-)

> The Classic UI already does all proxying server-side for the url= parameter

Thanks for reminding me, this indeed completely escaped me. So this actually IS already the servlet option that I mentioned above.

> If someone submitted a PR that implemented your option 2 but with proxying as is done for the url= attribute, would you reject it?

If this someone is you, I would never ever dare to reject it ;-) Go ahead!

**Comment by watou** [comment] 2016-11-03 14:47
Excellent!  I'll give it a go.

**Comment by watou** [comment] 2016-11-05 20:01
https://github.com/eclipse/smarthome/pull/2412
https://github.com/openhab/openhab-distro/pull/317

**Comment by lolodomo** [comment] 2017-01-17 13:22
@watou @kaikreuzer : can we make a new step and adjust the sitemap syntax ? The Image element is already defined and as I understood we just have to make the url= parameter optional. @watou: is it already done or is it still something to be done ? Are you able to propose this change ?

**Comment by lolodomo** [comment] 2017-01-17 22:22
I mention here an interesting discussion in my PR for the Sonos cover art about the usage of RawType for image items and the lack of format indication that could help UI to render the picture.
The question is: is RawType without any content type indication sufficient for UI ?

**Comment by lolodomo** [comment] 2017-01-17 22:37
Just an idea: maybe we could add an optional "format" parameter to the Image sitemap element to help UI ?

**Comment by watou** [comment] 2017-01-17 22:48
> maybe we could add an optional "format" parameter to the Image sitemap element to help UI ?

Not to always be raining on people's parades, but the user should not need to know the image format, and may not even be able to know it.  As it is, Sonos and `RawType` are both depending on a smart image renderer, like in modern browsers, to sniff out the format from the raw image data since they don't offer a Content-Type header.

**Comment by kaikreuzer** [comment] 2017-02-20 18:39
So shall we simply rely on smart image renderers, assuming that the UIs are anyhow only used on modern browsers? If not, we might have a look at using the StateDescription for it, e.g. the "pattern" property of it. The state description is meant to carry meta-information about the state.

**Comment by lolodomo** [comment] 2017-02-20 19:21
I am not familiar at all with WEB UI code but I will take a look to Basic UI code in case I am able to update it. Normally the Paper UI code should help me.

**Comment by kaikreuzer** [comment] 2017-02-20 19:22
We can also ask @resetnow for help, I would assume that it is easiest for him.

**Comment by lolodomo** [comment] 2017-02-20 20:55
Unfortunately looks too much difficult to me :-(

**Comment by resetnow** [comment] 2017-02-20 21:01
I'll look into it. Passing raw data without content-type header is not exactly the right thing to do, but it's easy enough to detect JPG and PNG magic bytes and it will cover 99% cases.

**Comment by lolodomo** [comment] 2017-02-20 21:04
Paper UI is apparently using an angularJS feature to load image data.
Neither Basic UI nor Classic UI are using angularJS.

**Comment by lolodomo** [comment] 2017-02-20 21:12
Note that Paper UI is probably only able to display JPEG images. It is hardcoded.

**Comment by lolodomo** [comment] 2017-02-20 21:34
Apparently the data URI to be used in HTML to provide the data encoded in base64 requires to define a media type like image/jpeg or image/png.

**Comment by lolodomo** [comment] 2017-02-20 22:09
Maybe we should enhance RawType with an optional media type and update the format method to return a data URI ?
With that done, UIs will not have to build the data URI but just get it from the state, and each binding could set the media type when they know it.

**Comment by lolodomo** [comment] 2017-02-20 22:36
Like suggested today by Kay, we could even consider the state pattern in channel type to produce the data URI. It will only require a little change in RawType to take into account the pattern.
But it would be better to not have systematically the need to hardcore the media type in the pattern. So adding a media type to RawType remains a good idea I think.

**Comment by lolodomo** [comment] 2017-02-20 22:56
So I can propose the following changes and apply it to the Sonos binding, keeping a compatibility for other bindings:
* Add an optional media type (string) to RawType
* Allow a pattern for image channels that let you substitute the media type and the encoded base64 data
* Consider the pattern parameter in RawType:format method; if no pattern set, returns the data URI currently used by Paper UI, that is a JPEG image encoded in base64.
* Add a pattern to the Sonos covert art channel and add a code to get image type from image URL
* Update Paper UI to get the data URI rather than building it.

With these changes, then all UIs will be able to retrieve a data URI to be used in img HTML tag.

Let me know if I can go in this direction.

**Comment by watou** [comment] 2017-02-20 23:40
What do you do when you don't have access to the media type from any source?  Do you emulate all that a web browser does in that situation in the server?  

I also wonder if it would be possible to suppress the loading and holding of raw image data in server memory either per binding or systemwide, since users who have no client viewing the image will have no need for consuming server heap space with images  

I think it's also important to consider use cases like: a rule that, when triggered, wants the latest image from the ultimate source.  Will it be the one held in server memory as an item state?

**Comment by lolodomo** [comment] 2017-02-20 23:54
The media type is optional in a data URI. We could suppress the hardcoded media type in Paper UI to test how WEB browsers deal with that kind of data URI.
If it does not work well, we could decide to set the media type to image/jpeg by default.

I agree with you with the unnecessary memory used by these image processed on the server side.
At least, each binding could avoid to download the image if the channel is not linked (done by the Sonos binding). But if the channel is linked, the image is updated everytime even if not viewed in any UI. No idea how to avoid that.

**Comment by watou** [comment] 2017-02-21 00:09
> If it does not work well, we could decide to set the media type to image/jpeg by default.

I hope it doesn't come to that, for all the cases where that will be a bad assumption.  Otherwise you are headed further down the road of duplicating client image handling in the server.

**Comment by lolodomo** [comment] 2017-02-21 07:04
@resetnow : I let you analyze the code but my feeling is that if we do the changes I propose, then it could work in Basic UI without any code to change.

**Comment by resetnow** [comment] 2017-02-21 07:08
I haven't looked at the code yet but my intention was to do the following:

1. Create a servlet (inside basicui) for rendering images from RawType
2. Render `image item=RawTypeItem` sitemap items to point at the created servlet
3. If it's possible to guess image type (jpg, png), add content-type header

**Comment by lolodomo** [comment] 2017-02-21 08:08
Please note that UIs already support image element attached to string item storing an URL.

**Comment by lolodomo** [comment] 2017-02-21 08:37
@resetnow : I have not studied the basic UI code in details but apparently it creates a img HTML tag repacing the src value by the item state. My idea is that if we have an item returning a date URI in the REST API, it should work the same way as with an item returning an image URL.

**Comment by kaikreuzer** [comment] 2017-02-21 08:38
> Create a servlet (inside basicui) for rendering images from RawType

No, this is completely against the idea - you already receive the image as an SSE event, so you should not create a separate communication channel for that.

> a rule that, when triggered, wants the latest image from the ultimate source. Will it be the one held in server memory as an item state?

Yes.

> I also wonder if it would be possible to suppress the loading and holding of raw image data in server memory either per binding or systemwide

Image items are items like all others. Suppressing events does not really make sense, because it is a pubsub mechanism and you do not know the subs. If you don't want images in memory, don't use these channels, but rather go for the url channels instead.

In general, image events should not be sent too often; bindings should rather only provide updates, if requested (through a REFRESH command) - this would be e.g. the update strategy for webcams.

**Comment by resetnow** [comment] 2017-02-21 08:40
>No, this is completely against the idea - you already receive the image as an SSE event, so you should not create a separate communication channel for that.

Ok, so how do I receive the image when the page is loaded initially?

**Comment by kaikreuzer** [comment] 2017-02-21 08:41
How do you receive the states of all other items on initial load?

**Comment by resetnow** [comment] 2017-02-21 08:42
So, encode the image data into page HTML?

**Comment by resetnow** [comment] 2017-02-21 08:44
This will work, my only concern is that base64 encoding will effectively quadruple the size of image.

**Comment by kaikreuzer** [comment] 2017-02-21 08:47
The same is the case for the SSE events, so it doesn't make it worse...

**Comment by lolodomo** [comment] 2017-02-21 08:48
As a POC, I could try to update the RawType to return a data URI and then check what happens in basic UI and classic UI.

**Comment by kaikreuzer** [comment] 2017-02-21 08:49
> return a data URI 

What is this supposed to be?

**Comment by resetnow** [comment] 2017-02-21 08:50
>The same is the case for the SSE events, so it doesn't make it worse...

That's why I was thinking about separate communication channel — it could also be implemented globally, not as a part of BasicUI

>What is this supposed to be?

`data:image/gif;base64,R0lGODdhMAAwAPAAAAAAAP...`

**Comment by kaikreuzer** [comment] 2017-02-21 08:53
We already have the separate communication channel for images with https://github.com/eclipse/smarthome/pull/2412#issue-187518826.

This issue here is just about NOT requiring a separate channel.

> data:image/gif;base64,R0lGODdhMAAwAPAAAAAAAP...

Ah, cool :-)

**Comment by lolodomo** [comment] 2017-02-21 09:00
The default pattern would be: `data:[<media type>];base64,<base64 data>`
There are tests to run to check what happens in common WEB browsers when no media type is provided.

**Comment by lolodomo** [comment] 2017-02-21 09:07
If no MIME type is provided, normally `text/plain` is assumed. So it should probably not work without a MIME type. So if the binding does not provide a MIME type, I would propose to consider `image/jpeg` as a default.

**Comment by lolodomo** [comment] 2017-02-21 12:22
For information, the RawType is currently used only by 5 bindings, each one used it only for one channel being a cover art.

**Comment by lolodomo** [comment] 2017-02-21 12:36
An interesting point about album art requirements for Sonos:
* Artwork embedded into the music files must be in one of the following formats: JPG, BMP, GIF or PNG.
* Maximum resolution for embedded artwork is 1024 x 1024.
* Album artwork that is placed into the music folder must be in JPG or GIF format and named folder.xxx (e.g., folder.jpg or folder.gif). Each album should be in its own folder and contain a single image file.
Several formats are possible.

**Comment by lolodomo** [comment] 2017-02-21 12:51
Additionaly, on the binding side, the following methods could be used to identify the MIME type: first getContentType() of course and when there is no content-type header then guessContentTypeFromStream().

**Comment by lolodomo** [comment] 2017-02-21 22:04
Here are my first results after updating RawType to produce a data URI + a minor change in Paper UI:
* Paper UI still displays the image as expected
* Paper UI (in Firefox) does not display the image if the data URI does not contain a MIME type like image/jpeg
* Unfortunately only the default image specified by url= in the sitemap image element is displayed in basci UI and classic UI. I don't know where is the code that trigger the failback to the default URL

As a conclusion, the change I proposed is not sufficient to make basic UI and classic UI displaying image items without enhancing their code.

As a side note,
* it is still necessary to update the sitemap syntax to not be forced to specify a url= to an image element
* Image channels are apparently not included in the default sitemap

**Comment by watou** [comment] 2017-02-22 02:19
> I don't know where is the code that trigger the failback to the default URL

Please see [here](https://github.com/eclipse/smarthome/blob/master/bundles/ui/org.eclipse.smarthome.ui/src/main/java/org/eclipse/smarthome/ui/internal/proxy/ProxyServletService.java#L260).

> it is still necessary to update the sitemap syntax to not be forced to specify a url= to an image element

Why is that necessary?  When an item has no valid image to offer, and the Image widget has no valid URL, what should the Image widget do?  At least with the mandatory `url=` parameter, the Image widget will have a chance to display a default image in case `item=` has no image or (usable) URL.

> Image channels are apparently not included in the default sitemap

Do you mean the demo sitemap?  If so, there wouldn't be since the sitemap-based UIs can't yet display them!  😄  Or perhaps I'm misunderstanding.

**Comment by lolodomo** [comment] 2017-02-22 06:58
Ah OK in the proxy !  It certainly requires a change in the proxy too.

By default sitemap, I mean the sitemap named _default.

**Comment by watou** [comment] 2017-02-22 07:30
> Ah OK in the proxy ! It certainly requires a change in the proxy too

If the client is to display a RawType value pushed via SSE, the client wouldn't need to use the proxy for that at all, right? The default `url=` would behave as defined, but further image updates would be made via SSE updates (I think).

**Comment by lolodomo** [comment] 2017-02-22 07:45
Yes, you're right. I have now to understand why UIs display the default image.
Maybe UIs use systematically the result of the proxied URL for image element ?

**Comment by lolodomo** [comment] 2017-02-22 07:54
Something done in the sitemap REST API maybe ?

**Comment by lolodomo** [comment] 2017-02-22 08:53
The problem is very probably here: https://github.com/eclipse/smarthome/blob/master/extensions/ui/org.eclipse.smarthome.ui.basic/src/main/java/org/eclipse/smarthome/ui/basic/internal/render/ImageRenderer.java#L57
We put as URL in the img HTML tag the URL of the proxied image that will be the default image in our case.

**Comment by lolodomo** [comment] 2017-02-22 13:55
I will do a new try later today but I think I know now how to easily fix classic UI and basic UI tp support image items.

Regarding my initial proposal, I think now that I will forget what I said about pattern because we don"t need that.

**Comment by lolodomo** [comment] 2017-02-22 21:58
Bingo, I got it. The only problem ramining is that the picture is not refreshed in basic UI (it is in classic UI).

**Comment by lolodomo** [comment] 2017-02-22 22:45
I created PR #3055

**Comment by lolodomo** [comment] 2017-02-22 23:01
One advantage of using an image item rather than an URL seems to be the time needed to render the image in UIs.

**Comment by watou** [comment] 2017-02-23 07:55
> One advantage of using an image item rather than an URL seems to be the time needed to render the image in UIs.

I'm very interested in understanding how you compared image rendering times.

**Comment by lolodomo** [comment] 2017-02-23 08:15
Nothing scientific, just a clear user feeling when doing my tests.

**Comment by lolodomo** [comment] 2017-02-24 15:52
Regarding my problem of image refresh in Basic UI, can someone tell me where is the code handling new events and triggering refresh ?

**Comment by resetnow** [comment] 2017-02-24 16:18
@lolodomo every Control object implements setValuePrivate method. It's called from either SSE or long-polling update listener.

**Comment by lolodomo** [comment] 2017-02-25 07:36
OK thank you, it leads to something else to be updated: a timestamp is updated at the end of the URL. It has to be avoided when the image URL is a data URI.

**Comment by lolodomo** [comment] 2017-02-25 07:46
Regarding the required default URL in the sitemap image element, it is something not obvious to choose for a final user. Could we imagine to make it optional in the syntax but have a default URL value as distribution setting. For openHAB, this setting could be set to the URL of an openHAB small image.
It could even be used by the "_default" sitemap.
What do you think about that ?

**Comment by watou** [comment] 2017-02-25 10:22
> a timestamp is updated at the end of the URL. It has to be avoided when the image URL is a data URI.

Does `refresh` even make sense when the associated item is an ImageItem?

> required default URL

I didn't want to change the DSL when adding `item=` support or leave the widget with no usable image, but if you look back at my PRs I think there is an edge case that uses a pre-existing blank PNG in some situation.  It certainly makes sense to me that an Image widget should be able to be associated with an item (ImageItem, StringItem containing a URL, or in future a LinkItem with a URIType state).  The default image, if unspecified, would have to be guaranteed to be available in that specific client.  

Please check all of your changes against Safari (and other major browsers), because I recall that changing the data URI didn't work in the version of Safari that was current at the time.

**Comment by lolodomo** [comment] 2017-02-25 14:32
@resetnow : I need your help.

First, if I put breakpoints in web-src/smarthome.js in Eclipse IDE, are they taken into account ?
If not, how can I debug ? Is there a way to log ?

Second, in ControlImage, I tried to change _t.setValuePrivate just to see if it is called. Here is the updated code:
```
		_t.setValuePrivate = function() {
            //_t.image.setAttribute("src", _t.url + "&t=" + Date.now());
            _t.image.setAttribute("src", "http://www.openhab.org/assets/images/openhab-logo-top.png&t=" + Date.now());
		};
```
The openHAB image is never displayed so I have the feeling that setValuePrivate is never called. Is it normal ?

I was then thinking that it could be because no SSE event is sent but I can see such events in my server logs:
```
2017-02-25 15:25:48.578 [DEBUG] [e.s.i.r.s.i.SitemapEventOutput:52   ] - Sent sitemap event for widget 020300 to subscription 524d8291-d67e-4b58-ae67-c9af44a98f68.
```
As my frame only contain the image element, I assume that it the event should be received and that finally should trigger a call to _t.setValue and so _t.setValuePrivate ?

**Comment by lolodomo** [comment] 2017-02-25 14:52
And another question: why is there a "web" and a "web-src" directories ? Shall I update only files in "web-src" ?

**Comment by resetnow** [comment] 2017-02-25 15:01
@lolodomo 

1. please refer to contributing.md in the BasicUI directory (mostly to the part where you need to run grunt to assemble client-side resources)
2. client-side javascript can be debugged in browser's developer tools (F12)

**Comment by lolodomo** [comment] 2017-02-25 15:29
No chance to just edit the source file in Eclipse IDE and then run from inside Eclipse ? I need to run "grunt" outside Eclipse after each file update ? Isn(t it something integrated in Eclipse that runs automatically when I run OH from inside Eclipse ?
If I run a "mvn clean install" in the root directory of Basic UI, is it ok ?

**Comment by resetnow** [comment] 2017-02-25 15:32
No, there is not. You can create a run configuration (there is a "Grunt" configuration type), which will basically call the same command from Eclipse. It still will need to be triggered manually.

**Comment by lolodomo** [comment] 2017-02-25 15:40
Just to understand, when I run "mvn clean install", it does not do all the job ?

**Comment by resetnow** [comment] 2017-02-25 15:43
It does not. Client-side scripts and styles are assembled with grunt. It's not included in the maven build process (as far as I remember due to legal reasons — it requires getting clearance on lots of javascript libraries).

**Comment by lolodomo** [comment] 2017-02-25 15:48
Tu understand, where are in the tree the source files to edit and the files that are produced by grunt and then used at runtime ?

Is it easy to install grunt on a Windows machine ? It looks more something for Linux...

**Comment by resetnow** [comment] 2017-02-25 15:50
Sources are in /web-src, resulting files are in /web. You need to install node.js and npm first, Google can help with the rest.

**Comment by lolodomo** [comment] 2017-02-25 15:53
For testing purposes, if I copy smarthome.js from web-src to web, can it work ?

**Comment by resetnow** [comment] 2017-02-25 15:55
It will work, but the changes must be validated by eslint (run from grunt) before being commited.

**Comment by lolodomo** [comment] 2017-02-25 16:10
Thank you for your explanations, I am now able to see the impact of my changes (I have copied smarthome.js from web-src to web and edited it in web).

If only few lines need to be updated, maybe I can provide them to you so that you can propose a proper PR ?

**Comment by lolodomo** [comment] 2017-02-25 16:32
Now that I can edit and debug the smarthome.js file (cool, thank you @resetnow ), I can see that setValuePrivate is called as expected but with itemState argument having the value "raw type (unknown): 4387 bytes". It is the format output of RawType.toString(). As a remember, I only put the data URI in RawType.toFullString(). So I can't update the image as I would like in setValuePrivate as I don't have the new data URI.
So I think I have first to change the SSE event so that data.item.state contains the data URI when the item is an image item.
@resetnow : is it the good way to do ?

**Comment by resetnow** [comment] 2017-02-25 16:39
>is it the good way to do ?

It's not really up to me right now. I mean it's technically correct and probably will work, you just need to confirm it with maintainers.

**Comment by lolodomo** [comment] 2017-02-25 20:07
@watou : a blank PNG would be OK. Will look for that in the existing code.

Regarding support of my changes in Safari, I will not be able to check that myself, sorry. But I will check at least with Firefox and Chrome.

**Comment by lolodomo** [comment] 2017-02-26 00:40
I succeeded making the update of image working in Basic UI (only 2 minor changes are required) but there is still one case that does not work, when state becomes UNDEF and you have suddenly to display the default URL while it was ignored when initially building the page.

@watou : I was asking myself if rather than bypassing the proxy, we could use the proxy even for images that are stored in image items ? The advantage is that there would be no change to do in Basic UI and Classic UI. But I have no idea if it makes sense and if it makesis doable for the proxy ?

**Comment by lolodomo** [comment] 2017-02-26 09:55
Sorry to share all my thoughts loudly lol
I see now that the proxy idea is a wrong idea.
But I think I have the solution: we need to store the default proxied URL in the HTML in case we need it at a certain time. So we just need to add a new entry in snippets/image.html to store it.

**Comment by lolodomo** [comment] 2017-02-26 10:30
Ok, the refresh of image in Basic UI is now working.

**Comment by lolodomo** [comment] 2017-02-27 08:18
In case no default URL is set, my idea would be that the proxy would return the none.png icon. What would be the URI to build that leads to this icon ? A relative path ?

**Comment by watou** [comment] 2017-02-27 09:43
> the proxy would return the none.png icon

The ProxyServlet is not able to address an image that isn't referenced via `url=` or `item=` in an Image sitemap widget.  The images/none.png image that is part of the Basic and Classic clients could be accessed without need of the ProxyServlet.

**Comment by resetnow** [comment] 2017-02-27 09:44
You can encode 1x1 transparent PNG in base64.

**Comment by watou** [comment] 2017-02-27 09:46
> You can encode 1x1 transparent PNG in base64.

I had trouble making that work in Safari in #1106.  See [here](https://github.com/eclipse/smarthome/pull/1106/files#diff-ee0239b05dcc713c6860244dfd4d8688R78).

**Comment by lolodomo** [comment] 2017-02-28 07:08
@watou : the current logic is mostly implemented by the ProxyServlet and hidden to the UIs. By the way, a minor update of the ProxyServlet will be required because if not it will lead to an exception (not valid URI).
We have now several combinations (StringItem, ImageItem, hardcoded url) and allowing to not set a default URL will even add more combinations. We could use images/none.png image that is part of the Basic and Classic clients but it will require to implement the full logic in UI.
This logic could be:
if itemState starts with "data:", use itemState (ImageItem)
else if itemState not NULL state, use the proxied URL (URL in StringItem)
else if url is not set in sitemap element, use images/none.png 
else use the proxyied URL

**Comment by watou** [comment] 2017-02-28 07:29
Why would the ProxyServlet need to be involved in using ImageItems' state to show images?  There are no http[s] URLs involved in those items.  If the client has hit the proxy servlet in order show an image from an ImageItem, then it's already on the wrong code path.  What am I missing here?

**Comment by lolodomo** [comment] 2017-02-28 07:56
No, I don't want to inject ImageItem in ProxyServlet, it is hanlded outside the ProxyServlet and it is ok. My concern is no more the ImageItem but the default URL and more precisely how to handle the case it will not be set in the sitemap image element (and so not provided by the ProxyServlet).
But that is ok, I will try to handle the full logic inside each UI. I have now already a good idea how to do it in Basic UI.

**Comment by lolodomo** [comment] 2017-02-28 08:24
To be clear, I would like any UI to support all these cases for the sitemap image element:
* url without item
* ImageIten with url as default
* ImageIten without url as default
* StringIten with url as default
* StringIten without url as default
And of course, there is still the refresh parameter to not forget.

**Comment by lolodomo** [comment] 2017-03-01 06:35
I have now something working in my 5 use cases in Basic UI and Classic UI.

@resetnow : I installed node.js, grunt-cli and grunt. What is the command to run at the root of Basic UI folder ? I tried just "grunt" but it seems to do nothing, web/smarthome.js is not updated.

**Comment by resetnow** [comment] 2017-03-01 06:37
`npm install` and `grunt`

**Comment by lolodomo** [comment] 2017-03-01 06:46
Works now, thanks.
I have errors of this kind: Mixed spaces and tabs  no-mixed-spaces-and-tabs
JavaScript file seems to not use the standard of the project (Eclipse IDE), that is tab for 4 spaces.
Not clear how I must update Eclipse IDE setting to update the JavaScript files.

**Comment by lolodomo** [comment] 2017-03-13 07:59
PR now merged.. issue to be closed.

**Closed** 2017-03-13 09:00 UTC
Labels: BasicUI, ClassicUI, UI
