### ISSUE TITLE
[digitalstrom] Status of DigitalStrom Server Thing: CONFIGURATION_PENDING Checking configuration...

### ISSUE THREAD

**Issue by hammergood** [eclipse/smarthome#6212] opened 2018-09-14 20:03 UTC
Hi everybody

Since I switched from OpenHab 2.2 to OpenHab 2.3, the digital stream add-on is not working properly anymore. First, I had the phenomenon that OpenHab lost the connection to the digital stream server after some time. After a reboot it worked for a short time again. Based on the description in Issue # 5651, I switched to Snapshot 2.4 (OpenHab & Add-ons). Now the DigitalStrom Server has the following status in OpenHab, which also appears immediately after a reboot: ONLINE - CONFIGURATION_PENDING Checking configuration ...

What can I try here? I also like to provide more data. Please write me what data you need and how I can generate it.

Thank you for your help!
hammergood

**Comment by hammergood** [comment] 2018-09-14 20:07
Maybe it's a double post to issue #6195

**Comment by htreu** [comment] 2018-10-17 11:47
Closing as duplicate of #6195.

**Closed by htreu** 2018-10-17 11:47 UTC
