### ISSUE TITLE
Add lock to items

### ISSUE THREAD

**Issue by PascalTurbo** [eclipse/smarthome#2916] opened 2017-01-29 11:20 UTC
This is a request for adding a lock state to every item which would allow the user to lock the current state of an item until it is unset. The idea isn't new. It's implemented on most KNX actors and works like charm.

### Use Case Motion Detector

In the normal mode, your motion detector will enable the light when you are moving and disable it, when no motion is detected anymore. But there are situations where you are interested in disabling the motion detection and simply enable - or disable - the light.

### Use Case Heater Control

There are many factors to control the heaters. For example

- Presence
- Outdoor Temperature
- Time of day

And the setting won't always be adopted to the whole building - there are situations where you want to control the temperature for a single room or a set of rooms independently.

## Current solutions

For achieving the two use cases you have to write rules. This may be ok for the motion detector use case but this will lead to extremely complex, ugly and unmanageable rules for the heater use case. In fact, at the moment I haven't implemented this for all of my rooms because it is to complex and not tolerant to failures. So my way is to disassemble the Actor from the heater and add an old school manual thermostat when I need an manual overdrive for a room - this isn't smart - this is unbearable.

## Feature Request

A solution to this could be the implementation of an locked state. If the lock is set, it isn't possible to switch the value or state of an item. To set an other value you first have to reset the lock.

    sendCommand(Office_Heater_Temperature, 20)
    // Office_Heater_Temperature == 20

    sendCommand(Office_Heater_Temperature.locked, ON)
    sendCommand(Office_Heater_Temperature, 15)
    // Office_Heater_Temperature == 20

    sendCommand(Office_Heater_Temperature.locked, ON)
    sendCommand(Office_Heater_Temperature, 15)
    // Office_Heater_Temperature == 15

**Comment by meyercg** [comment] 2017-01-29 11:46
+1

**Comment by kaikreuzer** [comment] 2017-01-29 15:14
Sounds like a duplicate of https://github.com/eclipse/smarthome/issues/2240?

**Comment by kaikreuzer** [comment] 2017-01-29 15:15
Feel free to add your thoughts and examples there!

**Closed by kaikreuzer** 2017-01-29 15:14 UTC
