### ISSUE TITLE
[Homematic] 2.4 snapshot binding not working on Mac OS X (Jetty start failed)

### ISSUE THREAD

**Issue by jewesta** [eclipse/smarthome#6576] opened 2018-11-26 09:59 UTC
I cannot get the Homematic binding working when running 2.4 snapshot under Mac OS X Mojave.

## Expected Behavior
After a fresh install, the binding should auto discover the HomeMatic Bridge and find all connected things.

## Current Behavior
The binding discovers only one bridge ("eQ3-HmIP-CCU3-App - <ip address>"). Adding it results in it being "OFFLINE - COMMUNICATION_ERROR Jetty start failed". The "Homematic Bridge" is not auto discovered. Adding it manually results in it being "OFFLINE - COMMUNICATION_ERROR Jetty start failed" as well.

## Steps to Reproduce (for Bugs)
2.3 (working)
- Unzip openhab-2.3.0.zip
- cd to install directory and ./start.sh
- Access <ip>:8080 and choose "Standard" UI configuration
- PaperUI --> Addons --> Bindings --> Install Homematic Binding
- PaperUI --> Configuration --> Things --> Add Homematic Bridge manually
- All things (switches, contacts, etc.) are discovered as expected

2.4 snapshot (not working)
- Unzip openhab-2.4.0-SNAPSHOT (tested build #1424 and later)
- cd to install directory and ./start.sh
- Access <ip>:8080 and choose "Standard" UI configuration
- PaperUI --> Addons --> Bindings --> Install Homematic Binding
- Installation takes a long time / does not come to an end "naturally"
- Log entry:
`Discovery Result with UID 'homematic:bridge:MEQxyz123' has been added.`
- Bridge "eQ3-HmIP-CCU3-App" discovered (in inbox). On a Raspberry, the "Homematic Bridge" would have been discovered as well but is missing here.
- PaperUI --> Configuration --> Things --> Add Homematic Bridge manually
- "Homematic Bridge" shows "Status: OFFLINE - COMMUNICATION_ERROR Jetty start failed"
- Log entry:
`2018-11-21 22:22:30.683 [hingStatusInfoChangedEvent] - 'homematic:bridge:a44c9e2b' changed from UNINITIALIZED to INITIALIZING
2018-11-21 22:22:30.873 [hingStatusInfoChangedEvent] - 'homematic:bridge:a44c9e2b' changed from INITIALIZING to OFFLINE (COMMUNICATION_ERROR): Jetty start failed`
- No things (switches, contacts, etc.) are discovered

## Context
I came from an openHABian scenario running 2.4 snapshots for quite a while. But as the Raspberry got too slow, I decided to migrate to a Mac mini 2012 running Mojave. Having failed to resolve the issue mentioned above, I set up openHAB 2.3, which runs without any problems. I also use a few other addons in addition to HomeMatic, namely MySQL, AVM Fritz, etc. and all works well.

## Your Environment
HomeMatic:
- Raspberry Pi with RaspberryMatic
- Latest firmware 3.37.8.20181026

openHAB:
- Mac mini 2012 Core i5 16GB RAM / 512GB SSD
- Mac OS X Mojave
- User account with admin priviledges
- Firewall off

**Comment by htreu** [comment] 2018-11-26 15:41
I can for now not reproduce your issue. Please issue the following statement on the openHAB console after starting up: `log:set DEBUG org.eclipse.smarthome.binding.homematic`.
Then rescan for the CCU and accept the inbox entry. This should bring up further log messages.

**Comment by htreu** [comment] 2018-11-26 15:47
@mdicke2s any idea what happens here?

**Comment by jewesta** [comment] 2018-11-26 22:32
I could successfully set up the latest 2.4 snapshot. No more problems with HomeMatic item discovery. Sorry for the fuss. Still don't know what went wrong before. Closing this issue.

**Comment by mdicke2s** [comment] 2018-11-27 06:44
@jewesta 
Good for you that it works now :-)
If the issue appears again, please let us know

**Comment by simonskkaiser** [comment] 2018-12-04 18:17
Hello, I am having the same issue as described above, after I upgraded to openHAB 2.4M6 and RaspberryMatic 3.41.11.20181126.
OpenHAB is running inside a docker container, I did not change the configuration of the container after the update, this should not be an issue. The following ports are open in the container:
  ports:
        - 9090:8080
        - 9443:8443
        - 5555:5555
        - 9125:9125
        - 9126:9126
        - 8181:8181
        - 9292:9292
        - 2000:2000
        - 2001:2001
        - 2010:2010
        - 8701:8701
        - 8101:8101
        - 43439:43439
The RaspberryMatic firewall configuration looks like this:
<img width="505" alt="image" src="https://user-images.githubusercontent.com/35561924/49463342-76177900-f7f8-11e8-9d3b-3ea73620d50f.png">

My ccu looks like this in PaperUI, but is configured via the following configuration in the things-file:
<img width="445" alt="image" src="https://user-images.githubusercontent.com/35561924/49463486-c989c700-f7f8-11e8-93ab-44ffe40bbc14.png">

Bridge homematic:bridge:ccu [ gatewayAddress="192.168.174.15", gatewayType="ccu", callbackHost="192.168.174.10", xmlCallbackPort=9125, binCallbackPort=9126 ]

The binding seems to be the current one. I cleared the cache and tmp folders already, without it changing the error.
<img width="383" alt="image" src="https://user-images.githubusercontent.com/35561924/49463535-f807a200-f7f8-11e8-8b61-9b239d3d2a73.png">

My ccu is not connecting successfully. After entering the above mentioned DEBUG setting for the binding I get the following output:

2018-12-04 19:08:24.972 [DEBUG] [matic.handler.HomematicBridgeHandler] - HomematicConfig[gatewayAddress=192.168.174.15,callbackHost=192.168.174.10,xmlCallbackPort=9125,binCallbackPort=9126,gatewayType=ccu,rfPort=2001,wiredPort=2000,hmIpPort=2010,cuxdPort=8701,groupPort=9292,timeout=15,discoveryTimeToLive=-1,installModeDuration=60,socketMaxAlive=900]
2018-12-04 19:08:24.974 [DEBUG] [.eclipse.smarthome.binding.homematic] - ServiceEvent REGISTERED - {org.eclipse.smarthome.config.discovery.DiscoveryService}={service.id=422, service.bundleid=196, service.scope=singleton} - org.eclipse.smarthome.binding.homematic
2018-12-04 19:08:24.999 [INFO ] [ternal.communicator.client.RpcClient] - Interface 'WIRED' on gateway 'ccu' not available, disabling support
2018-12-04 19:08:25.019 [INFO ] [ternal.communicator.client.RpcClient] - Interface 'CUXD' on gateway 'ccu' not available, disabling support
2018-12-04 19:08:25.037 [DEBUG] [ommunicator.AbstractHomematicGateway] - Initializing gateway with id 'ccu'
2018-12-04 19:08:25.038 [INFO ] [ommunicator.AbstractHomematicGateway] - HmGatewayInfo[id=CCU,type=CCU2,firmware=3.41.11.20181126,address=NEQ0605154,rf=true,wired=false,hmip=true,cuxd=false,group=true]
2018-12-04 19:08:25.039 [DEBUG] [ommunicator.AbstractHomematicGateway] - Used Homematic transfer modes: RF:XML_RPC, HMIP:XML_RPC, GROUP:XML_RPC
2018-12-04 19:08:25.045 [DEBUG] [nal.communicator.server.XmlRpcServer] - Initializing XML-RPC server at port 9125
2018-12-04 19:08:25.055 [DEBUG] [matic.handler.HomematicBridgeHandler] - Homematic bridge was set to OFFLINE-COMMUNICATION_ERROR due to the following exception: Jetty start failed
java.io.IOException: Jetty start failed
	at org.eclipse.smarthome.binding.homematic.internal.communicator.server.XmlRpcServer.start(XmlRpcServer.java:93) ~[?:?]
	at org.eclipse.smarthome.binding.homematic.internal.communicator.AbstractHomematicGateway.startServers(AbstractHomematicGateway.java:254) ~[?:?]
	at org.eclipse.smarthome.binding.homematic.internal.communicator.AbstractHomematicGateway.initialize(AbstractHomematicGateway.java:192) ~[?:?]
	at org.eclipse.smarthome.binding.homematic.handler.HomematicBridgeHandler.initializeInternal(HomematicBridgeHandler.java:108) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:?]
Caused by: java.net.BindException: Cannot assign requested address
	at sun.nio.ch.Net.bind0(Native Method) ~[?:?]
	at sun.nio.ch.Net.bind(Net.java:433) ~[?:?]
	at sun.nio.ch.Net.bind(Net.java:425) ~[?:?]
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223) ~[?:?]
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74) ~[?:?]
	at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:331) ~[?:?]
	at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:299) ~[?:?]
	at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80) ~[?:?]
	at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:235) ~[?:?]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) ~[?:?]
	at org.eclipse.jetty.server.Server.doStart(Server.java:398) ~[?:?]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) ~[?:?]
	at org.eclipse.smarthome.binding.homematic.internal.communicator.server.XmlRpcServer.start(XmlRpcServer.java:88) ~[?:?]
	... 10 more
2018-12-04 19:08:25.069 [DEBUG] [matic.handler.HomematicBridgeHandler] - Disposing bridge 'ccu'
2018-12-04 19:08:25.070 [DEBUG] [very.HomematicDeviceDiscoveryService] - Stopping Homematic discovery scan
2018-12-04 19:08:25.071 [DEBUG] [very.HomematicDeviceDiscoveryService] - Waiting for finishing Homematic device discovery scan
2018-12-04 19:08:25.071 [DEBUG] [very.HomematicDeviceDiscoveryService] - Finished Homematic device discovery scan on gateway 'ccu'
2018-12-04 19:08:25.073 [DEBUG] [.eclipse.smarthome.binding.homematic] - ServiceEvent UNREGISTERING - {org.eclipse.smarthome.config.discovery.DiscoveryService}={service.id=422, service.bundleid=196, service.scope=singleton} - org.eclipse.smarthome.binding.homematic
2018-12-04 19:08:25.108 [DEBUG] [nal.communicator.server.XmlRpcServer] - Stopping XML-RPC server

Is this enough information for somebody to assess whether there is an issue in the binding or a configuration error?
With openHAB 2.3 and RaspberryMatic 2.xx I had no issues.

If I can assist with further information please let me know.

Kind regards,
Simon

**Comment by jewesta** [comment] 2018-12-04 19:07
Hi @simonskkaiser. I am reopening this issue, if that’s OK.
If there is anything I can do (testing, e.g.) please let me know.

**Comment by jewesta** [comment] 2018-12-04 19:13
Just for the record: I never reproduced the issue with debugging switched on. By the time I switched it on, the issue had gone. But the (fewer) log entries I got in „normal“ logging mode looked exactly like the ones in the log @simonskkaiser posted.

**Comment by MHerbst** [comment] 2018-12-04 19:31
I have got the same RaspberryMatic version and I have tried it with openHAB Build 1443 (I think it is one build after M6) and M7. Both are working fine. I have configured the HM bridge in Paper UI with default settings (the bridge was autodetected). I would recommend to remove the manual definition temporarily and execute a test with the default settings.

I have compared your CCU firewall settings with my settings and they are quite similar regarding the ports. These are mine: 2001;2000;2010;8701;8181;9292;43439

In addition I have also configured my network under "IP-Adressen für den eingeschränkten Zugriff" (I am not sure whether this is really necessary). 

I have read in somewhere also that access problems may also caused because of the new reverse proxy for XMLRPC. Please check your Security settings and especially this setting:
![image](https://user-images.githubusercontent.com/616792/49467759-7406e780-f803-11e8-86c1-557709b69fae.png)
If it is not deactivated yet, please try with deactivated authentification.

If this solves the problem we should add a hint to the documentation.

**Comment by jewesta** [comment] 2018-12-04 21:04
I googled the Java BindException. Some have reported that they experienced this exception (completely different context though) after an IP address change.

From experience I can say that Mac networking can be problematic. Since it self-healed in my setup I would double check your infrastructure and I really suspect there is a random issue with the networking stack inside OSX. I have had situations where my mac would fail to reach IP addresses on my local network for no apparent reason. Especially after shuffling around some addresses by adding new devices and/or restarting others.

Have you checked your hosts-file?

**Comment by simonskkaiser** [comment] 2018-12-05 18:49
Interesting, it seems to be my mistake, although I cannot figure out, what went wrong.
Using network_mode: "host" breaks almost everything else, as my MQTT and DB all run in docker alongside openHAB, but HomeMatic starts working.
I'll have to dive deeper into my docker setup to try and find out what goes wrong when initialising the  connection through the network interface.

Sorry for the reopened issue, I was and still am not aware what changed in my network/docker configuration in the 10 minutes downtime of my container.
Maybe the exception could be caught to make the user aware, that there is a network connection issue?

Thank you all for your immediate help with debugging this issue.

**Comment by htreu** [comment] 2018-12-10 07:37
Closing here since this is an infrastructure problem.

**Closed by htreu** 2018-12-10 07:37 UTC
Labels: Binding-Homematic

**Comment by SymanK83** [comment] 2018-12-25 21:14
[https://github.com/eclipse/smarthome/issues/6547](url)
This issue was caused by the binding not binding to the correct network interface. See the above issue for reference. The fix/configuration enhancement has been merged already.
This may be relevant for anybody coming across this issue.
