### ISSUE TITLE
Thing Lifecycle : incorrect ThingStatus being reported, ThingHandler not being removed

### ISSUE THREAD

**Issue by kgoderis** [eclipse/smarthome#2945] opened 2017-01-31 20:51 UTC
I am prudent to call this a bug, but I witnessed the following strange behaviour. I have defined a Thing (a Tesla binding Thing), and then stop and start the binding through the console to test the lifecycle of the Thing. In the beginning all goes well:

The binding is started:

osgi> smarthome things
tesla:models:v12killer (Type=Thing, Status=**ONLINE**, Label=Tesla Model S, Bridge=null)

The binding is stopped:

osgi> stop 95
2017-01-31 21:36:35.925 [DEBUG] [.c.thing.internal.ThingManager:1018 ] - Thing handler factory 'TeslaHandlerFactory' removed
2017-01-31 21:36:35.925 [DEBUG] [.c.thing.internal.ThingManager:768  ] - Calling unregisterHandler handler for thing 'tesla:models:v12killer' at 'org.openhab.binding.tesla.internal.TeslaHandlerFactory@712648d8'.
2017-01-31 21:36:35.927 [DEBUG] [.c.thing.internal.ThingManager:800  ] - Calling dispose handler for thing 'tesla:models:v12killer' at 'org.openhab.binding.tesla.handler.TeslaHandler@4a8e48b3'.
2017-01-31 21:36:35.932 [DEBUG] [c.x.o.XmlDocumentBundleTracker:236  ] - Removing the XML related objects from module 'org.openhab.binding.tesla'...
2017-01-31 21:36:35.932 [DEBUG] [c.x.o.XmlDocumentBundleTracker:194  ] - Release the XmlDocumentProvider for the module 'org.openhab.binding.tesla'.
2017-01-31 21:36:35.935 [DEBUG] [c.x.o.XmlDocumentBundleTracker:236  ] - Removing the XML related objects from module 'org.openhab.binding.tesla'...
2017-01-31 21:36:35.935 [DEBUG] [c.x.o.XmlDocumentBundleTracker:194  ] - Release the XmlDocumentProvider for the module 'org.openhab.binding.tesla'.
2017-01-31 21:36:35.936 [DEBUG] [c.x.o.XmlDocumentBundleTracker:236  ] - Removing the XML related objects from module 'org.openhab.binding.tesla'...

osgi> smarthome things
tesla:models:v12killer (Type=Thing, Status=**UNINITIALIZED (HANDLER_MISSING_ERROR)**, Label=Tesla Model S, Bridge=null)

So far so good. I start the binding again

osgi> start 95
osgi> 2017-01-31 21:36:53.220 [DEBUG] [c.x.o.XmlDocumentBundleTracker:126  ] - Reading the XML document '/ESH-INF/binding/binding.xml' in module 'org.openhab.binding.tesla'...
2017-01-31 21:36:53.220 [DEBUG] [c.x.o.XmlDocumentBundleTracker:126  ] - Reading the XML document '/ESH-INF/thing/models.xml' in module 'org.openhab.binding.tesla'...
2017-01-31 21:36:53.221 [DEBUG] [c.x.o.XmlDocumentBundleTracker:177  ] - Create an empty XmlDocumentProvider for the module 'org.openhab.binding.tesla'.
2017-01-31 21:36:53.222 [DEBUG] [c.c.BundleProcessorVetoManager:70   ] - 'org.openhab.binding.tesla' still vetoed by '[org.eclipse.smarthome.config.xml.osgi.XmlDocumentBundleTracker$1@5fd4549f(/ESH-INF/thing/)]', queueing '[org.openhab.binding.tesla.handler.TeslaHandler@32cb22a6]'
2017-01-31 21:36:53.223 [DEBUG] [c.c.BundleProcessorVetoManager:70   ] - 'org.openhab.binding.tesla' still vetoed by '[org.eclipse.smarthome.config.xml.osgi.XmlDocumentBundleTracker$1@5fd4549f(/ESH-INF/thing/)]', queueing '[org.openhab.binding.tesla.internal.TeslaHandlerFactory@6f08011e]'
2017-01-31 21:36:53.237 [DEBUG] [c.x.o.XmlDocumentBundleTracker:177  ] - Create an empty XmlDocumentProvider for the module 'org.openhab.binding.tesla'.
2017-01-31 21:36:53.240 [DEBUG] [c.c.BundleProcessorVetoManager:65   ] - Finished loading meta-data of bundle 'org.openhab.binding.tesla'.
2017-01-31 21:36:53.242 [DEBUG] [c.c.BundleProcessorVetoManager:65   ] - Finished loading meta-data of bundle 'org.openhab.binding.tesla'.
2017-01-31 21:36:53.252 [DEBUG] [e.s.m.t.i.GenericThingProvider:1043 ] - Updating thing 'tesla:models:v12killer' from model 'tesla.things'.
2017-01-31 21:36:53.253 [DEBUG] [.c.thing.internal.ThingManager:532  ] - Cannot notify handler about updated thing 'tesla:models', because handler is not initialized (thing must be in status UNKNOWN, ONLINE or OFFLINE). Starting handler initialization instead.
2017-01-31 21:36:53.256 [DEBUG] [.c.thing.internal.ThingManager:653  ] - Attempt to initialize a handler twice for thing 'tesla:models:v12killer' at the same time will be ignored.

(Why does it say that the handler is initialised twice?)

In the logs I also get:

2017-01-31 21:41:23.295 [INFO ] [ome.event.ThingStatusInfoEvent:43   ] - 'tesla:models:v12killer' updated: ONLINE
2017-01-31 21:41:23.295 [INFO ] [nt.ThingStatusInfoChangedEvent:43   ] - 'tesla:models:v12killer' changed from INITIALIZING to **ONLINE**

together with all the usual logging the the handler spits out on the Tesla vehicle (= binding is running) but the console reports:

osgi> smarthome things
tesla:models:v12killer (Type=Thing, Status=**INITIALIZING**, Label=Tesla Model S, Bridge=null)

How is that possible? Why is the state wrongly reported? 

I stop the binding again:

osgi> stop 95
2017-01-31 21:44:44.775 [DEBUG] [.c.thing.internal.ThingManager:1018 ] - Thing handler factory 'TeslaHandlerFactory' removed
2017-01-31 21:44:44.778 [DEBUG] [c.x.o.XmlDocumentBundleTracker:236  ] - Removing the XML related objects from module 'org.openhab.binding.tesla'...
2017-01-31 21:44:44.778 [DEBUG] [c.x.o.XmlDocumentBundleTracker:194  ] - Release the XmlDocumentProvider for the module 'org.openhab.binding.tesla'.
2017-01-31 21:44:44.780 [DEBUG] [c.x.o.XmlDocumentBundleTracker:236  ] - Removing the XML related objects from module 'org.openhab.binding.tesla'...
2017-01-31 21:44:44.780 [DEBUG] [c.x.o.XmlDocumentBundleTracker:236  ] - Removing the XML related objects from module 'org.openhab.binding.tesla'...
2017-01-31 21:44:44.780 [DEBUG] [c.x.o.XmlDocumentBundleTracker:194  ] - Release the XmlDocumentProvider for the module 'org.openhab.binding.tesla'.

osgi> smarthome things
tesla:models:v12killer (Type=Thing, Status=**INITIALIZING**, Label=Tesla Model S, Bridge=null)

osgi> ls | grep tesla
false

dispose() is not called on the Handler, and the handler happily keeps running even when the bundle is gone!

**Comment by kgoderis** [comment] 2017-01-31 21:34
[Solved, but with possible some documentation changes to be made]

The runtime expects the Handler to set the ThingState in initialise(). So, if the initialisation of the ThingHandler is off-loaded to a separate thread (because it would not return fast enough, or other reason), then still in initialize() it is expected to set the State explicitly. If not, the phenomena here above is observed. We should make this clear in the documentation. 

Secondly, if the ThingStatus is set in a separate thread, and when intialize() and dispose() are used to schedule or cancel that thread, then a RentrantLock should be used around the code to schedule/cancel the thread. If not, there is a condition possible whereby the given thread is scheduled twice (when checking on isCancelled()...). A lot of bindings use this pattern to set up and tear down the handler.

**Comment by sjka** [comment] 2017-02-01 08:01
> We should make this clear in the documentation.

You are obviously right. If _you_ don't know it and don't see it, other people might also not see it. We have this info in there though: 

(From [Thing Handler Documentation](https://www.eclipse.org/smarthome/documentation/development/bindings/thing-handler.html)):

"Only Things with status (cf. Thing Status) UNKNOWN, ONLINE or OFFLINE are considered as initialized by the framework and therefore **it is the handler’s duty to assign one of these states sooner or later**. To achieve that, the status must be reported to the framework via the callback or BaseThingHandler.updateStatus(...) for convenience. Furthermore, the framework expects initialize() to be non-blocking and to return quickly. For longer running initializations, the implementation has to take care of scheduling a separate job which **must guarantee to set the status eventually**."

Something very similar is written in the `ThingHandler.initialize()` JavaDoc. Obviously we need to be more clear about this - where and how? Help with improving the documentation is highly appreciated!

> (Why does it say that the handler is initialised twice?)

As far as I can see, the shutdown procedure looks okay from the framework perspective: `ThingHandler.dispose()` _is_ called that the Thing is set to UNINITIALIZED so that the process can start from scratch when the factory comes back. Which it does. 

However, there indeed is something in your logs which worries me (as well as it did you):

```
2017-01-31 21:36:53.222 [DEBUG] [c.c.BundleProcessorVetoManager:70 ] - 'org.openhab.binding.tesla' still vetoed by [...], queueing '[org.openhab.binding.tesla.handler.TeslaHandler@32cb22a]'
2017-01-31 21:36:53.223 [DEBUG] [c.c.BundleProcessorVetoManager:70 ] - 'org.openhab.binding.tesla' still vetoed by [...], queueing '[org.openhab.binding.tesla.internal.TeslaHandlerFactory@6f08011]'
2017-01-31 21:36:53.252 [DEBUG] [e.s.m.t.i.GenericThingProvider:1043 ] - Updating thing 'tesla:models:v12killer' from model 'tesla.things'.
2017-01-31 21:36:53.253 [DEBUG] [.c.thing.internal.ThingManager:532 ] - Cannot notify handler about updated thing 'tesla:models', because handler is not initialized (thing must be in status UNKNOWN, ONLINE or OFFLINE). Starting handler initialization instead.
```

It looks like a little race condition between a ThingHandler which could not be initialized at first because the bundle was not yet fully loaded and the ThingHandlerFactory which had to wait with loading its Things from the Model until the bundle is fully loaded. 

Question is: Why is there already a ThingHandler although the Thing could not yet be loaded...?

**Comment by kgoderis** [comment] 2017-02-01 08:36
> it is the handler’s duty to assign one of these states sooner or later

In fact, it does so, but in a separate thread. And even when it is set in another thread, somehow this yields this phenomena of different ThingStates. Somehow it has to be set by the Thread that calls Initialize(), but I do not (yet) fully understand the reason for this

On the ThingHandler being present, maybe it was still the previous instance of the Handler being present? At the end I did a rather "quick" succession of "stop" and "start" bundle commands.

**Comment by sjka** [comment] 2017-02-01 09:26
Okay, I could reproduce the issue in a test case. Will look into it and provide a fix.

**Comment by kgoderis** [comment] 2017-02-03 16:24
@kaikreuzer My wrong usage of wording in  openhab/openhab2-addons#1813. That PR provides a work-around, but the root cause is still prevailing, maybe we need this issue open for the time being while @sjka is working on a fix

**Comment by kaikreuzer** [comment] 2017-02-03 16:32
That was Githubs auto-closing feature, not me ;-) Reopening again.

**Comment by maggu2810** [comment] 2017-02-04 09:02
> That was Githubs auto-closing feature

That is rather strange for me. Why can a PR in the openHAB addons repo auto close an issue in the ESH repo?

**Comment by kaikreuzer** [comment] 2017-02-04 09:08
That's how it works - maybe only because I have the right to close issues on both repos. I don't know if it would also do it if someone else does the merge.

**Closed** 2017-03-13 15:35 UTC
