### ISSUE TITLE
[LSP] Internal error when client reloads window

### ISSUE THREAD

**Issue by kubawolanin** [eclipse/smarthome#4459] opened 2017-10-26 16:34 UTC
Just tried to test LSP on `openHAB 2.2.0~20171025192122-1 (Build #1070)` without success.
VSCode extension: 0.2.0
Other users are also [reporting](https://community.openhab.org/t/visual-studio-code-openhab-extension/30205/107) the issues. 

cc: @sjka 

Steps to reproduce:
1. Install `lsp` addon to openHAB SNAPSHOT # 1070
2. Open VSCode with openHAB extension within `config` folder and proper REST connections setup (`openhab.host` config parameter pointing to the right *remote* address)
3. Add a new rule with `sendCommand()`
4. Reload window (Ctrl + Shift + P > type Reload window)

Expected result:
LSP highlights errors in the rule.

Actual result:
No errors appear on the editor. The following logs occur:

vscode output:
```log
[Error - 18:28:09] Server initialization failed.
  Message: Internal error, please look at the server's logs.
  Code: -32603 
```

openhab.log:
```log
2017-10-26 18:26:49.595 [ERROR] [eclipse.lsp4j.jsonrpc.RemoteEndpoint] - Internal error: java.lang.reflect.InvocationTargetException
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:53) ~[195:org.eclipse.lsp4j.jsonrpc:0.2.1.v20170706-0855]
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:105) [195:org.eclipse.lsp4j.jsonrpc:0.2.1.v20170706-0855]
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:203) [195:org.eclipse.lsp4j.jsonrpc:0.2.1.v20170706-0855]
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:139) [195:org.eclipse.lsp4j.jsonrpc:0.2.1.v20170706-0855]
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:149) [195:org.eclipse.lsp4j.jsonrpc:0.2.1.v20170706-0855]
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:77) [195:org.eclipse.lsp4j.jsonrpc:0.2.1.v20170706-0855]
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:84) [195:org.eclipse.lsp4j.jsonrpc:0.2.1.v20170706-0855]
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:51) ~[?:?]
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:51) ~[?:?]
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:103) [195:org.eclipse.lsp4j.jsonrpc:0.2.1.v20170706-0855]
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:84) [195:org.eclipse.lsp4j.jsonrpc:0.2.1.v20170706-0855]
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:61) ~[?:?]
2017-10-26 18:28:04.591 [DEBUG] [thome.model.lsp.internal.ModelServer] - Client /192.168.0.X:50950 disconnected
2017-10-26 18:28:08.623 [DEBUG] [thome.model.lsp.internal.ModelServer] - Going to wait for a client to connect
2017-10-26 18:28:08.623 [DEBUG] [thome.model.lsp.internal.ModelServer] - Client /192.168.0.X:50960 connected
2017-10-26 18:28:09.770 [ERROR] [eclipse.lsp4j.jsonrpc.RemoteEndpoint] - Internal error: java.lang.reflect.InvocationTargetException
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:53) ~[195:org.eclipse.lsp4j.jsonrpc:0.2.1.v20170706-0855]
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:105) [195:org.eclipse.lsp4j.jsonrpc:0.2.1.v20170706-0855]
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:203) [195:org.eclipse.lsp4j.jsonrpc:0.2.1.v20170706-0855]
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:139) [195:org.eclipse.lsp4j.jsonrpc:0.2.1.v20170706-0855]
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:149) [195:org.eclipse.lsp4j.jsonrpc:0.2.1.v20170706-0855]
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:77) [195:org.eclipse.lsp4j.jsonrpc:0.2.1.v20170706-0855]
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:84) [195:org.eclipse.lsp4j.jsonrpc:0.2.1.v20170706-0855]
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:51) ~[?:?]
```
```
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:53) ~[195:org.eclipse.lsp4j.jsonrpc:0.2.1.v20170706-0855]
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:105) [195:org.eclipse.lsp4j.jsonrpc:0.2.1.v20170706-0855]
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:203) [195:org.eclipse.lsp4j.jsonrpc:0.2.1.v20170706-0855]
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:139) [195:org.eclipse.lsp4j.jsonrpc:0.2.1.v20170706-0855]
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:149) [195:org.eclipse.lsp4j.jsonrpc:0.2.1.v20170706-0855]
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:77) [195:org.eclipse.lsp4j.jsonrpc:0.2.1.v20170706-0855]
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:84) [195:org.eclipse.lsp4j.jsonrpc:0.2.1.v20170706-0855]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:?]
	at java.lang.Thread.run(Thread.java:745) [?:?]
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:51) ~[?:?]
	... 11 more
Caused by: java.lang.IllegalArgumentException: Missing scheme
	at java.nio.file.Paths.get(Paths.java:134) ~[?:?]
	at org.eclipse.xtext.ide.server.UriExtensions.toPath(UriExtensions.java:36) ~[?:?]
	at org.eclipse.xtext.ide.server.UriExtensions.toPath(UriExtensions.java:31) ~[?:?]
	at org.eclipse.xtext.ide.server.LanguageServerImpl.getBaseDir(LanguageServerImpl.java:230) ~[?:?]
	at org.eclipse.xtext.ide.server.LanguageServerImpl.initialize(LanguageServerImpl.java:176) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:51) ~[?:?]
	... 11 more
```

**Comment by sjka** [comment] 2017-10-27 07:20
That's nasty... I'll try reproducing it and see if that's something we can fix or forward it to the xtext/lsp4j projects otherwise.

**Comment by sjka** [comment] 2017-10-27 07:26
I just updated my openHAB extension in VSCode to 0.2.0 - now I only get 

```
[Error - 09:23:40] Connection to server is erroring. Shutting down server.
[Error - 09:23:40] Connection to server is erroring. Shutting down server.
```

My breakpoints in the runtime are not hit, so it doesn't look like it was trying to connect at all. Any hints?

**Comment by sjka** [comment] 2017-10-27 08:10
Ahh, found it. You  secretly introduced a config parameter 😉 

I have created #43 to add it to the configuration description in order to benefit from the default value.

**Comment by maggu2810** [comment] 2017-11-05 11:04
Can you point us to the correct `#43`?

**Comment by kubawolanin** [comment] 2017-11-05 11:22
@maggu2810 I believe it's this one: https://github.com/openhab/openhab-vscode/pull/43

**Comment by maggu2810** [comment] 2017-11-06 15:11
Thank you @kubawolanin

**Comment by triller-telekom** [comment] 2018-04-19 13:50
I do not get any errors/warnings in the ESH console if I refresh my VisualStudioCode.

@sjka Was this issue fixed by your PR in openhab/openhab-vscode#43 ? Or did it just disappear? :) Please have a look at it since it was your PR and close this issue.

**Comment by sjka** [comment] 2018-04-19 14:33
No, openhab/openhab-vscode#43 only prevented me from reproducing it. But as we are speaking about that: I currently also cannot reproduce _this_ bug. Therefore I'll indeed close it until further complaints.

**Closed by sjka** 2018-04-19 14:34 UTC

**Comment by mjcumming** [comment] 2018-06-14 12:08
I am getting the error 
`[Error - 7:05:57 AM] Request textDocument/hover failed.
  Message: Internal error, please look at the server's logs.
  Code: -32603 `

I do not see anything in the openHAB2 log viewer. Any information I can add to help?

Mike

**Comment by triller-telekom** [comment] 2018-06-15 08:50
@mjcumming Since this issue is closed and your problem is clearly unrelated, may I kindly ask to create a new issue for your concern, please? And please describe what you did before you got this error, because otherwise no one can help you.

**Comment by mjcumming** [comment] 2018-06-15 16:01
will do!
