### ISSUE TITLE
New errors from sonos binding

### ISSUE THREAD

**Issue by JueBag** [eclipse/smarthome#1524] opened 2016-05-17 16:36 UTC
Hi,
after installing the last nigthly build from saturday ( Online Build #298) I'm getting error log entries from my sonos players like:

```
22:25:05.502 [ERROR] [g.jupnp.protocol.sync.ReceivingEvent] - Invalid subscription ID, no active subscription: (IncomingEventRequestMessage) NOTIFY /upnpcallback/dev/RINCON_B8E937BDEF0E01400_MR/svc/upnp-org/AVTransport/event/cb SEQUENCE: 7
```

I observed a change on the discovered things. On PaperUI each player used to be detected as something like: # **"sonos:zoneplayer:RINCON_B8E937BDEF0E01400",** however after the update that changed to : "sonos:PLAY1:RINCON_B8E937BDEF0E01400".
I changed that in my .Items file accordingly, resulting in responsive controls on my ClassicUI, however now I get those above mentioned errors. When using the old notation the controlls are NOT responsive.

**Comment by kaikreuzer** [comment] 2016-05-17 16:39
The change from zoneplayer to PLAY1 is correct, the updated binding now has individual support for specific features of the different devices.

Regarding the error logging, this is indeed not good and must be changed. Does it all work as expected despite the error messages?
@R-Edelhoff Could you please have a look at these errors? Thanks!

**Comment by JueBag** [comment] 2016-05-17 17:01
Yes, as far as I can say everything is working if the Items definition is changed  as stated above.

**Comment by R-Edelhoff** [comment] 2016-05-18 15:37
I was able to reproduce this issue and saw that it only occures when updating the Sonos binding while there are Sonos Things paired. When the binding is updated all upnp services will be subscribed again which leads to this error for one of these services (One of the subscriptionIDs is unknown to jupnp). This issue should only happen once after updating the binding and should be gone when repairing the Sonos devices.
 
It seems to be the case that the ThingType recreation ('zoneplayer' to 'PLAY1') has some influence here since the issue cannot be reproduced when "changeThingType()" is not invoked. 
Currenlty i am not sure why the subscription error occures in jupnp when the ThingType is changed.

**Comment by JueBag** [comment] 2016-05-18 16:07
OK.
So what should be the correct procedure for updating? 
Should all Sonos players be deleted before updating? 
Should the .Items file be updated manually with the new  naming convention? Or I  did I do something the wrong way?

**Comment by R-Edelhoff** [comment] 2016-05-18 16:12
As for now it would be best to unpair all Sonos devices before updating and re-pair them after the update has been executed. The ThingTypes however need to be adjusted in the .items file as they have changed in the new binding.

**Comment by JueBag** [comment] 2016-05-18 16:20
Thanks. If following that the error hold not occur, so I would not call that a bug.

**Comment by kaikreuzer** [comment] 2016-05-19 07:42
@JueBag So if you can confirm that after the migration the error does not occur anymore (as well as for any newly paired speaker), I would suggest to close this issue.

**Comment by JueBag** [comment] 2016-05-19 07:54
I'l be back home tonigth and will recheck.

**Comment by JueBag** [comment] 2016-05-19 18:21
Rechecked it, and its working as said by @R-Edelhoff. So closing is OK for me
One thing: Shouldn't this [https://github.com/mworion/openhab2/tree/master/addons/binding/org.openhab.binding.sonos](url) be updated with new syntax for the .Items file?

**Comment by kaikreuzer** [comment] 2016-05-19 18:56
There shouldn't be anything in the openhab2 repo about Sonos - your link is a 404...

**Closed by kaikreuzer** 2016-05-19 18:56 UTC

**Comment by maggu2810** [comment] 2016-05-19 19:52
There is something wrong with the address that is pointed to by the link.
But as it could be seen by the link text (that is IMHO the URL the link should point to) the link pointed to a forked openhab2 repository by mworion.
https://github.com/mworion/openhab2/tree/master/addons/binding/org.openhab.binding.sonos

@JueBag 
So, whatever you find in the repositories of @mworion should be discussed with that person.

**Comment by mworion** [comment] 2016-05-20 05:00
Hello,

Still forked openhanded for test purpose. I use it not any longer, so I delete it.

Orion.

Von meinem iPad gesendet
