### ISSUE TITLE
Image Link: Authentication not working anymore in 1009/Karaf 4.1.2

### ISSUE THREAD

**Issue by michaeljoos72** [eclipse/smarthome#4044] opened 2017-08-13 12:31 UTC
Hi

Not sure if this is related to snapshot build 1009 or with new Karaf Upgrade 4.1.2

But Sitemap-Images with authentication do not work anymore:

Image icon="camera" url="http://**user:password**@192.168.1.52/axis-cgi/jpg/image.cgi?camera=1&resolution=1280x720&compression=25" refresh=10000

In Webbrowers I get this dialog and in HabDroid there is no picture:

![image](https://user-images.githubusercontent.com/20517474/29249601-38b1b3e8-8033-11e7-837e-6c57c94480cb.png)

This was not the case in snapshot 1008

Thanks
Michael

**Comment by kaikreuzer** [comment] 2017-08-13 20:15
The ESH version has not changed between the builds 1008 and 1009.
The only thing that changed in this context is the version of Jetty (and thus also the Jetty Proxy, which is used for the image widgets) - it has been upgraded from 9.2.19 to 9.3.14. We would have to check whether our code requires some change here (and if so we need to think about more strictly defining the compatible version).

**Comment by kaikreuzer** [comment] 2017-08-13 20:31
The good news is: I can reproduce the issue.
The bad news is: We therefore indeed seem to have an issue 😞 .

I just briefly googled and came across https://github.com/eclipse/jetty.project/issues/806, which is fixed in 9.3.14 - afair, we did a workaround because of this bug, so it might make sense to use the new feature now. @svilenvul, as you were the bug reporter at that time, would you want to check that? It would mean though that we have to set the minimal version requirement of the Jetty client to 9.3.12 (which would be ok for me).

**Comment by watou** [comment] 2017-08-14 06:14
It may be that later [AbstractProxyServlet.java](https://github.com/eclipse/jetty.project/commits/jetty-9.4.x/jetty-proxy/src/main/java/org/eclipse/jetty/proxy/AbstractProxyServlet.java) versions no longer call the deprecated [`copyHeaders`](https://github.com/eclipse/smarthome/pull/2753/files#diff-58b13e7e76574d68a9bff9904cd8d817R56) (see my comment in the code) so the proxy servlet has to now instead override `copyRequestHeaders`. in order to maybe append the auth headers.

**Comment by kaikreuzer** [comment] 2017-08-14 06:39
Thanks for the hint, @watou! I remembered that there was some code that is to be changed when upgrading, but couldn't find it anymore (I only checked `ProxyServlet` and missed looking at the `AsyncProxyServlet`).

**Comment by kaikreuzer** [comment] 2017-08-14 07:28
Ok, I have updated my local target platform to include Jetty 9.3.14 and I indeed even get compilation errors at that code now - I'll look at how to get it working.

@maggu2810 & @sjka I guess as a result we should increase the minimal required version of Jetty to 9.3.x as we cannot guarantee compatibility otherwise. As Karaf/Pax-Web is by now on 9.3 as well, there probably isn't a strong reason for keeping support for 9.2 up, wdyt?

**Comment by sjka** [comment] 2017-08-14 08:13
I'm not aware of any, so okay from my side.

**Comment by svilenvul** [comment] 2017-08-14 08:58
>Thanks for the hint, @watou! I remembered that there was some code that is to be changed when upgrading, but couldn't find it anymore (I only checked ProxyServlet and missed looking at the AsyncProxyServlet).

I think this should be changed after the upgrade - https://github.com/eclipse/smarthome/blob/afe6ecafe38faccb8b705a9087de472da0d8bd21/bundles/io/org.eclipse.smarthome.io.net/src/main/java/org/eclipse/smarthome/io/net/http/HttpUtil.java#L196-L208

**Comment by kaikreuzer** [comment] 2017-08-14 09:07
That's the place that you could adapt once we upgraded, but the place that fixes the AsyncProxyServlet is [here](https://github.com/eclipse/smarthome/blob/067bd5122b4666452bda319cb4e1de13eda9ab00/bundles/ui/org.eclipse.smarthome.ui/src/main/java/org/eclipse/smarthome/ui/internal/proxy/AsyncProxyServlet.java#L49-L60). I am already on it - most work is the adaption of the target platform...

**Comment by kaikreuzer** [comment] 2017-08-14 10:17
Issue should be fixed by #4047.
@svilenvul Once this is merged, feel free to create a PR that cleans the HttpUtil from the current workaround, which then won't be needed anymore.

**Comment by maggu2810** [comment] 2017-08-14 13:15
> @maggu2810 & @sjka I guess as a result we should increase the minimal required version of Jetty to 9.3.x as we cannot guarantee compatibility otherwise. As Karaf/Pax-Web is by now on 9.3 as well, there probably isn't a strong reason for keeping support for 9.2 up, wdyt?

Okay for me.

**Closed** 2017-08-14 13:15 UTC
Labels: bug, Core
