### ISSUE TITLE
Random order of group members

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#4232] opened 2017-09-09 13:00 UTC
I moved from OH snapshot 1003 to snapshot 1034 and unfortunately discovered that group members are now presented in a random order and no more like since the origin of OH in the order they are declared in the item file.
Why having changed that ? This was practical to have a kind of control on the group members order.
It has been changed after snapshot 1003.

**Comment by openhab-5iver** [comment] 2017-09-10 09:00
The order of group members will also change after items files are saved.  So, after you get accustom to a random order, after you save an items file, you need to get used to another random order. I migrated from OH1 and have been using snapshots since before 2.1. I could be mistaken, but I think I've seen groups behave this way since I migrated. I'm currently on 1033. My preference would be for the group members to be listed alphabetically.

**Comment by lolodomo** [comment] 2017-09-10 09:05
My openHAB environment in production is stable and I don't update my items without restarting OH.
I am just asking myself why breaking something that was useful for most of users ?
Having the order of definition in the config file was a good idea.

**Comment by kaikreuzer** [comment] 2017-09-10 18:13
Looks like a duplicate of #3321 to me.

**Comment by lolodomo** [comment] 2017-09-10 18:59
No it is a different issue because I am not editing any file, I am just starting OH.
Until snapshot 1003, after a startup, the group members were in the order they are declared in my items file. No more with snapshot 1034.

**Comment by kaikreuzer** [comment] 2017-09-11 06:34
Editing also causes a reload, so I would say that it is very likely the same cause. Anyhow, if #3321 is fixed, your issue should not appear anymore either.

**Comment by sjka** [comment] 2017-09-11 13:24
as this concerns different locations in the code, let's keep the issues separate (although I understand that from a users' perspective it sucks equally).

**Closed** 2017-09-11 14:06 UTC
