### ISSUE TITLE
Yahoo Weather Bindings shows wrong Air Pressure

### ISSUE THREAD

**Issue by JungeG** [eclipse/smarthome#2527] opened 2016-11-24 08:12 UTC
after installing the Yahoo Weather Binding and setting the woeid 15002743 (Pinneberg). The air pressure is displayed with 33931,6 hPa, the web page shows 1002.0 Millibar - see attachment.
![yahoo weather binding](https://cloud.githubusercontent.com/assets/20333190/20590884/f697949a-b225-11e6-8c50-9be90008a28d.png)
![yahoo web page](https://cloud.githubusercontent.com/assets/20333190/20590885/f698c6e4-b225-11e6-8ddf-1f5170ae405b.png)

**Comment by kaikreuzer** [comment] 2016-11-24 08:54
Duplicate of https://github.com/eclipse/smarthome/issues/2502

**Closed by kaikreuzer** 2016-11-24 08:54 UTC
