### ISSUE TITLE
Advanced dynamically added channels are not hidden in Paper UI

### ISSUE THREAD

**Issue by wborn** [eclipse/smarthome#2911] opened 2017-01-28 11:31 UTC
For #2663 I am dynamically adding advanced channels (`colorzone`, `temperaturezone`) to `colormzlight` Things. That works well, however Paper UI does not hide these `advanced` channels when configuring or controlling a Thing.

I did some research and to me it seems Paper UI uses the response from the `thing-types` REST service to determine if channels should be hidden. 

However the dynamic channel types (`colorzone`, `temperaturezone`) are missing from the response of http://localhost:8080/rest/thing-types/lifx:colormzlight :

```json
{
    "channels": [{
        "description": "Selects the color of the light",
        "id": "color",
        "label": "Color",
        "tags": ["Lighting"],
        "properties": {},
        "category": "ColorLight",
        "advanced": false,
        "typeUID": "lifx:color"
    }, {
        "description": "Sets the temperature of the light",
        "id": "temperature",
        "label": "Temperature",
        "tags": [],
        "properties": {},
        "category": "Temperature",
        "advanced": false,
        "typeUID": "lifx:temperature"
    }],
    "channelGroups": [],
    "configParameters": [{
        "label": "LIFX device ID",
        "name": "deviceId",
        "required": true,
        "type": "TEXT",
        "readOnly": false,
        "multiple": false,
        "advanced": false,
        "limitToOptions": true,
        "options": [],
        "filterCriteria": []
    }, {
        "defaultValue": "300",
        "description": "The time to fade to the new color value (in ms).",
        "label": "Fade time",
        "name": "fadetime",
        "required": false,
        "type": "INTEGER",
        "readOnly": false,
        "multiple": false,
        "advanced": false,
        "limitToOptions": true,
        "options": [],
        "filterCriteria": []
    }],
    "parameterGroups": [],
    "properties": {},
    "UID": "lifx:colormzlight",
    "label": "LIFX Color MultiZone Light",
    "listed": true,
    "supportedBridgeTypeUIDs": [],
    "bridge": false
}
```

The channel type definitions used can be found in this [channel.xml](https://github.com/wborn/smarthome/blob/2663-lifx-multizone-support/extensions/binding/org.eclipse.smarthome.binding.lifx/ESH-INF/thing/channel.xml)

The channels are then dynamically created in this [LifxLightHandler.java](
https://github.com/wborn/smarthome/blob/2663-lifx-multizone-support/extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/handler/LifxLightHandler.java#L299).

**Comment by maggu2810** [comment] 2017-01-29 16:08
Sounds like a bug to me.
Also for dynamically added channels the advanced flag should be considered by using the resp. channel type regardless if it is part of the thing type.

**Comment by kaikreuzer** [comment] 2017-01-30 08:28
@maggu2810 I do not agree that this seems to be a bug in the Paper UI.

@wborn says: "However the dynamic channel types (colorzone, temperaturezone) are missing from the response" - so this is a problem in the REST API / ThingTypeRegistry and as such it looks like a duplicate of https://github.com/eclipse/smarthome/issues/2903 (although the analysis here on #2911 looks much more straight forward, so we might rather want to close #2903 as a duplicate...)

**Comment by kaikreuzer** [comment] 2017-01-30 08:31
I should read more carefully. Yes, if a channel is not part of the thing-type, its according channel-type info should be requested from channel-types REST uri instead.

@aounhaider1 Can you fix that?

**Comment by wborn** [comment] 2017-01-30 21:13
Thanks for having a look at this issue @aounhaider1 . I just made a local build with your fix and now see that the advanced property is part of the REST response. The Paper UI does not seem to use this property to determine if the channels should be hidden when configuring a Thing. 

See also the following screenshot:

![advanced-dynamic-channels](https://cloud.githubusercontent.com/assets/12213581/22441565/37345e74-e738-11e6-9e86-ed1b646ad59b.png)

---

---

I'm not sure if Paper UI should also hide advanced channels that are linked when controlling a thing. Currently it does not for these channels:

![advanced-dynamic-channels2](https://cloud.githubusercontent.com/assets/12213581/22441569/3ce3a208-e738-11e6-9a8c-fdeadfb2680b.png)

I don't remember ever seeing a "Show more/less" button in the Control view. So this may be a separate  issue.

**Comment by aounhaider1** [comment] 2017-01-31 10:05
I have created https://github.com/eclipse/smarthome/issues/2939 for first issue.
And you are right, show more/less option is not available on Control page at all.

**Comment by wborn** [comment] 2017-02-01 00:52
Thanks for having another look at the issue @aounhaider1 . I've made another local build but found that the channels were still not being hidden.

After debugging I think the remaining issue is that the Paper UI code is using `thingConfigService.getChannelTypeById(...)` in `checkAdvance(channels)` and `filterAdvance`  to compare `channel.id` (colorzone0, colorzone1, etc.) against `channelType.UID` (colorzone and temperaturezone).

Here are some AngularJS scope summaries that show what is happening in case of my binding:

```
thing:  { 
    channels: [
    ...
    { 
        linkedItems: [ Lifx_Z_2_Color_Zone0 ]
        uid: lifx:colormzlight:D073D5147687:colorzone0
        id: colorzone0
        channelTypeUID: lifx:colorzone
        itemType: ColorItem
        kind: STATE
        label: Color zone 0
        defaultTags: [  ]
        properties: {  } 
        configuration: {  } 
        showItems: false
        items: null
    } 
    ...
    ]
},


thingType:  { 
    channels: [
        {
            description: Selects the color of the light
            id: color
            label: Color
            tags: [ Lighting ]
            properties:  {  } 
            category: ColorLight
            advanced: false
            typeUID: lifx:color
        },
        ...
    ]
},


channelTypes: [
    ...
    { 
        parameters: [  ]
        parameterGroups: [  ]
        description: Selects the zone color of the light
        label: Color zone
        category: ColorLight
        itemType: Color
        kind: STATE
        tags: [ Lighting ]
        UID: lifx:colorzone
        advanced: true
    },
    ...
]
```

With the following changes I can for instance get the channels on the colormzlight Things to be properly hidden.

controllers.configuration.js
```
function checkAdvance(channels) {
    if (channels) {
        for (var i = 0, len = channels.length; i < len; i++) {
            var channel = channels[i];
            var id = channel.channelTypeUID.split(':', 2)[1];
            var channelType = $scope.getChannelTypeById(id);
            if (channelType && channelType.advanced) {
                return true;
            }
        }
    }
}
```

services.js
```
filterAdvance : function(thingType, channelTypes, channels, advanced) {
    var self = this;
    self.thingType = thingType, self.channelTypes = channelTypes, self.channels = channels;
    return $.grep(channels, function(channel, i) {
        var id = channel.channelTypeUID.split(':', 2)[1];
        var channelType = self.getChannelTypeById(self.thingType, self.channelTypes, id);
        return channelType ? advanced == channelType.advanced : true;
    });
},
```

Would that actually be a good solution? It is a bit unclear to me if  `getChannelTypeById(..)` should use channelId's or channelTypeId's as parameter.

**Comment by aounhaider1** [comment] 2017-02-01 14:53
@wborn Can you please check if https://github.com/eclipse/smarthome/pull/2949 fixes the issue for you?

**Closed** 2017-02-02 09:38 UTC
Labels: bug, PaperUI
