### ISSUE TITLE
build failure (automation)

### ISSUE THREAD

**Issue by maggu2810** [eclipse/smarthome#698] opened 2015-12-09 09:34 UTC
On my machine the current master could not be build (first try, will do a second one).

Perhaps this is related to: #317

The maven log extract:
https://gist.github.com/maggu2810/2347643952acf2ee8988

**Comment by maggu2810** [comment] 2015-12-09 09:57
Second one fails, too.
But a slightly different message.

The maven log extract:
https://gist.github.com/maggu2810/242c724fe3b98229f52f

first:
```text
Failed tests: 
  AutomationIntegrationTest.test chain of composite Modules:430->OSGiTest.waitForAssert:181 
Expected: is not null
     but: was null
```

second:
```text
Failed tests: 
  AutomationIntegrationTest.assert that a rule created from a template is executed as expected:554->OSGiTest.waitForAssert:-1->OSGiTest.waitForAssert:181 
Expected: is <ON>
     but: was <NULL>
```

**Comment by maggu2810** [comment] 2015-12-09 10:17
@marinmitev Do you know what is going on here?

**Comment by maggu2810** [comment] 2015-12-09 12:57
@marinmitev or @danchom Do you know what is going on here?

**Comment by marinmitev** [comment] 2015-12-09 13:08
I have checked twice the latest code and it builds with success all modules and all tests (in under 9minutes).
However your logs show that for some reason some of the test rules were not executed
I would recommend you to check with increasing the waiting time for the assertions on these two places
AutomationIntegrationTest.groovy:430
AutomationIntegrationTest.groovy:556
this file is located at \bundles\automation\org.eclipse.smarthome.automation.integration.test\src\test\groovy\org\eclipse\smarthome\automation\integration\test\

One additional question: Which versions of java and maven are you using?

**Comment by maggu2810** [comment] 2015-12-09 13:13
Will test increasing the waiting time.

```text
Apache Maven 3.1.1 (0728685237757ffbf44136acec0402957f723d9a; 2013-09-17 17:22:22+0200)
Maven home: /usr/share/maven-bin-3.1
Java version: 1.8.0_66, vendor: Oracle Corporation
Java home: /opt/oracle-jdk-bin-1.8.0.66/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.3.0-gentoo", arch: "amd64", family: "unix"
```

**Comment by kaikreuzer** [comment] 2015-12-09 13:21
Maybe the test is a bit unstable. Hudson was able to build it here: https://hudson.eclipse.org/smarthome/job/SmartHomeDistribution-Nightly/676/
But on another build it failed with https://hudson.eclipse.org/smarthome/job/SmartHomeDistribution-Nightly/680/testReport/junit/org.eclipse.smarthome.automation.integration.test/AutomationIntegrationTest/test_chain_of_composite_Modules/. We will have to investigate, I also had failures locally.

**Comment by maggu2810** [comment] 2015-12-09 13:27
I increased the timeout to 30 seconds and it still fails (and wait the whole 30 seconds)...
See the time difference between line 355 and 356 here:
https://gist.github.com/maggu2810/1b0bcaa5494a9e2c1c63#file-gistfile1-txt-L356

**Comment by maggu2810** [comment] 2015-12-09 13:28
Is there a problem that rules are "unsatisfied"?

**Comment by marinmitev** [comment] 2015-12-09 13:35
it seems the root cause is on line 350 where rule condition evaluates the item state
https://gist.github.com/maggu2810/1b0bcaa5494a9e2c1c63#file-gistfile1-txt-L350
myMotionItem4 state is NULL when the rule condition received the event
and on the previous line there is a log:
Event: smarthome/items/myMotionItem4/state
so it seems to be a problem with the order of event delivery - the item state was not changed when the rule condition received the event...
Kai, what do you think?

**Comment by BenediktNiehues** [comment] 2015-12-09 14:34
The problem lies in the rule definition of the test which shows a synchronization issue in event handling. Here the eventTrigger first reacts on the items state change and starts the rule, but the autoupdate did not yet set the new state to the item which is checked in the second condition. This can be stabilized if the new value of the items state is directly taken from the event which is given as output by the trigger.
I can provide a fix for this specific test and create a PR.

**Closed** 2015-12-09 16:03 UTC
