### ISSUE TITLE
PaperUI rule engine

### ISSUE THREAD

**Issue by dk8pn** [eclipse/smarthome#6275] opened 2018-09-25 19:21 UTC
Hello,
run the experimental rules for a while now. Actually use openHAB2.4.0 build #1346 on Windows10.  This was the first build for me, where the rules have been running immediately after a restart of openHAB without any additional interaction. 

Before i had to either disable/enable all rules or to start each rule in order to make them working. With the next snapshot build i have been back to the old Problem. Now i hesitate to update any more because my #1346 seems to be the best.

Is there a possibility to fix this issue for all builds or to describe which build should work and which not?

Thanks & best regards,

Willi

**Comment by htreu** [comment] 2018-09-26 05:35
Thanks for the bug report @dk8pn. Please describe your problem in more detail: Give an example rule and a complete log output during startup, ideally with DEBUG log level on all `org.eclipse.smarthome.automation` packages.
You enable DEBUG logging by issuing `log:set DEBUG org.eclipse.smarthome.automation` in the openHAB2 OSGi console.

**Comment by htreu** [comment] 2018-10-17 11:01
@dk8pn please provide some feedback. It would also be nice if you could test again with the latest openHAB snapshot as we refactored some of the automation internals. Thanks.

**Comment by dk8pn** [comment] 2018-10-22 16:18
Hello Henning,

i have installed the latest snapshot #1392 yesterday. The issue is the same as it was before. Try now to specify the problem in more detail:

1. Rules have been setup using the PaperUI. 
2. After start of openHAB2.4.0 #1392, the enabled rules administrated within the file automation_rules.json appear as "Idle", but they are not really running.
3. Disabled rules administrated within an extra JSON rules file automation_rules_disabled.json appear also as "Idle".
4. In order to get the rules running, i need to "update" them by opening each rule and confirm it without any change.

Will look now if the log tells me someting. With snapshot #1346, this was not necessary and all rules are active immediately after a restart of the programme. The disabled rules have been grey'd out. Hope that this helps you in some way?

Best regards,

Willi

**Comment by htreu** [comment] 2018-11-06 19:54
Hi @dk8pn sorry for the very late reply.

> 2018-10-21 12:18:47.022 [ERROR] [me.storage.json.internal.JsonStorage] - Couldn't deserialize value 'org.eclipse.smarthome.storage.json.internal.StorageEntry@73cefc'. Root cause is: Unable to invoke no-args constructor for interface org.eclipse.smarthome.automation.Rule. Register an InstanceCreator with Gson for this type may fix this problem.

This looks a lot like you have some "older" rules which can not be loaded from storage anymore. We had an API breaking change a while ago which resulted in this issue, see https://github.com/eclipse/smarthome/issues/5884 for reference.

**Comment by htreu** [comment] 2018-11-06 19:55
I'm closing this as a duplicate of https://github.com/eclipse/smarthome/issues/5884.

**Closed by htreu** 2018-11-06 19:55 UTC
Labels: Automation, feedback
