### ISSUE TITLE
Build error: Eclipse SmartHome Automation Module Timer Tests

### ISSUE THREAD

**Issue by resetnow** [eclipse/smarthome#780] opened 2015-12-24 10:44 UTC
I'm trying to build the latest git version and it fails at timer tests:

```
vlad@host:/opt/esh$ MAVEN_OPTS="-Xms1024m -Xmx1024m -XX:PermSize=1024m -XX:MaxPermSize=1024m" mvn clean install
...
...
...
[INFO] 
[INFO] --- tycho-p2-plugin:0.23.1:p2-metadata-default (default-p2-metadata-default) @ org.eclipse.smarthome.automation.module.timer.test ---
[INFO] 
[INFO] --- tycho-surefire-plugin:0.23.1:test (default-test) @ org.eclipse.smarthome.automation.module.timer.test ---
[INFO] {osgi.ws=gtk, osgi.os=linux, osgi.arch=x86, org.eclipse.update.install.features=true}
[ERROR] Cannot resolve project dependencies:
[ERROR]   You requested to install 'bundle org.eclipse.smarthome.core.scheduler 0.0.0' but it could not be found
[ERROR] 
[ERROR] See http://wiki.eclipse.org/Tycho/Dependency_Resolution_Troubleshooting for help.
```
```
vlad@host:/opt/esh$ git status 
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean
```
```
vlad@host:/opt/esh$ git log -n1
commit 627d2d304e752647f2589867b179cf7cbe64775a
Merge: c9a33df 0b8c927
Author: Kai Kreuzer <kai@openhab.org>
Date:   Wed Dec 23 23:31:25 2015 +0100

    Merge pull request #777 from maggu2810/model-rule-deps
    
    fix service dependencies

```

**Comment by kaikreuzer** [comment] 2015-12-24 10:52
Could you try if it works if you remove this one dependency here: https://github.com/eclipse/smarthome/blob/master/bundles/automation/org.eclipse.smarthome.automation.module.timer.test/pom.xml#L28

**Comment by kaikreuzer** [comment] 2015-12-24 10:55
Hm, no, likely it won't help as this bundle is required by the tests. Does it turn up in the reactor summary? I have no clue, why this cannot be found...

**Comment by resetnow** [comment] 2015-12-24 11:05
This bundle does appear in the summary (with FAILED) status

**Comment by kaikreuzer** [comment] 2015-12-24 11:13
Ah, then the problem is that Maven tries to build it only after the test execution.
If you add a dependency from the pom.xml of the test bundle to the core.scheduler project, this should solve the problem.

**Comment by maggu2810** [comment] 2015-12-24 13:42
@resetnow Have you added the dependency? If this solves your problem and there is a missing one in the pom, could you create a PR?

**Comment by resetnow** [comment] 2015-12-24 13:44
@maggu2810 unfortunately, I can't test it right now so I closed the PR.

**Comment by kaikreuzer** [comment] 2015-12-24 23:56
Reopening as I think this is indeed a bug.

**Comment by kaikreuzer** [comment] 2015-12-25 00:31
Hm, the reactor order looks ok (scheduler comes before the automation bundles) and I also could not reproduce the problem locally by removing the scheduler from my Maven repo. So closing it again as not reproducible.

**Closed by kaikreuzer** 2015-12-25 00:31 UTC

**Comment by resetnow** [comment] 2015-12-25 13:13
Just for the record, here is a somewhat full log: http://pastebin.com/VhP2Yd4s I wonder what could the cause of the error, is it something related to my local Maven setup because the issue isn't reproducible by others?

**Comment by maggu2810** [comment] 2015-12-27 15:10
@resetnow Thank you for your updates.
Are you fine, if we leave this closed?
If the clean up of the .m2 folder solves the problem, I believe this is not something that could be solved from our side. What do you think about?

**Comment by resetnow** [comment] 2015-12-27 15:15
@maggu2810 Yes, I too think this was on my side. I'm not sure about the cause of the issue, maybe that's because I haven't updated my local OH/ESH clones for several months and then tried to build the updated version. Anyway, I don't have any problems with the build after cleaning Maven cache.

**Comment by teichsta** [comment] 2015-12-27 19:01
> If the clean up of the .m2 folder solves the problem

i can confirm cleaning the .m2 folder solves the problem …
