### ISSUE TITLE
Broken image in basic ui for number items without explicit icon

### ISSUE THREAD

**Issue by metbril** [eclipse/smarthome#2994] opened 2017-02-10 08:13 UTC
Any Number type item without an explicitly defined icon (in a text based .items file) will show a broken image in basic UI.

Until a final choice has been made what to do with these icons i will create a PR to create a number icon that is an alias for the text icon.

**Comment by kaikreuzer** [comment] 2017-02-10 08:18
Sounds like a duplicate of what https://github.com/eclipse/smarthome/pull/2799 wants to address.

**Comment by rtvb** [comment] 2017-02-10 08:41
Re https://github.com/eclipse/smarthome/issues/2994#issuecomment-278884070

Not exactly. This is just a quick fix to remove an annoying issue.

**Comment by rtvb** [comment] 2017-02-10 08:51
The Switch related issue #1614 also has some discussion about the use of the text (and number) icon.

**Comment by kaikreuzer** [comment] 2017-02-13 11:38
Ok, checking [the code](https://github.com/eclipse/smarthome/blob/bcf246de9082bbac43ae07a0b641d443feb307f2/bundles/ui/org.eclipse.smarthome.ui/src/main/java/org/eclipse/smarthome/ui/internal/items/ItemUIRegistryImpl.java#L116), the assumption is indeed that we have an icon available for every item type - so there should be one for number.

What default icon would make sense here? I do not really like reusing the "text" icon as @rtvb suggested in #2995. The Paper UI uses something like an "arrow" as a symbol for measurement values. Alternatively, I would also be fine to use "none" here.
Btw, does anyone knows what openHAB 1 showed in that case? I'm actually pretty sure that there were no broken icon links...?

**Comment by resetnow** [comment] 2017-02-15 10:19
I would vote for "none" since there could be aby meaning behind a number.

**Comment by kaikreuzer** [comment] 2017-03-13 18:16
@rtvb If you agree with @resetnow, could you update #2995 accordingly?

**Comment by rtvb** [comment] 2017-03-13 19:01
I agree

**Comment by lolodomo** [comment] 2017-04-30 18:59
The mentioned PR was finally closed and we still are missing an icon for Number items.

Just after googling, why not this one for example ? http://icons.iconarchive.com/icons/custom-icon-design/pretty-office-10/128/Numbers-icon.png

**Comment by lolodomo** [comment] 2017-07-08 12:54
@sjka @kaikreuzer : this issue can now be closed. The none icon is used in the mentioned case.

**Closed** 2017-07-09 04:42 UTC
