### ISSUE TITLE
Eclipse SmartHome Configuration Dispatcher Tests failing

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#4734] opened 2017-12-14 07:34 UTC
Tests are still failing when running `mvn clean install` on a Windows 10 PC:
```
[INFO] --- tycho-surefire-plugin:1.0.0:test (default-test) @ org.eclipse.smarthome.config.dispatch.test ---
[INFO] Expected eclipse log file: D:\dev\openhab2\git\smarthome\bundles\config\org.eclipse.smarthome.config.dispatch.test\target\work\data\.metadata\.log
[INFO] Command line:
        [C:\Program Files\Java\jdk1.8.0_131\jre\bin\java.exe, -Dosgi.noShutdown=false, -Dosgi.os=win32, -Dosgi.ws=win32, -Dosgi.arch=x86_64, -Dosgi.clean=true, -jar, C:\Users\Laurent\.m2\repository\p2\osgi\bundle\org.eclipse.equinox.launcher\1.4.0.v20161219-1356\org.eclipse.equinox.launcher-1.4.0.v20161219-1356.jar, -data, D:\dev\openhab2\git\smarthome\bundles\config\org.eclipse.smarthome.config.dispatch.test\target\work\data, -install, D:\dev\openhab2\git\smarthome\bundles\config\org.eclipse.smarthome.config.dispatch.test\target\work, -configuration, D:\dev\openhab2\git\smarthome\bundles\config\org.eclipse.smarthome.config.dispatch.test\target\work\configuration, -application, org.eclipse.tycho.surefire.osgibooter.headlesstest, -testproperties, D:\dev\openhab2\git\smarthome\bundles\config\org.eclipse.smarthome.config.dispatch.test\target\surefire.properties]
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.eclipse.smarthome.config.dispatch.test.ConfigDispatcherOSGiTest
Tests run: 27, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 29.316 sec <<< FAILURE! - in org.eclipse.smarthome.config.dispatch.test.ConfigDispatcherOSGiTest
allConfigurationFilesWithGlobalPIDsAreProcessedAndConfigurationIsUpdated(org.eclipse.smarthome.config.dispatch.test.ConfigDispatcherOSGiTest)  Time elapsed: 1.157 sec
whenExclusivePIDFileIsDeleted_DeleteTheConfiguration(org.eclipse.smarthome.config.dispatch.test.ConfigDispatcherOSGiTest)  Time elapsed: 0.578 sec
propertiesForTheSameGlobalPIDInDifferentFilesMustBeOverriddenInTheOrderTheyWereLastModified(org.eclipse.smarthome.config.dispatch.test.ConfigDispatcherOSGiTest)  Time elapsed: 0.797 sec
ifThereIsNoPropertyValuePairForGlobalPIDAConfigurationWithTheGivenPIDWillNotExist(org.eclipse.smarthome.config.dispatch.test.ConfigDispatcherOSGiTest)  Time elapsed: 0.5 sec
valueIsStillValidIfItIsLeftEmpty(org.eclipse.smarthome.config.dispatch.test.ConfigDispatcherOSGiTest)  Time elapsed: 0.594 sec
PropertyValuePairsForALocalPIDInDifferentFilesAreStillAssociatedWithThatPID(org.eclipse.smarthome.config.dispatch.test.ConfigDispatcherOSGiTest)  Time elapsed: 0.672 sec
allConfigurationFilesWithLocalPIDsAreProcessedAndConfigurationIsUpdated(org.eclipse.smarthome.config.dispatch.test.ConfigDispatcherOSGiTest)  Time elapsed: 0.812 sec
propertiesForLocalPIDCanBeOverridden(org.eclipse.smarthome.config.dispatch.test.ConfigDispatcherOSGiTest)  Time elapsed: 0.625 sec
whenExclusivePIDisDefinedInlineFromDifferentFile_skipTheLine(org.eclipse.smarthome.config.dispatch.test.ConfigDispatcherOSGiTest)  Time elapsed: 0.563 sec
IfNoPIDIsDefinedInConfigurationFileWithNo_dotNameTheDefaultNamespacePlusTheFileNameBecomesPID(org.eclipse.smarthome.config.dispatch.test.ConfigDispatcherOSGiTest)  Time elapsed: 0.594 sec
localPIDIsOverriddenByGlobalPIDInDifferentFileIfTheFileWithTheGlobalOneIsModifiedLast(org.eclipse.smarthome.config.dispatch.test.ConfigDispatcherOSGiTest)  Time elapsed: 0.547 sec
whenPropertyValuePairsForAGlobalPIDAreInDifferentFilesPropertiesWillNotBeMerged(org.eclipse.smarthome.config.dispatch.test.ConfigDispatcherOSGiTest)  Time elapsed: 0.609 sec
whenTheConfigurationFileNameContainsDotAndNoPIDIsDefinedTheFileNameBecomesPID(org.eclipse.smarthome.config.dispatch.test.ConfigDispatcherOSGiTest)  Time elapsed: 0.656 sec
whenLocalPIDIsDefinedForGlobalPIDFile_AbortParsing(org.eclipse.smarthome.config.dispatch.test.ConfigDispatcherOSGiTest)  Time elapsed: 0.516 sec
whenLocalPIDIsAnEmptyStringTheDefaultNamespacePlusDotIsTheOverallPID(org.eclipse.smarthome.config.dispatch.test.ConfigDispatcherOSGiTest)  Time elapsed: 0.609 sec
ifPropertyIsLeftEmptyAConfigurationWithTheGivenPIDWillNotExist(org.eclipse.smarthome.config.dispatch.test.ConfigDispatcherOSGiTest)  Time elapsed: 0.469 sec
whenLocalPIDDoesNotContainDotTheDefaultNamespacePlusThatPIDIsTheOverallPID(org.eclipse.smarthome.config.dispatch.test.ConfigDispatcherOSGiTest)  Time elapsed: 0.829 sec
whenExclusiveConfigFileIsDeleted_shouldRemoveConfigFromConfigAdmin(org.eclipse.smarthome.config.dispatch.test.ConfigDispatcherOSGiTest)  Time elapsed: 12.603 sec  <<< FAILURE!
java.lang.AssertionError: The configuration with properties for the given pid was found but should have been removed.
Expected: is null
     but: was <org.eclipse.equinox.internal.cm.ConfigurationDictionary@4b213651>
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.eclipse.smarthome.config.dispatch.test.ConfigDispatcherOSGiTest.lambda$1(ConfigDispatcherOSGiTest.java:599)

propertiesForTheSameLocalPIDInDifferentFilesMustBeOverriddenInTheOrderTheyWereLastModified(org.eclipse.smarthome.config.dispatch.test.ConfigDispatcherOSGiTest)  Time elapsed: 0.706 sec
ifThePropertyIsNotPrefixedWithLocalPIDTheLastPIDBecomesPIDForThatProperty(org.eclipse.smarthome.config.dispatch.test.ConfigDispatcherOSGiTest)  Time elapsed: 0.895 sec
ifThePropertyValuePairIsPrefixedWithLocalPIDInTheSameFileTheGlobalPIDIsIgnored(org.eclipse.smarthome.config.dispatch.test.ConfigDispatcherOSGiTest)  Time elapsed: 0.603 sec
commentLinesAreNotProcessed(org.eclipse.smarthome.config.dispatch.test.ConfigDispatcherOSGiTest)  Time elapsed: 0.475 sec
whenGlobalPIDIsEmptyStringItRemainsAnEmptyString(org.eclipse.smarthome.config.dispatch.test.ConfigDispatcherOSGiTest)  Time elapsed: 0.531 sec
propertiesForPIDInFilesInServicesDirectoryMustOverrideDefaultProperties(org.eclipse.smarthome.config.dispatch.test.ConfigDispatcherOSGiTest)  Time elapsed: 0.672 sec
globalPIDIsOverriddenByLocalPIDInDifferentFileIfTheFileWithTheLocalOneIsModifiedLast(org.eclipse.smarthome.config.dispatch.test.ConfigDispatcherOSGiTest)  Time elapsed: 0.578 sec
txtFilesAreNotProcessed(org.eclipse.smarthome.config.dispatch.test.ConfigDispatcherOSGiTest)  Time elapsed: 0.485 sec
whenExclusiveConfigIsTruncated_OverrideReducedConfig(org.eclipse.smarthome.config.dispatch.test.ConfigDispatcherOSGiTest)  Time elapsed: 0.625 sec

Results :

Failed tests:
  ConfigDispatcherOSGiTest.whenExclusiveConfigFileIsDeleted_shouldRemoveConfigFromConfigAdmin:593->JavaTest.waitForAssert:69->JavaTest.waitForAssert:116->JavaTest.waitForAssert:148->lambda$1:599 The configuration with properties for the given pid was found but should have been removed.
Expected: is null
     but: was <org.eclipse.equinox.internal.cm.ConfigurationDictionary@4b213651>

Tests run: 27, Failures: 1, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Eclipse SmartHome .................................. SUCCESS [  0.766 s]
[INFO] Eclipse SmartHome Bundles .......................... SUCCESS [  0.110 s]
[INFO] Eclipse SmartHome Test Components .................. SUCCESS [  0.046 s]
[INFO] Eclipse SmartHome Core Components .................. SUCCESS [  0.032 s]
[INFO] Eclipse SmartHome Core ............................. SUCCESS [ 36.222 s]
[INFO] Eclipse SmartHome Configurations ................... SUCCESS [  0.047 s]
[INFO] Eclipse SmartHome Configuration Core ............... SUCCESS [  8.860 s]
[INFO] Eclipse SmartHome Configuration XML ................ SUCCESS [  5.704 s]
[INFO] Eclipse SmartHome AutoUpdate Binding ............... SUCCESS [  4.063 s]
[INFO] Eclipse SmartHome Test ............................. SUCCESS [ 11.105 s]
[INFO] Eclipse SmartHome I/O Components ................... SUCCESS [  0.031 s]
[INFO] Eclipse SmartHome Console .......................... SUCCESS [  4.470 s]
[INFO] Eclipse SmartHome Thing ............................ SUCCESS [ 12.626 s]
[INFO] Magic Bundle ....................................... SUCCESS [  4.485 s]
[INFO] Magic Bundle Tests ................................. SUCCESS [  8.292 s]
[INFO] Eclipse SmartHome Auth Components .................. SUCCESS [  0.032 s]
[INFO] Eclipse SmartHome JAAS Authentication .............. SUCCESS [  3.688 s]
[INFO] Eclipse SmartHome Configuration Dispatcher ......... SUCCESS [  4.641 s]
[INFO] Eclipse SmartHome Configuration Dispatcher Tests ... FAILURE [ 33.468 s]
```

**Comment by triller-telekom** [comment] 2017-12-14 15:01
I guess this is a duplicate of #4370, which will hopefully be solved by PR #4685

**Closed** 2018-01-03 14:13 UTC
Labels: Test
