### ISSUE TITLE
Rule Engine NullPointerException

### ISSUE THREAD

**Issue by mackelito** [eclipse/smarthome#3212] opened 2017-04-07 12:46 UTC
The rule get´s triggered at the correct time but throws this error
2017-03-31 22:13:03.088 [ERROR] [.automation.core.internal.RuleEngine] - Fail to execute rule '[rule_2, null]': java.lang.NullPointerException

Running the rule manually by clicking the play icon works fine.

**Comment by kaikreuzer** [comment] 2017-04-07 13:34
Looks like a duplicate of https://github.com/eclipse/smarthome/issues/3029, right?
If so, I assume you are using an older version as the issue is already fixed on master.

**Closed** 2017-04-07 13:34 UTC
Labels: duplicate
