### ISSUE TITLE
Rules: global variables no more initialized

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#3577] opened 2017-06-03 15:31 UTC
In my rule file, I have at top few global variables:
```
import org.joda.time.*
import java.util.regex.Matcher
import java.util.regex.Pattern

var DateTime lastDesarmTime = now.minusDays(1)
var boolean initMinimoteCourt = true
var boolean initMinimoteLong = true
val Pattern patternVoice1 = Pattern::compile("(donner|passer en hors gel|passer en mode confort|passer en mode réduit) (le |la |les |l'|du )(.*) (du |de la |de l'|dans le |dans la |dans l')(.*)")
val Pattern pattern2 = Pattern::compile("x-sonosapi-stream:s(\\d+?)\\?.+")
val Pattern pattern3 = Pattern::compile("x-rincon:.+")
var String voice = "voicerss:frFR"
```
With new installed build 937, at startup, I have now these warnings:
```
2017-06-03 12:46:26.828 [WARN ] [me.internal.engine.RuleContextHelper] - Variable 'lastDesarmTime' on rule file 'maison.rules' cannot be initialized with value '<XFeatureCallImplCustom>.minusDays(<XNumberLiteralImpl>)': An error occurred during the script execution: The name '<XFeatureCallImplCustom>.minusDays(<XNumberLiteralImpl>)' cannot be resolved to an item or type.
2017-06-03 12:46:26.864 [WARN ] [me.internal.engine.RuleContextHelper] - Variable 'patternVoice1' on rule file 'maison.rules' cannot be initialized with value '<XFeatureCallImplCustom>::compile(<XStringLiteralImpl>)': An error occurred during the script execution: The name 'Pattern' cannot be resolved to an item or type.
2017-06-03 12:46:26.873 [WARN ] [me.internal.engine.RuleContextHelper] - Variable 'pattern2' on rule file 'maison.rules' cannot be initialized with value '<XFeatureCallImplCustom>::compile(<XStringLiteralImpl>)': An error occurred during the script execution: The name 'Pattern' cannot be resolved to an item or type.
2017-06-03 12:46:26.881 [WARN ] [me.internal.engine.RuleContextHelper] - Variable 'pattern3' on rule file 'maison.rules' cannot be initialized with value '<XFeatureCallImplCustom>::compile(<XStringLiteralImpl>)': An error occurred during the script execution: The name 'Pattern' cannot be resolved to an item or type.
```
It looks like all variable init that use a call to a function are failing.
Then my rules are failing because the variable pattern2 is null (for example).

What was changed ? Is there a new way to define global variables ?

PS: With the previous installed builds, it was always working as expected (my previous installed snapshot was 889).

**Comment by lolodomo** [comment] 2017-06-03 15:38
I just checked that if I force the reload of my rule file (using a touch command) while OH is running, then the variables seems to be correctly initialized (no warnings displayed and rules working as expected).

**Comment by kaikreuzer** [comment] 2017-06-03 19:55
The only recent change that could have an impact on startup behavior of rules is imho https://github.com/eclipse/smarthome/pull/3563. But as build 889 was quite old already, I am not sure if there might be other stuff that could cause this...

**Comment by lolodomo** [comment] 2017-06-03 20:01
I discovered I already had this problem 16 months ago when using beta 2.
https://community.openhab.org/t/oh2-variable-initialization-in-rules-file-fails-at-startup/7164
It has then disappeared.
I will try the advice I got on the forum.

**Comment by kaikreuzer** [comment] 2017-06-03 20:09
Indeed the very same. That leaves the question: Why do your rules still look the same?

**Comment by lolodomo** [comment] 2017-06-03 20:19
Because my rules are stable and I don't update them often.
And as the problem disappeared, I did nothing.
By the way, it looks like a real bug.

**Comment by lolodomo** [comment] 2017-07-08 12:11
It might be in link with issue #1896.

**Comment by ahielg** [comment] 2017-08-07 06:08
It happen to me on the stable build of 2.1:
2017-08-04 14:16:07.611 [WARN ] [me.internal.engine.RuleContextHelper] - Variable 'timers' on rule file 'lights_dynamic.rules' cannot be initialized with value 'newHashMap': An error occurred during the script execution: The name 'newHashMap' cannot be resolved to an item or type.

**Comment by kaikreuzer** [comment] 2017-09-08 15:46
Closing as duplicate of #1650.

**Closed by kaikreuzer** 2017-09-08 15:46 UTC
Labels: DSLRules

**Comment by lolodomo** [comment] 2017-09-22 18:33
I finally found a workaround to my very annoying problem. I moved all variable intializations that are requiring a call to a function like `Pattern::compile `to a new rule triggered when the system is started. I have now a new error when this rule is run:
```
2017-09-22 20:18:20.117 [ERROR] [ntime.internal.engine.RuleEngineImpl] - Error during the execution of startup rule 'Démarrage': Cannot resolve proxy: maison.rules#/1
```
but it seems to be without any consequence. I will open a new issue.
