### ISSUE TITLE
Paper UI: Thing Configuration page loads slowly

### ISSUE THREAD

**Issue by markusjw** [eclipse/smarthome#3191] opened 2017-03-29 12:58 UTC
For larger numbers of configuration parameters, the thing configuration page takes so much time to load that Firefox and Chrome show error messages. Sometimes waiting helps, but sometimes the browser does not manage to show the page at all.
Admittedly, I have things with up to 1000 parameters, but this also happens for smaller amounts like 50 parameters.

The page head loads correctly, so it is different to #2040.
Also, there are a no sliders, so I think that value ranges do not have an influence like in #1700.

**Comment by aounhaider1** [comment] 2017-03-30 14:41
Can you please provide the config description of your parameters?

**Comment by markusjw** [comment] 2017-03-30 15:12
I provided some via e-mail.

**Comment by htreu** [comment] 2017-09-06 05:19
@markusjw are you able to provide your config description somewhere online? maybe pastebin.com and link it here? We did some performance tuning on the control page and config parameters might also be worth a look. thanks.

**Comment by markusjw** [comment] 2017-09-06 14:25
Sure. I'm looking forward to the result.
This is the example that I also sent to aounhaider1: https://pastebin.com/QVbbrxM6

**Comment by triller-telekom** [comment] 2018-04-19 14:56
I think this issue is a duplicate of #4093.

@htreu can you please close this issue and mark it as a duplicate (although it is older than the other one)

**Comment by htreu** [comment] 2018-04-20 06:42
Closed in favour of https://github.com/eclipse/smarthome/issues/4093.

**Closed by htreu** 2018-04-20 06:42 UTC
