### ISSUE TITLE
Hue: Timeout of 5000ms exceeded while initializing hue thing

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#4666] opened 2017-12-02 08:32 UTC
Running OH snapshot 1104, I got this warning at startup:
```
09:13:18.949 [WARN ] [rnal.common.AbstractInvocationHandler] - Timeout of 5000ms exceeded while calling method 'ThingHandler.initialize()' on 'org.eclipse.smarthome.binding.hue.handler.HueLightHandler@8006c'. Thread 'safeCall-6' (135) is in state 'WAITING'
        at sun.misc.Unsafe.park(Native Method)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:870)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1199)
        at java.util.concurrent.locks.ReentrantLock$NonfairSync.lock(ReentrantLock.java:209)
        at java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:285)
        at org.eclipse.smarthome.core.thing.internal.ThingManager.thingUpdated(ThingManager.java:406)
        at org.eclipse.smarthome.core.thing.internal.ThingRegistryImpl.notifyTrackers(ThingRegistryImpl.java:222)
        at org.eclipse.smarthome.core.thing.internal.ThingRegistryImpl.notifyListenersAboutUpdatedElement(ThingRegistryImpl.java:145)
        at org.eclipse.smarthome.core.thing.internal.ThingRegistryImpl.notifyListenersAboutUpdatedElement(ThingRegistryImpl.java:1)
        at org.eclipse.smarthome.core.common.registry.AbstractRegistry.updated(AbstractRegistry.java:188)
        at org.eclipse.smarthome.core.thing.internal.ThingManager$1$1.run(ThingManager.java:237)
        at org.eclipse.smarthome.core.thing.internal.ThingManager$1$1.run(ThingManager.java:1)
        at java.security.AccessController.doPrivileged(Native Method)
        ...
09:13:18.954 [WARN ] [home.core.thing.internal.ThingManager] - Initializing handler for thing 'hue:0200:bridge1:console' takes more than 5000ms.
09:13:18.969 [INFO ] [smarthome.event.ThingUpdatedEvent    ] - Thing 'hue:0200:bridge1:console' has been updated.
09:13:19.005 [INFO ] [ome.event.ThingStatusInfoChangedEvent] - 'hue:0200:bridge1:console' changed from INITIALIZING to ONLINE
```

**Comment by lolodomo** [comment] 2017-12-02 09:59
After few restarts of the snapshot 1104, it only occurred one time.

**Comment by kaikreuzer** [comment] 2017-12-02 13:57
@sjka Shoudn't the AbstractInvocationHandler log message be better only debug as we already have a WARN from the ThingManager?

How is the `initialize`call related to a blocking `thingUpdated`? Not sure whether this is a bug in the hue handler or rather in the framework...

**Comment by kaikreuzer** [comment] 2017-12-07 10:51
We noticed that this actually isn't a new problem, but a duplicate of https://github.com/eclipse/smarthome/issues/4375 (merely the format of the logging has changed a bit).

**Closed by kaikreuzer** 2017-12-07 10:51 UTC

**Comment by lolodomo** [comment] 2017-12-07 15:27
Not a duplicate, I am not adding thing from the inbox.

**Comment by kaikreuzer** [comment] 2017-12-07 15:33
It happens when the handler is initialized, it's the same. #4688 will fix it.
