### ISSUE TITLE
Refresh command on item linkage / creation

### ISSUE THREAD

**Issue by maggu2810** [eclipse/smarthome#1658] opened 2016-06-13 09:13 UTC
I an item is created its state is null until an update is triggered.
For items that are linked to a channel I think it would be possible to send a refresh command to the channel.
A binding that receives the refresh command for a channel could (if it is possible) trigger a state update.

For channels that are updated very rarely we could avoid items with state null if it is possible for the binding to supply the current state.

**Comment by kaikreuzer** [comment] 2016-06-13 14:43
This looks like a duplicate of what I did in https://github.com/eclipse/smarthome/pull/212 and which has been rejected at that time and the `channelLinked()` method had been added instead. What we can do is to have a default implementation in BaseThingHandler sending a REFRESH command to the handler.

Or do you ask for something different?

**Comment by maggu2810** [comment] 2016-06-13 16:17
Sorry, I missed that function.

Use case and current behavior:
* a thing handler manages a thing for a real device it receives updates and can request the current state
* a thing handler receives some input from the real devices
* the thing handler calls `updateState(CHANNEL_ID, value)`
* the Paper UI is used to link a newly created item with the channel
* current behaviour: the state of the item is null
* the state of the item will be updated on the next `updateState(CHANNEL_ID, value)` call

I assume if I implement `channelLinked()` to call `updateState(CHANNEL_ID, value)` again (e.g. after request the current value from the device again) the correct state is assigned to the item.

The documentation already states (IIRC) that `handleCommand` should handle the refresh command.

I don't know if this needs to be done in the base implementation or in the bindings...

If a binding does cache the states of the real device (not of items -- that is forbidden) we can differ between
* REFRESH: try to contact the real device and refresh your cached state
* `channelLinked()`: call `updateState` using the cached state 

IIRC there has been some discussions about links without existing items.
Before I start reading a lot of code, perhaps you can give me some hints...
If a link exists for channel A to a non-existing item B and the item B is created (so, after the link), the `channelLinked()` does not called again. Correct? Or is it not possible that a link exists before the respective item anymore.

**Comment by maggu2810** [comment] 2016-06-15 11:55
@kaikreuzer ping :wink:

**Comment by kaikreuzer** [comment] 2016-06-15 12:24
> Or is it not possible that a link exists before the respective item anymore.

A link indeed only makes sense if the item already exists.
With the new ChannelItemProvider, this should always be the case, because it specifically provides bindings for all links for which there is no other dedicated item.

I cannot rule out though, that the channelLinked() is called before the item is REALLY available (und thus receives the state update) - but if this doesn't always work, I would consider it a bug that should be reported and fixed.

If the documentation does not yet mention the channelLinked() method, I think we should add this - because it is indeed important to react on it (as you correctly describe in your use case above). Having a default implementation in BaseThingHander might still be useful though.

**Closed** 2016-06-19 18:07 UTC
