### ISSUE TITLE
REST API always returning state NULL for Group Item

### ISSUE THREAD

**Issue by GrimmiMeloni** [eclipse/smarthome#3045] opened 2017-02-20 12:19 UTC
**Situation:** State of a Group Item of type Contact is requested via Rest API, e.g. `http://<SERVER>:8080/rest/items/<GroupItemName>/state`

**Problem:** state is always returned as NULL, no matter what the actual value (either CLOSED or OPEN) as reported in event log is.

**Expected Behavior:** actual state should be returned from REST API

**Details:**
The group Item 'GrpWohnzimmerFenster' is setup as follows:

> Group:Contact:AND(CLOSED,OPEN) GrpWohnzimmerFenster "Wohnzimmer Fenster"

Several window contacts have been added to the group via PaperUI. Eventlog entries emitted by a group member changing its state indicate that things work:

> 2017-02-19 19:41:06.719 [ItemStateChangedEvent     ] - Fenster1_1_State changed from OPEN to CLOSED
> 2017-02-19 19:41:06.720 [GroupItemStateChangedEvent] - GrpWohnzimmerFenster changed from OPEN to CLOSED through Fenster1_1_State
> 2017-02-19 19:41:06.722 [GroupItemStateChangedEvent] - GrpWohnzimmerFenster changed from OPEN to CLOSED through Fenster1_1_State
> 2017-02-19 19:41:06.723 [GroupItemStateChangedEvent] - GrpWohnzimmerFenster changed from OPEN to CLOSED through Fenster1_1_State

It seems however impossible to explicitly request the current state of the group via the REST API, as it always returns NULL. This is problematic for REST clients when pulling the initial state, in my case HabPanel reloading in a fresh browser window. The client side information will be inaccurate until the first change event fires.

Additional question: According to the above event log excerpt, a a single change of state of one of the group members causes three GroupItemStateChange events to be fired. Shouldn't this only be one as well?

**Comment by maggu2810** [comment] 2017-02-20 12:24
There is an "update" and a "changed" event.
A changed event should only be fired if the new state differs from the previous state.
I assume this is a little bit timing related and the state is changed from different places. But I don't know.
I would expect only one "changed" event.

**Comment by lolodomo** [comment] 2017-03-12 17:40
I just tried to reproduce using group "Windows" from the demo sitemap. This group is defined like that:
```
Group:Contact:OR(OPEN, CLOSED)  Windows     "Open windows [(%d)]"               <contact>
```
http://192.168.1.4:8080/rest/items/Windows/state returned OPEN as expected.

Then I updated the group item to be more similar to your example:
```
Group:Contact:AND(OPEN, CLOSED)  Windows     "Open windows"               <contact>
```
http://192.168.1.4:8080/rest/items/Windows/state returned CLOSED.

So I can't reproduce your case. Maybe, the item in your group are all NULL ?

**Comment by lolodomo** [comment] 2017-07-08 12:52
Maybe the reason was that some items put in this group were not Contact items ?

**Comment by triller-telekom** [comment] 2017-09-28 15:02
I cannot reproduce the issue either. I put 2 `Contact` items in my group and the group status behaves accordingly and is retrievable via rest interface.

@GrimmiMeloni Can you still reproduce the issue? If not please close this issue.

**Comment by sjka** [comment] 2017-09-29 10:55
...or rather: please reopen with a minimal example item definition for reproducing this problem.

**Closed by sjka** 2017-09-29 10:55 UTC
