### ISSUE TITLE
[Tradfri] Exception occurred while informing handler:Task 

### ISSUE THREAD

**Issue by cweitkamp** [eclipse/smarthome#3867] opened 2017-07-20 16:37 UTC
After several restarts or changes in related *.items files I get a lot of errors like this:
```
2017-07-20 18:24:13.137 [ERROR] [ome.core.thing.link.ThingLinkManager] - Exception occurred while informing handler:Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@1ef875f rejected from java.util.concurrent.ScheduledThreadPoolExecutor@47d5df[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 3]
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@1ef875f rejected from java.util.concurrent.ScheduledThreadPoolExecutor@47d5df[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 3]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2047)[:1.8.0_65]
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823)[:1.8.0_65]
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:326)[:1.8.0_65]
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:533)[:1.8.0_65]
	at java.util.concurrent.ScheduledThreadPoolExecutor.execute(ScheduledThreadPoolExecutor.java:622)[:1.8.0_65]
	at java.util.concurrent.Executors$DelegatedExecutorService.execute(Executors.java:668)[:1.8.0_65]
	at org.eclipse.californium.core.network.CoapEndpoint.runInProtocolStage(CoapEndpoint.java:692)[175:californium-osgi:1.0.5]
	at org.eclipse.californium.core.network.CoapEndpoint.sendRequest(CoapEndpoint.java:390)[175:californium-osgi:1.0.5]
	at org.eclipse.californium.core.CoapClient.send(CoapClient.java:897)[175:californium-osgi:1.0.5]
	at org.eclipse.californium.core.CoapClient.send(CoapClient.java:879)[175:californium-osgi:1.0.5]
	at org.eclipse.californium.core.CoapClient.asynchronous(CoapClient.java:742)[175:californium-osgi:1.0.5]
	at org.eclipse.californium.core.CoapClient.get(CoapClient.java:345)[175:californium-osgi:1.0.5]
	at org.eclipse.smarthome.binding.tradfri.internal.TradfriCoapClient.asyncGet(TradfriCoapClient.java:57)[190:org.eclipse.smarthome.binding.tradfri:0.9.0.b5]
	at org.eclipse.smarthome.binding.tradfri.handler.TradfriLightHandler.handleCommand(TradfriLightHandler.java:162)[190:org.eclipse.smarthome.binding.tradfri:0.9.0.b5]
	at org.eclipse.smarthome.core.thing.binding.BaseThingHandler.channelLinked(BaseThingHandler.java:207)[105:org.eclipse.smarthome.core.thing:0.9.0.b5]
	at org.eclipse.smarthome.core.thing.link.ThingLinkManager.informHandlerAboutLinkedChannel(ThingLinkManager.java:264)[105:org.eclipse.smarthome.core.thing:0.9.0.b5]
	at org.eclipse.smarthome.core.thing.link.ThingLinkManager.access$3(ThingLinkManager.java:255)[105:org.eclipse.smarthome.core.thing:0.9.0.b5]
	at org.eclipse.smarthome.core.thing.link.ThingLinkManager$1.added(ThingLinkManager.java:125)[105:org.eclipse.smarthome.core.thing:0.9.0.b5]
	at org.eclipse.smarthome.core.thing.link.ThingLinkManager$1.added(ThingLinkManager.java:1)[105:org.eclipse.smarthome.core.thing:0.9.0.b5]
	at org.eclipse.smarthome.core.common.registry.AbstractRegistry.notifyListeners(AbstractRegistry.java:217)[98:org.eclipse.smarthome.core:0.9.0.b5]
	at org.eclipse.smarthome.core.common.registry.AbstractRegistry.notifyListeners(AbstractRegistry.java:236)[98:org.eclipse.smarthome.core:0.9.0.b5]
	at org.eclipse.smarthome.core.common.registry.AbstractRegistry.notifyListenersAboutAddedElement(AbstractRegistry.java:240)[98:org.eclipse.smarthome.core:0.9.0.b5]
	at org.eclipse.smarthome.core.internal.items.ItemRegistryImpl.notifyListenersAboutAddedElement(ItemRegistryImpl.java:292)[98:org.eclipse.smarthome.core:0.9.0.b5]
	at org.eclipse.smarthome.core.internal.items.ItemRegistryImpl.notifyListenersAboutAddedElement(ItemRegistryImpl.java:1)[98:org.eclipse.smarthome.core:0.9.0.b5]
	at org.eclipse.smarthome.core.common.registry.AbstractRegistry.added(AbstractRegistry.java:126)[98:org.eclipse.smarthome.core:0.9.0.b5]
	at org.eclipse.smarthome.core.common.registry.AbstractProvider.notifyListeners(AbstractProvider.java:51)[98:org.eclipse.smarthome.core:0.9.0.b5]
	at org.eclipse.smarthome.core.common.registry.AbstractProvider.notifyListeners(AbstractProvider.java:70)[98:org.eclipse.smarthome.core:0.9.0.b5]
	at org.eclipse.smarthome.core.common.registry.AbstractProvider.notifyListenersAboutAddedElement(AbstractProvider.java:74)[98:org.eclipse.smarthome.core:0.9.0.b5]
	at org.eclipse.smarthome.model.item.internal.GenericItemProvider.modelChanged(GenericItemProvider.java:364)[123:org.eclipse.smarthome.model.item:0.9.0.b5]
	at org.eclipse.smarthome.model.core.internal.ModelRepositoryImpl.notifyListeners(ModelRepositoryImpl.java:286)[122:org.eclipse.smarthome.model.core:0.9.0.b5]
	at org.eclipse.smarthome.model.core.internal.ModelRepositoryImpl.addOrRefreshModel(ModelRepositoryImpl.java:136)[122:org.eclipse.smarthome.model.core:0.9.0.b5]
	at org.eclipse.smarthome.model.core.internal.folder.FolderObserver.checkFile(FolderObserver.java:234)[122:org.eclipse.smarthome.model.core:0.9.0.b5]
	at org.eclipse.smarthome.model.core.internal.folder.FolderObserver.processWatchEvent(FolderObserver.java:297)[122:org.eclipse.smarthome.model.core:0.9.0.b5]
	at org.eclipse.smarthome.core.service.WatchQueueReader.run(WatchQueueReader.java:206)[98:org.eclipse.smarthome.core:0.9.0.b5]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_65]
```

**Comment by robbyb67** [comment] 2017-08-16 13:20
Same on my site. 
Removing and re-adding the Bulb and gateway things in PaperUI fixed that temporarily.

**Comment by thelaoshi** [comment] 2017-08-29 06:58
I dont even need to change anything. It just starts to happen after several hours. This time it took around 1-2 days till it started. Only solution is to restart openhab.
Usually https://github.com/eclipse/smarthome/issues/3869 comes first, and then a few hours later this bug starts. Really annoying. Already thinking of giving back the Ikea smarthome stuff for now, because this way its just not usable :-(

**Comment by ivivanov-bg** [comment] 2017-09-25 19:16
This seems to me like a bug in the californium library. If it is still reproducible (with the latest changes from today) I could invest some time these day investigating it.

**Comment by cweitkamp** [comment] 2017-10-03 06:12
I updated my prod system to the latest ESH stable in the last days. I also added some new TRADFRI devices. I was not able to reproduce the reported error recently. I will observe my logs in the next time and give feedback again. Maybe this one is resolved with one of the several contributions.

**Comment by cweitkamp** [comment] 2017-10-05 15:13
Bad news. Exception occured again. I guess it somehow depends on how long the OH2 system is running without a restart.

```
2017-10-05 17:05:51.588 [ERROR] [ome.core.thing.link.ThingLinkManager] - Exception occurred while informing handler: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@9f0701 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@1ad6150[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 109]
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@9f0701 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@1ad6150[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 109]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2047) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:326) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:533) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor.execute(ScheduledThreadPoolExecutor.java:622) [?:?]
	at java.util.concurrent.Executors$DelegatedExecutorService.execute(Executors.java:668) [?:?]
	at org.eclipse.californium.core.network.CoapEndpoint.runInProtocolStage(CoapEndpoint.java:692) [219:californium-osgi:1.0.5]
	at org.eclipse.californium.core.network.CoapEndpoint.sendRequest(CoapEndpoint.java:390) [219:californium-osgi:1.0.5]
	at org.eclipse.californium.core.CoapClient.send(CoapClient.java:897) [219:californium-osgi:1.0.5]
	at org.eclipse.californium.core.CoapClient.send(CoapClient.java:879) [219:californium-osgi:1.0.5]
	at org.eclipse.californium.core.CoapClient.asynchronous(CoapClient.java:742) [219:californium-osgi:1.0.5]
	at org.eclipse.californium.core.CoapClient.get(CoapClient.java:345) [219:californium-osgi:1.0.5]
	at org.eclipse.smarthome.binding.tradfri.internal.TradfriCoapClient.asyncGet(TradfriCoapClient.java:94) [220:org.eclipse.smarthome.binding.tradfri:0.9.0.201710030942]
	at org.eclipse.smarthome.binding.tradfri.handler.TradfriLightHandler.handleCommand(TradfriLightHandler.java:215) [220:org.eclipse.smarthome.binding.tradfri:0.9.0.201710030942]
	at org.eclipse.smarthome.core.thing.binding.BaseThingHandler.channelLinked(BaseThingHandler.java:205) [106:org.eclipse.smarthome.core.thing:0.9.0.201709260841]
	at org.eclipse.smarthome.core.thing.link.ThingLinkManager.informHandlerAboutLinkedChannel(ThingLinkManager.java:281) [106:org.eclipse.smarthome.core.thing:0.9.0.201709260841]
	at org.eclipse.smarthome.core.thing.link.ThingLinkManager.access$3(ThingLinkManager.java:272) [106:org.eclipse.smarthome.core.thing:0.9.0.201709260841]
	at org.eclipse.smarthome.core.thing.link.ThingLinkManager$2.added(ThingLinkManager.java:185) [106:org.eclipse.smarthome.core.thing:0.9.0.201709260841]
	at org.eclipse.smarthome.core.thing.link.ThingLinkManager$2.added(ThingLinkManager.java:1) [106:org.eclipse.smarthome.core.thing:0.9.0.201709260841]
	at org.eclipse.smarthome.core.common.registry.AbstractRegistry.notifyListeners(AbstractRegistry.java:235) [99:org.eclipse.smarthome.core:0.9.0.201709260841]
	at org.eclipse.smarthome.core.common.registry.AbstractRegistry.notifyListeners(AbstractRegistry.java:254) [99:org.eclipse.smarthome.core:0.9.0.201709260841]
	at org.eclipse.smarthome.core.common.registry.AbstractRegistry.notifyListenersAboutAddedElement(AbstractRegistry.java:258) [99:org.eclipse.smarthome.core:0.9.0.201709260841]
	at org.eclipse.smarthome.core.thing.link.ItemChannelLinkRegistry.notifyListenersAboutAddedElement(ItemChannelLinkRegistry.java:166) [106:org.eclipse.smarthome.core.thing:0.9.0.201709260841]
	at org.eclipse.smarthome.core.thing.link.ItemChannelLinkRegistry.notifyListenersAboutAddedElement(ItemChannelLinkRegistry.java:1) [106:org.eclipse.smarthome.core.thing:0.9.0.201709260841]
	at org.eclipse.smarthome.core.common.registry.AbstractRegistry.added(AbstractRegistry.java:131) [99:org.eclipse.smarthome.core:0.9.0.201709260841]
	at org.eclipse.smarthome.core.common.registry.AbstractRegistry.added(AbstractRegistry.java:1) [99:org.eclipse.smarthome.core:0.9.0.201709260841]
	at org.eclipse.smarthome.core.common.registry.AbstractProvider.notifyListeners(AbstractProvider.java:51) [99:org.eclipse.smarthome.core:0.9.0.201709260841]
	at org.eclipse.smarthome.core.common.registry.AbstractProvider.notifyListeners(AbstractProvider.java:69) [99:org.eclipse.smarthome.core:0.9.0.201709260841]
	at org.eclipse.smarthome.core.common.registry.AbstractProvider.notifyListenersAboutAddedElement(AbstractProvider.java:73) [99:org.eclipse.smarthome.core:0.9.0.201709260841]
	at org.eclipse.smarthome.model.thing.internal.GenericItemChannelLinkProvider.createItemChannelLink(GenericItemChannelLinkProvider.java:97) [135:org.eclipse.smarthome.model.thing:0.9.0.201709260841]
	at org.eclipse.smarthome.model.thing.internal.GenericItemChannelLinkProvider.processBindingConfiguration(GenericItemChannelLinkProvider.java:67) [135:org.eclipse.smarthome.model.thing:0.9.0.201709260841]
	at org.eclipse.smarthome.model.item.internal.GenericItemProvider.internalDispatchBindings(GenericItemProvider.java:331) [125:org.eclipse.smarthome.model.item:0.9.0.201709260841]
	at org.eclipse.smarthome.model.item.internal.GenericItemProvider.internalDispatchBindings(GenericItemProvider.java:303) [125:org.eclipse.smarthome.model.item:0.9.0.201709260841]
	at org.eclipse.smarthome.model.item.internal.GenericItemProvider.processBindingConfigsFromModel(GenericItemProvider.java:188) [125:org.eclipse.smarthome.model.item:0.9.0.201709260841]
	at org.eclipse.smarthome.model.item.internal.GenericItemProvider.modelChanged(GenericItemProvider.java:366) [125:org.eclipse.smarthome.model.item:0.9.0.201709260841]
	at org.eclipse.smarthome.model.core.internal.ModelRepositoryImpl.notifyListeners(ModelRepositoryImpl.java:309) [124:org.eclipse.smarthome.model.core:0.9.0.201709260841]
	at org.eclipse.smarthome.model.core.internal.ModelRepositoryImpl.addOrRefreshModel(ModelRepositoryImpl.java:122) [124:org.eclipse.smarthome.model.core:0.9.0.201709260841]
	at org.eclipse.smarthome.model.core.internal.folder.FolderObserver.checkFile(FolderObserver.java:242) [124:org.eclipse.smarthome.model.core:0.9.0.201709260841]
	at org.eclipse.smarthome.model.core.internal.folder.FolderObserver.processWatchEvent(FolderObserver.java:306) [124:org.eclipse.smarthome.model.core:0.9.0.201709260841]
	at org.eclipse.smarthome.core.service.WatchQueueReader.run(WatchQueueReader.java:204) [99:org.eclipse.smarthome.core:0.9.0.201709260841]
	at java.lang.Thread.run(Thread.java:745) [?:?]
```

**Comment by sjka** [comment] 2017-10-09 08:12
I can confirm this has not been fixed yet - it just happened to me on the latest master.

**Comment by ivivanov-bg** [comment] 2017-10-09 09:02
Ok - from what I see in the `org.eclipse.californium.core.network.CoapEndpoint.runInProtocolStage`:

`private void runInProtocolStage(final Runnable task) {
	executor.execute(new Runnable() {
		public void run() {
			try {
				task.run();
			} catch (Throwable t) {
				LOGGER.log(Level.SEVERE, "Exception in protocol stage thread: "+t.getMessage(), t);
			}
		}
	});
}`

Is there any other exception in the log (probably not implementing `Throwable`) which has caused the executor to be shutdown ?
If not .... I'm out of ideas - the executor should been shutdown only when the `CoapEndpoint` is destroyed - so I don't see any other reason it to be terminated.

**Comment by ivivanov-bg** [comment] 2017-10-23 20:02
@kaikreuzer, @sjka - I have an idea how to fix this issue but the code change is in the Californium library.
Can you please advice how should I proceed (because I'm not sure if the version used is the latest one and also if the latest version would also have this issue)

**Comment by boaks** [comment] 2017-10-24 13:05
Maybe we can get first some clarification on the intended life-cycle of the `TradfriLightHandler`!

FMPOV:
The life-cycle of `TradfriLightHandler` starts with `initialize` and ends with `dispose`.
That state is reflected in `active`. But `active` is only checked in `onUpdate` and `setStatus`, but **NOT** in `handleCommand`.

So:
Is `handleCommand` called after `dispose`?
Is this intended to be done or is this a life-cycle violation and must be fixed in smarthome?

The remaining question would then be, what should happen, if a request is "on the fly" and `dispose` is executed. Should the response then be still be processed? Or is it OK, to drop it?

**Comment by kaikreuzer** [comment] 2017-10-24 19:18
> Is this intended to be done or is this a life-cycle violation and must be fixed in smarthome?

It should be considered a violation, so I am with you that the `active` flag should be checked in `handleCommand`.

> what should happen, if a request is "on the fly" and dispose is executed.

Imho it is ok to silently drop the response (but we should see no warn/error logging about it).

**Comment by kaikreuzer** [comment] 2017-10-24 19:25
@boaks But this issue at hand here does not seem to be related to the handler lifecycle - it seems to happen after hours/days of normal operation and the handlers are are in such a case never disposed (that only happens upon shutdown of the system). Would you have any other explanation on how it can happen that the client is shut down?

**Comment by boaks** [comment] 2017-10-25 11:11
See my comment in 

https://github.com/eclipse/californium/pull/452#issuecomment-339273784

Currently I'm trying to "build" the smarthome project, hope it works :-).
Is there any experience, how long smarthome is running until this exception occurs?
It seems not too easy to statically analyse, why the executor is shutdown.
(Especailly, because until now I wasn't able to build it and therefore couldn't use the 
eclipse IDE to navigate through the sources.) 
But maybe the proposed stacktrace would help to bring the light into that shutdown :-).

**Comment by boaks** [comment] 2017-10-25 19:43
Build the current master seems to fail on my Win 10 PC (after more than 1 hour) :-) .

> [INFO] --- frontend-maven-plugin:1.0:npm (npm install) @ org.eclipse.smarthome.ui.paper ---
> [INFO] Running 'npm install' in C:\projects\smarthome\extensions\ui\org.eclipse.smarthome.ui.paper
> [WARNING] npm WARN engine bootstrap@3.3.2: wanted: {"node":"~0.10.1"} (current: {"node":"5.4.0","npm":"3.3.12"})

I switched to ref-0.9.0.b5. Hope that buids.

**Comment by boaks** [comment] 2017-10-25 19:46
ref-0.9.0.b5, after 3 minutes:

> [ERROR] Failed to resolve target definition C:\projects\smarthome\targetplatform\smarthome.target: Could not find "element-connector/0.0.0" in the repositories of the current location

**Comment by kaikreuzer** [comment] 2017-10-25 20:14
0.9.0.b5 won't help you much as it didn't include Tradfri yet....

Actually, if you use our [Oompf setup](https://www.eclipse.org/smarthome/documentation/development/ide.html), you can launch the code directly from the IDE without the need to build anything through Maven.

If you have a few minutes tomorrow, we can also do a debug session together on my computer, where everything is up and running in the IDE.

**Comment by boaks** [comment] 2017-10-25 20:29
OK, I meet the "other" Kai at 10:00, so maybe afterwards?

As far as I checked it, if `CoapEndpoint.setExecutor()` is used (before starting the endpoint), the shutdown is not called. I really don't like to fix the symptoms, but If others depend on it, it would be a chance.

**Comment by boaks** [comment] 2017-10-25 20:59
> ERROR: org.eclipse.equinox.p2.metadata.repository code=1002 Unable to read repository at http://download.eclipse.org/releases/oxygen.
> ERROR: org.eclipse.equinox.p2.repository code=0 An error occurred while downloading http://download.eclipse.org/technology/epp/packages/oxygen/content.xml.xz. The cache file C:\Users\Achim\.p2\org.eclipse.equinox.p2.repository\cache\downloading\-1747184149 could not be renamed to C:\Users\Achim\.p2\org.eclipse.equinox.p2.repository\cache\-1747184149.
>   at org.eclipse.equinox.internal.p2.repository.CacheManager.updateCache(CacheManager.java:428)
>   at org.eclipse.equinox.internal.p2.repository.CacheManager.createCacheFromFile(CacheManager.java:132)
>   at org.eclipse.equinox.internal.p2.metadata.repository.XZedSimpleMetadataRepositoryFactory.getLocalFile(XZedSimpleMetadataRepositoryFactory.java:56)
>   at org.eclipse.equinox.internal.p2.metadata.repository.XZedSimpleMetadataRepositoryFactory.load(XZedSimpleMetadataRepositoryFactory.java:78)
>   at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.factoryLoad(MetadataRepositoryManager.java:57)
>   at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository(AbstractRepositoryManager.java:768)
>   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>   at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
>   at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
>   at java.lang.reflect.Method.invoke(Unknown Source)
>   at org.eclipse.oomph.util.ReflectUtil.invokeMethod(ReflectUtil.java:117)
>   at org.eclipse.oomph.p2.internal.core.CachingRepositoryManager.loadRepository(CachingRepositoryManager.java:409)
>   at org.eclipse.oomph.p2.internal.core.CachingRepositoryManager.loadRepository(CachingRepositoryManager.java:201)
>   at org.eclipse.oomph.p2.internal.core.CachingRepositoryManager$Metadata.loadRepository(CachingRepositoryManager.java:476)
>   at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:96)
>   at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:92)
>   at org.eclipse.equinox.internal.p2.metadata.repository.CompositeMetadataRepository.addChild(CompositeMetadataRepository.java:166)
>   at org.eclipse.equinox.internal.p2.metadata.repository.CompositeMetadataRepository.<init>(CompositeMetadataRepository.java:106)
>   at org.eclipse.equinox.internal.p2.metadata.repository.CompositeMetadataRepositoryFactory.load(CompositeMetadataRepositoryFactory.java:122)
>   at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.factoryLoad(MetadataRepositoryManager.java:57)
>   at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository(AbstractRepositoryManager.java:768)
>   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>   at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
>   at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
>   at java.lang.reflect.Method.invoke(Unknown Source)
>   at org.eclipse.oomph.util.ReflectUtil.invokeMethod(ReflectUtil.java:117)
>   at org.eclipse.oomph.p2.internal.core.CachingRepositoryManager.loadRepository(CachingRepositoryManager.java:409)
>   at org.eclipse.oomph.p2.internal.core.CachingRepositoryManager.loadRepository(CachingRepositoryManager.java:201)
>   at org.eclipse.oomph.p2.internal.core.CachingRepositoryManager$Metadata.loadRepository(CachingRepositoryManager.java:476)
>   at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:96)
>   at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:92)
>   at org.eclipse.oomph.p2.internal.core.ProfileTransactionImpl$RepositoryLoader$Worker.perform(ProfileTransactionImpl.java:1613)
>   at org.eclipse.oomph.util.WorkerPool$Worker.run(WorkerPool.java:428)
>   at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)

:-). sometimes ... maybe, it work on an other day ...

**Comment by boaks** [comment] 2017-10-27 16:43
Finally the maven build went well ... long time to wait after the

`[WARNING] npm WARN engine bootstrap@3.3.2: wanted: {"node":"~0.10.1"} (current: {"node":"5.4.0","npm":"3.3.12"})`

I hope I can spend the time in one of the next weeks, to analyse the cause of the executor shutdown.

**Comment by kaikreuzer** [comment] 2017-11-03 15:25
FTR, I have created https://github.com/eclipse/smarthome/pull/4489. Once this is merged, we should enable debug logging on that new class and we should hopefully find out, what destroys the endpoint although nobody is shutting anything down.

**Comment by triller-telekom** [comment] 2018-04-19 14:52
I am running this version of the tradfri binding: 0.10.0.201804091757

I haven't seen such an exception in my log files.

@cweitkamp: Did you see the exception recently again, or can we close this issue?

**Comment by cweitkamp** [comment] 2018-04-22 08:26
@triller-telekom No, I did not see the exception again. I am fine with closing this issue.

**Closed** 2018-04-23 08:29 UTC
Labels: Binding-Trådfri, bug
