### ISSUE TITLE
Config file loading order

### ISSUE THREAD

**Issue by sipvoip** [eclipse/smarthome#3771] opened 2017-06-29 18:13 UTC
Today on a faster box you get all sorts of errors at startup because rules load before all of the items files have loaded.

https://community.openhab.org/t/config-file-loading-order-any-way-to-make-items-load-first/30741/2

It would be nice if .items files would load first before .rules.

**Comment by staehler** [comment] 2017-06-30 17:02
+1

**Comment by sjka** [comment] 2017-06-30 17:53
As "all sorts of errors at startup" is not really specific wrt what the actual problem is, I took the freedom to grab what I deemed important from the referenced community thread:

```
2017-06-29 10:10:03.821 [ERROR] [ntime.internal.engine.ExecuteRuleJob] - Error during the execution of rule Ping Pool Sensors: An error occurred during the script execution: The name 'Pool_Temperature' cannot be resolved to an item or type.
2017-06-29 10:10:03.821 [ERROR] [ntime.internal.engine.ExecuteRuleJob] - Error during the execution of rule Update inside average temperature and humidity: An error occurred during the script execution: The name 'Avg_Temperature' cannot be resolved to an item or type.
2017-06-29 10:10:03.898 [ERROR] [ntime.internal.engine.ExecuteRuleJob] - Error during the execution of rule Water Quality: An error occurred during the script execution: The name 'Water_Quality_A' cannot be resolved to an item or type.
2017-06-29 10:10:03.899 [ERROR] [ntime.internal.engine.ExecuteRuleJob] - Error during the execution of rule Water Rate: An error occurred during the script execution: The name 'Water_Meter' cannot be resolved to an item or type.
2017-06-29 10:10:04.747 [ERROR] [ntime.internal.engine.ExecuteRuleJob] - Error during the execution of rule Ping Sensors: An error occurred during the script execution: The name 'Hydrogen_Peroxide_Sensor' cannot be resolved to an item or type.
2017-06-29 10:10:04.749 [ERROR] [ntime.internal.engine.ExecuteRuleJob] - Error during the execution of rule Check Generator and Increment Runtimes: An error occurred during the script execution: The name 'Generator_Status' cannot be resolved to an item or type.
```

As we can see, this is about rule _execution_ and has nothing to do with loading the files. The model parser is built in a way that it is tolerant wrt not-yet-known items. However, at the point when the rules are getting executed they must be there for obvious reasons. Therefore it would make sense to start the rule engine execution only after Items and Things have been loaded and the Things are all initialized (if possible at all). 

We already have #1896 which is about exactly this - although written quite technical, therefore I would not have expected you to identify it as being the root cause for your troubles. It is being worked on already, so I hope we will have some significant improvements in this area soon. I will close this as it duplicates #1896.

**Closed by sjka** 2017-06-30 17:53 UTC
