### ISSUE TITLE
Hue binding: XML thing types in error on tag representation-property 

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#3963] opened 2017-08-05 20:31 UTC
When I open one of the XML thing types of the hue binding, I see an error on the tag `representation-property`.
@afuechsel : was the DTD updated ?

**Comment by lolodomo** [comment] 2017-08-05 22:11
@kaikreuzer : that is probably more something for you. The updated file has probably not be copied on the WEB.

**Comment by kaikreuzer** [comment] 2017-08-06 19:43
You are right, I didn't yet find the time to upload the latest version to eclipse.org/smarthome.
And trying it now, the git server isn't responding... I'll try again tomorrow.

**Comment by lolodomo** [comment] 2017-08-07 18:54
Without that, it looks like you are not able to create any hue thing.

**Comment by kaikreuzer** [comment] 2017-08-08 09:37
You mean it has an impact on the runtime side, really? Imho the xsd should only be checked in the IDE.

**Comment by lolodomo** [comment] 2017-08-08 09:55
When I run the server from Eclipse and try to create a hue bridge thing from its discovery, it fails with the current code. I am forced to update the XML to suppress the new tag if I want to have something working.

I have not tested outside Eclipse.

**Comment by kaikreuzer** [comment] 2017-08-08 09:59
Do you have a log of that failure?

**Comment by lolodomo** [comment] 2017-08-08 10:01
I can provide it later if you want. The error si something relative to XML validation.

**Comment by afuechsel** [comment] 2017-08-08 10:37
This would be interesting. There should be no XML validation in the runtime.

**Comment by lolodomo** [comment] 2017-08-08 17:38
Here are the log at startup:
```
2017-08-08 19:36:20.582 [DEBUG] [c.x.o.XmlDocumentBundleTracker:329  ] - Reading the XML document '/ESH-INF/binding/binding.xml' in module 'org.eclipse.smarthome.binding.ntp'...
2017-08-08 19:36:20.629 [INFO ] [rthome.event.InboxUpdatedEvent:43   ] - Discovery Result with UID 'hue:bridge:0017881108fc' has been updated.
2017-08-08 19:36:20.645 [DEBUG] [s.c.d.internal.PersistentInbox:190  ] - Updated discovery result for 'hue:bridge:0017881108fc'.
2017-08-08 19:36:20.660 [DEBUG] [c.x.o.XmlDocumentBundleTracker:329  ] - Reading the XML document '/ESH-INF/thing/bridge.xml' in module 'org.eclipse.smarthome.binding.hue'...
2017-08-08 19:36:20.676 [WARN ] [c.x.o.XmlDocumentBundleTracker:335  ] - The XML document '/ESH-INF/thing/bridge.xml' in module 'org.eclipse.smarthome.binding.hue' could not be parsed: representation-property : representation-property
---- Debugging information ----
message             : representation-property
cause-exception     : com.thoughtworks.xstream.mapper.CannotResolveClassException
cause-message       : representation-property
class               : java.util.ArrayList
required-type       : java.util.ArrayList
converter-type      : com.thoughtworks.xstream.converters.collections.CollectionConverter
path                : /thing-descriptions/bridge-type/representation-property
line number         : 15
class[1]            : org.eclipse.smarthome.core.thing.xml.internal.BridgeTypeXmlResult
converter-type[1]   : org.eclipse.smarthome.core.thing.xml.internal.BridgeTypeConverter
class[2]            : org.eclipse.smarthome.core.thing.xml.internal.ThingDescriptionList
converter-type[2]   : org.eclipse.smarthome.core.thing.xml.internal.ThingDescriptionConverter
version             : 1.4.7
-------------------------------com.thoughtworks.xstream.converters.ConversionException: representation-property : representation-property
---- Debugging information ----
message             : representation-property
cause-exception     : com.thoughtworks.xstream.mapper.CannotResolveClassException
cause-message       : representation-property
class               : java.util.ArrayList
required-type       : java.util.ArrayList
converter-type      : com.thoughtworks.xstream.converters.collections.CollectionConverter
path                : /thing-descriptions/bridge-type/representation-property
line number         : 15
class[1]            : org.eclipse.smarthome.core.thing.xml.internal.BridgeTypeXmlResult
converter-type[1]   : org.eclipse.smarthome.core.thing.xml.internal.BridgeTypeConverter
class[2]            : org.eclipse.smarthome.core.thing.xml.internal.ThingDescriptionList
converter-type[2]   : org.eclipse.smarthome.core.thing.xml.internal.ThingDescriptionConverter
version             : 1.4.7
-------------------------------
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:79)
	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)
	at org.eclipse.smarthome.core.thing.xml.internal.AbstractDescriptionTypeConverter.unmarshal(AbstractDescriptionTypeConverter.java:185)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)
	at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.readItem(AbstractCollectionConverter.java:71)
	at com.thoughtworks.xstream.converters.collections.CollectionConverter.addCurrentElementToCollection(CollectionConverter.java:98)
Caused by: com.thoughtworks.xstream.mapper.CannotResolveClassException: representation-property
	at com.thoughtworks.xstream.mapper.DefaultMapper.realClass(DefaultMapper.java:79)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.DynamicProxyMapper.realClass(DynamicProxyMapper.java:55)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.PackageAliasingMapper.realClass(PackageAliasingMapper.java:88)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.ClassAliasingMapper.realClass(ClassAliasingMapper.java:79)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
```
and then  when I try to create the hue bridge from the discovered thing:
```
2017-08-08 19:28:59.210 [ERROR] [s.c.thing.binding.ThingFactory:111  ] - Thing factory (class org.eclipse.smarthome.binding.hue.internal.HueThingHandlerFactory) returned null on create thing when it reports to support the thing type (hue:bridge).
2017-08-08 19:28:59.210 [WARN ] [s.c.d.internal.PersistentInbox:157  ] - Cannot create thing. No binding found that supports creating a thing of type hue:bridge.
```
Now if I update the file bridge.xml to suppress the tag `representation-property` and then restart OHeverything is then OK and the thing is created successfully.

**Comment by afuechsel** [comment] 2017-08-08 18:01
Oh, I know, what happened. The XStream parser is implemented in a very strange way.... It iterates through the XML and waits for specific tags. Now a new tag has been introduced and the strange implementation does not know it. And throws the error.

**Comment by afuechsel** [comment] 2017-08-08 18:02
Don't see an easy way to backport this.

**Comment by lolodomo** [comment] 2017-08-08 18:05
I have not tested and I will not in my production environment ;) but does it mean that any user with recent snapshots cannot create any new hue thing ?

**Comment by afuechsel** [comment] 2017-08-08 18:08
Hmm, as it seems, yes. Thanks to the hand-crafted parsing. :(

**Comment by lolodomo** [comment] 2017-08-08 18:09
In this case, this is a major issue.

**Comment by afuechsel** [comment] 2017-08-08 18:10
For the current hue binding we need the current parser.

**Comment by afuechsel** [comment] 2017-08-08 18:15
Just to understand this issue correctly: You are using the new hew binding with an openHAB installation, that does not use the changed XML parser of ESH?

**Comment by afuechsel** [comment] 2017-08-08 18:19
Why is openHAB using snapshot-builds of the bindings? Why not just use the latest release of the Hue binding in OH? @kaikreuzer can you shed some light on this? We cannot change the behavior of the parser in OH and the way it is implemented we would NEVER be able to extend the XML in any way.

**Comment by lolodomo** [comment] 2017-08-08 18:22
In fact, I ran OH from inside Eclipse taking the hue binding from my local sources but everything else from p2 platform.

**Comment by afuechsel** [comment] 2017-08-08 18:27
So this is probably not the way it was intended. Please note, that we need to extend other thing-type xmls too for the introduction of the representation properties.

**Comment by kaikreuzer** [comment] 2017-08-09 07:12
This is indeed not the intended way. You need to make sure that your launch config uses bundles that already include the required code - so also take the ESH XML bundles from the workspace, not from the p2 target.

**Comment by lolodomo** [comment] 2017-08-09 07:27
The new code handling the representation property is mot yet in the p2 target ?

**Comment by kaikreuzer** [comment] 2017-08-09 07:41
No, check https://github.com/eclipse/smarthome/wiki/ESH-used-in-openHAB.

**Comment by lolodomo** [comment] 2017-08-09 08:51
Isn't PR #3899 that I see included in last ESH build ?

**Comment by lolodomo** [comment] 2017-08-10 08:30
@kaikreuzer : did you finally push the updated file to eclipse.org/smarthome ?

So finally, was it only a problem with my launch configuration or is there really a problem with the XStream parser like @afuechsel suggested ?

Let me know if I should close the issue.

**Comment by lolodomo** [comment] 2017-08-11 16:49
For information, the problem at runtime has disappeared. I suppose that p2 has been updated.
So just remains the problem with invalid XSD.

**Comment by sjka** [comment] 2017-08-14 09:18
FYI: I just updated https://www.eclipse.org/smarthome/schemas/... to reflect the latest XSDs from the sources. Hope that helps...?

**Comment by kaikreuzer** [comment] 2017-08-14 09:18
Thanks!

**Closed by kaikreuzer** 2017-08-14 09:18 UTC

**Comment by lolodomo** [comment] 2017-08-14 14:32
Thank you @sjka , it is ok now.
