### ISSUE TITLE
No error is logged when access is denied while trying to play sound

### ISSUE THREAD

**Issue by claus007** [eclipse/smarthome#3120] opened 2017-03-06 15:36 UTC
When trying to play a file in Linux with the standard user rights no sound is played.
Also there is no log entry and if you try to play it in the ssh console there is also no (error) message.
Just nothing.
OS: Linux Ubuntu 16.10
OpenHab installed via package manager

**Comment by maggu2810** [comment] 2017-03-07 15:23
I would expect that the `FileAudioStream` would throw an Exception.
Could you dig into the code and check if the exception
* is not raised
* is catch silently

**Comment by htreu** [comment] 2017-09-06 10:55
I did test this on macOS with `doorbell.wav` which plays nicely from the OSGi console when permissions are granted. Doing a `chmod -r doorbell.wav` and trying to play again results in the console log `File 'doorbell.wav' not found!`.
@claus007 is this still an issue for you? If so please provide some more information about the file and steps to reproduce.

**Comment by claus007** [comment] 2018-03-13 14:50
:-) Of course it is no more issue for me - as I solved the problem for me.
Nevertheless, I would doubt that the error is the same - I mean what I got was an error, AFTER the file was loaded and is to be played.
Your error occurs much earlier in the program. 
So I would ask you to reproduce the error accordingly.

**Comment by htreu** [comment] 2018-03-14 10:45
> So I would ask you to reproduce the error accordingly.

I would happily do this. Just let me know your exact setup and the steps to reproduce. In the description above you say that

> to play it in the ssh console there is also no (error) message

What does that mean? Are you connected to the openHAB host via ssh? How is the openHAB host supposed to output the sound? Are you able to play sounds with other applications on the host (like mplayer)?

**Comment by claus007** [comment] 2018-03-21 10:03
If you are working on a mac I have no idea, MAYBE you can try this with a virtual machine ?
Install the OS, OH2 ... without adding the OH to the audio group...
Pretty simple eh?!

**Comment by triller-telekom** [comment] 2018-03-21 15:40
I did the same test as @htreu in https://github.com/eclipse/smarthome/issues/3120#issuecomment-327448535 with my linux machine and a freshly installed openHAB 2.2.0 and I can confirm that I get the same error if the permission are wrong.

@kaikreuzer Can you please close this issue since the original reporter doesn't have his problem anymore?

**Closed** 2018-03-21 15:42 UTC
Labels: feedback
