### ISSUE TITLE
NPE in PersistentInbox

### ISSUE THREAD

**Issue by DaHoC** [eclipse/smarthome#5920] opened 2018-07-16 13:21 UTC
We encountered a Nullpointer-Exception in `PersistentInbox` which prevents `org.eclipse.smarthome.config.discovery.internal.AutomaticInboxProcessor` component activation as it is thrown in a method called by the activate method.

    [SCR] Exception while activating instance org.eclipse.smarthome.config.discovery.internal.AutomaticInboxProcessor@fc49e9 of component org.eclipse.smarthome.config.discovery.internal.AutomaticInboxProcessor
    [...]
    Caused by: java.lang.NullPointerException
    --
    at org.eclipse.smarthome.config.discovery.internal.PersistentInbox.stream(PersistentInbox.java:303)
    at org.eclipse.smarthome.config.discovery.internal.PersistentInbox.getAll(PersistentInbox.java:297)
    at org.eclipse.smarthome.config.discovery.internal.AutomaticInboxProcessor.autoApproveInboxEntries(AutomaticInboxProcessor.java:230)
    at org.eclipse.smarthome.config.discovery.internal.AutomaticInboxProcessor.activate(AutomaticInboxProcessor.java:249)
    ... 63 more

**Comment by htreu** [comment] 2018-07-18 12:02
Summary of the findings in #5921:

The `StorageService` is `dynamic, mandatory` in `PersistentInbox` so an instance should be present when the `Inbox` is injected into `AutomaticInboxProcessor`. Depending on the `StorageService` implementation the `getValues()` method is the next candidate to return a `null` reference.

**Comment by maggu2810** [comment] 2018-07-19 11:56
@DaHoC It would be great if you can comment the commit ID your ESH bundles are based on to match the stacktrace to the correct sources.

The `PersistentInbox` has not been changed the last two month, but in general it would be helpful.

```Java
    @Override
    @NonNullByDefault({})
    public Stream<DiscoveryResult> stream() {
        return this.discoveryResultStorage.getValues().stream().filter(Objects::nonNull);
}
```

The `return ...;` line is the one the NPE is raised.

As @htreu already comment above, I don't this that `discoveryResultStorage` is null (if the lifecycle is not violated) so perhaps `getValues()` return null.

Which storage provider is used?

**Comment by DaHoC** [comment] 2018-07-23 10:36
We encounter this issue already since around 15/Nov/17 all the time in a gateway which is permanently performing lifecycle-tests, so there is a chance that indeed a matching StorageService component is not available at that point in time when the `stream()` call is made, called indirectly by the `AutomaticInboxProcessor` activator method.
But it might also be the case that the StorageService is present, but its `.getValues()` returns `null` - Trying to gain access to that information, also to which storage provider is used.
The commit ID the ESH bundles are based upon should be 6d32c35f934b6b5a627cc4a32ff91564902bdc2a

**Comment by DaHoC** [comment] 2018-07-24 07:57
Unable to provide more useful information, because during normal operation all services and dependencies are satisfied.
It is some effect only occurring during bundle / service life-cycle changes, maybe due to the way the `volatile` `discoveryResultStorage` is initialized aside during injection of the `StorageService`.
I came up with a possible explanation:

This injection is done in a different thread than the thread calling the `activate()` method, so that it causes a synchronization issue/race condition when in the "injection" thread the `discoveryResultStorage` is just about to being assigned while the "activate" thread accesses the not yet written (thus null) value.

To avoid this possible error cause, it is generally best to avoid misuse of setters and getters for other stuff than setting and getting the variable in question - It could be done rather easily in this case, and would complement the existing PR to make the code more clean & robust

**Comment by kaikreuzer** [comment] 2018-07-24 09:54
Thanks for your analysis.

> It could be done rather easily in this case, and would complement the existing PR to make the code more clean & robust

I assume you are talking about `PersistentInbox.setStorageService` here? How could that be easily changed considering that it is a dynamic reference?

**Comment by DaHoC** [comment] 2018-07-24 10:37
Exactly, I meant providing an accessor for the `discoveryResultStorage` instead of initializing it in the wired setter of `setStorageService(final StorageService storageService)`, something like

    @NonNullByDefault({})
    private synchronized Storage<DiscoveryResult> getDiscoveryResultStorage() {
        if (storageService == null) {
            return null; // What to do in this case, should not happen
        }
        return storageService.getStorage(DiscoveryResult.class.getName(), this.getClass().getClassLoader());
    }

However, this requires the specific StorageService implementation to not create a new storage for each call of `storageService.getStorage(..)` (which is a getter, not a ctor, so by convention it should be fine)

**Comment by maggu2810** [comment] 2018-07-24 12:37
The activate method is not called before any mandatory references are set (regardless if it is dynamic or not).
The variable is volatile.

I don't get the race condition you try to explain above. Can you explain the potential race condition more detailed?

**Comment by DaHoC** [comment] 2018-07-24 13:13
As said, it's just an assumption / attempt to explain a scenario where the NPE happens in lack of a better explanation:
E.g. the compiler/JVM/OSGi logic does not recognize that the `setStorageService` is not only a setter, but also initializes the `discoveryResultStorage`.
Therefore the OSGi lifecycle magic could mistakenly assume that the `activate()` method and this setter method are unrelated when in fact, the activate method relies on this setter being wired beforehand.
That could cause this storageService reference, especially as it is dynamic, to be injected at a later point in time, or/and by a different thread.
I'm open for alternative suggestions on how the NPE could otherwise happen.

**Comment by maggu2810** [comment] 2018-07-24 13:35
@DaHoC Can you modify your `PersistentInbox` `stream` method to look like

```Java
    @Override
    @NonNullByDefault({})
    public Stream<DiscoveryResult> stream() {
        final Storage<DiscoveryResult> discoveryResultStorage = this.discoveryResultStorage;
        try {
            final Collection<@Nullable DiscoveryResult> values = discoveryResultStorage.getValues();
            final Stream<DiscoveryResult> stream = values.stream();
            final Stream<DiscoveryResult> filteredStream = stream.filter(Objects::nonNull);
            return filteredStream;
        } catch (final NullPointerException ex) {
            final ScheduledFuture<?> timeToLiveChecker = this.timeToLiveChecker;
            logger.warn(
                    "NPE while trying to get the discovery result from the persistent inbox (storage: {}, ttl checker cancelled: {}).",
                    this.discoveryResultStorage, timeToLiveChecker == null ? "null" : timeToLiveChecker.isCancelled(),
                    ex);
            throw ex;
        }
    }
```

and check the result?

**Comment by DaHoC** [comment] 2018-07-25 07:09
I'm afraid that is not easily to do in our current setup because as mentioned that's a lifecycle-test gateway where the bundles are updated between versions all the time (from a repository, so I would have to update this repo which affects other gateways as well).

Furthermore, that code could only show if the `discoveryResultStorage` or its `getValues()` (or timeToLiveChecker) is null, which in any way does not contribute that much information value.

I'm unwilling to invest any more time into this, as the PR with a bugfix is already present, independent of the error causes lying beneath.
The code change of the PR might even turn out to be beneficial for later error analysis if there is some deeper error which would then cause other issues so that we can further encircle it.

**Comment by kaikreuzer** [comment] 2018-07-30 13:04
As  #5921 is merged, I guess we can close this.

**Closed by kaikreuzer** 2018-07-30 13:04 UTC
Labels: bug

**Comment by maggu2810** [comment] 2018-08-01 07:13
@DaHoC Can you provide the additional logs to further investigate the root cause of the NPE?

**Comment by DaHoC** [comment] 2018-08-01 15:05
Neither this NPE nor one of the incorporated log messages currently shows up in the logs.

However, this specific gateway has many issues about being unable to enable components, presumably caused by a deadlock issue, which would also explain the cause of this NPE to some extent.

Some examples repeating all over in the logs:

> [SCR] Enabling components of bundle org.eclipse.smarthome.core did not complete in 30000 ms

> [SCR] Enabling components of bundle org.eclipse.smarthome.core.thing did not complete in 30000 ms

> Getting a lock required more than 10000 ms. There might be a synchronization problem in this callstack or just the build/dispose process of some components took too long! 

> [SCR - WorkThread] Timeout occurred! Thread was blocked on processing [QueuedJob]

> [SCR] ComponentReference.unbind(): component instance not bound! It is: [redacted]@a2316b 
	Details:
	Problematic reference = Reference[name = TranslationProvider, interface = org.eclipse.smarthome.core.i18n.TranslationProvider, policy = static, cardinality = 1..1, target = null, bind = setTranslationProvider, unbind = unsetTranslationProvider]
	of service component = org.eclipse.smarthome.core.binding.xml.internal.XmlBindingInfoProvider
	component implementation class = org.eclipse.smarthome.core.binding.xml.internal.XmlBindingInfoProvider
	located in bundle with symbolic name = org.eclipse.smarthome.core.binding.xml
	bundle location = org.eclipse.smarthome.core.binding.xml

I'm still investigating further into the issue
