### ISSUE TITLE
[Sonos] UPnP action invocation results in an empty result, which sets the Thing to OFFLINE

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#4531] opened 2017-11-11 18:15 UTC
UPnP is broken !
The following line is failing (returning an empty result):
https://github.com/eclipse/smarthome/blob/fee1c67521d3d2b84bdf8ec82552a50bfad6faf5/extensions/binding/org.eclipse.smarthome.binding.sonos/src/main/java/org/eclipse/smarthome/binding/sonos/internal/handler/ZonePlayerHandler.java#L837
The result with the Sonos binding is that the thing is set to OFFLINE.
I have 2 Sonos and strangely it happens only for one of my 2 Sonos.

It looks like a critical bug in the new library version we are relying on (jUPnP).

I switch back to snapshot 1065 immediately.
@kaikreuzer : I think you should announce in the forum to absolutely avoid the snapshot 1078 for all users using UPnP, until a fix is found.

**Comment by lolodomo** [comment] 2017-11-11 18:17
As a temporay fix, could we revert to previous version of the library ?

**Comment by lolodomo** [comment] 2017-11-11 18:33
After restoring snapshot 1065, I have no problem.
So the stuff relative with UPnP has been broken between 1065 and 1078.
There were 2 things changed:
* some packages moved
* version of the jUPnP library updated

**Comment by lolodomo** [comment] 2017-11-11 18:40
I am suspecting this PR as natural source of the problem: https://github.com/eclipse/smarthome/pull/4487

**Comment by lolodomo** [comment] 2017-11-11 18:54
I am very confident that the problem is not inside the Sonos binding itself because I am running in my production environment the snapshot 1065 with a special version of the Sonos binding compiled recently from the PR 4500 and that works perfectly. This PR was the last change in the binding.

**Comment by kaikreuzer** [comment] 2017-11-11 19:07
> UPnP is broken !

Well, I have the impression you are generalizing a bit too much here.

- UPnP seems to work fine for discovery, there are no issues with Hue, Sonos, WeMo, etc.
- Sonos PLAY:1 works smoothly with UPnP actions and events, I do not see any issues with it.
- WeMo works smoothly with UPnP actions.

So what is left is that a specific action call that is done in the Sonos binding works differently than before. Let's spend the time and thoroughly analyse, why this happens and where the root issue actually is. In case it is in jUPnP, the issue should rather be reported at https://github.com/jupnp/jupnp.

**Comment by kaikreuzer** [comment] 2017-11-11 19:08
> I have 2 Sonos and strangely it happens only for one of my 2 Sonos.

Can you provide information about the model and firmware versions of those?

**Comment by lolodomo** [comment] 2017-11-11 19:23
My 2 Sonos are uptodate with firmware. This is not a problem with models and/or firmware as everything is working in snapshot 1065. Apparently the UPnP actions are failing. As the HTTP layer was changed in the jUPnP library (you confirml ?), maybe this is a problem with timeout of HTTP requests ?

**Comment by lolodomo** [comment] 2017-11-11 19:26
And of course I am not alone to notice the problem: https://community.openhab.org/t/sonos-things-are-offline/36030/15
dan12345 noticed the same issue after upgrading to snapshot 1078.

**Comment by lolodomo** [comment] 2017-11-11 19:30
Considering the message displayed in Paper UI, I can confirm that the problem is not the UPnP discovery but the run of the UPnP action requesting the device properties that returns nothing that is interpreted by the binding as a Sonos device not available on the network.

**Comment by lolodomo** [comment] 2017-11-11 19:33
But to answer to your question, it was failing for my PLAY:5 and working for my CONEECT:AMP.

**Comment by kaikreuzer** [comment] 2017-11-11 19:41
Can you come up with a step by step description on how to reproduce the problem? Or is it already enough to approve a PLAY:5 in the inbox and then it goes OFFLINE immediately?

> requesting the device properties that returns nothing that is interpreted by the binding as a Sonos device not available

Maybe this interpretation is a bit too strict as well and should be changed? Setting it offline should imho only happen in case of request timeouts (or does a null return value automatically mean that it ran into a timeout?)

**Comment by lolodomo** [comment] 2017-11-11 20:01
I just started one time on my RPI2 the new distribution with my Sonos things declared in a file. As usual.
The binding is checking the access to the Sonos device every minute by running an UPnP action that requests device properties. This is what is no more working, at least sometimes.

I did not notice this problem last weekend when developing on my fast PC.

What is the timeout with the new UPnP code ?

**Comment by lolodomo** [comment] 2017-11-11 21:08
Last weekend, we were still with the previous library so it is normal that I noticed nothing wrong.

**Comment by lolodomo** [comment] 2017-11-12 09:00
In Eclipse, it is working with last code `but I am still using jUPnP library version 2.2`.
When and how is updated the library version ? Everything is uptodate in my dev env except openhab-distro. Is it what triggers the update of library ?

**Comment by lolodomo** [comment] 2017-11-12 09:22
After upgrading openhab-distro, jUPnP version 2.3 appeared in Eclipse and of course now the Sonos binding is no not working. I hope that it is enough to convince anyone that the problem is due to the update of this library.
I have even the strange feeling that running this library could have a strange impact on the local network because just after starting OH I saw that my Sonos application on my Android tablet lose my Sonos ! Is it just a coincidence ?
In Eclipse, it is failing for all of my Sonos.
As I can reproduce it, I will investigate more in details where it fails.

**Comment by lolodomo** [comment] 2017-11-12 09:23
The bad news is I can no more develop the Sonos binding until this problem is fixed.

**Comment by lolodomo** [comment] 2017-11-12 09:41
Ok, I can see that the problem is at this line:
https://github.com/eclipse/smarthome/blob/master/bundles/io/org.eclipse.smarthome.io.transport.upnp/src/main/java/org/eclipse/smarthome/io/transport/upnp/UpnpIOServiceImpl.java#L289
It is returning null and I get the following log:
```
2017-11-12 10:38:04.092 [DEBUG] [e.s.i.t.upnp.UpnpIOServiceImpl:341  ] - Could not find action 'GetZoneInfo' for participant 'RINCON_xxxxxxxx'
```
Just to avoid the question, of course this action still exist and Sonos did not suppress this action. It is available in my production environment.

So the method `getAction` in the new version of the library seems to not work well.

**Comment by lolodomo** [comment] 2017-11-12 09:51
Sometimes it fails earlier in the method when searching the service:
```
2017-11-12 10:49:34.955 [DEBUG] [e.s.i.t.upnp.UpnpIOServiceImpl:345  ] - Could not find service 'DeviceProperties' for participant 'RINCON_xxxxxxx'
```

**Comment by lolodomo** [comment] 2017-11-12 10:02
My feeling is a general and random problem in the new library.

I can confirm that the service `urn:upnp-org:serviceId:DeviceProperties` is still listed when I run http://192.168.xx.xxx:1400/xml/device_description.xml.

**Comment by lolodomo** [comment] 2017-11-12 10:16
The time to get the XML device description in a WEB browser is very fast.

**Comment by lolodomo** [comment] 2017-11-12 10:21
I am not very optimist with a fast fix in jUPnP. @kaikreuzer : can we move back to version 2.2 in ESH ?

If not, is there a workaround for advanced users to replace the library version after deploying the distribution ?

**Comment by Dan1001** [comment] 2017-11-12 10:22
Probably a stupid question, but which version is 1065, so I can apt-get it?

**Comment by lolodomo** [comment] 2017-11-12 10:26
Snapshot 1065 that you can get from Cloudbees.

**Comment by lolodomo** [comment] 2017-11-12 10:30
I see the file `runtime/system/org/jupnp/org.jupnp/2.3.0/org.jupnp-2.3.0.jar` in the new 1078 distribution deployed. Could it work if I replace this file by the file `runtime/system/org/jupnp/org.jupnp/2.2.0/org.jupnp-2.2.0.jar` from my previous installation of the snapshot 1065 ?

**Comment by Dan1001** [comment] 2017-11-12 10:35
Now I'm certain it's a stupid question... but apt-get showpkg openhab2 only lists the last few versions, back to 30 October. How do I see/install earlier ones?

**Comment by Dan1001** [comment] 2017-11-12 10:54
Thanks. Unfortunately I now seem in a mess - having downgraded to 1075, all my bindings refuse to work:

` [ERROR] [core.karaf.internal.FeatureInstaller] - Failed installing 'openhab-persistence-mapdb, openhab-binding-airquality, openhab-misc-restdocs, openhab-binding-network, openhab-binding-denon1, openhab-ui-habpanel, openhab-binding-powermax1, openhab-binding-zoneminder, openhab-binding-harmonyhub, openhab-binding-chromecast, openhab-transformation-map, openhab-ui-classic, openhab-ui-habmin, openhab-ui-paper, openhab-action-twitter, openhab-binding-samsungtv, openhab-voice-voicerss, openhab-binding-weather1, openhab-binding-sonos, openhab-persistence-rrd4j, openhab-ui-basic, openhab-action-mail, openhab-misc-homekit, openhab-binding-gardena, openhab-binding-expire1, openhab-binding-WOL': Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=openhab-binding-sonos; type=karaf.feature; version="[2.2.0.SNAPSHOT,2.2.0.SNAPSHOT]"; filter:="(&(osgi.identity=openhab-binding-sonos)(type=karaf.feature)(version>=2.2.0.SNAPSHOT)(version<=2.2.0.SNAPSHOT))" [caused by: Unable to resolve openhab-binding-sonos/2.2.0.SNAPSHOT: missing requirement [openhab-binding-sonos/2.2.0.SNAPSHOT] osgi.identity; osgi.identity=esh-binding-sonos; type=karaf.feature [caused by: Unable to resolve esh-binding-sonos/0.9.0.SNAPSHOT: missing requirement [esh-binding-sonos/0.9.0.SNAPSHOT] osgi.identity; osgi.identity=org.eclipse.smarthome.binding.sonos; type=osgi.bundle; version="[0.9.0.201711101643,0.9.0.201711101643]"; resolution:=mandatory [caused by: Unable to resolve org.eclipse.smarthome.binding.sonos/0.9.0.201711101643: missing requirement [org.eclipse.smarthome.binding.sonos/0.9.0.201711101643] osgi.wiring.package; filter:="(osgi.wiring.package=org.eclipse.smarthome.config.discovery.upnp)"]]]
`

**Comment by lolodomo** [comment] 2017-11-12 10:57
Maybe try the snapshot 1073 which was built the 4th of November.
I am only certain that snapshot 1065 is working because I am running it.

**Comment by lolodomo** [comment] 2017-11-12 16:48
My try to overwrite the jupnp jar in the deployed 1078 distribution by an older version is apparently not working.

I am definitively back to snapshot 1065 until a solution is found with this broken library.

**Comment by kaikreuzer** [comment] 2017-11-13 07:44
Guys, please don't clutter this issues about openHAB distro updates/downgrades.

As mentioned [above](https://github.com/eclipse/smarthome/issues/4531#issuecomment-343686998), the only thing that will help us is to debug the issue to see what is the underlying cause. As mentioned, I do not have any other Sonos device than a PLAY:1 at hand and this does not show ANY issues.

```
2017-11-12 10:38:04.092 [DEBUG] [e.s.i.t.upnp.UpnpIOServiceImpl:341  ] - Could not find action 'GetZoneInfo' for participant 'RINCON_xxxxxxxx'
2017-11-12 10:49:34.955 [DEBUG] [e.s.i.t.upnp.UpnpIOServiceImpl:345  ] - Could not find service 'DeviceProperties' for participant 'RINCON_xxxxxxx'
```
@lolodomo These log messages look weird. Please check the source code yourself and you will see that nothing like that is logged in lines 341 and 345. Do you have any explanation for that? Can you confirm that you are definitely using the correct binaries?

**Comment by lolodomo** [comment] 2017-11-13 07:53
Yes I am using the 1078 distribution installed from scratch.
Concerning logs and my tests in Eclipse, the line numbers are different just because I added few additional logs to help me find where was the problem in io.transport.upnp.

**Comment by ViToni** [comment] 2017-11-13 08:11
@lolodomo Could you please open an issue at https://github.com/jupnp/jupnp and attach the `device_description.xml` for a working and non-wokring device. It would be great if you could attach the HTTP headers for both devices, too.

**Comment by lolodomo** [comment] 2017-11-13 08:20
In fact, using Eclipse to test in a dev env, it was failing for my 2 Sonos. As I tried to explain, after each restart, the library was not failing always in the same call.
We have a not fully predictable issue in the library.

I will provide my XML descriptions this evening.

**Comment by michaeljoos72** [comment] 2017-11-13 08:25
Hi all

I did not have time to debug yesterday. But my setup with 5pcs PLAY:1 have the same issue.

BR
Michael

**Comment by lolodomo** [comment] 2017-11-13 08:28
Regarding the declaration of issue in the right place, I take the time to open it rhis weekend but Kai already closed it this morning !

**Comment by lolodomo** [comment] 2017-11-13 08:36
Forum discussion: https://community.openhab.org/t/sonos-things-are-offline/36030

**Comment by kaikreuzer** [comment] 2017-11-13 09:36
> Kai already closed it this morning !

Because it didn't have any content and didn't even prove that there is an issue.
As I said, let's try to stay calm and analyse the issue.
It is confirmed that there is some issue with Sonos support, so we have this issue here and it is labelled as "bug".
We also have a few people that can reproduce it, so those need to get into their debugger and see what exactly is happening. Once we know this, we can decide on further measures.

**Comment by lolodomo** [comment] 2017-11-13 11:13
And ee know that the bug with Sonos appeared with the new library version as everthing is still ok with an older distribution (1065 in my case).

**Comment by garytse** [comment] 2017-11-13 11:19
Hi,

It appears that Sonos is having problem with firmware 8.1  
Here is a link to their discussion:
https://de.community.sonos.com/installation-und-nutzung-223378/sonos-update-8-1-1-vom-02-11-2017-bitte-um-info-zu-den-inhalten-6740652

The latest is 8.1.1; @lolodomo  would you mind re-testing it with 8.1.1 and let us know?  I cannot reproduce the problem with any of PLAY:1, PLAY:3, PLAY:5  (all with firmware 8.1.1 though).

Best regards,
Gary

**Comment by Dan1001** [comment] 2017-11-13 11:54
I too cured the problem by rolling-back my OH installation to a pre-November snapshot.

**Comment by michaeljoos72** [comment] 2017-11-13 12:00
I updated all my Sonos yesterday to 8.1.1. This did not resolve the issue. Will try to debug today evening.

**Comment by lolodomo** [comment] 2017-11-13 12:37
Yesterday, no newer firmware was available so I am probably using 8.1.1 but I will check this evening.

Additionally I can confirm that the library bug is not dependent on hardware and OS as I can reproduce it on RPI+Linux and Intel+Win10.

**Comment by lolodomo** [comment] 2017-11-13 19:13
My firmware is 8.1.1 too. This firmware works without problem with the snapshot 1065.

**Comment by lolodomo** [comment] 2017-11-14 08:06
As I have already identified the calls in ESH to the library that are failing and identified that it is not always failing in the same call (check my logs above), what could be the next step ? I suppose that it has to be considered and analyzed by a developer who knows this library code ?

**Comment by garytse** [comment] 2017-11-14 09:29
Hi @lolodomo,

Developers need to correlate with the problem you are reporting with the code.  In the log, you have: 
[e.s.i.t.upnp.UpnpIOServiceImpl:341  ] - Could not find action 'GetZoneInfo' for participant 'RINCON_xxxxxxxx'
[e.s.i.t.upnp.UpnpIOServiceImpl:345  ] - Could not find service 'DeviceProperties' for participant 'RINCON_xxxxxxx'

If you open below link, you will find that lines 341 and 345 are not printing out those 2 debugs.  That means the binary is from another version.

https://github.com/eclipse/smarthome/blob/master/bundles/io/org.eclipse.smarthome.io.transport.upnp/src/main/java/org/eclipse/smarthome/io/transport/upnp/UpnpIOServiceImpl.java#L345

**Comment by lolodomo** [comment] 2017-11-14 11:12
I already mentioned that the line numbers are wrong because I added few logs when testing in Eclipse.
I can easily provide the right line numbers.
By the way, anyone enabling the right debug logs can get these errors in a production environment too.

**Comment by lolodomo** [comment] 2017-11-14 18:14
Correct line numbers in source from master branch triggering the errors are 335 and 338.
https://github.com/eclipse/smarthome/blob/master/bundles/io/org.eclipse.smarthome.io.transport.upnp/src/main/java/org/eclipse/smarthome/io/transport/upnp/UpnpIOServiceImpl.java#L335

**Comment by lolodomo** [comment] 2017-11-14 19:58
Here is my device description: [play3.txt](https://github.com/eclipse/smarthome/files/1472348/play3.txt)
and the headers:
```
HTTP/1.1 200 OK
Content-Type: text/xml
Transfer-Encoding: chunked
Server: Linux UPnP/1.0 Sonos/39.2-47040 (ZPS5)
Connection: close
```

**Comment by lolodomo** [comment] 2017-11-14 20:00
@ViToni : I provided the Sonos device description in my previous message and identified which library calls are faling. Let me know if you need something else.

**Comment by lolodomo** [comment] 2017-11-14 20:01
There was just a new firmware relative to Pandora this evening so my firmware is now 8.2.

**Comment by kaikreuzer** [comment] 2017-11-16 09:41
I now got hold of a PLAY:3 and the good news is that I can reproduce the issues now in my network (having a PLAY:1 and PLAY:3 at the same time). I have it even when running from my ESH IDE, so I have a good situation for debugging and not having to guess.

Despite from the fact that all worked with the existing Sonos code before, I see that there are nonetheless bugs as even if the Sonos speakers are discovered through UPnP, the Things stay OFFLINE, so there is definitely some event handling missing. I'll look into the issue in depth today - some first cleanup is done with https://github.com/eclipse/smarthome/pull/4566 already.

**Comment by lolodomo** [comment] 2017-11-16 12:16
Excellent, thank you

**Comment by kaikreuzer** [comment] 2017-11-16 15:15
I did some extensive debugging. There wasn't really anything wrong in the Sonos binding, nor the ESH UPnPIOService, nor the JUPnP library, but the culprit was the Jetty HTTP client, which randomly killed the parsing of HTTP responses by closing the connection. I couldn't exactly figure out what caused this behavior. The result of it was the the hydration of devices with didn't fully succeed as a few services were often missing due to the failed http processing.

I wasn't able to identify a single commit in the Jetty project, but according to my tests, the very next patch release 9.3.15 does not show this behavior anymore. So my clear advice in order to solve this issue is to upgrade the Jetty client from 9.3.14 to 9.3.15. I have done so with #4569.

@lolodomo Could you be so kind and check this PR whether it solves the issue for you?

**Comment by lolodomo** [comment] 2017-11-17 07:32
I tried to run your branch but I got an exception at startup:
```
!ENTRY org.eclipse.smarthome.model.core 4 0 2017-11-17 08:30:15.833
!MESSAGE [org.eclipse.smarthome.folder(243)] The activate method has thrown an exception
!STACK 0
java.lang.NoSuchMethodError: org.eclipse.smarthome.binding.sonos.internal.SonosHandlerFactory.getBundleContext()Lorg/osgi/framework/BundleContext;
	at org.eclipse.smarthome.binding.sonos.internal.SonosHandlerFactory.createHandler(SonosHandlerFactory.java:103)
	at org.eclipse.smarthome.core.thing.binding.BaseThingHandlerFactory.registerHandler(BaseThingHandlerFactory.java:97)
	at org.eclipse.smarthome.core.thing.internal.ThingManager.doRegisterHandler(ThingManager.java:505)
	at org.eclipse.smarthome.core.thing.internal.ThingManager.registerHandler(ThingManager.java:482)
	at org.eclipse.smarthome.core.thing.internal.ThingManager.registerAndInitializeHandler(ThingManager.java:954)
	at org.eclipse.smarthome.core.thing.internal.ThingManager.thingAdded(ThingManager.java:363)
	at org.eclipse.smarthome.core.thing.internal.ThingRegistryImpl.notifyTrackers(ThingRegistryImpl.java:208)
	at org.eclipse.smarthome.core.thing.internal.ThingRegistryImpl.notifyListenersAboutAddedElement(ThingRegistryImpl.java:127)
	at org.eclipse.smarthome.core.thing.internal.ThingRegistryImpl.notifyListenersAboutAddedElement(ThingRegistryImpl.java:1)
	at org.eclipse.smarthome.core.common.registry.AbstractRegistry.added(AbstractRegistry.java:131)
	at org.eclipse.smarthome.core.common.registry.AbstractRegistry.added(AbstractRegistry.java:1)
	at org.eclipse.smarthome.core.common.registry.AbstractProvider.notifyListeners(AbstractProvider.java:51)
	at org.eclipse.smarthome.core.common.registry.AbstractProvider.notifyListeners(AbstractProvider.java:69)
	at org.eclipse.smarthome.core.common.registry.AbstractProvider.notifyListenersAboutAddedElement(AbstractProvider.java:73)
	at org.eclipse.smarthome.model.thing.internal.GenericThingProvider.lambda$21(GenericThingProvider.java:898)
```
Maybe I have to find what local bundle to start.

**Closed** 2017-11-17 15:01 UTC
Labels: Binding-Sonos, bug

**Comment by kaikreuzer** [comment] 2017-11-18 12:44
@lolodomo Looks as if you try to run it in the openHAB IDE, not the ESH IDE - this won't work.

**Comment by lolodomo** [comment] 2017-11-18 12:48
Ok, I have only one IDE setup with everything (OH+ESH).
