### ISSUE TITLE
Automation: Add a Number item type value threshold 

### ISSUE THREAD

**Issue by aisebastian** [eclipse/smarthome#4111] opened 2017-08-22 19:49 UTC
I propose to add the possibility of setting a threshold for number item types in rules:

E.g.:
When item "Distance" state update < 20 then ...

This way, you could use operators for less than or greater than to create automation rules.
Is such a feature planned in any way or does anyone have a suggestion on how it would best be implemented?

**Comment by kaikreuzer** [comment] 2017-08-22 20:15
I'd guess this is a duplicate of https://github.com/eclipse/smarthome/issues/3224.
(Note that bigger new features will only be implemented on the new rule engine)

**Closed by kaikreuzer** 2017-08-22 20:15 UTC
