### ISSUE TITLE
[HUE] Switch-off not working for Osram bulbs on older software version

### ISSUE THREAD

**Issue by joergkling** [eclipse/smarthome#1792] opened 2016-07-02 08:02 UTC
Osram bulbs (here PAR16 50 TW) don' switch off completely when using a toggle in classic/basic UI and the bulbs are on an older software version. However the predefined toggle in PaperUI works fine (regardless the software version).

**Item definition**
Switch	Light_Kueche_Innen1_Toggle					"Kueche Innen 1 Toggle"			(gLight_Kueche)	{channel="hue:0220:00178810d0dc:22:brightness"}

**Not working: V1.03.07**
* PAR16 50 TW

**Working: V1.04.12**
* PAR16 50 TW 
* Classic A60 RGBW
* Classic B40 TW - LIGHTIFY

**Comment by kaikreuzer** [comment] 2016-07-02 09:09
Did this work before the changes from https://github.com/eclipse/smarthome/pull/1652?

**Comment by joergkling** [comment] 2016-07-02 10:13
Seems so. I just tested this on a beta3 and there the switch is working for all bulbs/firmware.

**Comment by kaikreuzer** [comment] 2016-07-03 11:37
@afuechsel As this seems to be a regression caused by #1652, could you please have a look?

> However the predefined toggle in PaperUI works fine 

@joergkling Could you provide a bit more details on that? After all, the Paper UI also only sends commands to the item.

Can you reproduce it by issuing commands through the console (```smarthome:send Light_Kueche_Innen1_Toggle OFF```) and check whether it makes a difference if you use a Switch or Dimmer item type?

**Comment by joergkling** [comment] 2016-07-03 19:58
Mhhh, not sure what I did two days ago. Today I triggered again the OFF command via Paper UI and got the same result as when using a switch (meaning the light dimms down but does not switch off completely). So please ignore the statement: _However the predefined toggle in PaperUI works fine_ 

Sorry about the confusion.

**Comment by afuechsel** [comment] 2016-07-04 08:18
This could be related to the initialization of the isOsramPar16 in the HueLightHandler, which could be missed, as we recently have seen in some unstable tests and due to #1479. A workaround could be to remove this property completely and check the light type each time a command is processed, whether it is an OSRAM bulb and needs special handling. 

However, as it does not happen with newer firmwares, is there a chance that we could remove the special OSRAM handling completely (it is currently anyway only implemented for PAR16 50 TW) and we require the users to use the latest firmware for their bulbs?

**Comment by afuechsel** [comment] 2016-07-04 11:56
Any comments about removing the OSRAM hack completely? 

After analyzing this a bit, it turns out, that both this bug (where the isOsramPar16 is initialized too late) and also the spurious test failures, where the expected property value has not yet been set (https://github.com/eclipse/smarthome/pull/1652#issuecomment-230226871) have the same reason: 

Previously, as properties could be stored, it happened that they threw a lot of exceptions and the initialize method was called several time until all properties have been set (see my analysis here: https://github.com/eclipse/smarthome/issues/588#issuecomment-226458476). Therefore we removed in #1682 this feature, so properties will never be persisted. Unfortunately, due to #1479, now the initialize method initializing both the properties and the isOsramPar16 will sometimes be called too early. It is however ensured, that the properties will be set, after the bridge comes online.

**Comment by afuechsel** [comment] 2016-07-04 12:26
Created #1799 which should fix this issue. I am lacking of OSRAM bulbs, so @joergkling could you please retest with this branch? The PR should also fix the sporadic test failures.

**Comment by joergkling** [comment] 2016-07-04 12:50
Regarding the Osram hack: It could be that not all users have the chance to upgrade the software of the Osrams bulb. Reason for this is that as owner of the Hue bridge they don't have a Osram bridge which is needed for the update. I spent the extra money for an Osram bridge and this is why most of my bulbs are on the newest software version. 

Happy tho test the fix. I assume I need to wait for the merge and on the next day take the binding out of the cloudbee package and replace my local one!?

**Comment by afuechsel** [comment] 2016-07-04 12:56
I need to update the PR before it could be merged. I have no idea when this will be. In the meantime you could also just fetch my branch into your repo and build it locally, if you have everything setup to build Eclipse SmartHome. If not, I guess you have to wait for the merge.

**Comment by joergkling** [comment] 2016-07-24 11:41
Sorry, need to reopen this one. The OSRAM bulbs do not switch of anymore with the latest version:

196 | Active   |  80 | 0.9.0.201607221840    | Eclipse SmartHome hue Binding

Could that be because of [PR 1870](https://github.com/eclipse/smarthome/pull/1870/)?

**Comment by afuechsel** [comment] 2016-07-25 11:49
I would assume so. As I already commented on #1880, the removal of the initialization loop in HueBridgeHandler#onConnectionResumed could sometimes lead to the situation, that the properties would be initialized right before the polling loop resumed the connection so the lightId is still null and model or type values could not be retrieved. And so also the OSRAM hack would not work as the binding just does not know, that it's an OSRAM bulb. 

The whole problem with the hue binding is the asynchronous polling loop. If we could avoid the polling things would be easier. But as it stands, there is probably no other way then to poll for the changes. 

Any arguments against just adding the removed code lines again from #1880? Maybe @lolodomo could also jump in here and check.

**Comment by lolodomo** [comment] 2016-07-25 13:35
The PR that suppressed the loop in bridge handler is 1870. You can restore the code if you think that is the problem (I am not sure at all but I am not deep in hue code) but don't suppress the changes I have done with PR1870 and 1899 in the light handler.

**Comment by afuechsel** [comment] 2016-07-26 07:10
@joergkling could you test if my fix in #1920 really fixes your issue with the OSRAM bulbs now? I partly reverted some of the changes in #1870.

**Comment by joergkling** [comment] 2016-07-26 15:01
sure, will do once the changes are in a compiled form.

**Comment by maggu2810** [comment] 2016-07-27 08:51
I assume @afuechsel would like to ask if you can test, so we know if we should merge it at all. Correct?

**Comment by joergkling** [comment] 2016-07-27 09:09
What I was trying to say with my last comment is that I am not a java developer. So I need somebody to provide me with a binary version of the binding. Last time @afuechsel adviced me to wait for the merge and use the nightly build. Happy to try another approach, but I need the binary.

**Comment by maggu2810** [comment] 2016-07-27 09:16
Ah, okay, I understand.
Perhaps @afuechsel can build it for you.

**Comment by joergkling** [comment] 2016-07-28 15:26
@afuechsel or @lolodomo, could one of you kindly provide me with a binary version of the HUE binding which includes the changes from https://github.com/eclipse/smarthome/pull/1920? I would then do some testing with the OSRAM bulbs. Thanks!

**Comment by lolodomo** [comment] 2016-08-01 06:14
@joergkling : could you please test the last nightly build and confirm your problem ?

**Comment by joergkling** [comment] 2016-08-01 08:16
Thanks @lolodomo, tried the latest nightly build (smarthome) but unfortunately the OSRAM bulbs still don't switch off.

219 | Active   |  80 | 0.9.0.201607300907    | Eclipse SmartHome hue Binding

**Comment by afuechsel** [comment] 2016-08-01 08:28
@joergkling @lolodomo afaik the nightly build would not help as the pr is not yet merged so it is not built or am I wrong? @kaikreuzer ?

**Comment by kaikreuzer** [comment] 2016-08-01 08:56
I think @lolodomo is fully aware that #1920 isn't merged yet. So when he asked to test the nightly build, I guess he wanted to be sure that the issue at all still exists.
Note that he wrote [here](https://github.com/eclipse/smarthome/pull/1920#issuecomment-236328537) that he actually does not see any general problem with the setting of the properties anymore.

**Comment by afuechsel** [comment] 2016-08-01 09:01
It's interesting, that the problem does not occur for @lolodomo but for @joergkling. Thinking about this PR, it may be, that @lolodomo is right and it won't fix anything. I still would like to enable @joergkling to retest with this PR although we think, it should not make a difference. just to be sure. How can we provide him with a hue binding of this PR? Would the jar-file be enough?

**Comment by joergkling** [comment] 2016-08-01 09:06
The issue here is only valid for OSRAM bulbs which are on a software version from prior Q1 2016. 

@afuechsel, yep, a jar of the binding is sufficient. (assuming I can copy it to addons folder and do the unload/load in the console)

**Comment by afuechsel** [comment] 2016-08-01 12:33
@joergkling github only accepts zip files, so I zipped the jar before adding it here. Please try with this binding. Would be interesting to see, if this makes a difference. Although we all (including me now) think, it won't make any....

[org.eclipse.smarthome.binding.hue-0.9.0-SNAPSHOT.jar.zip](https://github.com/eclipse/smarthome/files/393716/org.eclipse.smarthome.binding.hue-0.9.0-SNAPSHOT.jar.zip)

**Comment by joergkling** [comment] 2016-08-01 18:18
Thanks, @afuechsel, I was able to install the binding. And yes, there seems to be no difference (in functionality & log) between the binding from yesterday's build and your ad-hoc version.

While testing I realized that I mixed up something and might have misled you :$ First off all, turning off the OSRAM bulb using a **switch** item is working.

But I can see a difference with the OSRAM bulbs when using a **dimmer** item. For the bulb on the newer firmware the command dimmer=0 turns the bulb off.  But the bulb on the older firmware stays on (dimmed to a low level). 

So the issue now is slightly different to the initial description as it regards to a dimmer item (and not a toggle).

**Comment by afuechsel** [comment] 2016-08-02 06:24
Ok, so I will close this PR and not merge it. It doesn't fix your issue. 

I still wonder, why it works for @lolodomo, setting the properties happens at exactly the same place, where the OSRAM hack is initialized. We need to retest it ourselves but I am still lacking the needed devices. 

And yes, I understood your original issue in the way you described the dimmer: it is a bug in older OSRAM firmwares, that it does not switch off completely when brightness=0, That was exactly the reason, the OSRAM hack was added to the hue binding in the first place.

**Comment by lolodomo** [comment] 2016-08-02 06:46
For information I just own Philips hue color lights, not OSRAM.

**Comment by afuechsel** [comment] 2016-08-02 06:51
@lolodomo yes, I understand, but you confirmed, that properties had been set for you each time. And as the OSRAM hack is initialized at exactly the same place, this is related. Furthermore, I added some test cases for both the property settings and the OSRAM hack, that are alyways green, confirming that OSRAM should work. There's probably a bug in my test cases then as well. I need to retest this issue to track it down.

**Comment by joergkling** [comment] 2016-08-02 07:35
All, please stop working on this for the moment. I just tested the OSRAM bulbs on a freshly installed system using the PaperUI only and there it works!!! So perhaps this is a local issue. Will do some more tests and report back.

**Comment by kaikreuzer** [comment] 2016-08-02 08:31
Ok, let's close it and in case you still see a problem, feel free to re-open (or create a new issue with a new description).

**Closed by kaikreuzer** 2016-08-02 08:31 UTC
Labels: bug, Hue
