### ISSUE TITLE
Proxy timeout when streaming with video widget 

### ISSUE THREAD

**Issue by HentschelT** [eclipse/smarthome#4873] opened 2018-01-08 00:21 UTC
When using the video widget in .sitemap with a video stream as input source like:
`Video encoding="mjpeg" url="http://cam:80/cgi-bin/hi3510/snap.cgi?&-getstream&-chn=1"`
(SV3C cam, but the result is the same for other streams), there is a proxy timeout after exactly 60 seconds, and the stream stops. The logs shows:

````
2018-01-07 15:38:10.713 [DEBUG] [.s.u.i.proxy.AsyncProxyServlet:257  ] - 734249762 asynchronous write of 704 bytes completed on HttpOutput@6c1f91a2{READY}
2018-01-07 15:38:10.718 [DEBUG] [.s.u.i.proxy.AsyncProxyServlet:73   ] - 734249762 proxying content to downstream: 1024 bytes
2018-01-07 15:38:10.718 [DEBUG] [.s.u.i.proxy.AsyncProxyServlet:251  ] - 734249762 asynchronous write start of 1024 bytes on HttpOutput@6c1f91a2{READY}
2018-01-07 15:38:10.718 [DEBUG] [.s.u.i.proxy.AsyncProxyServlet:257  ] - 734249762 asynchronous write of 1024 bytes completed on HttpOutput@6c1f91a2{READY}
2018-01-07 15:38:10.724 [DEBUG] [.s.u.i.proxy.AsyncProxyServlet:627  ] - 734249762 proxying failedjava.util.concurrent.TimeoutException: Total timeout 60000 ms elapsed
	at org.eclipse.jetty.client.TimeoutCompleteListener.run(TimeoutCompleteListener.java:71)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

2018-01-07 15:38:10.726 [DEBUG] [.s.u.i.proxy.AsyncProxyServlet:240  ] - 734249762 proxying complete
````

Is this intended behavior, and if so - is there a setting to change that to make streams work indefinitely? Or is this a bug?

(This is against 'master' as of Jan 7, 2018)

Thanks for any help,
-Th

EDIT: Using the same url in a different client like VLC doesn't result in a timeout, it streams until VLC is closed.

**Comment by lolodomo** [comment] 2018-01-08 22:50
Is it specific to a particular UI or the same (timeout) whatever the UI ?

**Comment by HentschelT** [comment] 2018-01-09 00:50
I only tried this in basic ui. Not sure if this works different somewhere else. 

Any particular UI you'd want me to test with?

Cheers,
-Th

**Comment by lolodomo** [comment] 2018-01-09 08:36
Please try with Classic UI and another WEB browser for example.
And try with encoding="HLS" in the sitemap to bypass the proxy and confirm that the 60s timeout is only introduced by the OH proxy.

**Comment by HentschelT** [comment] 2018-01-09 10:57
Tried with Firefox and Chrome in both classic and basic UI, same result. I never gotten any stream to work with 'HLS' (correct me if I'm wrong, but isn't that just a playlist format which would have to supply a valid playlist file? Any pointers to get that done on a simple mjpeg stream?)

FWIW, this is all using my dev environment - Eclipse on a MBP on OSX Yosemite..
If you could point me to an env where this is working for you (RPI3, Win, ...) , I'll gladly try that out.

Cheers,
-Th

**Comment by lolodomo** [comment] 2018-01-09 12:29
My comment about HLS was immediately suppressed because not appropriate.
Your tests seem to confirm the timeout is introduced by the proxy.
Do you have a video URL i cpuld use to reproduce?

**Comment by HentschelT** [comment] 2018-01-09 22:10
Try this one, it shows the error after 60 seconds:

http://webcam.st-malo.com/axis-cgi/mjpg/video.cgi?resolution=640x480

BTW, most public cams now do https/ssl, which is also broken in the proxy (different error). Lets do one thing at a time tho...

Cheers,
-Th

**Comment by lolodomo** [comment] 2018-01-13 10:42
60s is apparently the default Jetty proxy timeout: https://www.eclipse.org/jetty/documentation/9.4.x/proxy-servlet.html
We could probably set a different value but what value ?

**Comment by lolodomo** [comment] 2018-01-13 12:14
By setting the "timeout" property to 0 for the proxy servlet, it looks like I am able to go over the 60 seconds. The playback stops after around 3 minutes, with no error as if the video is finished.
Note that the same WEB cam URL is finishing after arouind the same delay when used in my browser. So this WEB cam is not a good candidate for testing as it seems that the stream is closed after around 3 minutes.
Even if it seems to work, I am not sure that my change is the right way to do.

**Comment by lolodomo** [comment] 2018-01-13 13:36
By the way, I think the timeout should be disabled only for video and not globally for all the proxy as I did.

**Comment by HentschelT** [comment] 2018-01-13 22:39
How do I change the timeout for the proxy - or disable the timeout?

**Comment by HentschelT** [comment] 2018-01-13 22:39
How about starting to apply the timeout if there is no more data coming thru  the proxy? Ths way, i.e. as long as there is data streaming, don't start the timeout handler, once data flow stops, start timeout handler. If the connection isn't closed within the timeout, and no data flowing -> trip timeout handler.

**Comment by lolodomo** [comment] 2018-01-14 07:26
I will finally publish my enhancement that makes the timeout as a setting of the proxy service.

**Comment by lolodomo** [comment] 2018-01-14 07:34
Can you open another issue for https/SSL with an example of URL I can reproduce your other issue ?

**Comment by lolodomo** [comment] 2018-01-14 08:28
I just discovered 2 very annoying additional problems:

* even when you leave the page with the video link in Basic UI, the proxy still streams the video. Due to this reason and until this is fixed, I don't think it is a good idea to disable the playback timeout in the proxy.
* In Basic UI, when I reopen the page containing the video (just defined with url=), I only get the invalid link icon. The link is http://192.168.0.xxx:8080/basicui/%proxied_url%&t=1515918032072 which is not normal.

I will open separate issue.

**Comment by HentschelT** [comment] 2018-01-14 08:42
For the https/ssl issue, please see:

https://github.com/eclipse/smarthome/issues/4918

Cheers,
-Th

**Comment by lolodomo** [comment] 2018-02-20 23:40
I come back to this problem. The timeout setting is an init parameter of the registered servlet, setr by default to 60s when the servlet is registered. So I only see 2 possibilities:

* either I set this setting to 0 to disable the timeout. In this case, all proxy requests will be run without any timeout.
* or I register two servlets, one with the default timeout and a second with no timeout. UIs could then use the second for video and keep the first one for image.

@kaikreuzer @maggu2810 and others: WDYT ? Is there a problem to disable the timeout for the proxy servlet ?

**Comment by maggu2810** [comment] 2018-02-23 14:09
Hm, there is the `timeout` and the `idleTimeout`, correct?
If my understanding is correct, as long as the idle timeout is not disabled the drawback could be that a connection will be never closed because at least one byte is transferred before the idle timeout hits.
Is this correct or do you find some other culprits disadvantages?
Should the timeout depend on the content type? For video streams I would agree that it should be (perhaps) disabled. For normal "request / response" ones I don't know if it is a good idea to keep idle sessions open forever.

**Comment by lolodomo** [comment] 2018-02-24 09:33
@maggu2810 : no sorry, that is not the problem. We are in the case of a MJPEG video with a continuous data transfer. With the default timeout parameter, even if data are being transfered, the connection will be closed after 60 seconds because the proxy considers that 60 seconds is the maximum acceptable to transfer data. It is this maximum delay that we want to disable, at least for video proxying.

So yes, maybe that is a better solution to disable it only for video data. In this case, I will create a second proxy alias named `proxyvideo` with the timeout parameter set to 0 and UI should be fixed to use this one only for video sitemap elements.

**Comment by lolodomo** [comment] 2018-02-24 11:30
Of course, `idleTimeout` remains applicable in all cases.

**Comment by maggu2810** [comment] 2018-02-24 15:08
> If my understanding is correct, as long as the idle timeout is not disabled the drawback could be that a connection will be never closed because at least one byte is transferred before the idle timeout hits.
Is this correct or do you find some other culprits disadvantages?

Why isn't this the problem?
* timeout = 0
* idleTimeout = 30

If 1 byte is transferred every 29 seconds, the connection remains open forever.

A problem offer a proxy with `timeout = 0` could be that you are able to create a DoS attack very easily.
Open connections without transferring anything as long as the proxy server does not accept new connections anymore.
Sure this could be done on a timeout with 60 seconds, too. You have just reopen the connections every 60 seconds.
The problem I see is that a buggy client (e.g. an Android / iOS app) could eat all resources without doing it by intention.

Can't we change the timeout after the header has been transferred from the proxied server to the client and the content-type is known? So we don't need to create a second proxy.

**Comment by lolodomo** [comment] 2018-02-24 16:47
Jetty proxy server seems to initialize its HTTP stuff only one time when the servlet is first started. Then the same HTTP stuff is reused for each call to the proxy server.

Without changing this timeout init parameter, I see no solution to the original problem, that is we are not able to properly render video through our internal proxy.

In this case, why not avoiding our internal proxy for all sitemap video elements and rather use the direct URL provided by the user ?

**Comment by HentschelT** [comment] 2018-02-24 20:48
One reason for using the proxy is that some cam urls may not be reachable from an outside network (for a good reason), but openhab ist reachable. 
Also the proxy changes the URL so that no original URL parameters (userid, password, auth. token, etc) are visible in the resulting UI HTML.

 Bypassing the proxy verbatim basically nullifies any use of openhab for me.

**Comment by lolodomo** [comment] 2018-02-25 09:04
In this case, I see no new solution.
I am sorry but I will forgive and switch to the next subject.

**Comment by maggu2810** [comment] 2018-02-25 19:28
> Jetty proxy server seems to initialize its HTTP stuff only one time when the servlet is first started. Then the same HTTP stuff is reused for each call to the proxy server.

Hm, the AbstractProxyServlet of Jetty has a public method `setTimeout` to set the `_timeout` member. This is the same member that is initialized by the init parameters.

The public `getTimeout` method (that default implementation returns that member) is used in the `service` method of the `ProxyServlet` class.

So, it would be possible to change the timeout dependent on the request very easily.

This is taken from the description of the `ProxyServletService`:

> The servlet registers as "/proxy" and expects the two parameters "sitemap" and "widgetId". It will hence provide the data of the url specified in the according widget.

So, the URL information is taken from the respective video or image widget.

```Java
String uriString = null;
if (widget instanceof Image) {
    uriString = ((Image) widget).getUrl();
} else if (widget instanceof Video) {
    uriString = ((Video) widget).getUrl();
} else {
    throw new ProxyServletException(HttpServletResponse.SC_FORBIDDEN,
            String.format("Widget type '%s' is not supported!", widget.getClass().getName()));
}
```
 
I don't know if it make sense but I assume it would be possible to add a `proxyTimeout` attribute for the video and image widget and we could use it to overwrite (if set) the timeout the proxy request should use.

If I understand the code correctly, we would need to overwrite

```Java
protected void sendProxyRequest(HttpServletRequest clientRequest, HttpServletResponse proxyResponse, Request proxyRequest)
```

in our servlet.

After adding the `proxyTimeoutFromRequest` (that could be similar as `uriFromRequest`) the `sendProxyRequest` could look like:

```Java
final Long proxyTimeout = service.proxyTimeoutFromRequest(clientRequest);
if (proxyTimeout != null) {
    proxyRequest.timeout(proxyTimeout, TimeUnit.MILLISECONDS);
}
super.sendProxyRequest(clientRequest, proxyResponse, proxyRequest);
```

I didn't tried it myself, but if I read the code correctly it should work.



But I assume the most simple solution for the problem would be if the ones that want that the proxy never ends, configure `org.eclipse.smarthome.proxy.timeout = 0` itself.

Correct?

**Comment by lolodomo** [comment] 2018-02-26 09:14
@maggu2810 : I think I already tried your solution (setTimeout) without success.

But you might be right about your last comment even if I am not sure that `org.eclipse.smarthome.proxy.timeout` is the correct path. I think `ui` should probably be inside this path ?

**Comment by maggu2810** [comment] 2018-02-26 09:21
> @maggu2810 : I think I already tried your solution (setTimeout) without success.

`setTimeout` must be called before the proxy request has been send. So all after `sendProxyRequest` will be too late. Changing the timeout after receiving the headers will not work.

But overriding `sendProxyRequest` modify the `proxyRequest` and then calling the super implementation should IMHO work.

> But you might be right about your last comment even if I am not sure that org.eclipse.smarthome.proxy.timeout is the correct path. I think ui should probably be inside this path ?

Perhaps the code has been changed, but I don't identify an `ui` suffix in the service (and so configuration) PID:
https://github.com/eclipse/smarthome/blob/89af3025393fd4bc965832c220dfd908d1e95ec9/bundles/ui/org.eclipse.smarthome.ui/src/main/java/org/eclipse/smarthome/ui/internal/proxy/ProxyServletService.java#L75

**Comment by lolodomo** [comment] 2018-02-26 11:45
Ok, I have not yet tested to override `sendProxyRequest`. Worth to be tried.

And ok for the PID, I made a mismatch in my head with the package name.

**Comment by lolodomo** [comment] 2018-03-03 17:30
@maggu2810 : you are the best, your solution seems to work well. I will update my PR.

**Comment by HentschelT** [comment] 2018-04-06 07:45
Hi @lolodomo , did your commit make it into the main eclipse/smarthome repository/build? I can close this report at that point.

**Closed** 2018-06-19 15:00 UTC
