### ISSUE TITLE
java.lang.NoSuchMethodError: org.eclipse.smarthome.config.core.Configuration.get(Ljava/lang/Object;)Ljava/lang/Object on Offline Distro #276

### ISSUE THREAD

**Issue by lsafelix75** [eclipse/smarthome#1446] opened 2016-05-02 05:42 UTC
Unfortunately, with the latest offline distro #276. I am still hitting the same issue:

2016-05-02 13:25:07.503 [ERROR] [ome.core.thing.internal.ThingManager] - Exception occured while initializing handler of thing 'xxxxxx:broker:mygateway1': java.lang.NoSuchMethodError: org.eclipse.smarthome.config.core.Configuration.get(Ljava/lang/Object;)Ljava/lang/Object;
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: org.eclipse.smarthome.config.core.Configuration.get(Ljava/lang/Object;)Ljava/lang/Object;
at java.util.concurrent.FutureTask.report(FutureTask.java:122)[:1.8.0]
at java.util.concurrent.FutureTask.get(FutureTask.java:206)[:1.8.0]
at org.eclipse.smarthome.core.common.SafeMethodCaller.callAsynchronous(SafeMethodCaller.java:179)[96:org.eclipse.smarthome.core:0.8.0.201604302105]
at org.eclipse.smarthome.core.common.SafeMethodCaller.call(SafeMethodCaller.java:72)[96:org.eclipse.smarthome.core:0.8.0.201604302105]
at org.eclipse.smarthome.core.common.SafeMethodCaller.call(SafeMethodCaller.java:56)[96:org.eclipse.smarthome.core:0.8.0.201604302105]
at org.eclipse.smarthome.core.thing.internal.ThingManager$7.run(ThingManager.java:659)[102:org.eclipse.smarthome.core.thing:0.8.0.201604302105]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[:1.8.0]
at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)[:1.8.0]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)[:1.8.0]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0]
at java.lang.Thread.run(Thread.java:744)[:1.8.0]
Caused by: java.lang.NoSuchMethodError: org.eclipse.smarthome.config.core.Configuration.get(Ljava/lang/Object;)Ljava/lang/Object;
at org.openhab.binding.talentswitchmqtt.handler.BrokerHandler.initialize(BrokerHandler.java:82)
at org.eclipse.smarthome.core.thing.internal.ThingManager$7$1.call(ThingManager.java:662)
at org.eclipse.smarthome.core.thing.internal.ThingManager$7$1.call(ThingManager.java:1)
at org.eclipse.smarthome.core.common.SafeMethodCaller$CallableWrapper.call(SafeMethodCaller.java:170)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0]
... 3 more

**Comment by maggu2810** [comment] 2016-05-02 06:09
As it is a duplicate of https://github.com/eclipse/smarthome/issues/1437#issuecomment-216107253, I close this one (and I still assume it is more a openhab distro / addons problem now).

**Closed by maggu2810** 2016-05-02 06:09 UTC

**Comment by kaikreuzer** [comment] 2016-05-02 06:28
I would say the binding needs to be recompiled, then it should work again. Sorry for the hassle...
