### ISSUE TITLE
[ENH] Regular Expression in configuration parameter definitions

### ISSUE THREAD

**Issue by MHerbst** [eclipse/smarthome#2972] opened 2017-02-04 10:26 UTC
In the configuration parameter definition there are several pre-defined types (text, integer). There is also the option to enter a context (like network, email, ...). But currently only the type is used to check whether a value is correct or not.

I am missing an option to specify a regular expression to validate an input before it is sent to the add-on. This could be used to validate whether a value is correct IP address or MAC address or a port number is valid.

**Comment by kaikreuzer** [comment] 2017-02-09 12:53
Looks like a duplicate of https://github.com/eclipse/smarthome/issues/2556.

**Closed by kaikreuzer** 2017-02-09 12:53 UTC
