### ISSUE TITLE
Sonos-Binding: Invalid Subscription

### ISSUE THREAD

**Issue by ByteBandito** [eclipse/smarthome#3935] opened 2017-08-02 09:20 UTC
Hey,

my SONOS-binding produces from time to time these errors:
`2017-08-02 11:09:32.404 [ERROR] [g.jupnp.protocol.sync.ReceivingEvent] - Invalid subscription ID, no active subscription: (IncomingEventRequestMessage) NOTIFY /upnpcallback/dev/RINCON_[.....]_MR/svc/upnp-org/AVTransport/event/cb SEQUENCE: 0`

Note: The binding still works. Before it and after also. Any those errors do not occur on startup, but as i said from time to time, sometimes after 8 hours or so... sometimes 2-3x close behind each other.

Any Idea? Is it a bug?

**Comment by lolodomo** [comment] 2017-08-02 14:29
It is produced by JUPNP and not openHAB.
It is not a bug. It does signal that an old subscription is now invalid.
Issue to be closed.

**Comment by lolodomo** [comment] 2017-08-02 14:31
It happens generally when restarting OH but not systematically.

**Comment by ByteBandito** [comment] 2017-08-02 14:35
But... its marked as [ERROR] and - at least in my case - it also happens from time to time... not only when OH is restarted.

**Comment by lolodomo** [comment] 2017-08-02 14:48
Please have a look to my issue #1903.

**Comment by ByteBandito** [comment] 2017-08-02 15:30
In issue #1903 the problem seems to occur only on startup, isnt it?

If you tell me, that i have to ignore this [error], ok.... everything works except that error-message.

**Comment by lolodomo** [comment] 2017-08-02 15:54
Yes, you have to ignore this error message especially if evrything is working well.
In my point of view, this message could occur only after OH requested new subscriptions. Normally it happens at OH restart or when restarting the binding or when the binding detected a transition OFFLINE => ONLINE for a Sonos device (generally after switching ON a Sonos that was power off).

That being said, I agree wit you that it would be better to have a different message but we have no way to control it because it is produced by an external library we are using.

**Comment by kaikreuzer** [comment] 2017-08-02 19:38
> but we have no way to control it because it is produced by an external library we are using.

Well, this is not entirely true. By chance, I am also the maintainer of jUPnP and I am doing [releases](https://github.com/jupnp/jupnp/releases) every now and then, which then flow into ESH & openHAB. So if you think that there is a bug or some logging should be changed, feel free to create PRs against that project.

**Comment by Dan1001** [comment] 2017-08-29 19:27
Has anyone found a neat way to exclude this error from the logs, without excluding other (real) errors from the Sonos binding?

thanks,

Dan

**Comment by triller-telekom** [comment] 2017-11-30 14:12
@lolodomo Are you sure we can ignore this error? I just had a look at the JUPNP repo and to me it looks like we could safely change the severity from error to debug here: https://github.com/jupnp/jupnp/blob/master/bundles/org.jupnp/src/main/java/org/jupnp/protocol/sync/ReceivingEvent.java#L122

WDYT?

**Comment by lolodomo** [comment] 2017-12-02 13:59
Yes I think.

**Comment by triller-telekom** [comment] 2017-12-04 08:43
@kaikreuzer I have created a PR based on this discussion: https://github.com/jupnp/jupnp/pull/90

**Comment by nesys** [comment] 2018-04-03 09:18
I've also from time to time the same error in my logs:

[ERROR] [g.jupnp.protocol.sync.ReceivingEvent] - Invalid subscription ID, no active subscription: (IncomingEventRequestMessage) NOTIFY /upnpcallback/dev/RINCON_000E58289D5001400/svc/upnp-org/AudioIn/event/cb SEQUENCE: 0

**Comment by triller-telekom** [comment] 2018-06-04 13:09
This issue is fixed by https://github.com/jupnp/jupnp/pull/90 @maggu2810 @sjka Can you please close this issue?

**Comment by kaikreuzer** [comment] 2018-06-04 13:16
But it will only be fixed for ESH once a new JUPnP version is released and the ESH TP is updated accordingly...

**Comment by triller-telekom** [comment] 2018-06-04 14:02
True. Once you find time, please create the new release. https://github.com/eclipse/smarthome/pull/5680 is waiting to update the target plattform :)

**Comment by lolodomo** [comment] 2018-08-14 11:14
@kaikreuzer created a new JUPnP version of the library.
So this issue could be closed now.

**Closed** 2018-08-14 11:15 UTC
