### ISSUE TITLE
Thing properties being merged into configuration properties

### ISSUE THREAD

**Issue by cdjackson** [eclipse/smarthome#1414] opened 2016-04-21 19:13 UTC
I'm not sure where this is happening - it may be a bug in the zwave binding, or it might be a bug in ESH. However, I'm seeing thing properties merged into the configuration properties - it seems to happen after a restart, but I can't nail down exactly where it's occurring...

In zwave, I update some properties to keep track of the device -:
```
                    Map<String, String> properties = editProperties();
                    properties.put(ZWaveBindingConstants.PROPERTY_CLASS_BASIC,
                            node.getDeviceClass().getBasicDeviceClass().toString());
                    ...
                    updateProperties(properties);
```

This seems to correctly update the properties, and it's separate from the configuration. If I now stop ESH/OH2 and restart, if I add a breakpoint at the beginning of `initialize()` I get properties being merged into the configuration.

This issue https://github.com/openhab/openhab2-addons/issues/814 is likely related since it's reporting a validation error, but the error is against a property that shouldn't be in the configuration, so I guess one of the validation checks doesn't find the config description or something. I think this is only a problem with PaperUI since it (I think?) still sends all configuration to ESH, not just changes?

I've tried following the obvious code through, and everything looks ok, but somewhere this is getting screwed up. I don't think it's in the binding (but since I can't find the source of the problem, I'm not ruling it out!)

It may also be linked to the change thing type function. The reason I say this is because in the discovery handler I add some properties on discovery. I think it's only these properties that end up in the configuration - when the thing is first approved, the properties only seem to be in the properties, and not in the configuration.  If I add more properties later in the thing handler (which I do), I never see these new properties in the configuration which makes me think it's linked somehow to discovery, or more likely, the thing type change (although the code in thing type change looks ok!).

More code 'bits' from zwave...

In discovery, I add properties -:
```
        DiscoveryResult discoveryResult = DiscoveryResultBuilder.create(thingUID).withProperties(properties)
                .withBridge(bridgeUID).withLabel(label).build();
```

and when I change the thing type...
```
        changeThingType(foundProduct.getThingTypeUID(), getConfig());
```

I think all this is correct?

**Comment by kaikreuzer** [comment] 2016-04-22 07:44
@sjka As Chris suspects that this could be related to the thing type change, does this ring any bell for you, what could cause this behavior?

**Comment by sjka** [comment] 2016-04-22 12:44
no, unfortunately it doesn't ring a bell. the ```changeThingType()``` only sets the given configuration, amended by default values if any are missing. I also double-checked the code and also can't see a place where they would be mixed up. The way you are using it looks correct. If it's related, than in a pretty nasty, non-obvious way.

The only places I know which could cause such a confusion are the ```PersistentInbox.approve()```, using ```getPropsAndConfigParams()``` to fill the config with props having identical names. And ```PersistentInbox.add()``` messes around with existing Things, in case they got discovered again (see https://www.eclipse.org/forums/index.php/t/1074125/). Could one of those be the culprit?

**Comment by cdjackson** [comment] 2016-04-22 13:06
I also looked at the inbox.approve method - I’m not sure why it was implemented this way, and I think the detection of properties and configuration may not be optimum, but I couldn’t see this issue caused there. It also seems that the first time the thing handler is called, properties and configuration are separate and they get combined after the thing is approved (but as above, the only ones that seem to be combined are the ones produced right at the beginning - it doesn’t seem to happen later, even after running for many weeks with regular restarts).

**Comment by cdjackson** [comment] 2016-04-22 13:28
> And PersistentInbox.add() messes around with existing Things, in case they got discovered again

Actually, this might be it... In the synchronizeConfiguration method, the properties are copied into the configuration.

```
    private boolean synchronizeConfiguration(Map<String, Object> properties, Configuration config) {
        boolean configUpdated = false;

        Set<Map.Entry<String, Object>> propertySet = properties.entrySet();

        for (Map.Entry<String, Object> propertyEntry : propertySet) {
            String propertyKey = propertyEntry.getKey();
            Object propertyValue = propertyEntry.getValue();

            Object configValue = config.get(propertyKey);

            if (((propertyValue == null) && (configValue != null))
                    || (propertyValue != null && !propertyValue.equals(configValue))) {

                // update value
                config.put(propertyKey, propertyValue);
                configUpdated = true;
            }
        }

        return configUpdated;
    }
```

Specifically the following check will write the property value into the config value if property value isn't  null and is different to the existing value -:
```
(propertyValue != null && !propertyValue.equals(configValue)
```

The inbox only seems to keep one set of properties (ie one list) and then it decides if it's a property or a config using the configuration description (if no config description, then it's a property, otherwise config) - as I mentioned earlier, this doesn't seem like a good idea, and this seems to confirm that I think.

Does anyone know why this was done this way, and if it's necessary?

**Comment by maggu2810** [comment] 2016-04-22 14:43
I don't know why this implementation has been chosen, but I could point you to the related
* forum thread: https://www.eclipse.org/forums/index.php/t/1066328/
* issue: #598

Have to read it myself now...

**Comment by cdjackson** [comment] 2016-04-22 14:57
Yep - I remember that discussion… I’m still not sure this is the best implementation - I would have probably preferred to keep properties and config separate. 

I suspect that maybe this worked in the past, but one other problem I see in this code is that it uses the thingTypeUID from the discovery result to get the configuration parameters - this will in any case be wrong given that the thing type might have changed (as it now does in ZWave), and this will also contribute to this problem since the detection of properties and configuration will now be based on mismatched thing types.

**Comment by maggu2810** [comment] 2016-04-22 15:14
Would it be an option if we start to store it separately from now and convert already persisted ones to the new separated representation?
So this code should be only handle old saved objects (that also have no thing type change implementation).

**Comment by cdjackson** [comment] 2016-04-30 12:15
@kaikreuzer any thoughts on how you like to solve this? Personally, I agree with @maggu2810 that we should keep config and properties separate.

**Comment by sjka** [comment] 2016-05-02 09:40
Before we change anything, I would like to understand the actual problem first. @cdjackson, if I understood it correctly, it came kind of a surprise to you that setting properties in the discovery result automagically updated some existing configuration properties. Having clarified that this is intended (let's keep the  discussion if it's good or bad at all out of here for the moment...), what problem is actually left here?
You mentioned that the changed ThingType is not taken into account when updating existing things. However, the synchronization algorithm which you also pasted above actually only updates existing configuration entries. It does not even look for the ThingType, but simply takes the ones from the existing Thing (i.e. ```thing.getConfiguration()```). So I wonder how that can mix up anything... Are you sure that when changing the ThingType you actually don't provide any configuration properties that should not be in there anymore?

**Comment by cdjackson** [comment] 2016-05-02 12:09
Firstly, to clarify that it is intended that properties end up in the properties AND the configuration? This seems a bit strange?

**Comment by kaikreuzer** [comment] 2016-05-02 12:15
A property is a key/value pair. DiscoveryResult-properties are something different than Thing-properties.
DiscoveryServices can simply add key/value pairs to the result - at that moment, this does not say anything about what these are good for.

**Comment by cdjackson** [comment] 2016-05-02 12:19
Ok, that’s fine, but if I put a load of properties into the discovery result, then they end up in the configuration in the thing. So, when I’m looking for them in the properties, they aren’t there and I add them again, so they end up in both places. Maybe we should stop using properties and we only ever use configuration?

**Comment by kaikreuzer** [comment] 2016-05-02 12:20
> then they end up in the configuration in the thing

If this is the case, then it is a bug. They should ONLY end up in the configuration, if the configuration already includes the same key as this entry. All the rest should be a regular property on the Thing.

**Comment by cdjackson** [comment] 2016-05-02 12:25
They do only end up in the configuration - so maybe it’s ok. My point was I thought they would end up in the properties. So, from the discovery they end up in the configuration, and then later I store the same stuff in the properties. So, it seems that properties is not supported and we shouldn’t use it? 

It’s a bit confusing. To me, properties are kind of system orientated information about the device/thing where configuration is more user orientated information. If the discovery only ever puts the data into the configuration, then it’s quite strange to me as that data is system type information (i.e. the vendor, model number etc) it’s not configuration (to me at least).

**Comment by sjka** [comment] 2016-05-02 12:44
> They do only end up in the configuration - so maybe it’s ok

No, it's not. It's exactly the opposite of the expected behavior (see @kaikreuzer's comment).

> To me, properties are kind of system orientated information about the device/thing where configuration is more user orientated information.

Fully agreed. Nothing has changed here.

> If the discovery only ever puts the data into the configuration [...]

No, it's supposed to only _update_ data that is already there. The question we need to answer is: who puts them there first place? The discovery only updates stuff in the configuration which _is already there_, but does _not_ put anything _new_ into it.

**Comment by cdjackson** [comment] 2016-05-02 13:25
> The discovery only updates stuff in the configuration which is already there, but does not put anything new into it.

Ok, so that's what it's meant to do, but let's take another look at this code...

```java
    private boolean synchronizeConfiguration(Map<String, Object> properties, Configuration config) {
        boolean configUpdated = false;

        Set<Map.Entry<String, Object>> propertySet = properties.entrySet();

        for (Map.Entry<String, Object> propertyEntry : propertySet) {
            String propertyKey = propertyEntry.getKey();
            Object propertyValue = propertyEntry.getValue();

            Object configValue = config.get(propertyKey);

            if (((propertyValue == null) && (configValue != null))
                    || (propertyValue != null && !propertyValue.equals(configValue))) {

                // update value
                config.put(propertyKey, propertyValue);
                configUpdated = true;
            }
        }
    }
```
We can ignore the first line of this conditional (for now at least - in reality, the problem is probably in this line) since it's ORed with the second part ```(propertyValue != null && !propertyValue.equals(configValue))```.

```propertyValue``` will be non null, so we effectively have the following -:

```java
if(!propertyValue.equals(config.get(propertyKey)) {
    config.put(propertyKey, propertyValue);
}
```

Given the first time through this loop (ie when the discovery entry is added the first time AFTER the thing is approved) ```config.get(propertyKey)``` is null, so we copy the data into the config. I guess the previous ```(configValue != null)``` was meant to check for this (??), but given the second statement is ORed, it doesn't work and the properties are copied into the config...

I think ;)

**Comment by maggu2810** [comment] 2016-05-02 13:33
We could add a "hasKey" to the Configuration class and check if the property key is present in the configuration first (null check could not be used to check for "is present").

**Comment by maggu2810** [comment] 2016-05-03 06:33
I added a method to check if a key is present in the configuration. I changed also the synchronizeConfiguration to use this method and tried to make it easy to read / understand.

I hope the desired logic is implemented correctly now.

**Comment by kaikreuzer** [comment] 2016-05-03 07:22
Thanks @maggu2810!
@cdjackson Can you confirm that this issue is resolved by that?

**Comment by maggu2810** [comment] 2016-05-10 18:45
@cdjackson ping :wink:

**Comment by cdjackson** [comment] 2016-05-10 22:09
It looks like it's probably working ok now. Thanks @maggu2810.

**Closed** 2016-05-10 22:13 UTC
Labels: Core
