### ISSUE TITLE
NPE in ThingTypeI18nLocalizationService

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#4152] opened 2017-08-29 09:03 UTC
An NPE has been reported [here](https://community.openhab.org/t/oh-2-2-0-snapshot-1025-zwave-npe/33711):

```
29-Aug-2017 09:06:00.745 [ERROR] [ab.binding.zwave.internal.protocol.ZWaveController] - Exception during ZWave thread: Input 2. {}
java.lang.NullPointerException: null
	at org.eclipse.smarthome.core.thing.i18n.ThingTypeI18nLocalizationService.createLocalizedThingType(ThingTypeI18nLocalizationService.java:67) [108:org.eclipse.smarthome.core.thing:0.9.0.201708281632]
	at org.eclipse.smarthome.core.thing.xml.internal.XmlThingTypeProvider.localize(XmlThingTypeProvider.java:128) [109:org.eclipse.smarthome.core.thing.xml:0.9.0.201708281632]
	at org.eclipse.smarthome.core.thing.xml.internal.XmlThingTypeProvider.localize(XmlThingTypeProvider.java:1) [109:org.eclipse.smarthome.core.thing.xml:0.9.0.201708281632]
	at org.eclipse.smarthome.config.xml.AbstractXmlBasedProvider.acquireLocalizedObject(AbstractXmlBasedProvider.java:211) [100:org.eclipse.smarthome.config.xml:0.9.0.201708281632]
	at org.eclipse.smarthome.config.xml.AbstractXmlBasedProvider.getAll(AbstractXmlBasedProvider.java:165) [100:org.eclipse.smarthome.config.xml:0.9.0.201708281632]
	at org.eclipse.smarthome.core.thing.xml.internal.XmlThingTypeProvider.getThingTypes(XmlThingTypeProvider.java:82) [109:org.eclipse.smarthome.core.thing.xml:0.9.0.201708281632]
	at org.eclipse.smarthome.core.thing.type.ThingTypeRegistry.getThingTypes(ThingTypeRegistry.java:48) [108:org.eclipse.smarthome.core.thing:0.9.0.201708281632]
	at org.eclipse.smarthome.core.thing.type.ThingTypeRegistry.getThingTypes(ThingTypeRegistry.java:59) [108:org.eclipse.smarthome.core.thing:0.9.0.201708281632]
	at org.openhab.binding.zwave.internal.ZWaveConfigProvider.initialiseZWaveThings(ZWaveConfigProvider.java:310) [203:org.openhab.binding.zwave:2.2.0.201708281802]
	at org.openhab.binding.zwave.internal.ZWaveConfigProvider.getProductIndex(ZWaveConfigProvider.java:355) [203:org.openhab.binding.zwave:2.2.0.201708281802]
	at org.openhab.binding.zwave.internal.ZWaveConfigProvider.getThingType(ZWaveConfigProvider.java:382) [203:org.openhab.binding.zwave:2.2.0.201708281802]
```
It looks to me as if no channel type can be resolved, which leads to the NPE.
@lolodomo Should we add a safe-guard here? I am not sure, in which situations we can fail to resolve the channel type, but it seems to happen...

**Comment by lolodomo** [comment] 2017-08-30 07:17
I will take a look. It seems to happen when initializing z-wave things. As you said it would be interesting to know in which cases the resolv fails.

**Comment by kaikreuzer** [comment] 2017-08-30 08:35
According to [this comment](https://community.openhab.org/t/oh-2-2-0-snapshot-1025-zwave-npe/33711/9?u=kai), it is most likely due to an invalid thing type definition (having channels that are of a non-declared type). So even if it is an error situation, we should harden the code here and not throw an NPE.

**Comment by mhilbush** [comment] 2017-08-30 12:03
@kaikreuzer Do you think the root cause of this issue is the same root cause that's causing the REST API calls to fail as described [here](https://community.openhab.org/t/oh-2-2-0-snapshot-1025-zwave-npe/33711/40).

**Comment by kaikreuzer** [comment] 2017-08-30 13:17
@mhilbush Yes, very likely as it seems that the REST response simply states that an unexpected NPE has happened.

**Comment by sihui62** [comment] 2017-09-01 15:19
I vote for a "critical bug" label because since #1024 openHAB is not fully usable anymore:

- 500 error in PaperUI
- Items tab missing
- NPE

https://community.openhab.org/t/bug-items-category-missing-paperui-error-500-on-build-1029-on-openhabian/33824
https://community.openhab.org/t/oh-2-2-0-snapshots-1025-1028-zwave-npe/33711/40

**Comment by lolodomo** [comment] 2017-09-01 15:39
To be closed, my PR fixing it was merged today.

**Closed** 2017-09-01 16:21 UTC
Labels: bug, Core

**Comment by sihui62** [comment] 2017-09-01 17:12
> my PR fixing it was merged today.

Thx @lolodomo (and all others) for your hard work, appreciate that.

**Comment by kaikreuzer** [comment] 2017-09-01 21:18
FTR, the latest openHAB distro 1030 includes this fix.
