### ISSUE TITLE
Incorrect types of Configuration properties passed to ModuleHandlers

### ISSUE THREAD

**Issue by vilchev** [eclipse/smarthome#2937] opened 2017-01-31 07:54 UTC
At the moment if we declare configuration with an Integer type property
for example having a 'count' int type Configuration Property
...
        {
          "name": "count",
          "type": "INTEGER",
          "label": "Count",
          "description": "Count",
          "required": true
        }
....

When RuleEngine creates the ModuleHandlers the normalized configuration which is passed to the ModuleHandler contains the property 'count' but with incorrect type -> BigDecimal.

So in order the ModuleHandler to receive its property in the correct type that was declared in the Module Type it has to manually normalize that value itself(but first having the knowledge that the property will be BigDecimal so that avoiding the class cast exception).
The problem is even nastier when having the property type Integer with additional 'multiple=true' then Handler receives a List of BigDecimals.

**Comment by danchom** [comment] 2017-01-31 08:05
Config property normalization converts all digit types (integer and decimal) to BigDecimal. This is the reason why the module handler receive BigDecimal instead of integer. For me it is not correct too.
@Kai could you explain why the normalization does not convert config values into types defined in their meta-data?

**Comment by kaikreuzer** [comment] 2017-01-31 08:07
I do not see a bug here.
For both "decimal" and "integer", the internal data type is BigDecimal - you can rely on this. We might have to document that a bit more specifically though.

**Comment by vilchev** [comment] 2017-01-31 08:28
> I do not see a bug here.
 If a user have declared its property type to be Integer and it receives something else in the end imho it is a bug (If user is not in depth with Configuration impl there is 100% chance of class cast except in the Handler).
We have an API that declares 4 types for Configuration property: TEXT, INTEGER, DECIMAL, BOOLEAN.
I don't see a point having the two types INTEGER, DECIMAL if at the end you will receive a third one BigDecimal in the ModuleHandler? so we actually have TEXT, NUMBER, BOOLEAN at the end?

> For both "decimal" and "integer", the internal data type is BigDecimal - you can rely on this
So each Handler should modify its logic either to normalize the type to the correct one (which is declared in the module type) or to modify its remaining 'Handler logic' to work with BigDecimals..

**Comment by sjka** [comment] 2017-01-31 13:08
You are mixing up two things here. In the config description, you have the option to specify that a value is expected to be an [INTEGER](https://en.wikipedia.org/wiki/Integer) in the sense of a number without fractions. We explicitly do NOT refer to java types there (as you might have concluded from the TEXT already, as there is no such class in the java language).
For the sake of simplicity, there was the decision made that bindings may rely on the numbers being represented as `j.m.BigDecimal` - either with or without fractions.

> [...] to normalize the type to the correct one [...] or to modify its remaining 'Handler logic' to work with BigDecimals

The "correct one" is BigDecimal in our framework. If you need for convenience any java integer datatype, you may easily use any of the `BigDecimal.longValueExact()` / `.intValueExact()`, `.shortValueExact()`/ `.byteValueExact()` methods available to you. That's indeed up to you as the implementor. 

No doubt we are lacking a detailed documentation about this. But otherwise I agree with @kaikreuzer: No bug to see here.

**Comment by vilchev** [comment] 2017-01-31 13:27
> We explicitly do NOT refer to java types there (as you might have concluded from the TEXT already, as there is no such class in the java language).

You actually do that defining the min value and max value are references to java types(at least in the javadoc):

```

    /**
     * The {@link Type} defines an enumeration of all supported data types a
     * configuration parameter can take.
     *
     * @author Michael Grammling - Initial Contribution
     */
    public enum Type {

        /**
         * The data type for a UTF8 text value.
         */
        TEXT,

        /**
         * The data type for a signed integer value in the range of [ {@link Integer#MIN_VALUE},
         * {@link Integer#MAX_VALUE}].
         */
        INTEGER,

        /**
         * The data type for a signed floating point value (IEEE 754) in the
         * range of [{@link Float#MIN_VALUE}, {@link Float#MAX_VALUE}].
         */
        DECIMAL,

        /**
         * The data type for a boolean ({@code true} or {@code false}).
         */
        BOOLEAN;

    }
```


> The "correct one" is BigDecimal in our framework. If you need for convenience any java integer datatype, you may easily use any of the BigDecimal.longValueExact() / .intValueExact(), .shortValueExact()/ .byteValueExact() methods available to you. That's indeed up to you as the implementor.

Well for single value, yes, its not a big pain to just do that but what about multiple=true? each Handler should normalize the whole list than?

**Comment by danchom** [comment] 2017-01-31 13:48
@sjka If these types are only for GUI, what is going on when I have integer property A=4 (set by GUI) and I want to show its value using configuration (get from config)? The GUI has to normalize the value again or to it will show A=4.0. 
Btw there is a bug in ConfigUtil.normalizeType(Object value, ConfigDescriptionParameter configDescriptionParameter) mehtod when config description is not specified. It only converts double into BigDecimal, integer are left as Integer. Are you ok to fix this?,

**Comment by sjka** [comment] 2017-01-31 13:59
no, `BigDecimal` remembers the precision, i.e. 

```
System.out.println(new BigDecimal("42").toPlainString());
```

gives `42`. So ideally UIs should not need to "normalize" it again.

> Btw there is a bug in ConfigUtil.normalizeType(Object value, ConfigDescriptionParameter configDescriptionParameter) mehtod when config description is not specified. It only converts double into BigDecimal, integer are left as Integer. Are you ok to fix this?,

I agree, this is not consistent. Unfortunately it is like that since quite some time. You may of course "fix" it if you will care for all the open source and commercial bindings that you are going to break 😉

**Comment by danchom** [comment] 2017-01-31 14:15
>So ideally UIs should not need to "normalize" it again.

I can't understand, I've set integer, but receive something different "4" or BigDecimal("4"). Is it a normal?
How to explain to ModuleHandler implementer that the type that they have set does not have any meaning?

**Comment by maggu2810** [comment] 2017-01-31 14:17
```java
    public static Object normalizeType(Object value, ConfigDescriptionParameter configDescriptionParameter) {
        if (configDescriptionParameter != null) {
            Normalizer normalizer = NormalizerFactory.getNormalizer(configDescriptionParameter);
            return normalizer.normalize(value);
        } else {
            return value instanceof Double ? BigDecimal.valueOf((Double) value) : value;
        }
    }
```

Shouldn't we be consistent and use BigDecimal as long as the value is a Number type (Float, Integer, Long, ...)? I think so. Normalize type should return a Boolean, BigDecimal or a String if possible as this are the only types that are allowed.
If something is broken then, perhaps it needs to be fixed then.

**Comment by maggu2810** [comment] 2017-01-31 14:19
INTEGER does not mean the Java Integer type, but an integral number type.
DECIMAL also allows fractional number types.
The real Java type is another story, so I don't see why it should not be valid to use BigDecimal in both cases.
We have also TEXT and use String...
The one thing is a description and the other one is a type for the representation.

**Comment by vilchev** [comment] 2017-01-31 14:32
> INTEGER does not mean the Java Integer type, but an integral number type.
> DECIMAL also allows fractional number types.
> The real Java type is another story, so I don't see why it should not be valid to use BigDecimal in both cases.
> We have also TEXT and use String...
> The one thing is a description and the other one is a type for the representation.-

Ok.. what is the purpose of having the two types(INTEGER, DECIMAL) instead of just NUMBER then? 
Sorry maybe I have a problem to understand this concept, but why we do make the users to choose between the two types as in the end it is totally ignored?

**Comment by vilchev** [comment] 2017-02-01 07:52
I see that this conversation goes to no end - I just wanted to share my view with you guys.

I do not know the usage of Configuration inside your whole project, but for Automation module this is like an API for clients that want to add a new ModuleType (ModuleType.json && ModuleHandler) to the system.

I see it as an incorrect behavior:

1. client creates json with ConfigProperty of type INTEGER
2. client creates an instance of its Module and sets for its property - "5"
3. but when Configuration is passed to his ModuleHandler he receives - 5.0 - here we just ignore his configuration, ignore his input data, and just return him a something different then INTEGER ( the definition that @maggu2810 state ), so he have to additionally do some work on that data (as @sjka stated) so he can continue his work..

**Comment by maggu2810** [comment] 2017-02-01 09:14
If you use INTEGER the scale of the used BigDecimal should be zero and not 1.
So, if 5 is changed to 5.0, then the BigDecimal has the wrong scale and I would consider that as a bug.

**Comment by danchom** [comment] 2017-02-01 09:30
I  thing the problem is not only with module handlers, the problem is always when you want to get data form the system. For example REST users will receive 5.0 value (with fraction) for INTEGER configuration property (without fraction) .
At the moment there is no way to denormalize  configuration property. The ConfiguUtil can be  extended with such method. On the other hand it is not convenient to do forward/backward normalization instead of   keeping values as they come.
My proposal is extend normalization util in automation module and keep data as they defined.
What do you think? @kaikreuzer,  @maggu2810 and @sjka

**Comment by maggu2810** [comment] 2017-02-01 09:56
IIRC (correct me if I am wrong) It is a limitation in the uaws REST JSON (de)serialization implementation that it does not keep the scale and not a problem that has been caused by using BigDecimal.

**Comment by danchom** [comment] 2017-02-01 10:01
@maggu2810  GSON parses numbers from JSON to double values. I think for that reason they have scale 1.

**Comment by vilchev** [comment] 2017-02-01 10:11
> So, if 5 is changed to 5.0, then the BigDecimal has the wrong scale and I would consider that as a bug.

That was my point. For clearance please see the POST/ GET requests for CreatingRule/GetRule

Configuration property is of Type INTEGER , multiple=true

![post](https://cloud.githubusercontent.com/assets/12597047/22502856/8678f6d0-e877-11e6-9c62-93484b5503c1.png)
![get](https://cloud.githubusercontent.com/assets/12597047/22502857/8683cfa6-e877-11e6-8478-60a0affd234b.png)

**Comment by danchom** [comment] 2017-02-27 13:18
May be this issue should be closed. The normalization of configuration properties without config description is merged but internal presentation will stay in big decimal not in the type of defined config description.

**Comment by maggu2810** [comment] 2017-02-27 14:19
Okay for me.

**Closed** 2017-02-27 17:59 UTC
Labels: Automation
