### ISSUE TITLE
response type for /rest/inbox changed from json to octet-stream

### ISSUE THREAD

**Issue by marin-k-marinov** [eclipse/smarthome#3802] opened 2017-07-05 07:37 UTC
After this change the Homebases on DEV started to return a response to `GET /rest/inbox` with 
`content-type: "application/octet-stream"`
instead of the expected until now
`content-type: "application/json"`

Is that a feature or a bug?

**Comment by sjka** [comment] 2017-07-05 08:15
What change are you referring to? And are you sure this is a problem of Eclipse SmartHome and not within QIVICON? To me it looks like this is out of scope here...

**Comment by htreu** [comment] 2017-07-05 08:28
I can confirm this issue. Here is the thing:
The `/rest/inbox` resource is configured to return a content-type `*/*` which from my understanding means it will respond with the content type requested by the client. Before ESH introduced JSON Streaming with #3500 this was `application/json` by default. Now when the client does not explicitly requests `application/json` it response with `application/octet-stream`.

**Comment by htreu** [comment] 2017-07-05 08:44
@marin-k-marinov please reopen this issue and change the description to a more general form like `response type for /rest/inbox changed from json to octet-stream`. tnx.

**Closed** 2017-07-05 10:41 UTC
