### ISSUE TITLE
Persisting disabled status not working

### ISSUE THREAD

**Issue by tolotos-rgu** [eclipse/smarthome#6840] opened 2019-01-12 13:00 UTC
Disabled z-wave things are enabled again after a reboot of openhab2 (v2.4.0).
I think the disabled state should be stored and handled at starttime. 

[https://community.openhab.org/t/disable-z-wave-things/63466](https://community.openhab.org/t/disable-z-wave-things/63466)

**Comment by kaikreuzer** [comment] 2019-01-12 14:06
Afaik, the disabled state is already persisted by the framework. Can you come up with a simple reproducible example that this is NOT the case? Something that does not require Z-Wave or other hardware for testing...

**Comment by tolotos-rgu** [comment] 2019-01-12 14:45
I used disabling only for my christmas outdoor switch. I switch it to disabled and remove the switch from the power outlet and store it together with the lights. After a reboot of openhabianpi the switch is enabled. 

I disabled a astro binding thing (astro:moon:local) and reboot my pi. The moon thing is enabled after the reboot.

**Comment by openhab-5iver** [comment] 2019-01-12 23:39
In case it's in some way related, I see the same behavior with rules marked as disabled being reenabled after an OH restart. S1493 and previous.

**Comment by kaikreuzer** [comment] 2019-01-14 08:49
Ok, unfortunately I can confirm the issue (seeing it with Things defined in files and with Things added through Paper UI likewise).
@YordanDZhelev Are you are of any issue with this? Is the feature working for you as expected?

**Comment by YordanDZhelev** [comment] 2019-01-14 08:52
@kaikreuzer I will retest asap.

**Comment by kaikreuzer** [comment] 2019-01-14 08:57
Thanks!

**Comment by FStolte** [comment] 2019-01-18 13:40
Looks like we simply forgot to remove the call that deletes the disabled entry from the database on thing removal. It was originally added there to avoid orphan entries of permanently deleted disabled things, but prevents the disabled status to be persisted after a reboot.

**Closed** 2019-01-30 08:49 UTC
