### ISSUE TITLE
LSP in VSCode does not work

### ISSUE THREAD

**Issue by udo1toni** [eclipse/smarthome#4601] opened 2017-11-21 11:18 UTC
### Informations about my hardware and software:

- openHAB server: xen vm 64bit 1GByte RAM, 1 Processor
  - os: debian stretch 64bit
  - java: Oracle 
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)
  - openHAB: openHAB Distribution Version Information
build-no        : Build #1088
online-repo     : https://openhab.jfrog.io/openhab/online-repo-snapshot/2.2
Repository        Version
openhab-distro  : 2.2.0-SNAPSHOT
smarthome       : 0.9.0-SNAPSHOT
openhab-core    : 2.2.0-SNAPSHOT
openhab1-addons : 1.11.0-SNAPSHOT
openhab2-addons : 2.2.0-SNAPSHOT
karaf           : 4.1.3
  - samba: Samba version 4.5.12-Debian
Protcoll is SMB2_10
- VSCode Client: Windows 7 professional 64bit, 8GByte RAM
  - VSCode: 
Version 1.18.1
Commit 929bacba01ef658b873545e26034d1a8067445e9
Datum 2017-11-16T18:32:36.023Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architektur x64
  - openHAB plugin: 0.3.0

When opening the conf folder by using the URI (`\\fqdn\openhab-conf\`) vscode gives an ERROR "Internal error, please look at the server's logs."

Server log is: 
```
11:18:40.037 [ERROR] [.eclipse.lsp4j.jsonrpc.RemoteEndpoint] - Internal error: java.lang.reflect.InvocationTargetException
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:53) ~[102:org.eclipse.lsp4j.jsonrpc:0.2.1.v20170706-0855]
        at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:105) [102:org.eclipse.lsp4j.jsonrpc:0.2.1.v20170706-0855]
        at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:203) [102:org.eclipse.lsp4j.jsonrpc:0.2.1.v20170706-0855]
        at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:139) [102:org.eclipse.lsp4j.jsonrpc:0.2.1.v20170706-0855]
        at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:149) [102:org.eclipse.lsp4j.jsonrpc:0.2.1.v20170706-0855]
        at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:77) [102:org.eclipse.lsp4j.jsonrpc:0.2.1.v20170706-0855]
        at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:84) [102:org.eclipse.lsp4j.jsonrpc:0.2.1.v20170706-0855]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
        at java.lang.Thread.run(Thread.java:748) [?:?]
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
        at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:51) ~[?:?]
        ... 11 more
Caused by: java.lang.IllegalArgumentException: URI has an authority component
        at sun.nio.fs.UnixUriUtils.fromUri(UnixUriUtils.java:53) ~[?:?]
        at sun.nio.fs.UnixFileSystemProvider.getPath(UnixFileSystemProvider.java:98) ~[?:?]
        at java.nio.file.Paths.get(Paths.java:138) ~[?:?]
        at org.eclipse.smarthome.model.lsp.internal.MappingUriExtensions.guessClientPath(MappingUriExtensions.java:94) ~[?:?]
        at org.eclipse.smarthome.model.lsp.internal.MappingUriExtensions.toUri(MappingUriExtensions.java:66) ~[?:?]
        at org.eclipse.xtext.ide.server.LanguageServerImpl.getBaseDir(LanguageServerImpl.java:225) ~[?:?]
        at org.eclipse.xtext.ide.server.LanguageServerImpl.initialize(LanguageServerImpl.java:176) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
        at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:51) ~[?:?]
        ... 11 more
```
Most interesting part is this:
```
Caused by: java.lang.IllegalArgumentException: URI has an authority component
```
Certainly the samba share is set to use user and password authentication.

When using a mapped windows share (`Q:\`, is set to `\\fqdn\openhab-conf\`) the VSCode ERROR stays the same, but the log is slightly another:
```
11:45:03.192 [INFO ] [del.lsp.internal.MappingUriExtensions] - Path mapping could not be done for 'file:///q%3A/', leaving it untouched
11:45:03.222 [ERROR] [.eclipse.lsp4j.jsonrpc.RemoteEndpoint] - Internal error: java.lang.reflect.InvocationTargetException
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:53) ~[102:org.eclipse.lsp4j.jsonrpc:0.2.1.v20170706-0855]
        at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:105) [102:org.eclipse.lsp4j.jsonrpc:0.2.1.v20170706-0855]
        at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:203) [102:org.eclipse.lsp4j.jsonrpc:0.2.1.v20170706-0855]
        at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:139) [102:org.eclipse.lsp4j.jsonrpc:0.2.1.v20170706-0855]
        at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:149) [102:org.eclipse.lsp4j.jsonrpc:0.2.1.v20170706-0855]
        at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:77) [102:org.eclipse.lsp4j.jsonrpc:0.2.1.v20170706-0855]
        at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:84) [102:org.eclipse.lsp4j.jsonrpc:0.2.1.v20170706-0855]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
        at java.lang.Thread.run(Thread.java:748) [?:?]
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
        at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:51) ~[?:?]
        ... 11 more
Caused by: java.lang.NullPointerException
        at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011) ~[?:?]
        at java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006) ~[?:?]
        at org.eclipse.xtext.resource.impl.ChunkedResourceDescriptions.setContainer(ChunkedResourceDescriptions.java:121) ~[?:?]
        at org.eclipse.xtext.ide.server.ProjectManager.lambda$createFreshResourceSet$5(ProjectManager.java:152) ~[?:?]
        at org.eclipse.xtext.xbase.lib.ObjectExtensions.operator_doubleArrow(ObjectExtensions.java:139) ~[?:?]
        at org.eclipse.xtext.ide.server.ProjectManager.createFreshResourceSet(ProjectManager.java:155) ~[?:?]
        at org.eclipse.xtext.ide.server.ProjectManager.lambda$newBuildRequest$4(ProjectManager.java:130) ~[?:?]
        at org.eclipse.xtext.xbase.lib.ObjectExtensions.operator_doubleArrow(ObjectExtensions.java:139) ~[?:?]
        at org.eclipse.xtext.ide.server.ProjectManager.newBuildRequest(ProjectManager.java:141) ~[?:?]
        at org.eclipse.xtext.ide.server.ProjectManager.doBuild(ProjectManager.java:111) ~[?:?]
        at org.eclipse.xtext.ide.server.ProjectManager.doInitialBuild(ProjectManager.java:107) ~[?:?]
        at org.eclipse.xtext.ide.server.BuildManager.doInitialBuild(BuildManager.java:138) ~[?:?]
        at org.eclipse.xtext.ide.server.WorkspaceManager.refreshWorkspaceConfig(WorkspaceManager.java:142) ~[?:?]
        at org.eclipse.xtext.ide.server.WorkspaceManager.initialize(WorkspaceManager.java:113) ~[?:?]
        at org.eclipse.xtext.ide.server.LanguageServerImpl.lambda$initialize$3(LanguageServerImpl.java:213) ~[?:?]
        at org.eclipse.xtext.ide.server.concurrent.RequestManager.runWrite(RequestManager.java:71) ~[?:?]
        at org.eclipse.xtext.ide.server.LanguageServerImpl.initialize(LanguageServerImpl.java:216) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
        at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:51) ~[?:?]
        ... 11 more
```
Most interesting part is now:
```
11:45:03.192 [INFO ] [del.lsp.internal.MappingUriExtensions] - Path mapping could not be done for 'file:///q%3A/', leaving it untouched
```
and therefor there is a null pointer exception, because there is no path set at all.

**Comment by jewesta** [comment] 2017-11-24 19:03
This is @jewesta from https://community.openhab.org/t/openhab-vs-code-extension-0-3-0/36228/28. Just thought I'd put my version of the error here for completeness' sake. I'm getting:

`2017-11-24 19:44:33.400 [INFO ] [el.lsp.internal.MappingUriExtensions] - Path mapping could not be done for 'file:///Users/jens/openHAB/openHAB-conf', leaving it untouched`

upon start of VS Code.

I am using the App Automounter to mount openhabian's SMB shares to a local folder on my Mac. Just to make sure this is not in some way the problem I disabled it and mounted manually via finder. It does not change the error, just the path. Which I guess is as expected:

`2017-11-24 19:57:58.971 [INFO ] [el.lsp.internal.MappingUriExtensions] - Path mapping could not be done for 'file:///Volumes/openHAB-conf', leaving it untouched`

Environment:

- MacBook Pro / High Sierra
- VS Code 1.18.1
- openHab plugin 0.3.0 (official)
- Raspberry Pi 3 / openhabian / #1094 

If I can do anything to help you resolving this, please just ask.

Thanks for all the great work!

**Comment by sjka** [comment] 2017-11-24 21:58
I have pushed #4626 which I think should fix the mapping problem with remote SMB shares - at leat in theory and on my windows/SMB setup. If there would be anybody following this issue with a development setup (i.e. Eclipse SmartHome within the IDE) who would like to try it out before it gets merged I'd be happy for any feedback!

**Closed** 2017-11-24 22:28 UTC
Labels: DSL

**Comment by kaikreuzer** [comment] 2017-11-24 23:23
Latest openHAB distro 1096 contains this fix!

**Comment by mhilbush** [comment] 2017-11-25 03:26
I installed 1096, and it does appear that this fix resolved the mapping problem when using SMB shares.

However, I was seeing all sorts of other errors as described here.  
https://community.openhab.org/t/jetty-update-karaf-4-1-3-upgrade-and-full-lsp-support/36354/66

I would've spent more time trying to diagnose what was happening, but this was my prod system, and I needed to revert to my most recent backup, which is based on build 1081.

**Comment by jewesta** [comment] 2017-11-25 08:59
Now on #1096. No more path mapping errors and no more exceptions on file open / file close. For the first time ever I'm seeing syntax errors being reported by VS Code! Wow. Thank you very much. This is great!

I am seeing the VS Code related errors @mhilbush reported as well. But they are probably errors that now appear because path mapping works. They are the direct results of actions within VS Code, so I do not see them as critical.

The following appears when autocompletion pops up by itself (not if I trigger it via Ctrl + Space):

```
[Error - 09:42:10] Request textDocument/completion failed.
  Message: Internal error, please look at the server's logs.
  Code: -32603 
```

Code:

<img width="687" alt="bildschirmfoto 2017-11-25 um 09 42 14" src="https://user-images.githubusercontent.com/25198212/33228939-45763908-d1c5-11e7-8009-96e063209de9.png">

Steps to reproduce:

- Place cursor right after the "r" of "var".
- Remove the "r" (backspace)
- Type "r"
- Wait for autocompletion to appear
- Autocompletion pops up finding the item "Voralarm". (see screenshot)
- Exception is logged

```
2017-11-25 09:46:42.065 [ERROR] [eclipse.lsp4j.jsonrpc.RemoteEndpoint] - Internal error: com.google.common.util.concurrent.ExecutionError: java.lang.NoClassDefFoundError: org/objectweb/asm/ClassReader
java.util.concurrent.CompletionException: com.google.common.util.concurrent.ExecutionError: java.lang.NoClassDefFoundError: org/objectweb/asm/ClassReader
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) [?:?]
	...
Caused by: com.google.common.util.concurrent.ExecutionError: java.lang.NoClassDefFoundError: org/objectweb/asm/ClassReader
	...
Caused by: java.lang.NoClassDefFoundError: org/objectweb/asm/ClassReader
	at org.eclipse.xtext.xbase.ide.types.ClasspathTypeDescriptor.forJarEntry(ClasspathTypeDescriptor.java:150) ~[?:?]
	at org.eclipse.xtext.xbase.ide.types.ClasspathScanner.loadJarDescriptors(ClasspathScanner.java:229) ~[?:?]
	at org.eclipse.xtext.xbase.ide.types.ClasspathScanner.loadDescriptors(ClasspathScanner.java:154) ~[?:?]
	at org.eclipse.xtext.xbase.ide.types.ClasspathScanner.lambda$getDescriptors$1(ClasspathScanner.java:83) ~[?:?]
	...
	at org.eclipse.xtext.xbase.ide.types.ClasspathScanner.getDescriptors(ClasspathScanner.java:85) ~[?:?]
	at org.eclipse.xtext.xbase.ide.types.ClasspathScanner.lambda$getBootClasspathDescriptors$2(ClasspathScanner.java:99) ~[?:?]
	at org.eclipse.xtext.xbase.lib.internal.FunctionDelegate.apply(FunctionDelegate.java:42) ~[?:?]
	...
	at org.eclipse.xtext.xbase.ide.contentassist.ClasspathBasedIdeTypesProposalProvider.createTypeProposals(ClasspathBasedIdeTypesProposalProvider.java:77) ~[?:?]
	at org.eclipse.xtext.xbase.ide.contentassist.XbaseIdeContentProposalProvider.completeJavaTypes(XbaseIdeContentProposalProvider.java:411) ~[?:?]
	at org.eclipse.xtext.xbase.ide.contentassist.XbaseIdeContentProposalProvider.completeJavaTypes(XbaseIdeContentProposalProvider.java:407) ~[?:?]
	at org.eclipse.xtext.xbase.ide.contentassist.XbaseIdeContentProposalProvider._createProposals(XbaseIdeContentProposalProvider.java:204) ~[?:?]
	at org.eclipse.xtext.xbase.ide.contentassist.XbaseIdeContentProposalProvider.createProposals(XbaseIdeContentProposalProvider.java:641) ~[?:?]
	at org.eclipse.xtext.ide.editor.contentassist.IdeContentProposalProvider.createProposals(IdeContentProposalProvider.java:94) ~[?:?]
	at org.eclipse.xtext.ide.server.contentassist.ContentAssistService.createProposals(ContentAssistService.java:108) ~[?:?]
	at org.eclipse.xtext.ide.server.contentassist.ContentAssistService.createCompletionList(ContentAssistService.java:73) ~[?:?]
	at org.eclipse.xtext.ide.server.LanguageServerImpl.lambda$completion$14(LanguageServerImpl.java:425) ~[?:?]
	at org.eclipse.xtext.ide.server.WorkspaceManager.doRead(WorkspaceManager.java:234) ~[?:?]
	at org.eclipse.xtext.ide.server.LanguageServerImpl.completion(LanguageServerImpl.java:427) ~[?:?]
	at org.eclipse.xtext.ide.server.LanguageServerImpl.lambda$completion$13(LanguageServerImpl.java:406) ~[?:?]
	at org.eclipse.xtext.ide.server.concurrent.RequestManager.lambda$runRead$2(RequestManager.java:116) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602) ~[?:?]
	... 5 more
```

I am also seeing osgi errors I've never seen before, which I'm guessing are unrelated to this issue.

```
2017-11-25 09:14:53.072 [ERROR] [org.openhab.binding.homematic       ] - Component descriptor entry 'OSGI-INF/*.xml' not found
2017-11-25 09:15:00.719 [ERROR] [org.openhab.binding.avmfritz        ] - Component descriptor entry 'OSGI-INF/*.xml' not found
```

**Comment by sjka** [comment] 2017-11-28 09:09
Thanks @jewesta for the detailed instructions!
I have created #4639 to track it.
