### ISSUE TITLE
Test failure(s): NtpOSGiTest

### ISSUE THREAD

**Issue by maggu2810** [eclipse/smarthome#2345] opened 2016-10-20 08:41 UTC
The build on the HIPP failed:
https://hudson.eclipse.org/smarthome/job/SmartHomeDistribution-Nightly/1387/

```text
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.eclipse.smarthome.binding.ntp.test.NtpOSGiTest
Tests run: 16, Failures: 1, Errors: 0, Skipped: 2, Time elapsed: 122.594 sec <<< FAILURE! - in org.eclipse.smarthome.binding.ntp.test.NtpOSGiTest
the dateTime channel is updated with the right time zone(org.eclipse.smarthome.binding.ntp.test.NtpOSGiTest) skipped
time is refreshed when string channel is linked(org.eclipse.smarthome.binding.ntp.test.NtpOSGiTest)  Time elapsed: 10.622 sec
if no time zone is set in the configuration, the dateTime channel is updated with the default one(org.eclipse.smarthome.binding.ntp.test.NtpOSGiTest)  Time elapsed: 10.115 sec
time is refreshed when dateTime channel is linked(org.eclipse.smarthome.binding.ntp.test.NtpOSGiTest)  Time elapsed: 10.124 sec
the status of a thing with string channel is updated with communication error, when unknown host is set in the configuraion(org.eclipse.smarthome.binding.ntp.test.NtpOSGiTest)  Time elapsed: 0.121 sec
the string channel is updated with the right formatting(org.eclipse.smarthome.binding.ntp.test.NtpOSGiTest)  Time elapsed: 10.247 sec  <<< FAILURE!
java.lang.AssertionError: The item was not of type StringType
Expected: is an instance of org.eclipse.smarthome.core.library.types.StringType
     but: <NULL> is a org.eclipse.smarthome.core.types.UnDefType
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:865)
	at org.junit.Assert$assertThat$0.callStatic(Unknown Source)
	at org.eclipse.smarthome.binding.ntp.test.NtpOSGiTest$_getItemState_closure4.doCall(NtpOSGiTest.groovy:421)
	at org.eclipse.smarthome.binding.ntp.test.NtpOSGiTest$_getItemState_closure4.doCall(NtpOSGiTest.groovy)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:292)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1015)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:39)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
	at org.eclipse.smarthome.test.OSGiTest.waitForAssert(OSGiTest.groovy:181)
	at org.eclipse.smarthome.test.OSGiTest.waitForAssert(OSGiTest.groovy)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:207)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:56)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:141)
	at org.eclipse.smarthome.binding.ntp.test.NtpOSGiTest.getItemState(NtpOSGiTest.groovy:416)
	at org.eclipse.smarthome.binding.ntp.test.NtpOSGiTest.this$3$getItemState(NtpOSGiTest.groovy)

if the property for formatting in the configuration of the string channel is null, the default formatting is used(org.eclipse.smarthome.binding.ntp.test.NtpOSGiTest)  Time elapsed: 10.079 sec
if no property for formatting is set in the configuration of the string channel, the default formatting is used(org.eclipse.smarthome.binding.ntp.test.NtpOSGiTest)  Time elapsed: 10.07 sec
if the property for formatting in the configuration of the string channel is empty string, the default formatting is used(org.eclipse.smarthome.binding.ntp.test.NtpOSGiTest)  Time elapsed: 10.07 sec
the calendar of the dateTime channel is updated with the right time zone(org.eclipse.smarthome.binding.ntp.test.NtpOSGiTest) skipped
the string channel is updated with the right time zone(org.eclipse.smarthome.binding.ntp.test.NtpOSGiTest)  Time elapsed: 10.08 sec
if no time zone is set in the configuration, the string channel is updated with the default one(org.eclipse.smarthome.binding.ntp.test.NtpOSGiTest)  Time elapsed: 10.063 sec
the string channel is updated on handleCommand(org.eclipse.smarthome.binding.ntp.test.NtpOSGiTest)  Time elapsed: 10.045 sec
the dateTime channel is updated on handleCommand(org.eclipse.smarthome.binding.ntp.test.NtpOSGiTest)  Time elapsed: 10.096 sec
if no time zone is set in the configuration, the calendar of the dateTime channel is updated with the default one(org.eclipse.smarthome.binding.ntp.test.NtpOSGiTest)  Time elapsed: 10.085 sec
the status of a thing with dateTime channel is updated with communication error, when unknown host is set in the configuraion(org.eclipse.smarthome.binding.ntp.test.NtpOSGiTest)  Time elapsed: 0.071 sec

Results :

Failed tests: 
  NtpOSGiTest.the string channel is updated with the right formatting:283->this$3$getItemState:-1->getItemState:416->OSGiTest.waitForAssert:-1->OSGiTest.waitForAssert:181 The item was not of type StringType
Expected: is an instance of org.eclipse.smarthome.core.library.types.StringType
     but: <NULL> is a org.eclipse.smarthome.core.types.UnDefType

Tests run: 16, Failures: 1, Errors: 0, Skipped: 2
```

Full log: [log.txt](https://github.com/eclipse/smarthome/files/541207/log.txt)

**Comment by maggu2810** [comment] 2016-10-20 08:44
@petarnv As the test has been written by you, can you have a look at?

**Comment by petarnv** [comment] 2016-10-20 11:52
Yes, I will look at it.

**Comment by petarnv** [comment] 2016-10-21 09:50
I saw that couple of builds have failed, because of the NTP Tests. I have pulled the latest changes, but I can't get this tests to fail. But judging from the log of builds on the HIPP, all the failures are caused by the fact that I can't get an item with type `StringType` from the item registry. On the other hand it is odd that I have no problem getting an item of type `DateTimeType`. I'm not sure yet what the problem is, but I will keep searching.

**Comment by maggu2810** [comment] 2016-10-21 10:05
Have you realized that message:

> the status of a thing with string channel is updated with communication error, when unknown host is set in the configuraion(org.eclipse.smarthome.binding.ntp.test.NtpOSGiTest)

**Comment by petarnv** [comment] 2016-10-21 10:22
Yes, but I don't think that a wrong host name may be the reason. When there is a wrong host name the thing is still online and the item registry is updated with the system time.

**Comment by kaikreuzer** [comment] 2016-10-21 20:03
The build is red since the beginning of this week now - it was only broken by introducing new tests (and not by breaking any existing ones), so I would think that we should deactivate it, if no solution can be found quickly.

**Comment by marcelrv** [comment] 2016-10-22 07:21
Strange indeed. When I did the testing ntptests ran fine in both Linux & Windows. 
@petarnv during testing I did have failures in other tests (i had to disable core.thing.test). Possibly that got fixed in the mean time, but broke the ntp tests

**Closed** 2016-10-23 17:41 UTC
