### ISSUE TITLE
[Sonos] Re-open {Fixes on UPnP infrastucture #4569} {UPnP action invocation results in an empty result, which sets the Thing to OFFLINE #4531}

### ISSUE THREAD

**Issue by kgoderis** [eclipse/smarthome#5460] opened 2018-04-24 21:00 UTC
Just bumped my operational system to  2.3.0-SNAPSHOT Build 1263  and I ran into exactly the problems described in the issues mentioned here above.

**Comment by kgoderis** [comment] 2018-04-24 21:46
When trying to replicate the problem in the ESH IDE, it was present at first, but after some time all sonos devices got "resolved" as being online. The JUNP version in the IDE is 2.3.0.201711021118, whereas the latest snapshot on Karaf reports 2.3.0 

@kaikreuzer you initially rooted the problem to the Jetty client. Just doing the same, I found that the IDE runs Jetty 9.3.22, whereas the SNAPSHOT contains 9.3.15. Time for another upgrade of the Jetty bundles? (At the time you bumped 9.3.14 to 9.3.15 I am not mistaken)

**Comment by maggu2810** [comment] 2018-04-25 11:56
The used Jetty bundles are part of the product setup -- in your case openHAB.
Karaf 4.2.0 is already out that uses Jetty 9.4.x (works for me in general).
openHAB still uses Karaf 4.1.x (AFAIK) -- to bump the Jetty version only or the whole Karaf the openHAB distro repo would be the correct place.

**Comment by kgoderis** [comment] 2018-04-25 16:52
@maggu2810 Tx - posted it here as the original Issues originated here, and because it is related to the Sonos binding. @kaikreuzer I am not an expert on Karaf, i.e. not my decision on Karaf 4.2.0, but to me the issue is severe enough to either bump in the short term, or find a short term workaround for openHAB. wdyt?

**Comment by kgoderis** [comment] 2018-04-25 16:56
@kaikreuzer FYI I get a bunch of these:

```
2018-04-25 18:54:18.930 [DEBUG] [org.jupnp.transport.Router          ] - Sending via TCP unicast stream: (OutgoingActionRequestMessage) POST http://192.168.0.179:1400/DeviceProperties/Control
2018-04-25 18:54:18.950 [INFO ] [org.jupnp.transport.spi.StreamClient] - Timeout of 10 seconds while waiting for HTTP request to complete, aborting: (OutgoingActionRequestMessage) POST http://192.168.0.165:1400/DeviceProperties/Control
```

Something fishy is going on indeed

**Comment by lolodomo** [comment] 2018-04-30 12:48
No, I have not seen this issue again. I restarted my OH server this morniong and my Sonos things are online. I am running snapshot 1262.

**Comment by J-N-K** [comment] 2018-04-30 17:42
@kaikreuzer, maybe I am wrong, bit I use OH snapshot 1256, which should already contain jetty 9.3.21, yet I see 9.3.15 in `bundle:list` (karaf shows 4.1.5). Maybe there is something wrong with the upgrade mechanism.

And even though I can't find the timeout error in my logs, I see my Play:1 thing going offline shortly after adding it:

```
19:22:08.998 [DEBUG] [org.jupnp.transport.Router           ] - Sending via TCP unicast stream: (OutgoingActionRequestMessage) POST http://192.168.1.253:1400/DeviceProperties/Control
19:22:09.066 [DEBUG] [org.jupnp.transport.Router           ] - Sending via TCP unicast stream: (OutgoingActionRequestMessage) POST http://192.168.1.253:1400/MediaRenderer/AVTransport/Control
19:22:18.214 [INFO ] [ome.event.ThingStatusInfoChangedEvent] - 'sonos:PLAY1:RINCON_949F3E050xxxxxxxx' changed from ONLINE to OFFLINE (COMMUNICATION_ERROR)
19:23:09.139 [INFO ] [ome.event.ThingStatusInfoChangedEvent] - 'sonos:PLAY1:RINCON_949F3E050xxxxxxxx' changed from OFFLINE (COMMUNICATION_ERROR) to OFFLINE (COMMUNICATION_ERROR): Der UPnP Speaker RINCON_949F3E050xxxxxxx ist nicht registriert.
``` 

The thing never turns online again until I use the Sonos discovery. Then it immediately comes online but switches to offline shortly after.

**Comment by kaikreuzer** [comment] 2018-04-30 21:07
@J-N-K You are right, there seems to be some weird mix of Jetty versions:
```
openhab> list -s -t 0| grep jetty                                                                                                                                                                            
 72 │ Active   │  30 │ 9.3.21.v20170918       │ org.eclipse.jetty.client
 73 │ Active   │  30 │ 9.3.21.v20170918       │ org.eclipse.jetty.continuation
 74 │ Active   │  30 │ 9.3.21.v20170918       │ org.eclipse.jetty.deploy
 75 │ Active   │  30 │ 9.3.21.v20170918       │ org.eclipse.jetty.http
 76 │ Active   │  80 │ 9.3.15.v20161220       │ org.eclipse.jetty.io
 77 │ Active   │  30 │ 9.3.21.v20170918       │ org.eclipse.jetty.io
 78 │ Active   │  30 │ 9.3.21.v20170918       │ org.eclipse.jetty.jaas
 79 │ Active   │  30 │ 9.3.21.v20170918       │ org.eclipse.jetty.jndi
 80 │ Active   │  30 │ 9.3.21.v20170918       │ org.eclipse.jetty.plus
 81 │ Active   │  30 │ 9.3.21.v20170918       │ org.eclipse.jetty.rewrite
 82 │ Active   │  30 │ 9.3.21.v20170918       │ org.eclipse.jetty.security
 83 │ Active   │  30 │ 9.3.21.v20170918       │ org.eclipse.jetty.security.jaspi
 84 │ Active   │  30 │ 9.3.21.v20170918       │ org.eclipse.jetty.server
 85 │ Active   │  30 │ 9.3.21.v20170918       │ org.eclipse.jetty.servlet
 86 │ Active   │  30 │ 9.3.21.v20170918       │ org.eclipse.jetty.servlets
 87 │ Active   │  80 │ 9.3.15.v20161220       │ org.eclipse.jetty.util
 88 │ Active   │  30 │ 9.3.21.v20170918       │ org.eclipse.jetty.util
 89 │ Active   │  30 │ 9.3.21.v20170918       │ org.eclipse.jetty.util.ajax
 90 │ Active   │  30 │ 9.3.21.v20170918       │ org.eclipse.jetty.webapp
 91 │ Active   │  80 │ 9.3.15.v20161220       │ org.eclipse.jetty.websocket.api
 92 │ Active   │  80 │ 9.3.15.v20161220       │ org.eclipse.jetty.websocket.common
 93 │ Active   │  30 │ 9.3.21.v20170918       │ org.eclipse.jetty.xml
179 │ Active   │  20 │ 2.3.0.201804261315     │ org.openhab.io.jetty.certificate
183 │ Active   │  30 │ 6.0.9                  │ org.ops4j.pax.web.pax-web-jetty
```
I hope that this can be resolved on openHAB side - I have created https://github.com/openhab/openhab-distro/issues/692 for it - I therefore suggest to close this issue here.

**Closed by kaikreuzer** 2018-04-30 21:07 UTC
Labels: Binding-Sonos

**Comment by derM0j0** [comment] 2018-07-04 15:40
test

**Comment by derM0j0** [comment] 2018-07-04 15:57
Hi,

i recently upgarded my System to 2.3.0 Release, and ever since i keep encountering this issue. 
My Sonos Things go Offline with Communication error for a couple of minutes. After about 12-24h after reboot all Sonos Things are offline. I have digged though all the threads concerning proplems with UpNP and Sonos Thing going offline as a result i reinstalled the Openhab multiple times and 2 Days ago upgarded to 2.4.0-Snapshot BUILD #1308. Nothing has helped.  My Setup:

>list -s -t 0 | grep jetty --> shows all jetty versions as  9.3.21.v20170981
>JUPnP Libary 2.4.0
>Eclipse UPNP Discovery and Transport = 0.10.0.201806271317

Bindings:
> 	Sonos Binding
> 	LG TV Binding
> 	AVM FRITZ!Box Binding
> 	Network Binding
> 	MQTT Binding
> 	MapDB Persistence

I keep seeing following Error Flow for all my Sonos Speaker:

`2018-07-03 18:50:55.722 [WARN ] [org.jupnp.transport.spi.StreamClient] - HTTP request failed: (OutgoingActionRequestMessage) POST http://192.168.178.102:1400/DeviceProperties/Control (Connect Timeout)/n
2018-07-03 18:50:55.826 [hingStatusInfoChangedEvent] - 'sonos:PLAYBAR:wz' changed from ONLINE to OFFLINE (COMMUNICATION_ERROR): The Sonos player RINCON_000E58B2D0C101400 is not available in local network.
2018-07-03 18:51:03.009 [WARN ] [org.jupnp.transport.spi.StreamClient] - HTTP request took a long time (7253ms): (OutgoingSubscribeRequestMessage) SUBSCRIBE http://192.168.178.102:1400/GroupManagement/Event
2018-07-03 18:51:55.869 [hingStatusInfoChangedEvent] - 'sonos:PLAYBAR:wz' changed from OFFLINE (COMMUNICATION_ERROR): The Sonos player RINCON_000E58B2D0C101400 is not available in local network. to ONLINE
`

When i switch the SD card to my previous System running openhab 2.1. Release and 2.2.0 Jupnp all the Communication related Errors are gone. (although i have a issue with loosing my config upon reboot)

The issue is on openhab side and all fixes i have seen so far are not helping. 

Should i open a new Threat with this or can you point me to the proper fix?

Saludso M0j0
