### ISSUE TITLE
No handler for command 'things' was found.

### ISSUE THREAD

**Issue by kgoderis** [eclipse/smarthome#760] opened 2015-12-20 15:56 UTC
osgi> smarthome things
No handler for command 'things' was found.

This just happened after a regular restart of the OH2/ESH runtime. What could be causing this? The runtime is operating correctly, all Things are instantiated (as well as ThingHandlers).

**Comment by kgoderis** [comment] 2015-12-20 15:57
Oh... and the handler for "inbox" is also missing

**Comment by kgoderis** [comment] 2015-12-20 16:06
ahum. solved by completely removing anything that is in ../userdata. 

Is this due to some stuff stored in mapdb, linked to inbox ?

**Comment by kaikreuzer** [comment] 2015-12-20 19:00
No, this should not be related to anything in userdata...
Anyhow, as the problem is solved, I close this issue. If it occurs again (and best in a reproducible way), feel free to reopen.

**Closed by kaikreuzer** 2015-12-20 19:00 UTC
