### ISSUE TITLE
Duplicated entry after modifying config in text based mode

### ISSUE THREAD

**Issue by MageGH** [eclipse/smarthome#2831] opened 2017-01-15 20:54 UTC
Original entry:
Group GF_Wardrobe    "Wardrobe"      \<bath\>  (gGF)
Modified entry:
Group GF_Wardrobe    "Wardrobe"      \<wardrobe\>  (gGF)

On the Basic UI the entry will be duplicated and the duplication can be seen in the SmartHome-Designer also.

**Comment by kaikreuzer** [comment] 2017-01-15 21:14
Looks like a duplicate of https://github.com/eclipse/smarthome/issues/637.

**Closed by kaikreuzer** 2017-01-15 21:14 UTC
Labels: duplicate
