### ISSUE TITLE
Rule deserialization broken

### ISSUE THREAD

**Issue by maggu2810** [eclipse/smarthome#5884] opened 2018-07-09 19:12 UTC
IMHO #4468 has broken the storage mechanism for rules.

See https://github.com/eclipse/smarthome/pull/4468#issuecomment-403564760

**Comment by maggu2810** [comment] 2018-07-09 19:58
A simple demonstration: https://github.com/maggu2810/smarthome/commit/a7610cbc9012c1aa0a986b02153e71193bba08fd

The `serializeDeserialize` already breaks the test.

Shouldn't stuff that is added to our storage be implemented using simple DTOs?
So, not as an interface but as a class?

We don't use interfaces for `Things`, why do we want to use one for `Rule`, `Trigger`, ...

**Comment by kaikreuzer** [comment] 2018-07-10 22:17
> Shouldn't stuff that is added to our storage be implemented using simple DTOs?

Yes, where ever serialisation is done, the entities should be mapped to the according DTOs - this step clearly seems to be missing in your demo (you need to call `RuleDTOMapper.map(rule)` before passing it to GSON).

> We don't use interfaces for Things

Which we should (see the problems with consumers calling all the setter methods on it despite the fact that they must not).

> why do we want to use one for Rule, Trigger, ...

Because the clean up this time happened first on the automation part. The ´Thing` class was once introduced in the hope that we do not need DTOs, but that we can use the POJO for serialisation. The same was originally the idea with the `Rule` class. In both cases, we learned that we need dedicated DTOs and have introduced them, so there is imho no valid reason to keep the entities as classes instead of interfaces - and we are offering builders for constructing instances in all cases.

**Comment by maggu2810** [comment] 2018-07-11 05:16
Would be great if we don't need that changes. Perhaps I miss some fundamental point.
My findings have been that no old rule has been able to be loaded again.

Rules that have been saved in front of your changes and stored by our mapdb storage will be loaded after the changes by the mapdb storage again.

Let's have a look at:
https://github.com/eclipse/smarthome/blob/447b2d6/bundles/storage/org.eclipse.smarthome.storage.mapdb/src/main/java/org/eclipse/smarthome/storage/mapdb/internal/MapDbStorage.java#L145

The `valueTypeName` is set to `org.eclipse.smarthome.automation.Rule` that has been the class before and the interface now.

There are two situations:

* save and restore rules after your changes has been done
Can you point me to the place a "map to DTO" is called  in front of storing the rule ot the mapdb (and "map from DTO" is called on restoring the rule from the mapdb)?

* restore rules after your changes that has been stored in front of your changes
How can this work if `valueTypeName` is set to `org.eclipse.smarthome.automation.Rule` and not to the `DTO` class?

**Comment by maggu2810** [comment] 2018-07-11 07:15
Let's have a look at the situation after the changes has been merged:

> Yes, where ever serialisation is done, the entities should be mapped to the according DTOs

The `ManagedRuleProvider` does not override the "internal to persistent mapping" methods (and reverse but uses the "identity" of `DefaultAbstractManagedProvider`.

```
    protected abstract E toElement(@NonNull String key, @NonNull PE persistableElement);
    protected abstract PE toPersistableElement(E element);
```

So it seems to me that also the current implementation does not use the DTOs to store the elements.

**Comment by kaikreuzer** [comment] 2018-07-11 13:31
> So it seems to me that also the current implementation does not use the DTOs to store the elements.

This sounds plausible. Could you or @adimova or @sjka come up with an PR as a fix? Do you agree that such a fix would render #5888 unnecessary?

**Comment by maggu2810** [comment] 2018-07-11 13:42
If the rules are not stored and restored (after a fix has been created) using the DTOs, I still don't see how it solve the deserialization of previously created rules in the MapDB storage (see comment above).

**Comment by maggu2810** [comment] 2018-07-11 15:37
Compatibility:
* the class / interface name differs
* the serialized data differs because the `Configuration` of `Rule`, `Trigger`, `Action` and `Condition` previously contained the member `properties` that contains the configuration itself. Now the configuration is stored without an additional member properties

So, it mapping the "value type name" is not enough, we need also to "fix" the "value as string" as we need to remove the properties and merge that childs to the configuration...

But where should this code be placed?

A simple hack would be:
https://github.com/maggu2810/smarthome/commit/fffe6eb19a0fd6a28c9364a69f897491650aca77

**Comment by kaikreuzer** [comment] 2018-07-23 08:20
> As it is said in #5884 (comment) we should use the DTO objects instead of the automation objects, but this breaks the compatibility.

I would consider it a flaw that the DTOs weren't used for it so far - it seems to be the much better option.

My very strong preference would be to not squeeze the migration logic into the framework code itself - my fear is that this can quickly result in complex and hardly manageable code, which only addresses the fact that we did some wrong decisions in the past.
If anyone needs a solution for migrating old data, could that be potentially done as a completely external logic like a migration script?

Wrt the incompatibilities in the ConfigDescriptionParameter - this is indeed not in sync, which is imho a problem not only for the rule engine:

> The first on is that the defaultValue is annotated with @SerializedName("default") in ConfigDescriptionParameter and it is not in ConfigDescriptionParameterDTO.

Hm, I once tried to fix this with https://github.com/eclipse/smarthome/pull/2842, but that was closed in favor of https://github.com/eclipse/smarthome/pull/3612, which seemed to have failed to correctly fix it - I do not know whether this was on purpose, probably only @htreu can tell... As we have "default" in the XML serialisation, I would strongly suggest to do the same for the JSON serialisation and thus introduce the `@SerializedName("default")` here.

> The second one is that ConfigDescriptionParameter has a field step but ConfigDescriptionParameterDTO has stepsize instead.

This indeed is an ugly mix here. The `ConfigDescriptionParameterBuilder` also has a `withStepSize`, while our [documentation](https://www.eclipse.org/smarthome/documentation/development/bindings/xml-reference.html#xml-structure-for-configuration-descriptions) for the XML uses `step` (as the XML parser does not parse to the DTOs but directly to the POJOs for historic reasons). I'd suggest to change this field to "step" in the DTO as well.

**Comment by maggu2810** [comment] 2018-07-23 08:47
If the migration of old data is left to the solution, I would prefer to not use `@SerializedName("default")` but change the name of the member variable so a one to one mapping could be used. The annotation is Gson specific and should not be part of a implementation agnostic DTO.

**Comment by kaikreuzer** [comment] 2018-07-23 09:13
> but change the name of the member variable so a one to one mapping could be used. 

Well, we cannot change it to "default" as this is a Java keyword. And "default" is used in our XML serialisation and I doubt we can easily change this as it is used in every binding already. And having different serialisation for XML and JSON should imho be avoided. I agree that Gson specific annotation is not nice, but as long as we declare GSON to be the used library for JSON serialisation, this could be acceptable. After all, we also have a specific mapping in our XML parser.

**Comment by adimova** [comment] 2018-07-23 11:03
> And having different serialisation for XML and JSON should imho be avoided.

I agree, if we change the "default" to "defaultValue" this will break the JSON schemas for automation objects as all particular json file containing such resources

**Comment by maggu2810** [comment] 2018-07-23 11:18
Just if we ever consider to use a JSON (de)serialization API and custom implementations e.g. one for Gson:
Gson supports the [configuration] of a [FieldNamingStrategy].
It should be relative "simple" to translate every field using the name "defaultValue" to "default" or use a custom annotation. An example about a custom strategy can be found here: https://stackoverflow.com/a/43518439/7546824 (but that is much more advanced than we ever need).

[configuration]: https://google.github.io/gson/apidocs/com/google/gson/GsonBuilder.html#setFieldNamingStrategy-com.google.gson.FieldNamingStrategy-
[FieldNamingStrategy]: https://google.github.io/gson/apidocs/com/google/gson/FieldNamingStrategy.html

**Comment by kaikreuzer** [comment] 2018-07-24 15:38
@maggu2810 That is an interesting feature, but I fail to understand what you are trying to suggest.
Would you be fine with adding the annotation to the DTO? Or shall we instead implement a FieldNamingStrategy? Or are you completely against introducing GSON specific stuff in the DTOs?

**Comment by kaikreuzer** [comment] 2018-07-24 16:37
What irritates me is that FieldNamingStrategy is also a GSON specific class, so we are not having any GSON-independent solution with that either.
Ok, it would not be within the DTO itself, but I wonder whether this is actually a good thing - at least, with the annotation, anyone debugging the code would directly clearly see what is happening. Hiding it in a FieldNamingStrategy class can be rather surprising, don't you think? I for myself would be pretty confused to see the DTO but find some different JSON on the REST API - the annotation would be an excellent hint for humans.

**Comment by kaikreuzer** [comment] 2018-07-26 07:38
Instead of the annotation, we could of course also leave a simple comment in the DTO.
So up to you, what solution you prefer as long as we agree to use "default" for the serialised version!

**Comment by maggu2810** [comment] 2018-07-26 08:18
In the long run the `FieldNamingStrategy` should be the more portable solution. I cannot judge how much changes of the current code base it needs. Perhaps we could also move that change to #5856

**Comment by maggu2810** [comment] 2018-07-26 08:19
In the long run the `FieldNamingStrategy` should be the more portable solution. I cannot judge how much changes of the current code base it needs. Perhaps we could also move that change to #5856

@flaviocosta-net Do you consider the usage of `FieldNamingStrategy` for your GSON wrapper implementation? How do you want to handle the `@SerializedName` annotation for other implementations?

**Comment by adahmen** [comment] 2018-12-23 10:02
I upgraded my openhab installation yesterday from 2.3 stable to 2.4 stable and all my rules are gone :-( 
I think it's because of this discussion / change.

And I have this kind of error message in my log:
`2018-12-23 10:52:50.064 [ERROR] [me.storage.json.internal.JsonStorage] - Couldn't deserialize value 'org.eclipse.smarthome.storage.json.internal.StorageEntry@ccb11a'. Root cause is: Unable to invoke no-args constructor for interface org.eclipse.smarthome.automation.Rule. Register an InstanceCreator with Gson for this type may fix this problem.`

What can I do to reanimate my rules?

**Comment by maggu2810** [comment] 2018-12-24 08:12
I have added this code into my systems do be able to load old and new rules:
https://github.com/maggu2810/smarthome/commit/5ca7a0816b271b155f919a14b01d3fce77fc49ad

**Comment by maggu2810** [comment] 2018-12-24 09:34
Hi @adahmen,
you need to consider that Eclipse SmartHome is a framework that is used by different products.
Which feature of the framework is used in which version, with or without modifications or used at all is in the responsibility of the product.

See also Kai's comment above:

> My very strong preference would be to not squeeze the migration logic into the framework code itself - my fear is that this can quickly result in complex and hardly manageable code, which only addresses the fact that we did some wrong decisions in the past.
If anyone needs a solution for migrating old data, could that be potentially done as a completely external logic like a migration script?

I agree that such a migration logic cannot really be added to the framework itself, otherwise there exists  more migration logic then remaining code, some days (and most of the versions we migrate from is not used by products at all).

So, why there has been no migration support should be discussed at the openHAB community forum.
But I assume the answer is pretty easy:
The automation engine has AFAIK an experimental feature only without any guarantees.
But let's answer this question at other places from guys with more knowledge.

**Comment by adahmen** [comment] 2018-12-24 10:47
OK, will move the discussion to the OpenHAB forum.
And yes, I agree that the answer will be "No" :-)
But at least there should be some information how to delete the old rules ....
They should not remain inside the OpenHAB installation.

**Comment by MrCupola** [comment] 2019-01-11 01:51
> I have added this code into my systems do be able to load old and new rules:
> [maggu2810@5ca7a08](https://github.com/maggu2810/smarthome/commit/5ca7a0816b271b155f919a14b01d3fce77fc49ad)

Sorry to ask, but I'm not a big expert here, but how to use the code to load old rules?

**Comment by maggu2810** [comment] 2019-01-12 14:01
If you don't know what to do, it is perhaps no option for you.
You need to merge that code into the code base and build the changed bundles yourself.
I assume it could be simpler for you to recreate the rules.

**Comment by MrCupola** [comment] 2019-01-12 15:05
> If you don't know what to do, it is perhaps no option for you.
> You need to merge that code into the code base and build the changed bundles yourself.
> I assume it could be simpler for you to recreate the rules.

Yep, absolutely, thanks for your time.
Need to study a little more to be at least aware of how it works

**Closed** 2019-04-18 19:30 UTC
Labels: Automation, Critical

**Comment by Narasingha123** [comment] 2019-08-08 14:18
Which version to use for the mentioned issue ? I am using ESH 0.10.0-SNAPSHOT.

Rules are created and i am able to GET as well ,but not able to delete/update the rules.

org.eclipse.smarthome.storage.json.internal.JsonStorage deserialize] - Couldn’t deserialize value ‘org.eclipse.smarthome.storage.json.internal.StorageEntry@352def97’. Root cause is: Unable to invoke no-args constructor for interface org.eclipse.smarthome.automation.Trigger. Register an InstanceCreator with Gson for this type may fix this problem.
2019-08-08 12:34:58.265 [WARNING] [org.eclipse.smarthome.core.common.registry.AbstractManagedProvider update] - Could not update element with key 18d3f965-f6f1-4a0f-98ad-942f4b6b0b39 in ManagedRuleProvider, because it does not exists.
2019-08-08 12:34:58.265 [INFO ] [org.eclipse.smarthome.automation.rest.internal.RuleResource update] - Received HTTP PUT request for update at ‘rules/18d3f965-f6f1-4a0f-98ad-942f4b6b0b39’ for the unknown rule ‘18d3f965-f6f1-4a0f-98ad-942f4b6b0b39’.  

Thanks in advance.
