### ISSUE TITLE
BaseBridgeHandler.childHandlerInitialized will not be called if the bridge will be configured at runtime

### ISSUE THREAD

**Issue by mgeramb** [eclipse/smarthome#5215] opened 2018-03-10 10:46 UTC
**Steps to reproduce:**
Create a bridge device in PaperUI
Create a child device in PaperUI, but do not select the bridge
Open the child device configuration again and select now the bridge

**Expected result:**
The function childHandlerInitialized of the bridge will be called after the initialize function of child was called

**Current result:**
Only the initialize function of the child thing will be called.

**Comment by maggu2810** [comment] 2018-03-12 11:13
Hm, I would expect the same result as you mentioned.
@sjka WDYT?

**Comment by sjka** [comment] 2018-03-13 10:39
Yes, me too. Sounds like a bug to me.

**Comment by sjka** [comment] 2018-03-13 14:30
I did a little further analysis. There are two options:

a)
the thing handler _was_ successfully initialized before because it could handle the missing bridge situation gracefully and went ONLINE. Then the bridge handler is _not_ informed _correctly_ as the child handle won't be initialized again. It gets informed about the updated thing instead. All good, works a designed.

b)
the thing handle failed during the initialize and threw an exception, the thing went into `UNINITIALIZED/HANDLER_INITIALIZING_ERROR`. In this case, the framework attempts to initialize the handler. However, there is glitch in there - the handler was created before with the "old" thing, and therefore we  run into this situation:

https://github.com/eclipse/smarthome/blob/ec3cc58a493da1293c166513928ce92b8c85eeff/bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingManager.java#L571-L574

As a result, the thing manager updates the wrong thing.

**Comment by sjka** [comment] 2018-03-13 14:40
I have pushed a fix to be reviewed. Thanks again for report this with such clear steps how to reproduce it! It helped me to understand "some weird behavior" which was observed at times.

**Comment by mgeramb** [comment] 2018-03-13 16:25
Thanks for your quick help!

**Closed** 2018-03-14 10:35 UTC
Labels: Core, bug
