### ISSUE TITLE
[digitalstrom]

### ISSUE THREAD

**Issue by maxx92** [eclipse/smarthome#5594] opened 2018-05-20 10:13 UTC
I got following error message when trying to remove a "offline" item:

java.lang.NullPointerException: null
	at org.eclipse.smarthome.binding.digitalstrom.handler.BridgeHandler.childThingRemoved(BridgeHandler.java:445) [218:org.eclipse.smarthome.binding.digitalstrom:0.10.0.b1]
	at org.eclipse.smarthome.binding.digitalstrom.handler.SceneHandler.handleRemoval(SceneHandler.java:114) [218:org.eclipse.smarthome.binding.digitalstrom:0.10.0.b1]
	at org.eclipse.smarthome.core.thing.internal.ThingManager$7.run(ThingManager.java:821) [116:org.eclipse.smarthome.core.thing:0.10.0.b1]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:?]

**Comment by maxx92** [comment] 2018-05-20 10:14
Are these numerous headaches coming from the digitalstrom server or from the binding? To compare: my homematic binding works like a charm...

**Comment by 9037568** [comment] 2018-05-20 16:01
The errors are from the binding, but they could be being caused by something the server is doing wrong (or just differently than the binding expects)

**Comment by triller-telekom** [comment] 2018-05-23 09:46
@MichaelOchel Can you please have a look at this, since you wrote large parts of that binding? Thanks!

**Comment by MichaelOchel** [comment] 2018-06-03 17:01
I think that this NullPointerException is already fixed with #3182. The stable version of openHAB 2.2 does not have included this PR.

**Comment by triller-telekom** [comment] 2018-06-04 12:07
@maxx92 Can you confirm that this NPE is gone if you update to the newest openHAB 2.3 release which was released a couple of days ago? If so, can you please close this issue with a comment that it is fixed? Thanks!

**Comment by maxx92** [comment] 2018-06-04 12:32
Hello all. I wish I could confirm but I cannot as since last week when I updated to OH2.3, the digitalstrom binding stopped working. I am still desperately waiting for the crucial tip to get me going again...[https://github.com/eclipse/smarthome/issues/5651#issuecomment-394176695](url)

**Comment by triller-telekom** [comment] 2018-06-04 13:06
The comment you are linking to is gone, or at least its a dead link, can you fix it please?

**Comment by kaikreuzer** [comment] 2018-08-21 16:57
According to https://github.com/eclipse/smarthome/issues/5594#issuecomment-394175882, the exception that is described here has been fixed, so I'd suggest to close this issue.

**Closed by kaikreuzer** 2018-08-21 16:57 UTC
Labels: Binding-Digitalstrom
