### ISSUE TITLE
Rule filenames with underscores

### ISSUE THREAD

**Issue by KidSquid1** [eclipse/smarthome#4532] opened 2017-11-12 15:14 UTC
I have encountered a situation where a rule file containing an underscore character will not get processed.

I've posted this issue on the OH forum, 
[https://community.openhab.org/t/astro-rule-weirdness/35709/13](url)
along with the OH documentation repository 
**[https://github.com/openhab/openhab-docs/issues/561#issuecomment-343742501](url)**
as I initially was under the impression that any rule file containing an underscore would not work.

Further testing has shown some rule files with an underscore will process others will not.

My testing showed that by using a simple rule.

```
rule "pingMe"

when
	// Every 1 minute...
	Time cron "0 0/1 * * * ?"
then
       // Place the following entry in my log file
	logInfo("pingMe.rules","pingMe just pinged me.")
end
```

Rule without the underscore in the name....
```
2017-11-11 20:20:51.978 [INFO ] [el.core.internal.ModelRepositoryImpl] - Loading model 'pingme.rules'
2017-11-11 20:20:52.011 [INFO ] [el.core.internal.ModelRepositoryImpl] - Refreshing model 'pingme.rules'
2017-11-11 20:21:00.005 [INFO ] [.smarthome.model.script.pingMe.rules] - pingMe just pinged me without an underscore.
2017-11-11 20:22:00.001 [INFO ] [.smarthome.model.script.pingMe.rules] - pingMe just pinged me without an underscore.
```

Renaming the rule with an underscore in the name worked as well.

```
2017-11-11 20:24:46.828 [INFO ] [el.core.internal.ModelRepositoryImpl] - Refreshing model 'ping_me.rules'
2017-11-11 20:25:00.005 [INFO ] [.smarthome.model.script.pingMe.rules] - pingMe just pinged me with an underscore.
```
So this seems to indicate in this situation that the underscore is not an issue.....

Yet my original rule of:

```
rule "Holiday Mode On"
when
    Channel 'astro:sun:home:set#event' triggered START
then
if (VIR_HolidaySwitch.state==ON)
{
    HolidayRemote1.sendCommand(ON)
    FntPatioPlug.sendCommand(ON)
    WalkGatePlug.sendCommand(ON)
    GarageHolidaySwitch.sendCommand(ON)
}
end

rule "Holiday Mode Off"
when
    Time cron "0 1 0 1/1 * ? *" 
then
if (VIR_HolidaySwitch.state==ON)
{
    HolidayRemote1.sendCommand(OFF)
    FntPatioPlug.sendCommand(OFF)
    WalkGatePlug.sendCommand(OFF)
    GarageHolidaySwitch.sendCommand(OFF)
}	
end

```
Runs fine when the file is named **sunsetholiday.rules**, yet will _NOT_ run when named **sunset_holiday.rules**
Could it be something with ASTRO?

**Comment by sjka** [comment] 2017-11-13 15:07
I cannot reproduce this, not even with your second example. The job gets scheduled as expected and when altering the timer to run every 2 second it also does it nicely (with complaining about the missing items on my system, of course).

What does your log say at times when it is _not_ working?

**Comment by KidSquid1** [comment] 2017-11-16 17:51
Unfortunately nothing gets logged at all when the rule does not run.  @sjka what version of OH are you currently running?

**Comment by triller-telekom** [comment] 2017-11-24 12:57
@KidSquid1 He has probably used the current master branch from ESH to test this.

But I am wondering if you renamed the rules file while Oh was running? If so, could you please test your rule, if its working, stop OH, rename the rule and start OH again?

I am assuming this bug might be a duplicate of #4619. Are you also doing the renaming on a remote file system like a samba share?

**Comment by triller-telekom** [comment] 2018-07-12 14:54
@KidSquid1 Since we haven't heard from you, is this still an issue for this or would you like to close it?

**Comment by triller-telekom** [comment] 2018-08-03 12:58
@kaikreuzer can you please close this issue?

**Closed** 2018-08-03 13:08 UTC
