### ISSUE TITLE
org.eclipse.smarthome.core.scheduler.CronExpression error in dayOfWeek

### ISSUE THREAD

**Issue by schnidrig** [eclipse/smarthome#3912] opened 2017-07-30 13:23 UTC
With the current implementation, the expression: `* * * ? * SAT,SUN *` does not match July 30 2017 which is wrong. (isSatisfiedBy returns false)

I think the error is at: https://github.com/eclipse/smarthome/blob/master/bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/scheduler/CronExpression.java#L1097.

It should rather read: 

    for (int i = 1; i <= 6; i++) {

**Comment by maggu2810** [comment] 2017-07-31 17:39
@kgoderis Can you have a look at?

**Comment by kgoderis** [comment] 2017-08-01 18:25
@schnidrig @maggu2810 I am not sure about that, because the Java doc for Calendar states : "When setting or getting the WEEK_OF_MONTH or WEEK_OF_YEAR fields, Calendar must determine the first week of the month or year as a reference point. The first week of a month or year is defined as the earliest seven day period beginning on getFirstDayOfWeek() and containing at least getMinimalDaysInFirstWeek() days of that month or year"

Although at first sight one could think that July 2017 contains 6 weeks -  because it runs over 6 weeks (with first day of the week being Monday) - but according to the API doc, you can not have more than 5 weeks in a month. 

Did you test the code with the above change, or did you discover the issue through the debugger? 

[I am a bit short on time to fully test it now - last week of work and then 3 weeks off]

**Comment by schnidrig** [comment] 2017-08-02 15:19
Well, I don't know what the solution is. I noticed, that the cron expression I had did not work for July 2017. I searched for the error in the debugger. When I changed the code (replaced 5 with 6) then my expression worked. I don't know if this breaks anything else though.

**Comment by kgoderis** [comment] 2017-08-02 18:28
@schnidrig well, if that works then that would mean that the implementation of Calendar is somewhat different from the doc. For me it is ok to patch as you suggest, given that in the algorithm the invalid/excessive candidate dates that are added are removed from the list of candidate dates anyways

**Comment by schnidrig** [comment] 2017-08-03 07:06
Sounds good to me.

**Comment by kaikreuzer** [comment] 2017-08-03 08:45
FTR: Since today, our unit tests even stumble across that issue as it tests Dec 31, where December also has 6 weeks. Our [build is RED](https://hudson.eclipse.org/smarthome/job/SmartHomeDistribution-Nightly/2038/testReport/junit/org.eclipse.smarthome.core.scheduler/CronExpressionTest/findNext/), so we urgently need a fix!

**Comment by afuechsel** [comment] 2017-08-03 09:28
Not sure, if this is related, but the CronExpressionTest#findNext fails for each build less than 150 days before year's end. For now I will disable this test, but this needs to be fixed definitely. After debugging a little bit I found out, that CronExpression#applyExpressionParts is not able to calculate dates, that would require a change to the next year, it fails e.g. for `0 0 0 ? * *'` and `2017 Dec 31, 23:01`.

**Comment by kaikreuzer** [comment] 2017-08-03 09:34
@kgoderis Any chance you could have a quick look as you know the mechanisms best and might have an idea how to address it?

**Comment by kgoderis** [comment] 2017-08-06 14:55
@kaikreuzer Not in the very short term. Leaving tonight, out for 3+ weeks *without* a PC. Not sure how I will survive that situation

**Comment by kaikreuzer** [comment] 2017-08-06 15:32
> without a PC

Are you being kidnapped? This cannot be on concious decision, can it? 😟

**Comment by kgoderis** [comment] 2017-08-06 19:23
@kaikreuzer It is, in fact.... Without a doubt you noticed that I am a bit below the radar lately, and I need  a break from everything and everyone.

**Comment by kgoderis** [comment] 2017-09-02 15:55
@kaikreuzer Kai, based on your investigation of alternative schedulers, are there any - at first sight - that can be extended to support different expression formats?

**Comment by kaikreuzer** [comment] 2017-09-04 08:25
Sorry, I didn't yet do any investigation on the alternatives, so I cannot answer this question - I only listed in #4133, what people mentioned to me in the past as potential implementations.

**Comment by schnidrig** [comment] 2017-09-04 19:50
Just noticed, that the expression: * * * ? * SAT,SUN * does not match Sept 3 2017 either.

**Comment by kgoderis** [comment] 2017-09-07 18:52
> Not sure, if this is related, but the CronExpressionTest#findNext fails for each build less than 150 days before year's end. For now I will disable this test, but this needs to be fixed definitely. After debugging a little bit I found out, that CronExpression#applyExpressionParts is not able to calculate dates, that would require a change to the next year, it fails e.g. for 0 0 0 ? * *' and 2017 Dec 31, 23:01.

@afuechsel I can confirm this is a bug and is due to the fact that our cronexpression does not support the fact that the Year field is non mandatory per Quartz cron expression definition, e.g. It wrongly assumes it is a mandatory field. I will provide a fix for this shortly

**Closed** 2017-09-11 20:35 UTC
Labels: bug, Core, Critical
