### ISSUE TITLE
[Astro PaperUI] Radiation wrong, unit missing, negative values

### ISSUE THREAD

**Issue by NorbertHD** [eclipse/smarthome#3569] opened 2017-06-02 15:02 UTC
Astro in PaperUI has some errors. When the altitude is not set, the radiaton values are reasonable.
![rad](https://cloud.githubusercontent.com/assets/8472266/26731465/7879cc84-47b4-11e7-8eb0-c2a68607c232.png)

But if I set the altitude to e.g. 100 m the values are way to high and diffuse radiation is negativ.
![rad2](https://cloud.githubusercontent.com/assets/8472266/26731481/8a938216-47b4-11e7-9c84-5d5630da6370.png)

Also the unit specifier for duration is missing, it should be "min".
![unit](https://cloud.githubusercontent.com/assets/8472266/26731560/be985eec-47b4-11e7-8e6e-19692046eb49.png)

When there is no "evening night" a duration of -1 is shown.
![negative](https://cloud.githubusercontent.com/assets/8472266/26731623/f10cfc34-47b4-11e7-8fa1-20ca54247abb.png)

**Comment by sjka** [comment] 2017-06-08 09:59
@gerrieg this looks like something for the expert

**Comment by gerrieg** [comment] 2017-06-08 16:53
The radiation has been implemented by @clinique 

@clinique 
Can you please check this and when you're there, can you please fix the other two small issues too?  😉 Thanks!

**Comment by sjka** [comment] 2017-06-08 20:12
Oh, right... Thanks!

**Comment by clinique** [comment] 2017-06-08 21:46
@gerrieg , sure, I'll do

**Comment by clinique** [comment] 2017-06-12 16:09
Pushing a PR adressing first two bugs, but the third one is as designed.

**Comment by NorbertHD** [comment] 2017-06-12 17:51
@clinique Thank you very much.

I have 3 other small issues:

"Moon age" and "Moon illumination" also don't have units. They should have "d" and "%".

The label of the "Full moon" channel-type is wrong (New moon):
```
	<channel-type id="fullMoon">
		<item-type>DateTime</item-type>
!!!!		<label>New moon</label>
		<description>The DateTime for full moon</description>
		<state readOnly="true" pattern="%1$tF %1$tR" />
	</channel-type>
```

**Comment by clinique** [comment] 2017-06-12 21:26
Ok, I'll integrate these small issues in the same PR

**Comment by clinique** [comment] 2017-06-13 07:16
PR was already merged.

**Comment by NorbertHD** [comment] 2017-06-13 18:55
I don't think that the PR fixes the altitude problem.
The parenthesis around the expression "(altitude / 1000)" makes it now an integer division.
So all altitude values between 0 and 999 m have the same result of 0.
When you set the altitude to 1000 m or above you should see wrong radiation values again.

**Comment by NorbertHD** [comment] 2017-06-17 13:31
Now with build 951, where the PR is included, I get really wrong radiation values, when altitude is above 1000 m.
![radi](https://user-images.githubusercontent.com/8472266/27253208-925f5d36-5370-11e7-8db9-9629ee1889af.png)

I think there are parenthesis missing in the M Expression and the "(altitude / 1000)"  expression should be turned back in a double division.

Please use the following diff:
```
diff --git "a/\\extensions\\binding\\org.eclipse.smarthome.binding.astro\\src\\main\\java\\org\\eclipse\\smarthome\\binding\\astro\\internal\\calc\\SunCalc.java" "b/\\extensions\\binding\\org.eclipse.smarthome.binding.astro\\src\\main\\java\\org\\eclipse\\smarthome\\binding\\astro\\internal\\calc\\SunCalc.java"
index ab3a91589..e742b0f69 100644
--- "a/\\extensions\\binding\\org.eclipse.smarthome.binding.astro\\src\\main\\java\\org\\eclipse\\smarthome\\binding\\astro\\internal\\calc\\SunCalc.java"
+++ "b/\\extensions\\binding\\org.eclipse.smarthome.binding.astro\\src\\main\\java\\org\\eclipse\\smarthome\\binding\\astro\\internal\\calc\\SunCalc.java"
@@ -91,8 +91,8 @@ public class SunCalc {
         // Direct Solar Radiation (in W/m²) at the atmosphere entry
         // At sunrise/sunset - calculations limits are reached
         double rOut = (elevation > 3) ? SC * (0.034 * Math.cos(DEG2RAD * (360 * dayOfYear / daysInYear)) + 1) : 0;
-        double altitudeRatio = (altitude != null) ? 1 / Math.pow((1 - (6.5 / 288) * (altitude / 1000)), 5.256) : 1;
-        double M = Math.sqrt(1229 + Math.pow(614 * sinAlpha, 2)) - 614 * sinAlpha * altitudeRatio;
+        double altitudeRatio = (altitude != null) ? 1 / Math.pow((1 - (6.5 / 288) * (altitude / 1000.0)), 5.256) : 1;
+        double M = (Math.sqrt(1229 + Math.pow(614 * sinAlpha, 2)) - 614 * sinAlpha) * altitudeRatio;

         // Direct radiation after atmospheric layer
         // 0.6 = Coefficient de transmissivité
```

And for the rest of the small items this diff:
```
diff --git "a/\\extensions\\binding\\org.eclipse.smarthome.binding.astro\\ESH-INF\\thing\\channels.xml" "b/\\extensions\\binding\\org.eclipse.smarthome.binding.astro\\ESH-INF\\thing\\channels.xml"
index c3507cdfe..45fb67984 100644
--- "a/\\extensions\\binding\\org.eclipse.smarthome.binding.astro\\ESH-INF\\thing\\channels.xml"
+++ "b/\\extensions\\binding\\org.eclipse.smarthome.binding.astro\\ESH-INF\\thing\\channels.xml"
@@ -100,7 +100,7 @@
 		<item-type>Number</item-type>
 		<label>Duration</label>
 		<description>The duration time in minutes of the event</description>
-		<state readOnly="true" pattern="%.1f min"/>
+		<state readOnly="true" pattern="%d min"/>
 	</channel-type>

 	<channel-type id="rangeEvent">
@@ -313,7 +313,7 @@

 	<channel-type id="fullMoon">
 		<item-type>DateTime</item-type>
-		<label>New moon</label>
+		<label>Full moon</label>
 		<description>The DateTime for full moon</description>
 		<state readOnly="true" pattern="%1$tF %1$tR" />
 	</channel-type>
@@ -329,14 +329,14 @@
 		<item-type>Number</item-type>
 		<label>Moon age</label>
 		<description>The age of the moon in days</description>
-		<state readOnly="true" />
+		<state readOnly="true" pattern="%d d" />
 	</channel-type>

 	<channel-type id="illumination">
 		<item-type>Number</item-type>
 		<label>Moon illumination</label>
 		<description>The illumination of the moon in %</description>
-		<state readOnly="true" />
+		<state readOnly="true" pattern="%.2f %%" />
 	</channel-type>

 	<channel-type id="phaseName"> 
```

**Comment by clinique** [comment] 2017-06-20 11:56
Ok, new PR submitted. Your corde solves the calculation problem. Thanks

**Closed** 2017-06-28 17:54 UTC
Labels: Binding-Astro
