### ISSUE TITLE
Eclipse mockito tests problem

### ISSUE THREAD

**Issue by VelinYordanov** [eclipse/smarthome#3918] opened 2017-07-31 15:21 UTC
Hello, 

When I tried to run mockito tests I got a `java.lang.NoClassDefFoundError: org/objenesis/ObjenesisStd`.
I tried to fix this by adding the org.objenesis package to the MANIFEST.MF but then i started getting the following exception:

```
org.mockito.exceptions.base.MockitoException: 
Mockito cannot mock this class: class org.eclipse.smarthome.core.thing.ManagedThingProvider
Mockito can only mock visible & non-final classes.
If you're not sure why you're getting this error, please report to the mailing list.
	at org.eclipse.smarthome.binding.fsinternetradio.test.FSInternetRadioHandlerOSGiTest.setUp(FSInternetRadioHandlerOSGiTest.java:138)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: org.mockito.cglib.core.CodeGenerationException: java.lang.reflect.InvocationTargetException-->null
	at org.mockito.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:238)
	at org.mockito.cglib.proxy.Enhancer.createHelper(Enhancer.java:378)
	at org.mockito.cglib.proxy.Enhancer.createClass(Enhancer.java:318)
	at org.mockito.internal.creation.jmock.ClassImposterizer.createProxyClass(ClassImposterizer.java:110)
	at org.mockito.internal.creation.jmock.ClassImposterizer.imposterise(ClassImposterizer.java:62)
	at org.mockito.internal.creation.jmock.ClassImposterizer.imposterise(ClassImposterizer.java:56)
	at org.mockito.internal.creation.CglibMockMaker.createMock(CglibMockMaker.java:23)
	at org.mockito.internal.util.MockUtil.createMock(MockUtil.java:26)
	at org.mockito.internal.MockitoCore.mock(MockitoCore.java:51)
	at org.mockito.Mockito.mock(Mockito.java:1243)
	at org.mockito.internal.configuration.MockAnnotationProcessor.process(MockAnnotationProcessor.java:30)
	at org.mockito.internal.configuration.MockAnnotationProcessor.process(MockAnnotationProcessor.java:16)
	at org.mockito.internal.configuration.DefaultAnnotationEngine.createMockFor(DefaultAnnotationEngine.java:43)
	at org.mockito.internal.configuration.DefaultAnnotationEngine.process(DefaultAnnotationEngine.java:66)
	at org.mockito.internal.configuration.InjectingAnnotationEngine.processIndependentAnnotations(InjectingAnnotationEngine.java:71)
	at org.mockito.internal.configuration.InjectingAnnotationEngine.process(InjectingAnnotationEngine.java:55)
	at org.mockito.MockitoAnnotations.initMocks(MockitoAnnotations.java:108)
	... 26 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mockito.cglib.core.ReflectUtils.defineClass(ReflectUtils.java:385)
	at org.mockito.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:220)
	... 42 more
Caused by: java.lang.SecurityException: class "org.eclipse.smarthome.core.thing.ManagedThingProvider$$EnhancerByMockitoWithCGLIB$$8761ce3e"'s signer information does not match signer information of other classes in the same package
	at java.lang.ClassLoader.checkCerts(ClassLoader.java:898)
	at java.lang.ClassLoader.preDefineClass(ClassLoader.java:668)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:761)
	... 48 more

java.lang.NullPointerException
	at org.eclipse.smarthome.binding.fsinternetradio.test.FSInternetRadioHandlerOSGiTest.tearDown(FSInternetRadioHandlerOSGiTest.java:146)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)


```

I then tried running other mockito tests on the smarthome platform like the org.eclipse.smarthome.magic.test and i got the same errors.

Can you help me with that?

**Comment by davidgraeff** [comment] 2017-07-31 16:32
Your smarthome git checkout needs to be recent (there were changes just a few days ago regarding the target platform for tests). Reload the target platform to be sure. Execute tests by clicking in the package explorer, right click on the test in question: Run as -> Plugin Test

**Comment by VelinYordanov** [comment] 2017-08-02 11:30
Is there a way for the tests to be ran as Junit Test?

**Comment by svilenvul** [comment] 2017-08-02 13:45
I am also not able to run any tests using Mockito as Junit Tests.
I think it is some sort of incompatibility between `org.mockito_1.9.5.v201311280930.jar` and `org.objenesis_1.0.0.v201105211943` from the target platform.

I have looked at the `org.mockito_1.9.5.v201311280930.jar` and in the manifest it is written:
>Bundle-Name: Mockito Mock Library for Java. Hamcrest-core & Objenesis 
 included in the bundle.

..., but the bundle doesn't contain the hamcrest and objenesis packages (they are imported).

I have found a  `mockito-all-1.9.5.jar` in my local maven repo and replacing the jar from the target platform with it seems to be the solution to this issue. 

Unfortunately I could not find the location from where it was downloaded.

Could someone take a look? It is really hard to work on https://github.com/eclipse/smarthome/issues/3305 with these problems.

**Comment by davidgraeff** [comment] 2017-08-02 16:18
Plugin tests are good enough for working on other tasks for now but should be fixed in the long run, I agree. But Openhab for example doesn't even support this, they expect u to create special launch files

**Comment by kaikreuzer** [comment] 2017-08-02 19:34
> I am also not able to run any tests using Mockito as Junit Tests.

@htreu Can you help here?

> But Openhab for example doesn't even support this, they expect u to create special launch files

@davidgraeff What do you mean exactly? The testing possibilities/infrastructure should be exactly the same for ESH and openHAB.

**Comment by davidgraeff** [comment] 2017-08-02 19:44
@kaikreuzer Without looking for the other bug report, but there you said that run as > plugin test would not work for openhab addon tests and a launch config should be created instead. But in fact with the ESH target platform I can exactly do this run as plugin test but with the Openhab target it does not work.

**Comment by kaikreuzer** [comment] 2017-08-02 19:52
> But in fact with the ESH target platform I can exactly do this

This is then just by a lucky chance. Note that we also have launch configs for all/most our tests in ESH. Using "run as->plugin test" normally does not work, since it adds far to much stuff to the launched OSGi runtime - it is definitely a completely different environment to what is used during the Maven execution. So in general it is a good idea to create a launch config specifically for your plug-in tests, so that you have under control, which bundles are being installed and/or activated for the test execution). This is nothing special to ESH/openHAB, but simply the way PDE works.

**Comment by davidgraeff** [comment] 2017-08-02 19:56
@kaikreuzer thank you for the clarification. the ESH docs regarding testing should be updated. They still recommend run as and they say 'mvn test' on the command line and I just recently got to know that this is wrong as well.

**Comment by htreu** [comment] 2017-08-03 12:17
> I am also not able to run any tests using Mockito as Junit Tests.

The classpath for the test fragment simply is not complete from a pure JUnit Runner pov. Only the `JRE System Library` and `Plug-in Dependencies` are part of the classpath. Even the main bundle (for which the test bundle is a fragment) is not part of the classpath. As @kaikreuzer stated we need to run our tests as `Junit Plug-in Test` (since that is what our bundles are).

When running a Test class as `JUnit Plug-in Test` w/o a specific launch config the default plugin configuration is `all workspace and enabled target plugins` which _might_ get you there. But its in any case a better option to create a launch config for the whole test fragment. I will update the test documentation on how to create one.

**Comment by svilenvul** [comment] 2017-08-04 10:46
>  davidgraeff commented 2 days ago 
> Plugin tests are good enough for working on other tasks for now but should be fixed in the long run, I agree.

I also agree, I thought this was the reason why we have started to [move groovy unit tests to JUnit, mockito & hamcrest](https://github.com/eclipse/smarthome/issues/3305).

>  htreu commented 22 hours ago 
> The classpath for the test fragment simply is not complete from a pure JUnit Runner pov.

Yes this is correct, but the problem is not hard to solve, a few adjustments to the target platform will solve it.

**Comment by htreu** [comment] 2018-01-29 14:13
In the meantime we made the the observation that JUnit & mockito tests _can_ in fact be run as pure JUnit tests:
In addition to the already allowed `Require-bundle` entries in `MANIFEST.MF` of the test fragment ([see 9. here](https://www.eclipse.org/smarthome/documentation/development/guidelines.html#b-osgi-bundles)) you have to put `org.objenesis` to the list.
This allows JUnit & mockito tests that are not derived from one of OSGiTest or JavaOSGiTest to directly run as JUnit tests.

_However:_
Just recently this behaviour changed: During test execution as described above the following root exception is thrown (this is from running the `ConfigDispatcherFileWatcherTest`):

```
Caused by: java.lang.SecurityException: class "org.eclipse.smarthome.config.dispatch.internal.ConfigDispatcher$$EnhancerByMockitoWithCGLIB$$8384a44c"'s signer information does not match signer information of other classes in the same package
```

This is strange as some time ago(TM) this did work. Ping @sjka.

**Comment by kaikreuzer** [comment] 2018-04-09 15:25
This can imho be closed, now that we are using Mockito 2.

**Closed by kaikreuzer** 2018-04-09 15:25 UTC
