### ISSUE TITLE
Rollershutter Items with wrong image state

### ISSUE THREAD

**Issue by maglnet** [eclipse/smarthome#3445] opened 2017-05-13 09:43 UTC
I updated my openhab2 installation to the latest snapshot. Now my Rollershutters are displayed wrong. They do not have a numeric state within the UI but `ON` / `OFF`.

I did some small check and I think the following lines could be the source of my problem.
https://github.com/eclipse/smarthome/commit/8ba0e7cdd141595e5d7fbe8a3d7716ce63cba799#diff-5d3a30bfebd36343f1f1d61e9f589de1R491

My understanding: It seems that the my Rollershutter is an instance of `Switch` and so it is converted to `ON` or `OFF`. So one should probably check the Item, too.

Perhaps @triller-telekom can have a look at this, as he committed the mentioned code parts?

best regards
Matthias

**Comment by triller-telekom** [comment] 2017-05-15 09:36
Can you please provide some details about how your sitemap and items files look like? 

Ist your item a `Rollershutter` and you set it to a `Switch` in the sitemap?

**Comment by lolodomo** [comment] 2017-05-15 16:15
I am asking myself if we will not have a similar problem when using a `String `item combined with a `Switch `element with mappings in the sitemap ?
If true, it is a major problem.

Not sure we have these 2 cases in the demo sitemap.

The problem is that a `Switch `element in sitemap is not always linked to a OnOffType.

**Comment by lolodomo** [comment] 2017-05-15 17:05
Sorry it is probably ok for String item as there is no conversion to OnOffType.

**Comment by maglnet** [comment] 2017-05-15 21:58
Hi, my config looks like this:

Groups / Items:
```
[...]
Group:Rollershutter:AVG gShutterEG "Rollläden EG [%.0f %%]" <groundfloor> (gShutter)
Rollershutter  ROLL_KUECHE_GROSS   "Rolladen Küche Terrasse [%.0f %%]" (gShutterEG)  { channel="homematic:HG-HM-LC-Bl1PBU-FM:ccu:XXXXXXXXXX:1#LEVEL" }
[...]
```

And within my sitemap, I only added the Group:
```
[...]
Group item=gShutterEG
[...]
```

Also if I add the item itself it doesn't work:
```
[...]
Default item=ROLL_KUECHE_GROSS
[...]
```

The result within the sitemap looks like this:
![grafik](https://cloud.githubusercontent.com/assets/4430279/26081178/f1301096-39c9-11e7-93e7-0c6bb28ce4bf.png)

If you need any other information, please ask.

Best regards
Matthias

**Comment by lolodomo** [comment] 2017-05-15 22:07
Personnally, I am lost. I see "100 %" displayed in the UI. Isn't it what you expect ? What was the result before the change ?

**Comment by maglnet** [comment] 2017-05-15 22:08
Oh, yes, sorry, that was a misleading information, I'm talking about the icon's state, please see the URL.

**Comment by lolodomo** [comment] 2017-05-15 22:13
You mean, the icon at left ?

**Comment by maglnet** [comment] 2017-05-15 22:17
Yes, the icon's source is `../icon/rollershutter?state=ON&format=png`. So `state=ON` is wrong here.  
And this results in not showing the correct icon (e.g. with a closed blind, when the percentage is 100%).

**Comment by lolodomo** [comment] 2017-05-15 22:23
Ok, that is clear now. Your initial analysis was correct. The new conversion to OnOffType leads to an unexpected icon in this case.
@triller-telekom : any idea ? should we avoid the conversion to OnOffType for Rollershutter items ?

**Comment by lolodomo** [comment] 2017-05-15 22:26
I suppose the conversion is useful if you define that in the sitemap:
```
Switch item=ROLL_KUECHE_GROSS
```

**Comment by lolodomo** [comment] 2017-05-15 22:31
@maglnet : maybe your remark is only how looks like the icon rollershutter-on.png ? Would you expect that rollershutterèon.png be identical to rollershutter-100.png ?
Or do you expect in your case icon rollershutter-50.png when your rollershutter is half opened (50M) ?

**Comment by maglnet** [comment] 2017-05-16 05:21
@lolodomo : Before I updated my openhab installation to the latest snapshot version the parameter `state` had exactly the value that the percentage was showing. e.g. `?state=66` and was resulting in the icon next to this value (e.g. `rollershutter-70.png`).  

So I would expect that It behaves like this again and so resulting in an icon representing the state of my real rollershutter :)

**Comment by triller-telekom** [comment] 2017-05-16 08:14
@lolodomo : I did some debugging and I think the bug is within the client site and has something to do with using `Default` in the sitemap for the rollershutter.

I now have:
Items file:
```
Rollershutter  ROLL_KUECHE_GROSS   "Rolladen Küche Terrasse [%.0f %%]" (gShutterEG)  { channel="homematic:HG-HM-LC-Bl1PBU-FM:ccu:XXXXXXXXXX:1#LEVEL" }
```
Sitemap file:
```
Default item=ROLL_KUECHE_GROSS
```

What I observe is that the state in the sitemap is only updated once I completely reload the page, i.e. incoming SitemapEvents do NOT update it.

A breakpoint in `Smarthome.js` at `if (!(data.widgetId in smarthome.dataModel)) ` shows that the `widgetId` is not in the `dataModel`?

Another finding: [Here](https://github.com/eclipse/smarthome/blob/master/bundles/io/org.eclipse.smarthome.io.rest.sitemap/src/main/java/org/eclipse/smarthome/io/rest/sitemap/internal/PageChangeListener.java#L204) I get a `DefaultImpl` for the widget and thus this conversion method is doing nothing to the state. The `SitemapEvent` still has the percentage value and not `on/off`.

Can you confirm that?

**Comment by lolodomo** [comment] 2017-05-16 09:52
There are several issues with default elements, one is the refresh. I will work to fix all of them. But i have not thought about the state conversion.

Can you first try with switch rather than default in the sitemap ?

**Comment by triller-telekom** [comment] 2017-05-16 13:21
@maglnet If you use `Switch` in the sitemap it will work again after my PR is merged.

@lolodomo I fixed this issue with my PR but it would be nice if you can take care of the `DefaultImpl` problems and maybe create a separate issue for this.

But why is the `RollerShutter` a `Switch` in the sitemap? I know we have it in the demo configs from openHAB but they are rendered differently from a switch and thus they should also be a different widget type... I guess thats due to "historical reasons" probably. :-)

**Comment by lolodomo** [comment] 2017-05-16 13:26
In fact, there is no specific sitemap element defined for the roller shutter. I have no idea why.

**Closed** 2017-05-16 13:44 UTC

**Comment by maglnet** [comment] 2017-05-16 16:27
Thank you for the quick solution. 👍 
I'll check this with an openhab snapshot in the next days.

**Comment by triller-telekom** [comment] 2017-05-17 07:19
@maglnet: Please be aware that @kaikreuzer has to build openHAB with the newest ESH release which is not the case for every openHAB release.
