### ISSUE TITLE
[homematic] openHAB2.2 isn't able to connect or recognize RasperryMatic bridge

### ISSUE THREAD

**Issue by mdicke2s** [eclipse/smarthome#5795] opened 2018-06-25 12:26 UTC
_From @nRaecheR on March 9, 2018 15:38_

## Expected Behavior

Searching a new Homematic bridge in the Thing inbox should find the RaspberryMatic bridge

## Current Behavior
Searching a new Homematic bridge in the Thing inbox didn't find the RaspberryMatic bridge and a manual added Homematic Bridge thing says the connection has been refused (connection error)

## Possible Solution
n/a

## Steps to Reproduce (for Bugs)
1. Install Homematic Binding 2.2 on openHABian 1.5, updated to latest versions 
2. Go to Inbox in PaperUI and chosse the + Button
3. Select Homematic Binding 
4. Wait for search to finish
5. Choose Manual add thing and enter IP address of RaspberryMatic (latest version)

## Context
The device can't be added as thing and is non-functional for OpenHAB2. I've installed tcpdump on the OpenHABian installation and it seems there isn't even any network traffic from OpenHAB to the given RaspberryMatic IP address.

## Your Environment
* Version used: 
 - OpenHAB 2.2 on latest OpenHABian 1.5, all packages updated 
 - Homematic Binding 2.2 from repo
 - RaspberryMatic 2.31.25.20180225, Firewall setting on Full Access for both APIs

* Both devices running on different RPI3s
* Both devices are in the same subnet (192.168.46.x)
* Both devices are able to ping each other.
* Both devices are using the Ethernet adapter, not the Wifi adapter.

_Copied from original issue: openhab/openhab2-addons#3309_

**Comment by MHerbst** [comment] 2018-10-04 08:54
@mdicke2s  I have tested it with openHAB 2.4 M4 and the autodetect for the gateway does not work. But manually adding the bridge in Paper UI is working. Tested with the following environment:

- Windows 10 with Java 1.8 (and also Ubuntu 18.04)
- openHAB 2.4 M4
- Raspberry with RPI-RF-MOD (this is the same hardware configuration as the CCU3) and Raspberrymatic 3.37.8.20180929

**Comment by mdicke2s** [comment] 2018-10-04 09:37
Thanks @MHerbst for retesting.

Originally this issue was not created by me (I was the one moving it from Openhab project to eclipse smarthome). @nRaecheR this issue should be fixed with openHAB 2.4. Could you please confirm that the issue is solved once you updated Openhab?

**Comment by MHerbst** [comment] 2018-10-04 09:58
@mdicke2s Should I create a new issue regarding the autodetect problem? This doesn't seem to be solved.

**Comment by mdicke2s** [comment] 2018-10-04 11:37
@MHerbst sorry, I didn't read carefully. Basically the issue is still valid, but you have proposed a workaround (not using autodetect). Due to the fact that the documentation claims that autodetect is supported on all gateways plus the fact that Raspberrymatic claims to be 100% compliant with CCU, I would rate this as a bug and therefore we should leave this open (except you prefer replacing it with a new issue which is more focused on **CcuDiscoveryService does not discover Raspberrymatic**).

**Comment by MHerbst** [comment] 2018-10-04 16:02
@mdicke2s I think it is better to create a new issue because this remaining problem is new and caused by Raspberrymatic. Maybe it will also happen with a "real) CCU3. Therefore I have created #6314 that already contains some more information.

**Comment by nRaecheR** [comment] 2018-10-05 06:03
I'll test OH 2.4 as soon as it is released. Thank you.

**Comment by mdicke2s** [comment] 2018-10-08 08:30
@MHerbst I saw you already pushed a fix for #6314. Thanks for your contribution. Which release of openhab will contain your change?

**Comment by MHerbst** [comment] 2018-10-08 08:43
@mdicke2s After some debugging the patch was easy :-). Kai merged it this night. I don't exactly know when a build of ESH bindings will be integrated into an OH build. But at the latest, it will be part of the next milestone build.

**Comment by mdicke2s** [comment] 2018-10-08 08:48
Ok, thx :-)

**Comment by MHerbst** [comment] 2018-12-26 20:55
@mdicke2s Is this problem still open with 2.4? I would assume that is solved with the latest changes

**Comment by nRaecheR** [comment] 2019-01-08 09:52
After updating to OH 2.4.0 my RaspberryMatic is recognized and all sensors are shown as things. I think it is safe to close this bug now. Thank you all for your good work!

**Comment by maggu2810** [comment] 2019-01-09 09:19
@nRaecheR Thank you for comment.
As there is no feedback from @mdicke2s that states that the problem still exists, let's close this issue.

**Closed** 2019-01-09 09:18 UTC
Labels: Binding-Homematic
