### ISSUE TITLE
Leak (or excessive memory usage) in SitemapResource

### ISSUE THREAD

**Issue by sebmarchand** [eclipse/smarthome#5008] opened 2018-01-31 01:34 UTC
(This is a continuation of the discussion on this OpenHab issue: https://community.openhab.org/t/sitemap-causing-oom/38936/10)

**Summary**:
It looks like there's no restriction on how many objects [SitemapResource::eventOutputs](https://github.com/eclipse/smarthome/blob/dcef6131b70c231a604b4beec5dc9e1769fbb88f/bundles/io/org.eclipse.smarthome.io.rest.sitemap/src/main/java/org/eclipse/smarthome/io/rest/sitemap/internal/SitemapResource.java#L130)  can contain and this can easily lead to an OOM. 

**Details**:
If I keep OpenHab2's BasicUI open in my browser for a long period of time (e.g. overnight) this will likely lead to an OOM crash, I've investigated a bit on this and the heap dump I got seem to point to [SitemapResource::eventOutputs](https://github.com/eclipse/smarthome/blob/dcef6131b70c231a604b4beec5dc9e1769fbb88f/bundles/io/org.eclipse.smarthome.io.rest.sitemap/src/main/java/org/eclipse/smarthome/io/rest/sitemap/internal/SitemapResource.java#L130).

Here's some information from the heap dump analysis:

Problem Suspect (as provided by Memory Analyzer):
> One instance of "org.eclipse.smarthome.io.rest.sitemap.internal.SitemapResource" loaded by "org.eclipse.smarthome.io.rest.sitemap" occupies 893,758,768 (89.71%) bytes. The memory is accumulated in one instance of "org.eclipse.smarthome.io.rest.sitemap.internal.SitemapResource" loaded by "org.eclipse.smarthome.io.rest.sitemap".

And here's the "Path to GC root" for this SitemapResource object:

```
Class Name                                                                                                          | Shallow Heap | Retained Heap
---------------------------------------------------------------------------------------------------------------------------------------------------
org.eclipse.smarthome.io.rest.sitemap.internal.SitemapResource @ 0xc45e1a88                                         |           48 |   893,758,768
'- m_implementationObject org.apache.felix.scr.impl.manager.ComponentContextImpl @ 0xc45e18a0                       |           56 |           720
   '- m_componentContext org.apache.felix.scr.impl.manager.SingleComponentManager @ 0xc45e0680                      |          104 |         1,816
      |- service org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl @ 0xc45e16d0                     |           64 |           408
      |  '- [232] java.lang.Object[567] @ 0xc5fa49e8                                                                |        2,288 |         2,288
      |     '- elementData java.util.ArrayList @ 0xc48317c0                                                         |           24 |         2,312
      |        '- allPublishedServices org.eclipse.osgi.internal.serviceregistry.ServiceRegistry @ 0xc482d9b8       |           48 |       107,192
      |           |- serviceRegistry org.eclipse.osgi.internal.framework.EquinoxContainer @ 0xc43feec8              |           72 |         4,544
      |           |  |- container org.eclipse.osgi.internal.url.URLStreamHandlerFactoryImpl @ 0xc44ced18            |           40 |           200
      |           |  |  '- factory class java.net.URL @ 0xc4306878 System Class                                     |           32 |           864
      |           |  |- equinoxContainer org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle @ 0xc464bd88|           40 |            80
      |           |  |- container org.eclipse.osgi.internal.url.ContentHandlerFactoryImpl @ 0xc48329c8              |           40 |           128
      |           |  |- container org.eclipse.osgi.internal.framework.BundleContextImpl @ 0xc4ca9718                |           40 |           424
      |           |  |- threadFactory java.util.concurrent.ScheduledThreadPoolExecutor @ 0xc464bcf8                 |           80 |           528
      |           |  |- equinoxContainer org.eclipse.osgi.internal.framework.EquinoxBundle @ 0xc4796458             |           32 |            48
      |           |  |- equinoxContainer org.eclipse.osgi.internal.framework.EquinoxBundle @ 0xc47eef80             |           32 |            48
      |           |  |- container org.eclipse.osgi.internal.framework.BundleContextImpl @ 0xc4f919d8                |           40 |           904
      |           |  |- container org.eclipse.osgi.internal.loader.BundleLoader @ 0xd6457650                        |           72 |         1,040
      |           |  '- Total: 9 entries                                                                            |              |              
      |           |- registry org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl @ 0xc4cb3480        |           64 |           360
      |           |- registry org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl @ 0xc94d6988        |           64 |           376
      |           '- Total: 3 entries                                                                               |              |              
      |- value java.util.HashMap$Node @ 0xc5c61730                                                                  |           32 |            56
      '- Total: 2 entries                                                                                           |              |              
---------------------------------------------------------------------------------------------------------------------------------------------------
```

I think that the root cause of my problem has nothing to do with the SitemapResource , there shouldn't be so many event sent to it in the first place and I'll investigate on this separately, but it'd be nice if there was a way to make sure that this class can't cause this excessive memory usage. 

Thanks! Please let me know if there's anything I can share here to make it easier to debug this issue. I've tried looking at it but it's beyond my Java skills :)

**Comment by maggu2810** [comment] 2018-02-01 06:54
About 890 MB overnight if keeping the BasicUI open? Should we add the label critical?

**Comment by kaikreuzer** [comment] 2018-02-01 07:38
If anybody can reproduce and confirm this issue, yes, I would also consider it critical.

**Comment by sebmarchand** [comment] 2018-02-01 13:27
Note that this is the consequence of another issue, so it might be relatively hard to repro, I think that it was caused by https://github.com/eclipse/smarthome/issues/4871 but I'm not entirely sure. I've removed some addons from the 'binding=' line in one of the addons.cfg file and it seemed to fix the issue, I'll put them back and see if the problem repro...

The suggestion here was to limit the number of elements that can be contained in SitemapResource::eventOutputs.

**Comment by sjka** [comment] 2018-02-01 14:53
> The suggestion here was to limit the number of elements that can be contained in SitemapResource::eventOutputs.

`eventOutputs` is a Map (subscription to event output) and contains only a single element per subscription. So limiting doesn't really make sense here. The question should rather be: what caused so many subscriptions to exist on your system? And under what circumstances aren't they cleaned up?

**Comment by mhilbush** [comment] 2018-02-01 15:16
>  I think that it was caused by #4871 but I'm not entirely sure. I've removed some addons from the 'binding=' line in one of the addons.cfg file and it seemed to fix the issue, I'll put them back and see if the problem repro

If you really are experiencing the same thing I saw in #4871, I'll be surprised if adding the bindings back to addons.cfg will reintroduce the problem.  In the testing I did, once the offending binding was removed from addons.cfg (in my case it was restdocs), adding it back to addons.cfg never reintroduced the problem.  I kept a backup of the broken environment, so in my testing I always was able to go back to a consistent (and broken) environment.  It will be interested to see what happens in your case.

In #4871, BasicUI was getting a new subscription every minute.  I think I still have the backup.  If you'd like, I can restore my broken environment, leave BasicUI running, and see what happens.

**Comment by sebmarchand** [comment] 2018-02-05 18:46
I've tried to repro this but it didn't worked (which is a good thing for me because it means that my setup is now more stable).

**Comment by sebmarchand** [comment] 2018-02-07 19:08
Ha! I've reinstalled the Nest bindings and it seems like the problem re-appeared! I'm seeing the "Offline: waiting for connection to become available" message every few secs in BasicUI and the memory used by OpenHab (according to "/etc/init.d/openhab2 status") is slowly increasing over time...

Is there anything I can do to gather more debug information?

**Comment by lolodomo** [comment] 2018-02-08 07:18
Did you see that issue: https://github.com/openhab/openhab-core/issues/286
What is the content of your addons.cfg file ?

**Comment by lolodomo** [comment] 2018-02-11 12:42
If for a certain reason, the SSE connection in Basic UI fails, the message "Offline: waiting for connection to become available" is then displayed and there is an automatic try to reconnect it after 10 seconds through a POST call to /rest/sitemaps/events/subscribe. Such a call will allocate a new subscription ID on the server side. Maybe these subscriptions are never released. As already discussed in this other issue https://github.com/eclipse/smarthome/issues/4809 they are apparently properly released when the server tries to use the SSE link to send an event update. But if no event update happens, it is possiblethat the stuff is not released.
Maybe the server should kill one SSE connection and release the subscription ID after a certain amount of inactivity on this connection ?
Or we could introduce a REST call to unsubscribe a subscription ID ? It will be called by Basic UI after a connection error is detected.

**Comment by sebmarchand** [comment] 2018-02-12 15:06
There's nothing in my /etc/openhab2/services/addons.cfg file, but the '' file isn't empty (this file seem to be auto-generated?):

package = standard
ui = basic,paper,habpanel,classic,habmin
binding = insteonplm1,mqtt1,sonos,wemo,systeminfo,nest
misc = ,openhabcloud,ruleengine,restdocs
transformation = map
remote = true
legacy = true
persistence = mysql


not sure if the fact that the 'misc' line is an issue, I haven't updated this file myself, so maybe it's an error with the code that generates this?

**Comment by lolodomo** [comment] 2018-02-14 20:59
Yes, the misc value starting with `,` is weird.

**Comment by sebmarchand** [comment] 2018-02-14 21:20
Ha sorry, copy-paste issue in my previous reply, this is the content of the "/var/lib/openhab2/etc/org.openhab.addons.cfg" file. I'll remove the ',' at the beginning of the misc line and see what happen

**Comment by lolodomo** [comment] 2018-05-09 11:53
Looking at the code, I can confirm that eventOutputs is not cleaned even when the SSE connection is properly closed. It should be fixed.

**Comment by lolodomo** [comment] 2018-05-09 11:58
I added that fix in my PR 5556.

Now if we want to avoid an infinite creation of sitemap SSE subscriptions, we could decide to limit the subscriptions to a max number ?

**Comment by maggu2810** [comment] 2018-05-15 08:16
> Now if we want to avoid an infinite creation of sitemap SSE subscriptions, we could decide to limit the subscriptions to a max number ?

I agree that the number of subscriptions should be limited (configurable by config admin), so the ESH instance can protect itself to not run out of its limits.

**Comment by lolodomo** [comment] 2018-05-19 11:15
What status should we set in the response when the server has reached the limit ?
PS: it has to be handled in Basic UI.

**Comment by lolodomo** [comment] 2018-05-19 11:49
There is a linked subject being how to be sure that the subscriptions will be released. I proposed a solution in #4809.

**Comment by maggu2810** [comment] 2018-05-22 12:17
What about 429?
https://tools.ietf.org/html/rfc6585#section-4

**Comment by lolodomo** [comment] 2018-05-29 10:51
I created the PR #5648 for the configurable max number of sitemap SSE subscriptions.

I did not used 429 as error status because it is not defined in the enum.

**Comment by lolodomo** [comment] 2018-05-29 11:06
The next step would be to add an additional mechanism to trigger the release of the subscriptions when the client is gone.

**Comment by lolodomo** [comment] 2018-06-11 23:14
After the recent changes, I think we can now close this issue.

**Closed** 2018-06-12 06:38 UTC
Labels: UI, bug
