### ISSUE TITLE
Breaking API Change: BridgeBuilder

### ISSUE THREAD

**Issue by chr-fritz** [eclipse/smarthome#1908] opened 2016-07-25 07:35 UTC
@b2b0b73bd319ea5ae5877c6fffaa075225b7ca23 breaks the API of BridgeBuilder.
Before this commit the following code compiles without any problems:
```java
Bridge monitor=BridgeBuilder.create(new ThingTypeUID("a:b"),"myid")
        .withProperties(new HashMap<String,String>())
        .build();
```
After this commit it failes with "incompatible types: Thing cannot be converted to Bridge".

**Comment by maggu2810** [comment] 2016-07-25 07:48
You are right, it is caused by #1894 the fix for #1887.
The with... methods of the bridge builder change the instance information to thing builder.

The only solution I know about (if we don't want change the usage of BridgeBuilder) would be to override all with... methods of ThingBuilder in BridgeBuilder, calling the super method, and return a BridgeBuilder instance.

**Comment by kaikreuzer** [comment] 2016-07-25 08:05
fixed by #1911

**Closed by kaikreuzer** 2016-07-25 08:05 UTC
