### ISSUE TITLE
Thing updates by handers should not be persisted

### ISSUE THREAD

**Issue by abinmathewabraham** [eclipse/smarthome#2216] opened 2016-09-26 09:10 UTC
The dynamic channels I created if not removed, is being shown up again when the server is restarted due to the cache of the Thing. If there is an option for Thing to not persist any changes it had, it would give more flexibility for the developer

**Comment by kaikreuzer** [comment] 2016-09-27 13:14
FTR: This is related to https://github.com/eclipse/smarthome/issues/588#issuecomment-226565087, where @kgoderis suggested: "it should be possible to dynamically define channels on Things without these channel definitions being persisted, because the creation of those channels is triggered/dependent on the data that is read from the remote device. These channels can be "built up" every time the runtime starts (or, the ThingHandler(re) initializing)"

**Comment by sjka** [comment] 2016-09-29 10:37
this is a duplicate of #1977

**Comment by kaikreuzer** [comment] 2016-09-29 10:38
Indeed, thanks.

**Closed by kaikreuzer** 2016-09-29 10:38 UTC
Labels: Core, duplicate
