### ISSUE TITLE
Authentication API: Add documentation

### ISSUE THREAD

**Issue by maggu2810** [eclipse/smarthome#2620] opened 2016-12-08 08:55 UTC
This issue continues https://github.com/eclipse/smarthome/pull/2587#issuecomment-265682729

**Comment by maggu2810** [comment] 2016-12-08 08:55
Don't know why it has been asked me for authentication. Tried different combinations now. I does not ask me anymore.
But it does not work.

I tried Karaf with ESH (+TP) and no other stuff (using my sample karaf packaging) and accessed tested the GET method of rest/things

http://127.0.0.1:8181/rest/things
```java
{
  "error": {
    "message": "User not authorized.",
    "http-code": 403,
    "exception": {
      "class": "javax.ws.rs.ForbiddenException",
      "message": "User not authorized.",
      "localized-message": "User not authorized."
    }
  }
}
```

```text
karaf@root()> feature:list | grep Started | sort


aries-blueprint                           | 4.0.7            |          | Started     | standard-4.0.7          | Aries Blueprint
aries-proxy                               | 4.0.7            |          | Started     | standard-4.0.7          | Aries Proxy
bundle                                    | 4.0.7            | x        | Started     | standard-4.0.7          | Provide Bundle support
config                                    | 4.0.7            | x        | Started     | standard-4.0.7          | Provide OSGi ConfigAdmin support
deployer                                  | 4.0.7            | x        | Started     | standard-4.0.7          | Karaf Deployer
diagnostic                                | 4.0.7            | x        | Started     | standard-4.0.7          | Provide Diagnostic support
esh-automation-api                        | 0.9.0.SNAPSHOT   | x        | Started     | karaf-0.9.0-SNAPSHOT    |
esh-automation-commands                   | 0.9.0.SNAPSHOT   | x        | Started     | karaf-0.9.0-SNAPSHOT    |
esh-automation-core                       | 0.9.0.SNAPSHOT   | x        | Started     | karaf-0.9.0-SNAPSHOT    |
esh-automation-module-core                | 0.9.0.SNAPSHOT   | x        | Started     | karaf-0.9.0-SNAPSHOT    |
esh-automation-module-script              | 0.9.0.SNAPSHOT   | x        | Started     | karaf-0.9.0-SNAPSHOT    |
esh-automation-module-script-defaultscope | 0.9.0.SNAPSHOT   | x        | Started     | karaf-0.9.0-SNAPSHOT    |
esh-automation-module-timer               | 0.9.0.SNAPSHOT   | x        | Started     | karaf-0.9.0-SNAPSHOT    |
esh-automation-parser-gson                | 0.9.0.SNAPSHOT   | x        | Started     | karaf-0.9.0-SNAPSHOT    |
esh-automation-providers                  | 0.9.0.SNAPSHOT   | x        | Started     | karaf-0.9.0-SNAPSHOT    |
esh-automation-rest                       | 0.9.0.SNAPSHOT   | x        | Started     | karaf-0.9.0-SNAPSHOT    |
esh-base                                  | 0.9.0.SNAPSHOT   | x        | Started     | karaf-0.9.0-SNAPSHOT    | ESH
esh-io-console-karaf                      | 0.9.0.SNAPSHOT   | x        | Started     | karaf-0.9.0-SNAPSHOT    | Karaf Console support for SmartHome stuff
esh-io-rest-sitemap                       | 0.9.0.SNAPSHOT   | x        | Started     | karaf-0.9.0-SNAPSHOT    |
esh-kat.cpy-jersey-min-2.22.2             | 0.9.0.SNAPSHOT   |          | Started     | karaf-tp-0.9.0-SNAPSHOT |
esh-model-item                            | 0.9.0.SNAPSHOT   |          | Started     | karaf-0.9.0-SNAPSHOT    |
esh-model-item-runtime                    | 0.9.0.SNAPSHOT   | x        | Started     | karaf-0.9.0-SNAPSHOT    |
esh-model-persistence                     | 0.9.0.SNAPSHOT   |          | Started     | karaf-0.9.0-SNAPSHOT    |
esh-model-persistence-runtime             | 0.9.0.SNAPSHOT   | x        | Started     | karaf-0.9.0-SNAPSHOT    |
esh-model-rule                            | 0.9.0.SNAPSHOT   |          | Started     | karaf-0.9.0-SNAPSHOT    |
esh-model-rule-runtime                    | 0.9.0.SNAPSHOT   | x        | Started     | karaf-0.9.0-SNAPSHOT    |
esh-model-script                          | 0.9.0.SNAPSHOT   |          | Started     | karaf-0.9.0-SNAPSHOT    |
esh-model-script-runtime                  | 0.9.0.SNAPSHOT   | x        | Started     | karaf-0.9.0-SNAPSHOT    |
esh-model-sitemap                         | 0.9.0.SNAPSHOT   |          | Started     | karaf-0.9.0-SNAPSHOT    |
esh-model-sitemap-runtime                 | 0.9.0.SNAPSHOT   | x        | Started     | karaf-0.9.0-SNAPSHOT    |
esh-model-thing                           | 0.9.0.SNAPSHOT   |          | Started     | karaf-0.9.0-SNAPSHOT    |
esh-model-thing-runtime                   | 0.9.0.SNAPSHOT   | x        | Started     | karaf-0.9.0-SNAPSHOT    |
esh-storage-mapdb                         | 0.9.0.SNAPSHOT   | x        | Started     | karaf-0.9.0-SNAPSHOT    |
esh-tp-httpclient                         | 0.9.0.SNAPSHOT   |          | Started     | karaf-tp-0.9.0-SNAPSHOT |
esh-tp-jax-rs                             | 0.9.0.SNAPSHOT   |          | Started     | karaf-tp-0.9.0-SNAPSHOT |
esh-tp-jax-rs-min                         | 0.9.0.SNAPSHOT   |          | Started     | karaf-tp-0.9.0-SNAPSHOT |
esh-tp-jax-rs-provider-gson               | 0.9.0.SNAPSHOT   |          | Started     | karaf-tp-0.9.0-SNAPSHOT | JAX-RS provider for de/serialization using Gson
esh-tp-jax-rs-provider-security           | 0.9.0.SNAPSHOT   |          | Started     | karaf-tp-0.9.0-SNAPSHOT | Security provider for jaxrs
esh-tp-jupnp                              | 0.9.0.SNAPSHOT   |          | Started     | karaf-tp-0.9.0-SNAPSHOT | UPnP/DLNA library for Java
esh-tp-xtext                              | 0.9.0.SNAPSHOT   |          | Started     | karaf-tp-0.9.0-SNAPSHOT | Xtext - Language Engineering Made Easy
esh-ui                                    | 0.9.0.SNAPSHOT   |          | Started     | karaf-0.9.0-SNAPSHOT    |
esh-ui-icon                               | 0.9.0.SNAPSHOT   |          | Started     | karaf-0.9.0-SNAPSHOT    |
esh-ui-iconset-classic                    | 0.9.0.SNAPSHOT   | x        | Started     | karaf-0.9.0-SNAPSHOT    |
esh-ui-paper                              | 0.9.0.SNAPSHOT   | x        | Started     | karaf-0.9.0-SNAPSHOT    |
feature                                   | 4.0.7            | x        | Started     | standard-4.0.7          | Features Support
http                                      | 4.0.7            |          | Started     | standard-4.0.7          | Implementation of the OSGI HTTP Service
instance                                  | 4.0.7            | x        | Started     | standard-4.0.7          | Provide Instance support
jaas                                      | 4.0.7            | x        | Started     | standard-4.0.7          | Provide JAAS support
kar                                       | 4.0.7            | x        | Started     | standard-4.0.7          | Provide KAR (KARaf archive) support
log                                       | 4.0.7            | x        | Started     | standard-4.0.7          | Provide Log support
management                                | 4.0.7            | x        | Started     | standard-4.0.7          | Provide a JMX MBeanServer and a set of MBeans in
package                                   | 4.0.7            | x        | Started     | standard-4.0.7          | Package commands and mbeans
pax-http                                  | 4.3.0            |          | Started     | org.ops4j.pax.web-4.3.0 | Implementation of the OSGI HTTP Service
pax-http-jetty                            | 4.3.0            |          | Started     | org.ops4j.pax.web-4.3.0 |
pax-jetty                                 | 9.2.19.v20160908 |          | Started     | org.ops4j.pax.web-4.3.0 | Provide Jetty engine support
scr                                       | 4.0.7            |          | Started     | standard-4.0.7          | Declarative Service support
service                                   | 4.0.7            | x        | Started     | standard-4.0.7          | Provide Service support
shell                                     | 4.0.7            | x        | Started     | standard-4.0.7          | Karaf Shell
shell-compat                              | 4.0.7            | x        | Started     | standard-4.0.7          | Karaf Shell Compatibility
ssh                                       | 4.0.7            | x        | Started     | standard-4.0.7          | Provide a SSHd server on Karaf
system                                    | 4.0.7            | x        | Started     | standard-4.0.7          | Provide System support
```

```text
karaf@root()> bundle:list -t 0  | grep -i smarthome


112 | Active   |  80 | 0.9.0.201612080810    | Eclipse SmartHome Automation API
113 | Active   |  80 | 0.9.0.201612080810    | Eclipse SmartHome Automation commands
114 | Active   |  80 | 0.9.0.201612080810    | Eclipse SmartHome Automation Core
115 | Active   |  80 | 0.9.0.201612080810    | Eclipse SmartHome Automation Module Core
116 | Active   |  80 | 0.9.0.201612080810    | Eclipse SmartHome Automation Module Script
117 | Active   |  80 | 0.9.0.201612080810    | Eclipse SmartHome Automation Script Globals
118 | Active   |  80 | 0.9.0.201612080810    | Eclipse SmartHome Automation Module Timer
119 | Active   |  80 | 0.9.0.201612080810    | Eclipse SmartHome Automation GSON Parser
120 | Active   |  80 | 0.9.0.201612080810    | Eclipse SmartHome Automation Providers
121 | Active   |  80 | 0.9.0.201612080810    | Eclipse SmartHome Automation REST API
122 | Active   |  80 | 0.9.0.201612080810    | Eclipse SmartHome Config Core
123 | Active   |  80 | 0.9.0.201612080810    | Eclipse SmartHome Configuration Discovery
124 | Active   |  80 | 0.9.0.201612080810    | Eclipse SmartHome Config Dispatcher
125 | Active   |  75 | 0.9.0.201612080810    | Eclipse SmartHome Config XML
126 | Active   |  80 | 0.9.0.201612080810    | Eclipse SmartHome Core
127 | Active   |  80 | 0.9.0.201612080810    | Eclipse SmartHome Core Audio
128 | Active   |  80 | 0.9.0.201612080810    | Eclipse SmartHome AutoUpdate Binding
129 | Active   |  80 | 0.9.0.201612080810    | Eclipse SmartHome Core Binding XML
130 | Active   |  80 | 0.9.0.201612080810    | Eclipse SmartHome Core ID
131 | Active   |  80 | 0.9.0.201612080810    | Eclipse SmartHome Core Persistence
132 | Active   |  80 | 0.9.0.201612080810    | Eclipse SmartHome Scheduler Service
133 | Active   |  80 | 0.9.0.201612080810    | Eclipse SmartHome Core Thing
134 | Active   |  75 | 0.9.0.201612080810    | Eclipse SmartHome Core Thing XML
135 | Active   |  80 | 0.9.0.201612080810    | Eclipse SmartHome Transformation Service
136 | Active   |  80 | 0.9.0.201612080810    | Eclipse SmartHome Core Voice
137 | Active   |  80 | 0.9.0.201612080810    | Eclipse SmartHome Console
138 | Active   |  80 | 0.9.0.201612080810    | Eclipse SmartHome Console for OSGi runtime Karaf
139 | Active   |  80 | 0.9.0.201612080810    | Eclipse SmartHome Monitor
140 | Active   |  80 | 0.9.0.201612080810    | Eclipse SmartHome Net I/O Bundle
141 | Active   |  80 | 0.9.0.201612080810    | Eclipse SmartHome REST Interface Bundle
142 | Active   |  80 | 0.9.0.201612080810    | Eclipse SmartHome Authentication Support for the REST Interface
143 | Active   |  80 | 0.9.0.201612080810    | Eclipse SmartHome Core REST API
144 | Active   |  80 | 0.9.0.201612080810    | Eclipse SmartHome Sitemap REST API
145 | Active   |  80 | 0.9.0.201612080810    | Eclipse SmartHome SSE REST API
146 | Active   |  80 | 0.9.0.201612080810    | Eclipse SmartHome Model Core
147 | Active   |  80 | 0.9.0.201612080810    | Eclipse SmartHome Item Model
148 | Active   |  80 | 0.9.0.201612080810    | Eclipse SmartHome Item Model Runtime
149 | Active   |  80 | 0.9.0.201612080810    | Eclipse SmartHome Persistence Model
150 | Active   |  80 | 0.9.0.201612080810    | Eclipse SmartHome Persistence Runtime
151 | Active   |  80 | 0.9.0.201612080810    | Eclipse SmartHome Rule Model
152 | Active   |  80 | 0.9.0.201612080810    | Eclipse SmartHome Rule Runtime
153 | Active   |  80 | 0.9.0.201612080810    | Eclipse SmartHome Script
154 | Active   |  80 | 0.9.0.201612080810    | Eclipse SmartHome Script Runtime
155 | Active   |  80 | 0.9.0.201612080810    | Eclipse SmartHome Sitemap Model
156 | Active   |  80 | 0.9.0.201612080810    | Eclipse SmartHome Sitemap Runtime
157 | Active   |  80 | 0.9.0.201612080810    | Eclipse SmartHome Thing Model
158 | Active   |  80 | 0.9.0.201612080810    | Eclipse SmartHome Thing Model Runtime
159 | Active   |  80 | 0.9.0.201612080810    | Eclipse SmartHome MapDB Storage Service
160 | Active   |  80 | 0.9.0.201612080810    | Eclipse SmartHome UI
161 | Active   |  80 | 0.9.0.201612080810    | Eclipse SmartHome UI Icons
162 | Active   |  80 | 0.9.0.201612080810    | Eclipse SmartHome Classic IconSet
163 | Active   |  80 | 0.9.0.201612080810    | Eclipse SmartHome Paper UI
```

**Comment by maggu2810** [comment] 2016-12-08 09:03
> Since resources are annotated with `@Secured` they will require security context. Adding possibility to ignore them will require changes in jaxrs-security which currently controls access.

@splatch So, could you explain it for me - for a noob of that authentication stuff:
How can I get the Paper UI working again in my Karaf contain without authentication?

**Comment by maggu2810** [comment] 2016-12-08 09:48
* So, as soon as com.eclipsesource.jaxrs.provider.security is installed (could be wired), authentication is necessary. Correct?
* If no authentication module is provided we will receive a 403. Correct?
* If I add com.eclipsesource.jaxrs.provider.security I can see the same behaviour.

* Why has the security provider been added to the normal feature that brings basic jax-rs support?
https://github.com/eclipse/smarthome/pull/2587/files#diff-4a9141e52b541c23c41eb45e0691c812R51
* Shouldn't this bundle only be installed if authentication is requested?
* Should the existence of a bundle take the decision if authentication is used or not? The bundle could be installed because of some other bundles.

**Comment by kaikreuzer** [comment] 2016-12-08 10:09
As mentioned in https://github.com/eclipse/smarthome/pull/2587#issuecomment-265684672: The jax-rs security bundle processes the REST annotations and enforces security.

> Shouldn't this bundle only be installed if authentication is requested?

Correct.

> Why has the security provider been added to the normal feature that brings basic jax-rs support?

Because I didn't think of this implication - my assumption was that if no AuthenticationProvider implementation is available, this bundle will accept all requests, but it is the other way round.

So the fix should be simple: Have the jax-rs security bundle as a separate Karaf feature. Do you all agree?

**Comment by maggu2810** [comment] 2016-12-08 10:15
#2621 will solve it as long as no one install the jax-rs security provider because of some reason (also the Eclipse IDE SmartHome launch config does not include the rest.auth bundle in its "standard" config).

**Comment by maggu2810** [comment] 2016-12-08 10:18
@kaikreuzer Let's assume I want to use jaas or basic authentication for the REST interface, do you have any guide how to setup Karaf to state which roles has been assined to some username (+password)? As it is not related to ESH I don't care about any documentation here, but I assume you would like to use it one time in openHAB.

**Comment by kaikreuzer** [comment] 2016-12-08 10:43
It is right that I want to use it for openHAB, but I still have to figure out the next steps myself - I only wanted to have @splatch's work merged as a starting point. It is clear that parts are still missing to make it work for solutions like openHAB. There e.g. needs to be some login page/mechanism, the UIs need to be enabled to send authorization headers with their requests etc.

**Comment by maggu2810** [comment] 2016-12-08 10:55
#2621 has been merged, so it is working for me and for the moment as previously.
I still don't know how to handle the case if the jax-rs security provider is injected by some other bundles in my runtime (as written above e.g. if I enable the bundle in the Eclipse IDE runtime).
I assume the general approach (not the Karaf relate part) should be documented in the ESH documentation (the concept about the authentication API).

**Comment by kaikreuzer** [comment] 2017-01-02 09:17
As all works as designed, I have updated the title of this issue that documentation still needs to be added for this.

**Comment by kirantpatil** [comment] 2017-08-03 11:44
@kaikreuzer, any updates on Authentication API full feature support in ESH with backend DB integration to create/update/delete User/Password and Role from UI?

**Comment by kirantpatil** [comment] 2017-08-03 11:44
Why this feature is neglected ?

**Comment by kaikreuzer** [comment] 2017-08-03 14:15
> any updates on Authentication API full feature support in ESH with backend DB integration to create/update/delete User/Password and Role from UI?

No, and I don't think this is the goal for ESH - the idea was rather to provide a framework to more easily allow solutions that are built on ESH to more easily integrate authentication mechanism.

> Why this feature is neglected ?

Because nobody seems to be interested in it (by means of putting own effort into it).
I tried to make it all work in some way for openHAB half a year ago, but gave up, because authentication on JAX-RS alone isn't enough for openHAB and getting it smoothly integrated with servlets, Pax-Web, Karaf, etc. was nothing that I managed to do with tolerable effort.

So if you are interested in driving this feature further, please feel free to do so!

**Comment by antoniosv** [comment] 2018-04-06 09:39
I'm having the opposite problem as @maggu2810 . I would like to be denied access to, say, things/items when I use curl without the headers of basic-authentication. However, all requests go through even though the endpoint things/items is annotated by `@RolesAllowed({ Role.ADMIN })`. 
I'm guessing that, at some point, basic authentication was disabled, but what was changed?

**Comment by kaikreuzer** [comment] 2018-04-07 17:43
Let me close this issue here as the whole authentication/security topic is currently rediscussed in https://github.com/eclipse/smarthome/issues/579 - it therefore does not make sense to document the current state as it won't stay as it is and anyhow is no properly usable solution.

**Closed by kaikreuzer** 2018-04-07 17:43 UTC
