### ISSUE TITLE
In Sitemaps LabelColor and ValueColor not working on Group:Switches in BasicUI

### ISSUE THREAD

**Issue by rgerrans** [eclipse/smarthome#2900] opened 2017-01-26 17:40 UTC
I've defined the following group switch:

`Group:Switch:OR(ON, OFF)	Motion	"Motion"	<motion>	(Sensor)`

In my sitemap I tried to apply the following label/value colors:

`Group item=Motion		label="Motion [%s]"	labelcolor=[ON="Red"] valuecolor=[ON="Red"]`

But in the BasicUI it doesn't show up in Red though it does in the Android App

**Comment by geiststreicher** [comment] 2017-03-02 09:50
The same is true for a "Selection" element in the sitemap:

Selection item=PresenceString label="Presence" labelcolor=[hmvar_presentState==ON="green", hmvar_presentState==OFF="red"] mappings=[auto="auto", present="here", notPresent="not here"]

The entries are shown without any labelcolor in the BasicUI.

It works perfectly in the ClassicUI, except that not only the label is colored, but the displayed selection entry, too. Though this might be by design (and is okay for me).

**Comment by lolodomo** [comment] 2017-03-13 00:03
I found what's wrong for groups and fixed it.
But there is still something not working, that is the dynamic update of the value and the value color when the frame is opened. Label color update is now ok.

**Comment by lolodomo** [comment] 2017-03-13 00:12
@geiststreicher : can you please open a specific issue for selection element ?

**Comment by geiststreicher** [comment] 2017-03-13 11:02
@lolodomo: Of course I can :) I opend the issue #3143

**Comment by lolodomo** [comment] 2017-03-16 07:58
To be closed now that PR #3139 is merged.

**Closed** 2017-03-16 08:00 UTC
