### ISSUE TITLE
Basic UI no longer updates icons

### ISSUE THREAD

**Issue by xsnrg** [eclipse/smarthome#2322] opened 2016-10-14 20:39 UTC
from: https://community.openhab.org/t/icons-no-longer-updating-in-basicui/15199/7

Using Chrome or Firefox, icons no longer update in BasicUI.

I am using Linux as the client, and either Firefox or Chrome as the browser on the client, I have tried build 531, 536, and 537.  I have used a NUC running LInux and a Pi2 as the servers.  I have tried various devices, though lights are easiest to test, and have tried z-wave switches as well as insteon switches, trying to eliminate variables.

The icons did update nearly instantly prior to about Oct 8-9.  I have been trying nearly every OH2 build for the last couple weeks.

Sitemap examples were asked for, most all of my sitemaps, including these devices, use groups, so the entries are simply of the form:

                Group label="First Floor Devices"       item=ff
                Group label="Second Floor Devices"      item=sf
                Group label="Basement Devices"          item=bs          
                Group label="Outside Lights"            item=outLights

the insteon items look as such:

Switch OfficeLight           "office light"             <light>        (ALL,lights,ff,ffA)               [ "Lighting" ]  {insteonplm="1F.4C.F9:F00.00.12#switch"} 
Switch KitchenSinkLight      "kitchen sink"             <light>        (ALL,lights,ff,ffA)               [ "Lighting" ]  {insteonplm="33.1C.BA:F00.00.12#switch"}

MapDB is used for the z-wave items and all 2.x bindings.

Other information: 

This appears to be a UI/visual thing.  All devices still work normally, all rules for the devices still fire, and all output from device activity appears in the log.   
Habdroid still works normally.  
Refreshing the BasicUI page shows the proper icon states to match the switch items.

**Comment by wborn** [comment] 2016-10-14 21:23
Yes I've also seen this issue after more testing. It looks a lot like the issue I reported in #2030. But this time around it is harder to reproduce. Some pages still have a proper eventsstream, but others don't. I've also seen the eventsstream stop like this on the demo. 

When I enabled logging on the sitemap package, I saw the frontend subscribing itself to events. But when events are generated (on such pages), there is never any logging of the events being sent the frontend.

**Comment by wborn** [comment] 2016-10-14 22:10
I don't know if it is the same issue. But when I open 6 tabs to the same Basic UI in Chrome, it totally stops working. As soon as I go back from 6 to 5 works again.

**Comment by smar000** [comment] 2016-10-15 07:18
I am seeing the issue with the item states as well. For example, a simple string item:
`String 	Last_Location_Method "Location method"`

and a corresponding sitemap entry:
`Text item=Last_Location_Method label="Last Location Method [%s]" icon="flow"`

The `Last_Location_Method ` state is then updated in a rule. The state is verified as updated via REST. However, the BasicUI sitemap no longer automatically updates the state of the item. A refresh of the page shows the correct state. As @xsnrg  said, this seems to be a UI issue as the underlying system looks to be working (and HABdroid refreshes item states correctly).

**Comment by kaikreuzer** [comment] 2016-10-15 10:07
Thanks @smar000, an example like yours is what we need in order to reproduce things. A single item and a single widget on a sitemap. So I did exactly this and here is the result:

https://www.youtube.com/watch?v=gy6xpob_404 (seeing Chrome, Safari & Firefox side by side).

**Comment by mhilbush** [comment] 2016-10-15 10:47
I'm seeing the same thing as @smar000.  I have an item `CurrentTime` that's updated every 60 seconds by the NTP binding.  I see `CurrentTime` being updated every minute in events.log, however, the time is never updated in the Basic UI.  It updates on the page only on the first load of the page, and when I refresh the page.  I see this across multiple platforms (Windows, Mac, Android) and across multiple browsers (Chrome, Firefox, and Safari).

Is there something specific I should look at to help identify root cause?

**Comment by kaikreuzer** [comment] 2016-10-15 10:50
Can you reproduce the steps that I did in the video posted above? What is the difference to your situation?

**Comment by mhilbush** [comment] 2016-10-15 11:01
Not exactly what you did.  But here's a trace of events.log showing the CurrentTime updates, yet Chrome, Firefox, and Safari all are showing an old date.

<img width="1440" alt="screen shot 2016-10-15 at 6 58 20 am" src="https://cloud.githubusercontent.com/assets/19286354/19409590/161e39cc-92a5-11e6-9025-0c2c99d08a7a.png">

**Comment by mhilbush** [comment] 2016-10-15 11:14
A couple other facts.
- I have one system on build 524 and other one on 537.  I see the same behavior on both systems.
- I see these bundles on the 537 build.  Does that look right?
```
openhab> bundle:list -s | grep paper
187 | Active   |  80 | 0.9.0.201610131442    | org.eclipse.smarthome.ui.paper, Fragments: 188
188 | Resolved |  80 | 2.0.0.201610140851    | org.openhab.ui.paperui, Hosts: 187

```

**Comment by kaikreuzer** [comment] 2016-10-15 11:47
I guess we are more interested in the version of the Basic UI ;-)

As mentioned above: Please help analyzing the problem by first confirming that what I do in the video is working for you as well, so we can be sure we start off common grounds.
Then try to slightly change this setup until it shows your issues.

**Comment by mhilbush** [comment] 2016-10-15 11:49
> I guess we are more interested in the version of the Basic UI ;-)

Yeah, sorry about that.  :-(

**Comment by mhilbush** [comment] 2016-10-15 12:38
Here you go.  This is on my Ubuntu box running build 524, where I have only Chrome and Firefox installed.
https://youtu.be/zgx64m45xpg

**Comment by kaikreuzer** [comment] 2016-10-15 12:46
What your video lacks is the moment that you initially request the UI.
Note that it is normal that you won't have any updates if you just leave the browser on the page and do changes to items or sitemaps or you restart the runtime.

**Comment by mhilbush** [comment] 2016-10-15 13:17
> What your video lacks is the moment that you initially request the UI.

Ok, ok.
https://youtu.be/ZicFT1lT0CQ

**Comment by smar000** [comment] 2016-10-15 13:29
Thanks @kaikreuzer. I have also just tried again using exactly same approach as on your video. Using build 537 of OH and Chrome 53.0.2785.143m on Windows 10, my results are the same as before - i.e. the item state does not dynamically update and remains as `-` until I do a refresh of the page.  

However, I repeated the test using IE 11 (actually 11.321.14393.0), and this time, the updates show correctly. 

The problem therefore may be something to do with the build of Chrome.

**Comment by resetnow** [comment] 2016-10-15 15:38
>Was this also supposed to be addressed by the recent fixes in the BasicUI or is this a different issue?

Yes. It worked for me, but I had to restart openhab in order to get it working.

**Comment by resetnow** [comment] 2016-10-15 15:39
As a side note, please try cleaning you browser cache! It's a very unlikely cause but since we are trying to narrow down a problem it's worth a try.

**Comment by xsnrg** [comment] 2016-10-15 15:54
I have tried Chrome with incognito, cleared cache in normal mode, and firefox normal and private browsing.  The result is the same for me in every case.  The icons do not update.  A refresh of the browser in each case shows the proper icons that reflect the states.  It looks like @mhilbush 's video.

**Comment by xsnrg** [comment] 2016-10-15 16:44
To try to get more information that may be valuable, I created a new sitemap that looks like this:

```
sitemap test label="test sitemap"
{
	Frame label="fake switches" {
		Switch label="Fake 1"		item=fakeswitch1
		Switch label="Fake 2"		item=fakeswitch2
		}
}
```

and the corresponding .items file:
```
Switch fakeswitch1 
Switch fakeswitch2
```
I load this new site map in chrome and it exhibits the same behaviour that the actual items do in my live sitemap, so I hit good ole F12 in the browser on this stripped down sitemap, and there are some errors:

> background.js:21 Uncaught ReferenceError: FSM is not defined(…)(anonymous function) @ background.js:21
> options.js:54 Uncaught TypeError: Cannot set property 'innerHTML' of null(…)buildSlider @ options.js:54(anonymous function) @ options.js:123
> thank_you.js:7 Uncaught TypeError: Cannot set property 'innerHTML' of null(…)(anonymous function) @ thank_you.js:7
> options.js:25 Uncaught TypeError: Cannot set property 'onchange' of null(…)(anonymous function) @ options.js:25
> fsm.js:28 Uncaught TypeError: FSM.method is not a function(…)(anonymous function) @ fsm.js:28

**Comment by resetnow** [comment] 2016-10-15 17:12
None of referenced Javascript files belong to BasicUI (it should be smarthome.js or mdl.js). Do they appear every time page is refreshed?

**Comment by xsnrg** [comment] 2016-10-15 17:23
Good question, yes, they are there all the time, but I think we can ignore this as they are not there in incognito mode, so there must be a plugin on that browser.  I will chase that down later.  Ignoring those then, there are no js errors.  Incognito mode behaves the same without the errors.  Will keep digging.

**Comment by resetnow** [comment] 2016-10-15 17:29
Thanks for checking this. Chrome can display event stream if you click on Network tab in devtools, refresh the page, click that long subscription ID and then click “Event stream” tab. Do you see any events in there?

**Comment by xsnrg** [comment] 2016-10-15 17:51
This is bizarre.  It started working correctly.  There are no events without moving a switch, as you would expect, but when the switch is toggled, there are events.  They are below, and the icons are updated as one would suspect.  I completely restarted chrome and it is still working, so I reloaded and went back to my sitemap.  My sitemap is not working, and there are no events in the stream.

What I am going to do now is make my test sitemap look more like my real one.  In looking at the network stream, there is a new subscription for each frame of the sitemap.  I want my test sitemap to reflect the same frame navigation.  Will follow back up.

```
{"widgetId":"0000","label":"Fake 1","visibility":true,"item":{"state":"ON","type":"Switch","name":"fakeswitch1","tags":[],"groupNames":[]},"sitemapName":"test","pageId":"test"}	
12:34:51.668
event	{"widgetId":"0000","label":"Fake 1","visibility":true,"item":{"state":"OFF","type":"Switch","name":"fakeswitch1","tags":[],"groupNames":[]},"sitemapName":"test","pageId":"test"}	
12:34:53.222
event	{"widgetId":"0000","label":"Fake 1","visibility":true,"item":{"state":"ON","type":"Switch","name":"fakeswitch1","tags":[],"groupNames":[]},"sitemapName":"test","pageId":"test"}	
12:34:54.971
event	{"widgetId":"0000","label":"Fake 1","visibility":true,"item":{"state":"OFF","type":"Switch","name":"fakeswitch1","tags":[],"groupNames":[]},"sitemapName":"test","pageId":"test"}	

```

**Comment by BClark09** [comment] 2016-10-15 17:53
This seems to be an intermittent problem for everyone, the eventsource is created (times out after 1 minute and a new one is created), but it doesn't respond to any changes.

![image](https://cloud.githubusercontent.com/assets/8983584/19412192/469f0762-9308-11e6-96ee-aa327e2c4dc7.png)

Every now and then I get a working view, and the eventsource receives the event and updates the widget accordingly.

**Comment by resetnow** [comment] 2016-10-15 18:01
>In looking at the network stream, there is a new subscription for each frame of the sitemap.

Subscription should be the same, but its ID is sent every time a navigation event occurs, so server knows which widgets should receive events.

**Comment by xsnrg** [comment] 2016-10-15 18:16
so... try this sitemap with the same .items file from before.

```
sitemap test label="test sitemap"
{
	Frame label="first fake frame" {	
		Switch label="Fake 1"		item=fakeswitch1
		}
	Frame label="2nd fake frame" {
		Switch label="Fake 2"		item=fakeswitch2
		}
}
```

The first switch operates and updates.  The second switch also has events appear in the stream, but the browser does not update the elements.

**Comment by xsnrg** [comment] 2016-10-15 19:25
I just upgraded to build 542, and now I have a consistent experience to report.  Here is a video:

[youtube video](https://youtu.be/jSztyY83ty8)

Starting from a fresh chrome browser, I go to the bookmark that I have set for my sitemap.  The sitemap loads, and there is a subscription.  I click on a link to go to the next page, and there is not a new subscription.  Is the assumption here is that the same subscription should work, or should there be a new one?  The events do not show up in the stream for the switch on this page.  Refresh the page, and now there is a new subscription, and the switch information updates with events in the stream.

I am not sure what is different in this build, if anything, but this is reproducible for me now.

**Comment by resetnow** [comment] 2016-10-15 19:27
>Is the assumption here is that the same subscription should work

Yes, they should. The subscription is updated with the address of the page you go into.

**Comment by smar000** [comment] 2016-10-16 09:00
I think @BClark09  is correct. The problem is intermittent and may be specific to Chrome (possibly on Windows). My Chrome has again stopped showing updated item states this morning, but IE is still working. I have tried all the usual methods of clearing browser cache etc in Chrome, but that didn't help.

> Yes. It worked for me, but I had to restart openhab in order to get related events.

@resetnow WRT the chart visibility tag issue, this is there even after a restart. The issue is also present on both IE and Chrome. In the Chrome dev tools, I don't see anything showing in the Event Stream as the various period change buttons are clicked. However,  the Network Stream panel lists the chart period button each time it is clicked, with a status of `200 `, type `xhr `and initiator `smarthome.js:1`.

**Comment by resetnow** [comment] 2016-10-16 09:04
>IE is still working

IE does not support event streams and uses long-polling. It seems that the problem is related to the event stream generation, therefore IE is not affected.

**Comment by wborn** [comment] 2016-10-16 10:40
I especially have this issue on pages with a lot of updates. So I wrote little stress test that can reproduce it on the demo by opening closing windows a lot of times. This is the rule I used:

```
rule "open/close windows"
when
	System started
then
	while (true) {
	        sendCommand(Window_GF_Frontdoor, OPEN)
	        sendCommand(Window_GF_Kitchen, OPEN)
	        sendCommand(Window_GF_Living, OPEN)
	        sendCommand(Window_GF_Toilet, OPEN)
	        sendCommand(Window_FF_Bath, OPEN)
	        sendCommand(Window_FF_Bed, OPEN)
	        sendCommand(Window_FF_Office_Window, OPEN)
	        sendCommand(Window_FF_Office_Door, OPEN)
	        sendCommand(Window_FF_Bed, OPEN)
	        sendCommand(Garage_Door, OPEN)
	        Thread::sleep(250)
	        sendCommand(Window_GF_Frontdoor, CLOSED)
	        sendCommand(Window_GF_Frontdoor, CLOSED)
	        sendCommand(Window_GF_Kitchen, CLOSED)
	        sendCommand(Window_GF_Living, CLOSED)
	        sendCommand(Window_GF_Toilet, CLOSED)
	        sendCommand(Window_FF_Bath, CLOSED)
	        sendCommand(Window_FF_Bed, CLOSED)
	        sendCommand(Window_FF_Office_Window, CLOSED)
	        sendCommand(Window_FF_Office_Door, CLOSED)
	        sendCommand(Window_FF_Bed, CLOSED)
	        sendCommand(Garage_Door, CLOSED)
	        Thread::sleep(250)
	}
end
```

Things start work pretty well initially. But after a while the items on the `Open windows` group page no longer update for me.

**Comment by wborn** [comment] 2016-10-16 11:16
More specifically. The events stream to the `Open windows` group page breaks when I reload this page a couple of times.

**Comment by mhilbush** [comment] 2016-10-17 10:58
I turned on trace level debugging and saw this.  Problem is my sitemap is not called demo...  I changed the name of my sitemap to demo.sitemap, and the basic UI updates started working.

```
2016-10-17 06:50:03.479 [DEBUG] [t.sitemap.SitemapSubscriptionService] - Created new subscription with id dd012e48-e046-4ba6-8a1a-d135d998ed9d
2016-10-17 06:50:03.485 [DEBUG] [t.sitemap.SitemapSubscriptionService] - Subscription dd012e48-e046-4ba6-8a1a-d135d998ed9d changed to page basic-ui-test of sitemap basic-ui-test
2016-10-17 06:50:03.486 [DEBUG] [est.sitemap.internal.SitemapResource] - Client requested sitemap event stream for subscription dd012e48-e046-4ba6-8a1a-d135d998ed9d.
2016-10-17 06:50:07.326 [DEBUG] [thome.io.rest.core.item.ItemResource] - Received HTTP POST request at 'items/MySwitch1' with value 'ON'.
2016-10-17 06:50:09.670 [DEBUG] [thome.io.rest.core.item.ItemResource] - Received HTTP POST request at 'items/MySwitch1' with value 'OFF'.
2016-10-17 06:50:10.778 [DEBUG] [thome.io.rest.core.item.ItemResource] - Received HTTP POST request at 'items/MySwitch1' with value 'ON'.
2016-10-17 06:50:11.347 [DEBUG] [thome.io.rest.core.item.ItemResource] - Received HTTP POST request at 'items/MySwitch1' with value 'OFF'.
2016-10-17 06:50:12.907 [DEBUG] [thome.io.rest.core.item.ItemResource] - Received HTTP POST request at 'items/MySwitch2' with value 'ON'.
2016-10-17 06:50:13.506 [DEBUG] [thome.io.rest.core.item.ItemResource] - Received HTTP POST request at 'items/MySwitch2' with value 'OFF'.
2016-10-17 06:50:14.012 [DEBUG] [thome.io.rest.core.item.ItemResource] - Received HTTP POST request at 'items/MySwitch2' with value 'ON'.
2016-10-17 06:50:14.490 [DEBUG] [thome.io.rest.core.item.ItemResource] - Received HTTP POST request at 'items/MySwitch2' with value 'OFF'.
2016-10-17 06:50:17.261 [DEBUG] [basic.internal.servlet.WebAppServlet] - Servlet request received!
2016-10-17 06:50:17.261 [DEBUG] [basic.internal.servlet.WebAppServlet] - reading sitemap demo
2016-10-17 06:50:17.261 [TRACE] [el.core.internal.ModelRepositoryImpl] - Configuration model 'demo.sitemap' can not be found
2016-10-17 06:50:17.261 [TRACE] [sitemap.internal.SitemapProviderImpl] - Sitemap demo cannot be found

```

**Comment by mhilbush** [comment] 2016-10-17 11:14
Well, maybe not.  I can't seem to reproduce the behavior that made it work.

**Comment by mhilbush** [comment] 2016-10-17 11:37
@kaikreuzer What's happeneing here is pretty strange.  I can consistently reproduce this behavior after a fresh restart of OH2.
 https://youtu.be/mpEcXMPkiFQ

**Comment by mhilbush** [comment] 2016-10-17 11:48
In another scenario, if I start with the sitemap named demo, it works.  After changing to another sitemap, it never works again (even with demo).  Again, I can reproduce this only after a clean restart.
https://youtu.be/CCEX-PDEPCw

**Comment by resetnow** [comment] 2016-10-17 17:47
So I did some debugging and there is a potential problem: <a href="https://github.com/eclipse/smarthome/blob/master/bundles/io/org.eclipse.smarthome.io.rest.sitemap/src/main/java/org/eclipse/smarthome/io/rest/sitemap/SitemapSubscriptionService.java#L184">it seems like sitemap name is compared to the sitemap file name</a>.

In the example given by @xsnrg, sitemap should be saved under name test.sitemap. Or demo.sitemap, and then it should start with `sitemap demo`. For me it works even after a constant abusive page refresh.

**Comment by kaikreuzer** [comment] 2016-10-17 18:18
> Or demo.sitemap, and then it should start with sitemap demo

This is indeed required and was so since the beginning of sitemaps in OH1. We might want to add some validation that logs a warning if this is not the case.

**Comment by kaikreuzer** [comment] 2016-10-17 18:18
So is there actually an issue left here? Could anyone summarize?

**Comment by wborn** [comment] 2016-10-17 18:29
Yes I still have a reproducible issue with the demo (see comment above). The sitemap name is `demo.sitemap` and it starts of with `sitemap demo label="Main Menu"`. The timing of my example may seem absurd. But when I change it to 500ms and spam the refresh button of my browser, the eventsstream always breaks.

**Comment by BClark09** [comment] 2016-10-17 18:31
Unfortunately so. I have a default.sitemap which starts "sitemap default", and I am still experiencing this issue inconsistently. I can't seem to find a way to reproduce this problem reliably, since sometimes doing the same steps works, sometimes it doesn't. Furthermore:

```
sitemap default label="Main Menu"
{
	Frame label="Areas"
	{
		Text label="Bedroom" icon="bedroom" 
		{
			Frame label="Bedroom Light" 
			{
				Switch         item=Bedroom_Light_Toggle label="Switch" icon="switch"
				Colorpicker    item=Bedroom_Light_Colour
				Switch         item=Bedroom_Light_ColourLoop
			}
			Frame label="Motion Sensor"
			{
				Switch         item=Bedroom_MotionSensor_Enabled                                

				Text           item=Bedroom_MotionSensor_Luminance
				Text           item=Bedroom_MotionSensor_Battery
				Text           item=Bedroom_MotionSensor_Temperature
				Text           item=Bedroom_MotionSensor_Motion
			}
		}
		Text label="Kitchen" icon="kitchen" 
		{
			Frame label="Kitchen Controls" 
			{
				Switch         item=Kitchen_Light_Toggle label="Switch" icon="switch"
				Slider         item=Kitchen_Light_Brightness
			}
		}
}
```

The last time this issue occurred was with the above sitemap, I went into "Bedroom" and I saw a live update of my sensors and my hue lights, either when they come on from a rule or if I changed them manually with HABdroid. If I went back and into "Kitchen", no events would come through for either of the two items, go back to "Bedroom" and it still works for them.

**Comment by mhilbush** [comment] 2016-10-17 18:32
> Or demo.sitemap, and then it should start with sitemap demo

Ah, that was it for me.  If the name inside the sitemap file doesn't match the name of the sitemap file (before the .), then it almost works (i.e. the pages render correctly, but nothing updates).  And, yes, I would agree a warning would be very helpful.  👍

**Comment by xsnrg** [comment] 2016-10-17 18:41
I too, knew of the rule they must match.  My example sitemap as well as my home sitemap follow the rule and still exhibit the issue.

```
$ cat test.sitemap 
sitemap test label="test sitemap"
```

**Comment by resetnow** [comment] 2016-10-17 20:07
@kaikreuzer out of curiosity have you been able to reproduce the issue?

Also, I think it wouldn't hurt to post what platform we're running openhab on. I tested on Linux (Fedora), openjdk 1.8.0_101.

**Comment by xsnrg** [comment] 2016-10-17 20:34
Tested on Fedora 23 server with Oracle JDK version "1.8.0_60".  
Client chrome 54, and Firefox 49 on Fedora 24

**Comment by wborn** [comment] 2016-10-17 20:58
openHAB 2.0.0-SNAPSHOT Build *#*546
Chrome 54.0.2840.59 (64-bit)
Oracle Java 1.8.0_101 (64-bit)
Ubuntu 16.04.1 LTS
Firefox 49.0

My issue is something in the backend. Because when the eventsstream breaks on a certain page, it breaks on all my browsers for that page. Also on browers/devices that did not yet connect. It really reminds me of the issue I reported in #2030.

**Comment by resetnow** [comment] 2016-10-17 21:02
Well this is certainly <i>not</i> a browser compatibility issue. Event stream was used in BasicUI before, just in a different way.

That's two people with Oracle JDK, by the way.

**Comment by xsnrg** [comment] 2016-10-17 21:29
Just reproduced it on a Pi2, also Oracle JDK 1.8.0_70

**Comment by wborn** [comment] 2016-10-17 21:40
My issue is only reproducible with my stress test rule when only one browser connected to the `Open windows` page and I spam the refresh button. When I spam the refresh button while a second browser is also connected, it keeps working.

**Comment by resetnow** [comment] 2016-10-18 16:14
It would be nice to try with openjdk then.

**Comment by BClark09** [comment] 2016-10-18 16:26
Pi3 (Debian Jessie), also Oracle JDK 1.8.0_65

Will try open JDK and get back to you.

**Comment by wborn** [comment] 2016-10-18 16:33
I think I found the issue. At line 116 in `SitemapSubscriptionService` the `listener` is removed whereas I think it should remove the `sitemapPage`. The `.remove(..)` works on map keys, which should be the `sitemapPage`. Whereas the `listener` is the value of the map.

When I apply this change my reproduction scenario can no longer reproduce the issue. I can then spam the reload button all I want. Maybe you can crosscheck this change @resetnow ?

**Comment by resetnow** [comment] 2016-10-18 16:34
I'll check it in an hour or so

**Comment by resetnow** [comment] 2016-10-18 17:08
>I think I found the issue. At line 116 in SitemapSubscriptionService the listener is removed whereas I think it should remove the sitemapPage. The .remove(..) works on map keys, which should be the sitemapPage. Whereas the listener is the value of the map.

Sounds right to me. It's not clear to me why I can't reproduce it though. Could you open a PR? (I'm not fluent in Java so @kaikreuzer may have different opinion on this),

**Comment by wborn** [comment] 2016-10-18 18:18
Here's a fix for people who are eager to test and want to see if my fix also solves their issue:

* Download [org.eclipse.smarthome.io.rest.sitemap-0.9.0-SNAPSHOT.zip](https://github.com/eclipse/smarthome/files/537029/org.eclipse.smarthome.io.rest.sitemap-0.9.0-SNAPSHOT.zip)
* Rename .zip to .jar
* Open console and find the bundle ID to update:
```
bundle:list | grep 'Sitemap REST API'
```
* Update the bundle (e.g. when bundle ID is 118):
```
bundle:update 118 file:///home/pi/org.eclipse.smarthome.io.rest.sitemap-0.9.0-SNAPSHOT.jar
```
* Restart ESH/openHAB

**Closed** 2016-10-18 18:49 UTC
Labels: BasicUI

**Comment by xsnrg** [comment] 2016-10-19 01:06
Thanks for the sleuthing folks!
