### ISSUE TITLE
BasicUI Errors in treatment of Default element type

### ISSUE THREAD

**Issue by mherwege** [eclipse/smarthome#3040] opened 2017-02-18 23:44 UTC
I create the following simple test sitemap:
`sitemap test label="Test"
{
	Frame {
		Switch item=Licht_Zithoek
		Slider item=Licht_Zithoek
		Setpoint item=Licht_Zithoek minValue=0 maxValue=100 step=5
		Default item=Licht_Zithoek
	}
}`
Licht_Zithoek is a dimmer item.
The above sitemap shows correctly.
If I put the Default element type first, I get another frame around all 4 elements inside the first frame.
If I ommit the frame and put all the elements at the highest level, the Default element type will not show at all.

**Comment by lolodomo** [comment] 2017-05-06 18:16
It is a duplicate of issue #2933.
@kaikreuzer : please close this issue.

**Closed** 2017-05-06 18:36 UTC
