### ISSUE TITLE
Basic UI: problem with dates

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#961] opened 2016-01-31 21:53 UTC
I display two date/time in my home page, using a specific format defined in my items file. One is the current time (from NTP binding).
When I open the Basic UI, these dates are correctly displayed.
Then I got these warnings:
```
22:50:12.328 [WARN ] [ternal.render.AbstractWidgetRenderer] - Cannot escape path '2016-01-31T22:49:14' in URL. Returning unmodified path.
22:50:12.335 [WARN ] [ternal.render.AbstractWidgetRenderer] - Cannot escape path '2016-01-17T16:52:10' in URL. Returning unmodified path.
22:50:14.928 [INFO ] [marthome.event.ItemStateChangedEvent] - Date changed from 2016-01-31T22:49:14 to 2016-01-31T22:50:14
```
And then my current date is displayed with the default format.

No problem with classic UI.

**Comment by kaikreuzer** [comment] 2016-02-02 10:52
@resetnow Could you please have a look?

**Comment by resetnow** [comment] 2016-02-04 05:55
@lolodomo could you please post an item definition and a sitemap entry?

**Comment by s-simma** [comment] 2016-02-04 06:34
same problem here with item:
DateTime CurrentDate    "Datum [%1$tA, %1$td.%1$tm.%1$tY  %1$tT]"   { channel="ntp:ntp:demo:dateTime" }

**Comment by resetnow** [comment] 2016-02-04 07:51
ok, I'll check it later today, but it could be related to #640. Once the date gets updated via NTP, the formatting is lost.

**Comment by resetnow** [comment] 2016-02-04 19:16
So it is related to #640. Once the date is updated via NTP, it is also updated in BasicUI and it loses formatting.

**Comment by kaikreuzer** [comment] 2016-02-05 07:43
Closing as duplicate of #640.

**Closed by kaikreuzer** 2016-02-05 07:43 UTC
Labels: BasicUI
