### ISSUE TITLE
[Test failures] AutomationIntegrationTest

### ISSUE THREAD

**Issue by sjka** [eclipse/smarthome#2810] opened 2017-01-12 13:18 UTC
```
assert that ruleNow method executes actions of the rule(org.eclipse.smarthome.automation.integration.test.AutomationIntegrationTest)  Time elapsed: 0.074 sec  <<< FAILURE!
java.lang.AssertionError: 
Expected: is <ON>
     but: was <OFF>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:865)
	at org.junit.Assert.assertThat(Assert.java:832)
	at org.junit.Assert$assertThat.callStatic(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:53)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:157)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:169)
	at org.eclipse.smarthome.automation.integration.test.AutomationIntegrationTest.assert that ruleNow method executes actions of the rule(AutomationIntegrationTest.groovy:452)
```

```
Results :
Failed tests: 
  AutomationIntegrationTest.assert that ruleNow method executes actions of the rule:452 
Expected: is <ON>
     but: was <OFF>
Tests run: 21, Failures: 1, Errors: 0, Skipped: 0
```

see https://travis-ci.org/eclipse/smarthome/builds/191295087

**Comment by danchom** [comment] 2017-01-13 09:41
I think this is not a  problem, I can't reproduce it and as I see the Travis was run this test many times after that.
For me the problem was in delay of travis execution or problem with item state change.

**Comment by sjka** [comment] 2017-01-13 10:52
It appears to me a matter of timing. I didn't say it happens always, but usually stuff like this hits again when it hurts most - building releases, urgent fixes, etc. That's why so far in this project we had the good habit to fix also test instabilities that only occur sometimes.

**Comment by maggu2810** [comment] 2017-01-15 11:19
> we had the good habit to fix also test instabilities that only occur sometimes.

👍

**Comment by maggu2810** [comment] 2017-06-23 11:27
@sjka This report is rather old. Are you willing to close this issue?

**Closed** 2017-06-23 13:08 UTC
Labels: Automation, bug, Test
